---
sidebar: sidebar 
permalink: hu-aix-70.html 
keywords: host utilities, aix, powervm, vios, 3.1, 7.0, netapp, ontap 
summary: 'Le utilità host AIX aiutano a gestire l"archiviazione ONTAP collegata a un host AIX.' 
---
= Installare le utilità host AIX 7,0
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Le utilità host AIX aiutano a gestire l'archiviazione ONTAP collegata a un host AIX.

Le utilità host di AIX supportano i seguenti protocolli:

* FC
* FCoE
* ISCSI


Le utilità host di AIX supportano i seguenti ambienti:

* Microsoft Multipath i/o (MPIO) AIX (sistema operativo nativo)
* PowerVM
+
Per ulteriori informazioni su PowerVM, consultare il Red Book IBM PowerVM Live Partition Mobility.



.Prima di iniziare
* Per un funzionamento affidabile, verificare che sia supportata l'intera configurazione iSCSI, FC o FCoE.
+
È possibile utilizzare https://imt.netapp.com/matrix/#welcome["Tool di matrice di interoperabilità"^] per verificare la configurazione.

* Il tracciamento dinamico deve essere attivato per tutti gli initiator FC e FCoE.



NOTE: Il pacchetto software utilità host NetApp AIX è disponibile su link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.0["Sito di supporto NetApp"^]in un file compresso `tar.gz file`. È necessario installare il kit di utilità host AIX mentre si utilizza MPIO AIX con l'archiviazione ONTAP.

.Fasi
. Accedere al proprio host.
+
** Su un host AIX, accedere come *root*.
** Su un host PowerVM, accedere come *padmin*, quindi immettere il `oem_setup_env` comando per diventare un utente root.


. Accedere a https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.0["Sito di supporto NetApp"^] e scaricare il file compresso contenente le utilità host in una directory dell'host.
. Accedere alla directory contenente il download.
. Decomprimere il file ed estrarre il pacchetto software di SAN Toolkit:
+
`# tar -xvf ntap_aix_host_utilities_7.0.tar.gz`

+
La seguente directory viene creata quando si decomprime il file: `ntap_aix_host_utilities_7.0`. Questa directory contiene una delle seguenti sottodirectory: MPIO, NON_MPIO o SAN_Tool_Kit.

. Installare il MPIO AIX:
+
`# installp -aXYd /var/tmp/ntap_aix_host_utilities_7.0/MPIO NetApp.MPIO_Host_Utilities_Kit`

. Installare IL kit di strumenti SAN:
+
`# installp -aXYd /var/tmp/ntap_aix_host_utilities_7.0/SAN_Tool_Kit/NetApp.SAN_toolkit`

. Riavviare l'host.
. Verificare l'installazione:
+
`# lslpp -l |grep -i netapp`

+
[listing]
----
NetApp.MPIO_Host_Utilities_Kit.config
                             7.0.0.0  COMMITTED  NetApp MPIO PCM Host Utilities
  NetApp.MPIO_Host_Utilities_Kit.fcp
                             7.0.0.0  COMMITTED  NetApp MPIO PCM Host Utilities
  NetApp.MPIO_Host_Utilities_Kit.iscsi
                             7.0.0.0  COMMITTED  NetApp MPIO PCM Host Utilities
  NetApp.MPIO_Host_Utilities_Kit.pcmodm
                             7.0.0.0  COMMITTED  NetApp MPIO PCM Host Utilities
NetApp.SAN_toolkit.sanlun  7.0.0.0  COMMITTED  NetApp SAN Toolkit sanlun
----
. Verificare la versione del software:
+
`# sanlun version`

+
[listing]
----
7.0.725.3521
----
. Verificare che il `lbp_enabled` parametro SCSI UNMAP sia aggiunto all'ODM eseguendo i seguenti comandi:
+
`# odmget -q "uniquetype=disk/fcp/NetAppMPIO" PdAt |grep  "lbp_enabled"`

+
[listing]
----
attribute = "lbp_enabled"
----
+
`# odmget -q "uniquetype=disk/fcp/NetAppMPIO and attribute=lbp_enabled" PdAt`

+
[listing]
----
PdAt:
        uniquetype = "disk/fcp/NetAppMPIO"
        attribute = "lbp_enabled"
        deflt = "true"
        values = "true,false"
        width = ""
        type = "R"
        generic = ""
        rep = "s"
        nls_index = 18
----




== Toolkit SAN

AIX host Utilities è un software host NetApp che fornisce un toolkit della riga di comando sull'host IBM AIX. Il toolkit viene installato quando si installa il pacchetto NetApp host Utilities. Questo kit fornisce `sanlun` Utility che consente di gestire LUN e HBA (host bus adapter). Il `sanlun` Il comando restituisce le informazioni relative alle LUN mappate all'host, al multipathing e alle informazioni necessarie per creare gruppi di iniziatori.

*Esempio*

Nell'esempio seguente, il `sanlun lun show` Il comando restituisce le informazioni del LUN.

[listing]
----
# sanlun lun show all
----
*Esempio di output*

[listing]
----
controller(7mode)/ device host lun

vserver(Cmode) lun-pathname filename adapter protocol size mode
----------------------------------------------------------------
data_vserver   /vol/vol1/lun1 hdisk0 fcs0    FCP      60g C
data_vserver   /vol/vol2/lun2 hdisk0 fcs0    FCP      20g C
data_vserver   /vol/vol3/lun3 hdisk11 fcs0   FCP      20g C
data_vserver   /vol/vol4/lun4 hdisk14 fcs0   FCP      20g C
----

NOTE: Questo toolkit è comune a tutte le configurazioni e i protocolli delle utilità host. Di conseguenza, tutti i componenti non si applicano a ogni configurazione. I componenti inutilizzati non influiscono sulle prestazioni del sistema. Il SAN Toolkit è supportato sulle versioni AIX e PowerVM/VIOS
