---
sidebar: sidebar 
permalink: hu-aix-73.html 
keywords: Host Utilities, aix, powervm, vios, 3.1, 7.2 netapp, ontap 
summary: Descrive come utilizzare IBM AIX 7.3 e/o PowerVM VIOS 4.x con ONTAP 
---
= Configurare AIX 7.3/VIOS 4.x per FCP e iSCSI con storage ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Il software AIX Host Utilities fornisce strumenti di gestione e diagnostica per gli host AIX connessi allo storage ONTAP .  Quando si installano le AIX Host Utilities su un host AIX 7.3/VIOS 4.x, è possibile utilizzare le Host Utilities per gestire le operazioni del protocollo FCP e iSCSI con LUN ONTAP .



== Passaggio 1: Se lo si desidera, attivare l'avvio SAN

È possibile configurare l'host per utilizzare l'avvio SAN per semplificare la distribuzione e migliorare la scalabilità.  Se la configurazione non supporta l'avvio SAN, è possibile utilizzare un avvio locale.

[role="tabbed-block"]
====
.Boot SAN
--
L'avvio SAN è il processo di configurazione di un disco collegato a SAN (un LUN) come dispositivo di avvio per un host AIX/PowerVM.  È possibile configurare un LUN di avvio SAN per funzionare in un ambiente AIX Multipath I/O (MPIO) che utilizza il protocollo FC ed esegue AIX Host Utilities con il protocollo FC o FCoE.  Il metodo utilizzato per creare un LUN di avvio SAN e installare una nuova immagine del sistema operativo in un ambiente AIX MPIO dipende dal protocollo utilizzato.

.Fasi
. Utilizzare illink:https://mysupport.netapp.com/matrix/#welcome["Tool di matrice di interoperabilità"^] per verificare che il sistema operativo AIX, il protocollo e la versione ONTAP supportino l'avvio SAN.
. Seguire le best practice per la configurazione di un avvio SAN riportate nella documentazione del fornitore.


--
.Avvio locale
--
Eseguire un avvio locale installando il sistema operativo AIX sul disco rigido locale, ad esempio su un SSD, SATA o RAID.

--
====


== Passaggio 2: installare le utilità host AIX

NetApp consiglia vivamente di installare AIX Host Utilities per supportare la gestione ONTAP LUN e assistere il supporto tecnico nella raccolta dei dati di configurazione.  Il pacchetto MPIO di Host Utilities fornisce supporto MPIO per AIX e VIOS.


NOTE: L'installazione di AIX Host Utilities fornisce impostazioni di timeout aggiuntive sull'host AIX.

link:hu-aix-80.html["Installa AIX Host Utilities 8.0"] .



== Fase 3: Verificare la configurazione multipath per l'host

È possibile utilizzare il multipathing con AIX e PowerVM per gestire le LUN ONTAP .

Il multipathing consente di configurare più percorsi di rete tra l'host e il sistema di archiviazione.  Se un percorso fallisce, il traffico prosegue sui percorsi rimanenti.  Gli ambienti AIX e PowerVM di Host Utilities utilizzano la soluzione multipathing nativa di AIX (MPIO).

Il Path Control Module (PCM) è responsabile del controllo di più percorsi per un host AIX.  Il PCM è un codice fornito dal fornitore di storage che gestisce la gestione dei percorsi e viene installato e abilitato durante l'installazione di Host Utilities.

Per garantire che il multipathing sia configurato correttamente per l'host, verificare di aver configurato le impostazioni consigliate da NetApp per i LUN ONTAP .

.Fasi
. Verificare che "MPIO NetApp" sia disponibile.  "MPIO NetApp" viene caricato durante l'installazione di AIX Host Utilities e diventa disponibile dopo il riavvio dell'host.
+
[source, cli]
----
lsdev -Cc disk
----
+
.Output di esempio
`hdisk1  Available 00-00-02 MPIO NetApp FCP Default PCM Disk`

. Le utilità host AIX caricano le seguenti impostazioni dei parametri per le LUN ONTAP .
+
.Mostra impostazioni parametri
[%collapsible]
====
[cols="4*"]
|===
| Parametro | Ambiente | Valore per AIX | Nota 


| algoritmo | MPIO | round_robin | Impostato da host Utilities 


| hcheck_cmd | MPIO | richiesta | Impostato da host Utilities 


| hcheck_interval | MPIO | 30 | Impostato da host Utilities 


| hcheck_mode | MPIO | non attivo | Impostato da host Utilities 


| lun_reset_spt | MPIO / non MPIO | sì | Impostato da host Utilities 


| trasferimento_massimo | MPIO / non MPIO | LUN FC: 0x100000 byte | Impostato da host Utilities 


| qfull_dly | MPIO / non MPIO | ritardo di 2 secondi | Impostato da host Utilities 


| queue_depth | MPIO / non MPIO | 64 | Impostato da host Utilities 


| policy_di_riserva | MPIO / non MPIO | no_reserve | Impostato da host Utilities 


| re_timeout (disco) | MPIO / non MPIO | 30 secondi | Utilizza i valori predefiniti del sistema operativo 


| dintrk | MPIO / non MPIO | Sì | Utilizza i valori predefiniti del sistema operativo 


| fc_err_recov | MPIO / non MPIO | Fast_fail | Utilizza i valori predefiniti del sistema operativo 


| q_type | MPIO / non MPIO | semplice | Utilizza i valori predefiniti del sistema operativo 


| num_cmd_elems | MPIO / non MPIO | 1024 per AIX 3072 per VIOS | FC EN1B, FC EN1C 


| num_cmd_elems | MPIO / non MPIO | 1024 per AIX | FC EN0G 
|===
====
. Configurare le seguenti impostazioni per ottimizzare le operazioni di I/O per FC e iSCSI.
+
[role="tabbed-block"]
====
.FCP
--
[cols="4*"]
|===
| Parametro | Versioni AIX | Valore predefinito del sistema operativo AIX | Valore consigliato da NetApp 


.4+| rw_timeout (disco) | AIX 7.3TL3 | NPIV: 30 secondi, vSCSI: 45 secondi | NPIV: 30 secondi, vSCSI: 120 secondi 


| AIX 7.2TL5 | NPIV: 30 secondi, vSCSI: 45 secondi | NPIV: 30 secondi, vSCSI: 120 secondi 


| VIOS 3.1 | 30 secondi | 30 secondi 


| VIOS 4.1 | 30 secondi | 30 secondi 
|===
--
.ISCSI
--
[cols="4*"]
|===
| Parametro | Versioni AIX | Valore predefinito del sistema operativo AIX | Valore consigliato da NetApp 


.5+| rw_timeout (disco) | AIX 7.3TL3 | vSCSI:45 secondi | vSCSI: 120 secondi 


| AIX 7.2TL5 | vSCSI:45 secondi | vSCSI: 120 secondi 


| VIOS 3.1 | 120 secondi | 30 secondi 


| VIOS 4.1 | 120 secondi | 30 secondi 


| Tutti i sistemi AIX7.2 e AIX 7.3 autonomi | 120 secondi | 30 secondi 


| isw_err_recov (iscsi0) | Tutti i sistemi AIX7.2 e AIX 7.3 autonomi | errore ritardato | fast_fail 
|===
--
====
. Se la configurazione di archiviazione include MetroCluster o SnapMirror ActiveSync, modifica le impostazioni predefinite:
+
[role="tabbed-block"]
====
.MetroCluster
--
Per impostazione predefinita, il sistema operativo AIX impone un timeout I/O più breve quando non sono disponibili percorsi verso una LUN.  Ciò potrebbe verificarsi in configurazioni che includono un fabric SAN a switch singolo e in configurazioni MetroCluster in cui si verificano failover non pianificati.  Per ulteriori informazioni e modifiche consigliate alle impostazioni predefinite, consultare l'articolo della Knowledge Baselink:https://kb.netapp.com/on-prem/ontap/mc/MC-KBs/What_are_AIX_Host_support_considerations_in_a_MetroCluster_configuration["Quali sono le considerazioni sul supporto dell'host AIX in una configurazione MetroCluster ?"^] .

--
.Sincronizzazione attiva SnapMirror
--
A partire da ONTAP 9.11.1, la sincronizzazione attiva SnapMirror è supportata per un host AIX.  Il cluster primario in una configurazione AIX è il cluster "attivo".

In una configurazione AIX, i failover sono dirompenti.  A ogni failover è necessario eseguire una nuova scansione sull'host per riprendere le operazioni di I/O.

Fare riferimento all'articolo della Knowledge Baselink:https://kb.netapp.com/on-prem/ontap/DP/SnapMirror/SnapMirror-KBs/How_to_configure_AIX_Host_for_SnapMirror_active_sync_in_ONTAP["Come configurare un host AIX per la sincronizzazione attiva di SnapMirror"^] .

--
====
. Verificare le impostazioni dei parametri e che siano elencati più percorsi per un LUN ONTAP :
+
[source, cli]
----
lsmpio
----
+
Nell'esempio seguente per un sistema AFF o FAS , il PCM è elencato per NetApp.

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
# lsmpio -l hdisk1
name    path_id  status   path_status  parent  connection

hdisk1  0        Enabled  Non          fscsi6  203200a098ba7afe,5b000000000000
hdisk1  1        Enabled  Non          fscsi8  203100a098ba7afe,5b000000000000
hdisk1  2        Enabled  Sel,Opt      fscsi6  203000a098ba7afe,5b000000000000
hdisk1  3        Enabled  Sel,Opt      fscsi8  203800a098ba7afe,5b000000000000
#
lsattr -El hdisk1
*PCM             PCM/friend/NetAppDefaultPCM Path Control Module*                     False
PR_key_value    0x6d0000000002              Persistant Reserve Key Value            True
algorithm       round_robin                 Algorithm                               True
clr_q           no                          Device CLEARS its Queue on error        True
dist_err_pcnt   0                           Distributed Error Sample Time           True
dist_tw_width   50                          Distributed Error Sample Time           True
hcheck_cmd      inquiry                     Health Check Command                    True
hcheck_interval 30                          Health Check Interval                   True
hcheck_mode     nonactive                   Health Check Mode                       True
location                                    Location Label                          True
lun_id          0x5b000000000000            Logical Unit Number ID                  False
lun_reset_spt   yes                         LUN Level Reset                         True
max_transfer    0x100000                    Maximum TRANSFER Size                   True
node_name       0x204800a098ba7afe          FC Node Name                            False
pvid            none                        Physical volume identifier              False
q_err           yes                         Use QERR bit                            True
q_type          simple                      Queuing TYPE                            True
qfull_dly       2                           Delay in seconds for SCSI TASK SET FULL True
queue_depth     64                          Queue DEPTH                             True
reassign_to     120                         REASSIGN time out value                 True
reserve_policy  PR_shared                   Reserve Policy                          True
rw_timeout      30                          READ/WRITE time out value               True
scsi_id         0xec409                     SCSI ID                                 False
start_timeout   60                          START unit time out value               True
timeout_policy  fail_path                   Active/Passive Disk Path Control Module True
ww_name         0x203200a098ba7afe          FC World Wide Name                      False
----
====
. Verificare lo stato del percorso per le LUN ONTAP :
+
[source, cli]
----
sanlun lun show
----
+
Gli output di esempio seguenti mostrano lo stato del percorso corretto per le LUN ONTAP in una configurazione ASA, AFF o FAS .

+
[role="tabbed-block"]
====
.Configurazioni ASA
--
Una configurazione ASA ottimizza tutti i percorsi verso una determinata LUN, mantenendoli attivi ("primari").  Ciò migliora le prestazioni gestendo le operazioni di I/O attraverso tutti i percorsi contemporaneamente.

.Mostra esempio
[%collapsible]
=====
[listing]
----
# sanlun lun show -p |grep -p hdisk78
                    ONTAP Path: vs_aix_clus:/vol/chataix_205p2_vol_en_1_7/jfs_205p2_lun_en
                           LUN: 37
                      LUN Size: 15g
                   Host Device: hdisk78
                          Mode: C
            Multipath Provider: AIX Native
        Multipathing Algorithm: round_robin
------ ------- ------ ------- --------- ----------
host   vserver  AIX                      AIX MPIO
path   path     MPIO   host    vserver     path
state  type     path   adapter LIF       priority
------ ------- ------ ------- --------- ----------
up     primary  path0  fcs0    fc_aix_1     1
up     primary  path1  fcs0    fc_aix_2     1
up     primary  path2  fcs1    fc_aix_3     1
up     primary  path3  fcs1    fc_aix_4     1
----
=====
--
.Configurazione AFF o FAS
--
Una configurazione AFF o FAS deve avere due gruppi di percorsi con priorità maggiore e minore. I percorsi Active/Optimized di priorità più elevata sono serviti dal controller in cui si trova l'aggregato. I percorsi a priorità inferiore sono attivi ma non ottimizzati perché serviti da un controller diverso. I percorsi non ottimizzati vengono utilizzati solo quando non sono disponibili percorsi ottimizzati.

L'esempio seguente mostra l'output corretto per un LUN ONTAP con due percorsi attivi/ottimizzati ("primari") e due percorsi attivi/non ottimizzati ("secondari"):

.Mostra esempio
[%collapsible]
=====
[listing]
----
# sanlun lun show -p |grep -p hdisk78
                    ONTAP Path: vs_aix_clus:/vol/chataix_205p2_vol_en_1_7/jfs_205p2_lun_en
                           LUN: 37
                      LUN Size: 15g
                   Host Device: hdisk78
                          Mode: C
            Multipath Provider: AIX Native
        Multipathing Algorithm: round_robin
------- ---------- ------ ------- ---------- ----------
host    vserver    AIX                        AIX MPIO
path    path       MPIO   host    vserver         path
state   type       path   adapter LIF         priority
------- ---------- ------ ------- ---------- ----------
up      secondary  path0  fcs0    fc_aix_1        1
up      primary    path1  fcs0    fc_aix_2        1
up      primary    path2  fcs1    fc_aix_3        1
up      secondary  path3  fcs1    fc_aix_4        1
----
=====
--
====




== Passaggio 4: rivedere i problemi noti

Non ci sono problemi noti.



== Quali sono le prossime novità?

link:hu-aix-command-reference.html["Scopri come utilizzare lo strumento AIX Host Utilities"] .
