---
sidebar: sidebar 
permalink: hu-proxmox-ve-9x.html 
keywords: proxmox, VE, 9.x, netapp, ontap, iscsi, fcp 
summary: Installare Linux Host Utilities su un host Proxmox VE 9.x per gestire le operazioni del protocollo FCP e iSCSI con LUN ONTAP . 
---
= Configurare Proxmox VE 9.x per FCP e iSCSI con storage ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Configurare Proxmox VE 9.x per il multipathing e con parametri e impostazioni specifici per le operazioni del protocollo FCP e iSCSI con storage ONTAP .

FCP e iSCSI con Proxmox VE 9.x presentano le seguenti limitazioni note:

* Linux Host Utilities non supporta i sistemi operativi Proxmox VE 9.x.
* La configurazione di avvio SAN non è supportata.




== Passaggio 1: confermare la configurazione multipath per l'host

È possibile utilizzare il multipathing con Proxmox VE 9.x per gestire le LUN ONTAP .

Per verificare che il multipathing sia configurato correttamente per l'host, verificare che il `/etc/multipath.conf` file sia definito e che siano configurate le impostazioni consigliate da NetApp per i LUN ONTAP.

.Fasi
. Verificare che il `/etc/multipath.conf` file venga chiuso. Se il file non esiste, creare un file vuoto a zero byte:
+
[source, cli]
----
touch /etc/multipath.conf
----
. La prima volta che `multipath.conf` si crea il file, potrebbe essere necessario attivare e avviare i servizi multipath per caricare le impostazioni consigliate:
+
[source, cli]
----
systemctl enable multipathd
----
+
[source, cli]
----
systemctl start multipathd
----
. Ogni volta che si avvia l'host, il file vuoto `/etc/multipath.conf` con zero byte carica automaticamente i parametri multipath dell'host raccomandati da NetApp come impostazioni predefinite. Non è necessario apportare modifiche al `/etc/multipath.conf` file per l'host perché il sistema operativo è compilato con i parametri multipath che riconoscono e gestiscono correttamente i LUN ONTAP.
+
La tabella seguente mostra le impostazioni dei parametri multipercorso compilati nativi del sistema operativo Linux per i LUN ONTAP.

+
.Mostra impostazioni parametri
[%collapsible]
====
[cols="2"]
|===
| Parametro | Impostazione 


| detect_prio | sì 


| dev_loss_tmo | "infinito" 


| failback | immediato 


| fast_io_fail_tmo | 5 


| caratteristiche | "2 pg_init_retries 50" 


| flush_on_last_del | "Sempre" 


| gestore_hardware | "1" 


| no_path_retry | coda 


| path_checker | "a" 


| policy_di_raggruppamento_percorsi | "group_by_prio" 


| path_selector | "tempo di servizio 0" 


| intervallo_polling | 5 


| prio | "ONTAP" 


| prodotto | LUN 


| retain_attached_hw_handler | sì 


| peso_rr | "uniforme" 


| user_friendly_names | no 


| vendor | NETAPP 
|===
====
. Facoltativamente, sovrascrivere il valore predefinito per `find_multipaths` parametro per garantire che le LUN ONTAP vengano rilevate e gestite correttamente da multipathd:
+
--
.. Impostato `find_multipaths` su "no" nella sezione predefinita di `/etc/multipath.conf` :
+
[source, cli]
----
defaults {
    find_multipaths "no"
}
----
.. Ricarica il servizio multipath:
+
[source, cli]
----
systemctl reload multipathd
----


--
+

NOTE: Per impostazione predefinita, la configurazione multipath nativa del sistema operativo Proxmox imposta `find_multipaths` a "*strict*" con il byte zero vuoto `/etc/multipath.conf` file di configurazione ogni volta che si avvia l'host.  Ciò può impedire all'host di rilevare i LUN ONTAP appena presentati come dispositivi multipath, il che significa che non vengono visualizzati automaticamente sotto il controllo multipath.  Le LUN ONTAP esistenti rimangono scoperte e sotto il controllo multipath dopo ogni riavvio.

. Verificare le impostazioni dei parametri e lo stato del percorso dei LUN ONTAP:
+
[source, cli]
----
multipath -ll
----
+
I parametri multipath predefiniti supportano le configurazioni ASA, AFF e FAS. In queste configurazioni, una singola LUN ONTAP non deve richiedere più di quattro percorsi. Se sono presenti più di quattro percorsi, potrebbero verificarsi problemi con i percorsi durante un errore di storage.

+
I seguenti output di esempio mostrano le impostazioni corrette dei parametri e lo stato del percorso per i LUN ONTAP in una configurazione ASA, AFF o FAS.

+
[role="tabbed-block"]
====
.Configurazione ASA
--
Una configurazione ASA ottimizza tutti i percorsi verso una determinata LUN, mantenendoli attivi. In questo modo, le performance vengono migliorate grazie alle operazioni di i/o in tutti i percorsi contemporaneamente.

.Mostra esempio
[%collapsible]
=====
[listing]
----
multipath -ll
3600a098038315071592b59713261566d dm-38 NETAPP,LUN C-Mode
size=100G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 8:0:0:7 sdbv 68:144 active ready running
  |- 9:0:0:7 sdbx 68:176 active ready running
  |- 6:0:0:7 sdbr 68:80  active ready running
  `- 7:0:0:7 sdbt 68:112 active ready running

----
=====
--
.Configurazione AFF o FAS
--
Una configurazione AFF o FAS deve avere due gruppi di percorsi con priorità maggiore e minore. I percorsi Active/Optimized di priorità più elevata sono serviti dal controller in cui si trova l'aggregato. I percorsi a priorità inferiore sono attivi ma non ottimizzati perché serviti da un controller diverso. I percorsi non ottimizzati vengono utilizzati solo quando non sono disponibili percorsi ottimizzati.

L'esempio seguente mostra l'output per un LUN ONTAP con due percorsi attivi/ottimizzati e due percorsi attivi/non ottimizzati:

.Mostra esempio
[%collapsible]
=====
[listing]
----
multipath -ll
3600a0980383149764b5d567257516273 dm-0 NETAPP,LUN C-Mode size=150G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| |- 16:0:3:0  sdcg 69:64  active ready running
| `- 10:0:0:0  sdb  8:16   active ready running
`-+- policy='service-time 0' prio=10 status=enabled
  |- 10:0:1:0  sdc  8:32   active ready running
  `- 16:0:2:0  sdcf 69:48  active ready running
----
=====
--
====




== Passaggio 2: conferma la configurazione iSCSI per il tuo host

Assicurati che iSCSI sia configurato correttamente per il tuo host.

.A proposito di questa attività
Eseguire i seguenti passaggi sull'host iSCSI.

.Fasi
. Verificare che il pacchetto iSCSI initiator (open-iscsi) sia installato:
+
[source, cli]
----
$apt list |grep open-iscsi
----
+
Dovresti vedere un output simile al seguente esempio:

+
[listing]
----
open-iscsi/stable,now 2.1.11-1+deb13u1 amd64
----
. Verificare il nome del nodo iSCSI initiator, che si trova nel file  `/etc/iscsi/initiatorname.iscsi`:
+
[source, cli]
----
InitiatorName=iqn.YYYY-MM.com.<vendor>:<host_name>
----
. Configura il parametro di timeout della sessione iSCSI situato nel file  `/etc/iscsi/iscsid.conf`:
+
[source, cli]
----
node.session.timeo.replacement_timeout = 5
----
+
Il parametro  `replacement_timeout`iSCSI controlla per quanto tempo il livello iSCSI deve attendere che un percorso o una sessione scaduti si ristabiliscano prima di interrompere qualsiasi comando su di esso. Dovresti impostare il valore di  `replacement_timeout`a 5 nel file di configurazione iSCSI.

. Abilitare il servizio iSCSI:
+
[source, cli]
----
$systemctl enable iscsid
----
. Avvia il servizio iSCSI:
+
[source, cli]
----
$systemctl start iscsid
----
. Verificare che il servizio iSCSI sia in esecuzione:
+
[source, cli]
----
$systemctl status iscsid
----
+
.Mostra esempio
[%collapsible]
====
[listing]
----
● iscsid.service - iSCSI initiator daemon (iscsid)
     Loaded: loaded (/usr/lib/systemd/system/iscsid.service; disabled; preset: enabled)
     Active: active (running) since Fri 2026-02-20 22:14:34 IST; 2 days ago
 Invocation: 37a44a6ebd3a4e3898dcc6c408b85bec
TriggeredBy: ● iscsid.socket
       Docs: man:iscsid(8)
    Process: 4985 ExecStartPre=/usr/lib/open-iscsi/startup-checks.sh (code=exited, status=0/SUCCESS)
    Process: 4988 ExecStart=/usr/sbin/iscsid (code=exited, status=0/SUCCESS)
   Main PID: 4991 (iscsid)
      Tasks: 2 (limit: 151112)
     Memory: 12.5M (peak: 15.5M)
        CPU: 2.438s
     CGroup: /system.slice/iscsid.service
             ├─4990 /usr/sbin/iscsid
             └─4991 /usr/sbin/iscsid

----
====
. Scopri i target iSCSI:
+
[source, cli]
----
$iscsiadm --mode discovery --op update --type sendtargets --portal <target_IP>
----
+
.mostra esempio
[%collapsible]
====
[listing]
----
iscsiadm --mode discovery --op update --type sendtargets --portal
192.168.166.70
192.168.166.70:3260,1042 iqn.1992-08.com.netapp:sn.c770be5d934811f0b624d039eac809ba:vs.5
192.168.165.71:3260,1045 iqn.1992-08.com.netapp:sn.c770be5d934811f0b624d039eac809ba:vs.5
192.168.165.70:3260,1044 iqn.1992-08.com.netapp:sn.c770be5d934811f0b624d039eac809ba:vs.5
192.168.166.71:3260,1043 iqn.1992-08.com.netapp:sn.c770be5d934811f0b624d039eac809ba:vs.5
----
====
. Accedi ai target:
+
[source, cli]
----
$iscsiadm --mode node -l all
----
. Imposta iSCSI per accedere automaticamente all'avvio dell'host:
+
[source, cli]
----
$iscsiadm --mode node -T <target_name> -p <ip:port> -o update -n node.startup -v automatic
----
+
Sostituisci  `<target_name>` con il nome del target a cui desideri accedere automaticamente all'avvio dell'host. Sostituisci  `<ip:port>` con l'indirizzo IP e il numero di porta del target. Ad esempio:

+
[source, cli]
----
iscsiadm --mode node -T iqn.1992-08.com.netapp:sn.c770be5d934811f0b624d039eac809ba:vs.5 -p 192.168.166.70:3260 -o update -n node.startup -v automatic
----
. Verificare le sessioni iSCSI:
+
[source, cli]
----
$iscsiadm --mode session
----
+
.Mostra esempio
[%collapsible]
====
[listing]
----
iscsiadm --mode session
tcp: [1] 192.168.166.71:3260,1043 iqn.1992-08.com.netapp:sn.c770be5d934811f0b624d039eac809ba:vs.5 (non-flash)
tcp: [2] 192.168.165.71:3260,1045 iqn.1992-08.com.netapp:sn.c770be5d934811f0b624d039eac809ba:vs.5 (non-flash)
tcp: [3] 192.168.165.70:3260,1044 iqn.1992-08.com.netapp:sn.c770be5d934811f0b624d039eac809ba:vs.5 (non-flash)
tcp: [4] 192.168.166.70:3260,1042 iqn.1992-08.com.netapp:sn.c770be5d934811f0b624d039eac809ba:vs.5 (non-flash)
----
====




== Passaggio 3: facoltativamente, escludere un dispositivo dal multipathing

Se necessario, è possibile escludere un dispositivo dal multipathing aggiungendo il WWID per il dispositivo indesiderato alla stanza "blacklist" per il `multipath.conf` file.

.Fasi
. Determinare il WWID:
+
[source, cli]
----
/lib/udev/scsi_id -gud /dev/sda
----
+
"sda" è il disco SCSI locale che si desidera aggiungere alla blacklist.

+
Un esempio di WWID è `360030057024d0730239134810c0cb833`.

. Aggiungere il WWID alla "blacklist" stanza:
+
[source, cli]
----
blacklist {
	     wwid   360030057024d0730239134810c0cb833
        devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
        devnode "^hd[a-z]"
        devnode "^cciss.*"
}
----




== Passaggio 4: personalizzare i parametri multipath per le LUN ONTAP

Se l'host è connesso a LUN di altri fornitori e le impostazioni dei parametri multipath vengono sovrascritte, è necessario correggerle aggiungendo più avanti nel `multipath.conf` file che si applicano specificamente ai LUN di ONTAP. In caso contrario, i LUN di ONTAP potrebbero non funzionare come previsto.

Controllare il file, in particolare nella sezione dei valori predefiniti, per verificare `/etc/multipath.conf` le impostazioni che potrebbero sovrascrivere <<multipath-parameter-settings,impostazioni predefinite per i parametri multipath>>.


CAUTION: Non sovrascrivere le impostazioni dei parametri consigliate per i LUN ONTAP. Queste impostazioni sono necessarie per ottenere prestazioni ottimali della configurazione host. Per ulteriori informazioni, contattare l'assistenza NetApp, il fornitore del sistema operativo o entrambi.

Nell'esempio seguente viene illustrato come correggere un valore predefinito sovrascritto. In questo esempio, il `multipath.conf` file definisce i valori per `path_checker` e `no_path_retry` che non sono compatibili con i LUN ONTAP e non è possibile rimuovere questi parametri perché gli array di storage ONTAP sono ancora collegati all'host. È invece possibile correggere i valori per `path_checker` e `no_path_retry` aggiungendo una stanza di dispositivo al `multipath.conf` file che si applica specificamente ai LUN di ONTAP.

.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
defaults {
   path_checker      *readsector0*
   no_path_retry     *fail*
}

devices {
   device {
      vendor          "NETAPP"
      product         "LUN"
      no_path_retry   *queue*
      path_checker    *tur*
   }
}
----
====


== Passaggio 5: rivedere i problemi noti

Non ci sono problemi noti.
