---
sidebar: sidebar 
permalink: hu-solaris-80.html 
keywords: host utilities, unified, oracle, linux, 7.1, netapp, ontap 
summary: Descrive come utilizzare Solaris Host Utilities 8.0 con ONTAP 
---
= Installa Solaris Host Utilities 8.0 per l'archiviazione ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Le Solaris Host Utilities aiutano a gestire lo storage ONTAP collegato a un host Solaris e supportano il supporto tecnico nella raccolta dei dati di configurazione.

Solaris Host Utilities supporta i seguenti ambienti Solaris e protocolli di trasporto.  Questi sono gli ambienti principali supportati:

* Il sistema operativo nativo con Oracle Solaris I/O Multipathing (MPxIO) e protocollo FC o iSCSI su un sistema che utilizza un processore SPARC o x86/64.
* Veritas Dynamic Multipathing (DMP) con protocollo FC o iSCSI su un sistema che utilizza un processore SPARC.


Solaris Host Utilities 8.0 supporta la serie Solaris 11.4.

.Prima di iniziare
Verificare che la configurazione iSCSI, FC o FCoE sia supportata.  Puoi usare illink:https://imt.netapp.com/matrix/#welcome["Tool di matrice di interoperabilità"^] per verificare la tua configurazione.

.Fasi
. Accedi al tuo host come root.
. Scaricare una copia del file compresso contenente le utility host da link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/6.2/downloads["Sito di supporto NetApp"^] a una directory sull'host.
+
[role="tabbed-block"]
====
.CPU SPARC
--
[source, cli]
----
netapp_solaris_host_utilities_8_0_sparc.tar.gz
----
--
.Processore x86/x64
--
[source, cli]
----
netapp_solaris_host_utilities_8_0_amd.tar.gz
----
--
====
. Vai alla directory sul tuo host che contiene il download.
. Decomprimere il file utilizzando il `gunzip` comando, quindi estrarre il file utilizzando `tar -xvf` :
+
[source, cli]
----
gunzip netapp_solaris_host_utilities_8_0_sparc.tar.gz
----
+
[source, cli]
----
tar -xvf netapp_solaris_host_utilities_8_0_sparc.tar
----
. Aggiungi i pacchetti estratti dal file tar al tuo host:
+
[source, cli]
----
pkgadd
----
+
I pacchetti vengono aggiunti a. `/opt/NTAP/SANToolkit/bin` directory.

+
Nell'esempio seguente viene utilizzato il `pkgadd` comando per installare il pacchetto di installazione di Solaris:

+
[source, cli]
----
pkgadd -d ./NTAPSANTool.pkg
----
. Verificare che il toolkit sia stato installato correttamente utilizzando il seguente comando nel percorso installato:
+
[source, cli]
----
pkgchk
----
+
.Mostra output di esempio
[%collapsible]
====
[listing]
----
# pkgchk -l -p /opt/NTAP/SANToolkit

Pathname: /opt/NTAP/SANToolkit
Type: directory
Expected mode: 0755
Expected owner: root
Expected group: sys
Referenced by the following packages: NTAPSANTool
Current status: installed

# ls -alR /opt/NTAP/SANToolkit
/opt/NTAP/SANToolkit:
total 1038
drwxr-xr-x   3 root     sys            4 Mar  7 13:11 .
drwxr-xr-x   3 root     sys            3 Mar  7 13:11 ..
drwxr-xr-x   2 root     sys            6 Mar 17 18:32 bin
-r-xr-xr-x   1 root     sys       432666 Dec 31 13:23 NOTICES.PDF

/opt/NTAP/SANToolkit/bin:
total 3350
drwxr-xr-x   2 root     sys            6 Mar 17 18:32 .
drwxr-xr-x   3 root     sys            4 Mar  7 13:11 ..
-r-xr-xr-x   1 root     sys      1297000 Feb  7 22:22 host_config
-r-xr-xr-x   1 root     root         996 Mar 17 18:32 san_version
-r-xr-xr-x   1 root     sys       309700 Feb  7 22:22 sanlun
-r-xr-xr-x   1 root     sys          677 Feb  7 22:22 vidpid.dat

# cd /usr/share/man/man1; ls -al host_config.1 sanlun.1
-r-xr-xr-x   1 root     sys        12266 Feb  7 22:22 host_config.1
-r-xr-xr-x   1 root     sys         9044 Feb  7 22:22 sanlun.1
----
====
. Configurare i parametri host per l'ambiente "MPxIO" o "Veritas DMP" utilizzando `/opt/NTAP/SANToolkit/bin/host_config` comando con lo stack multipath dal riferimento comandi:
+
`/opt/NTAP/SANToolkit/bin/host_config -setup -protocol fcp|iscsi|mixed -multipath mpxio|dmp|non [-noalua] [-mcc 60|90|120]`

+
[cols="2*"]
|===
| Ad esempio, se la tua configurazione è... | Utilizzare il comando... 


| FCP con multipath come MPxIO | `#/opt/NTAP/SANToolkit/bin/host_config -setup -protocol fcp -multipath mpxio`Per informazioni sulle modifiche alla configurazione per SnapMirror ActiveSync, consultare l'articolo della Knowledge Baselink:https://kb.netapp.com/on-prem/ontap/DP/SnapMirror/SnapMirror-KBs/Solaris_Host_support_recommended_settings_in_SnapMirror_active_sync_formerly_SM_BC_configuration["Impostazioni consigliate per il supporto host Solaris nella configurazione SnapMirror ActiveSync (in precedenza SM-BC)"^] . 


| FCP con multipath come DMP | `#/opt/NTAP/SANToolkit/bin/host_config -setup -protocol fcp -multipath dmp` 


| FCP su MetroCluster con multipath come MPxIO e il valore All Paths Down è impostato su 120 s.  (Questa è l'impostazione consigliata per le configurazioni MetroCluster ). | `#/opt/NTAP/SANToolkit/bin/host_config -setup -protocol fcp -multipath mpxio -mcc 120`Per ulteriori informazioni, consultare l'articolo della Knowledge Baselink:https://kb.netapp.com/on-prem/ontap/mc/MC-KBs/Solaris_host_support_considerations_in_a_MetroCluster_configuration["Considerazioni sul supporto degli host Solaris in una configurazione MetroCluster"^] . 
|===
. Riavviare l'host.
+
Le utility host caricano le seguenti impostazioni dei parametri di timeout consigliate da NetApp per le LUN ONTAP .

+
.Mostra esempio
[%collapsible]
====
[listing]
----
#prtconf -v |grep NETAPP
   value='NETAPP  LUN' +
   physical-block-size:4096,
   retries-busy:30,
   retries-reset:30,
   retries-notready:300,
   retries-timeout:10,
   throttle-max:64,
   throttle-min:8,
   disksort:false,
   cache-nonvolatile:true'
----
====
. Verificare l'installazione di Host Utilities:
+
[source, cli]
----
sanlun version
----




== Quali sono le prossime novità?

link:hu-solaris-san-toolkit.html["Scopri di più sul SAN Toolkit"] .
