---
sidebar: sidebar 
permalink: hu-veritas-8x.html 
keywords: host utilities, veritas, infoscale, 8, netapp, ontap, sanhost, iscsi, red, hat linux, oracle, linux 
summary: Utilizza Linux Host Utilities con Veritas Infoscale 8 per host RHEL e Oracle Linux per gestire le operazioni dei protocolli FC, FCoE e iSCSI con LUN ONTAP . 
---
= Configurare Veritas Infoscale 8 per FC, FCoE e iSCSI con storage ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Il software Linux Host Utilities fornisce strumenti di gestione e diagnostica per gli host Linux connessi allo storage ONTAP . Utilizzare Linux Host Utilities con Veritas Infoscale 8 per gli host Oracle Linux (basati su Red Hat Compatible Kernel), Red Hat Enterprise Linux (RHEL) e SUSE Linux Enterprise Server per supportare la gestione delle operazioni del protocollo FC, FCoE e iSCSI con LUN ONTAP .



== Passaggio 1: Se lo si desidera, attivare l'avvio SAN

È possibile configurare l'host in modo che utilizzi l'avvio SAN per semplificare l'installazione e migliorare la scalabilità.

.Prima di iniziare
* Utilizzare link:https://mysupport.netapp.com/matrix/#welcome["Tool di matrice di interoperabilità"^]per verificare che il sistema operativo Linux, l'HBA (host Bus Adapter), il firmware HBA, il BIOS di avvio HBA e la versione ONTAP supportino l'avvio SAN.
* Fare riferimento al portale di supporto Veritas (matrice dei prodotti, ricerca della piattaforma e matrice HCL) per verificare il supporto della configurazione di avvio SAN e i problemi noti.


.Fasi
. link:https://docs.netapp.com/us-en/ontap/san-admin/provision-storage.html["Crea un LUN di avvio SAN e mappalo all'host"^].
. Abilitare l'avvio SAN nel BIOS del server per le porte a cui è mappato il LUN di avvio SAN.
+
Per informazioni su come attivare il BIOS HBA, consultare la documentazione specifica del vendor.

. Verificare che la configurazione sia stata eseguita correttamente riavviando l'host e verificando che il sistema operativo sia attivo e funzionante.




== Fase 2: Installare le utilità host Linux

NetApp consiglia vivamente link:hu-luhu-release-notes.html["installazione delle utilità host Linux"] per supportare la gestione ONTAP LUN e assistere il supporto tecnico nella raccolta dei dati di configurazione.


NOTE: L'installazione di Linux host Utilities non modifica le impostazioni di timeout dell'host sul proprio host Linux.



== Passaggio 3: confermare la configurazione Veritas Dynamic Multipathing per l'host

Utilizzare Veritas Dynamic Multipathing (VxDMP) con Veritas Infoscale 8 per gestire le LUN ONTAP .

Per garantire che VxDMP sia configurato correttamente per l'host, è necessario verificare la configurazione di VxDMP e controllare la configurazione di Array Support Library (ASL) e Array Policy Module (APM). I pacchetti ASL e APM per i sistemi di storage NetApp vengono installati durante l'installazione del software Veritas.


NOTE: Per gli ambienti multipath eterogenei, tra cui Veritas Infoscale, Linux Native Device Mapper e LVM Volume Manager, fare riferimento alla documentazione di Veritas Product Administration per le impostazioni di configurazione.

.Prima di iniziare
Assicurati che la tua configurazione soddisfi i requisiti di sistema. Vedi il link:https://mysupport.netapp.com/matrix/#welcome["Tool di matrice di interoperabilità"^] e la matrice Veritas HCL.

.Fasi
. Verificare che l'array di destinazione ONTAP sia collegato al multipath VxDMP:
+
[source, cli]
----
vxdmpadm
----
+
.Mostra esempio
[%collapsible]
====
[listing]
----
# vxdmpadm listenclosure
ENCLR_NAME   ENCLR_TYPE  ENCLR_SNO     STATUS      ARRAY_TYPE    LUN_COUNT    FIRMWARE
=====================================================================================
sfrac0       SFRAC       804Xw$PqE52h  CONNECTED   ALUA          43           9800
# vxdmpadm getdmpnode
NAME       STATE    ENCLR-TYPE  PATHS  ENBL  DSBL ENCLR-NAME
===================================================================
sfrac0_47  ENABLED  SFRAC       4      4     0    sfrac0
----
====
. Controllare la configurazione dei pacchetti ASL e APM. NetApp consiglia di utilizzare i pacchetti supportati più recenti elencati sul portale di supporto Veritas.
+
.Mostra un esempio di configurazione ASL e APM
[%collapsible]
====
[listing]
----
# vxdmpadm list dmpnode dmpnodename=sfrac0_47 | grep asl
asl        = libvxnetapp.so
# vxddladm listversion |grep libvxnetapp.so
libvxnetapp.so                  vm-8.0.0-rev-1   8.0

# rpm -qa |grep VRTSaslapm
VRTSaslapm-x.x.x.0000-RHEL8.X86_64
vxddladm listsupport libname=libvxnetapp.so
ATTR_NAME   ATTR_VALUE
=========================================
LIBNAME     libvxnetapp.so
VID         NETAPP
PID         All
ARRAY_TYPE  ALUA, A/A
----
====
. Per una configurazione ottimale del sistema nelle operazioni di failover dello storage, verificare di disporre dei seguenti parametri sintonizzabili Veritas VxDMP:
+
[cols="2*"]
|===
| Parametro | Impostazione 


| dmp_lun_retry_timeout | 60 


| dmp_path_age | 120 


| dmp_restore_interval | 60 
|===
. Impostare i parametri sintonizzabili DMP su online:
+
[source, cli]
----
# vxdmpadm settune dmp_tunable=value
----
. Verificare che i parametri sintonizzabili siano impostati correttamente:
+
[source, cli]
----
# vxdmpadm gettune
----
+
L'esempio seguente mostra i parametri sintonizzabili VxDMP effettivi su un host SAN.

+
.Mostra esempio
[%collapsible]
====
[listing]
----
# vxdmpadm gettune

Tunable                    Current Value    Default Value
dmp_cache_open                      on                on
dmp_daemon_count                    10                10
dmp_delayq_interval                 15                15
dmp_display_alua_states             on                on
dmp_fast_recovery                   on                on
dmp_health_time                     60                60
dmp_iostats_state              enabled           enabled
dmp_log_level                        1                 1
dmp_low_impact_probe                on                on
dmp_lun_retry_timeout               60                30
dmp_path_age                       120               300
dmp_pathswitch_blks_shift            9                 9
dmp_probe_idle_lun                  on                on
dmp_probe_threshold                  5                 5
dmp_restore_cycles                  10                10
dmp_restore_interval                60               300
dmp_restore_policy         check_disabled   check_disabled
dmp_restore_state              enabled           enabled
dmp_retry_count                      5                 5
dmp_scsi_timeout                    20                20
dmp_sfg_threshold                    1                 1
dmp_stat_interval                    1                 1
dmp_monitor_ownership               on                on
dmp_monitor_fabric                  on                on
dmp_native_support                 off               off
----
====
. Configurare i valori di timeout del protocollo:
+
[role="tabbed-block"]
====
.FC/FCoE
--
Utilizzare i valori di timeout predefiniti per FC e FCoE.

--
.iSCSI
--
Imposta il `replacement_timeout` valore del parametro a 120.

L'iSCSI `replacement_timeout` Il parametro controlla per quanto tempo il livello iSCSI deve attendere che un percorso o una sessione scaduti si ristabiliscano prima di non riuscire a eseguire alcun comando su di essi. NetApp consiglia di impostare il valore di `replacement_timeout` a 120 nel file di configurazione iSCSI.

.Esempio
[listing]
----
# grep replacement_timeout /etc/iscsi/iscsid.conf
node.session.timeo.replacement_timeout = 120
----
--
====
. Impostare i valori "udev rport" dell'host per gli host delle serie RHEL 8 e 9 per supportare l'ambiente Veritas Infoscale negli scenari di failover dell'archiviazione.
+
Configurare i valori "udev rport" creando il file `/etc/udev/rules.d/40-rport.rules` con il seguente contenuto di file:

+
[listing]
----
# cat /etc/udev/rules.d/40-rport.rules
KERNEL=="rport-*", SUBSYSTEM=="fc_remote_ports", ACTION=="add", RUN+=/bin/sh -c 'echo 20 > /sys/class/fc_remote_ports/%k/fast_io_fail_tmo;echo 864000 >/sys/class/fc_remote_ports/%k/dev_loss_tmo'"
----
+

NOTE: Per tutte le altre impostazioni specifiche di Veritas, fare riferimento alla documentazione standard del prodotto Veritas Infoscale.

. Verificare le impostazioni dei parametri e lo stato del percorso dei LUN ONTAP:
+
Nelle configurazioni AFF, FAS o ASA , una singola LUN ONTAP non dovrebbe richiedere più di quattro percorsi. Più di quattro percorsi possono causare problemi in caso di guasto dell'archiviazione.

+
Gli esempi seguenti mostrano le impostazioni corrette dei parametri e lo stato del percorso per le LUN ONTAP in una configurazione ASA, AFF o FAS .

+
[role="tabbed-block"]
====
.Configurazione ASA
--
Una configurazione ASA ottimizza tutti i percorsi verso una determinata LUN, mantenendoli attivi. In questo modo, le performance vengono migliorate grazie alle operazioni di i/o in tutti i percorsi contemporaneamente.

.Mostra esempio
[%collapsible]
=====
[listing]
----
# vxdmpadm getsubpaths dmpnodename-sfrac0_47
NAME  STATE[A]   PATH-TYPE[M]   CTLR-NAME   ENCLR-TYPE  ENCLR-NAME  ATTRS  PRIORITY
===================================================================================
sdas  ENABLED (A)    Active/Optimized c13   SFRAC       sfrac0     -      -
sdb   ENABLED(A) Active/Optimized     c14   SFRAC       sfrac0     -      -
sdcj  ENABLED(A)  Active/Optimized     c14   SFRAC       sfrac0     -      -
sdea  ENABLED (A)    Active/Optimized c14   SFRAC       sfrac0     -
----
=====
--
.Configurazione AFF o FAS
--
Una configurazione AFF o FAS deve avere due gruppi di percorsi con priorità maggiore e minore. I percorsi Active/Optimized di priorità più elevata sono serviti dal controller in cui si trova l'aggregato. I percorsi a priorità inferiore sono attivi ma non ottimizzati perché serviti da un controller diverso. I percorsi non ottimizzati vengono utilizzati solo quando non sono disponibili percorsi ottimizzati.

L'esempio seguente visualizza l'output per una LUN ONTAP con due percorsi attivi/ottimizzati e due percorsi attivi/non ottimizzati:

.Mostra esempio
[%collapsible]
=====
[listing]
----
# vxdmpadm getsubpaths dmpnodename-sfrac0_47
NAME  STATE[A]   PATH-TYPE[M]   CTLR-NAME   ENCLR-TYPE  ENCLR-NAME  ATTRS  PRIORITY
===================================================================================
sdas  ENABLED     Active/Non-Optimized c13   SFRAC       sfrac0     -      -
sdb   ENABLED(A)  Active/Optimized     c14   SFRAC       sfrac0     -      -
sdcj  ENABLED(A)  Active/Optimized     c14   SFRAC       sfrac0     -      -
sdea  ENABLED     Active/Non-Optimized c14   SFRAC       sfrac0     -      -
----
=====
--
====




== Passaggio 4: Problemi noti

Non ci sono problemi noti.



== Quali sono le prossime novità?

* link:hu-luhu-command-reference.html["Informazioni sull'utilizzo dello strumento Linux host Utilities"] .

