---
sidebar: sidebar 
permalink: hu_aix_61.html 
keywords: host utilities, aix, powervm, vios, 3.1, 7.2 netapp, ontap 
summary: Descrive come utilizzare IBM AIX 7.2 e/o PowerVM VIOS 3.1 con ONTAP 
---
= Installare le utilità host AIX 6,1 per l'archiviazione ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Le utilità host AIX consentono di gestire lo storage ONTAP collegato a un host AIX.  NetApp consiglia vivamente di installare AIX Host Utilities per migliorare la gestione dello storage ONTAP e aiutare il supporto NetApp a raccogliere informazioni sulla configurazione.

AIX Host Utilities 6.1 supporta i seguenti protocolli di trasporto e ambienti AIX:

* FC, FCoE e iSCSI
* AIX Microsoft Multipath I/O (MPIO)
* PowerVM
+
Per ulteriori informazioni su PowerVM, consultare il Red Book IBM PowerVM Live Partition Mobility.



.A proposito di questa attività
* Per gestire l'archiviazione ONTAP collegata a un host AIX, è necessario installare AIX Host Utilities SAN Toolkit con AIX MPIO.
* Quando installi AIX Host Utilities, non viene modificata alcuna impostazione sul tuo host AIX.


.Prima di iniziare
* Utilizzare illink:https://mysupport.netapp.com/matrix/#welcome["Tool di matrice di interoperabilità"^] per verificare che il sistema operativo AIX, il protocollo e la versione ONTAP supportino l'avvio SAN.
* Abilita il tracciamento dinamico per tutti gli iniziatori FC e FCoE eseguendo il `chdev -l <fscsi_device> -a dyntrk=ye` comando sull'host AIX.


.Fasi
. Accedere al proprio host.
+
[role="tabbed-block"]
====
.AIX
--
Su un host AIX, accedere come *root*.

--
.PowerVM
--
Su un host PowerVM:

.. Accedi come *padmin*.
.. Diventa un utente root:
+
[source, cli]
----
oem_setup_env
----


--
====
. Accedere alla https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/6.1/downloads["Sito di supporto NetApp"^] E scaricare il file compresso contenente le utilità host in una directory dell'host.
. Accedere alla directory contenente il download.
. Decomprimere il file ed estrarre il pacchetto software DEL toolkit SAN.
+
[source, cli]
----
tar -xvf ntap_aix_host_utilities_6.1.tar.gz
----
+
La seguente directory viene creata quando si decomprime il file: `ntap_aix_host_utilities_6.1`. Questa directory avrà una delle seguenti sottodirectory: MPIO, NON_MPIO o SAN_Tool_Kit.

. Installare il MPIO AIX:
+
[source, cli]
----
installp -aXYd /var/tmp/ntap_aix_host_utilities_6.1/MPIO NetApp.MPIO_Host_Utilities_Kit
----
. Installare IL kit di strumenti SAN:
+
[source, cli]
----
installp -aXYd /var/tmp/ntap_aix_host_utilities_6.1/SAN_Tool_Kit NetApp.SAN_toolkit
----
. Riavviare l'host.
. Verificare l'installazione:
+
[source, cli]
----
sanlun version
----




== Quali sono le prossime novità?

link:hu-aix-san-toolkit.html["Scopri di più su AIX SAN Toolkit"] .
