---
sidebar: sidebar 
permalink: hu_aix_71.html 
keywords: host utilities, aix, 7.1 netapp, ontap 
summary: Descrive come utilizzare IBM AIX 7.1 con ONTAP 
---
= Utilizzare IBM AIX 7.1 con ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È possibile utilizzare le impostazioni di configurazione dell'host SAN ONTAP per configurare IBM AIX 7,1 con ONTAP come destinazione.



== Installare le Utility host AIX

È necessario installare il kit di utilità host AIX quando si utilizza AIX Microsoft Multipath i/o (MPIO) con l'archiviazione ONTAP.

È possibile scaricare il file compresso contenente i pacchetti software host Utilities dal link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/6.1/downloads["Sito di supporto NetApp"^]. Dopo aver scaricato il file, è necessario estrarlo per ottenere i due pacchetti software necessari per installare le utilità host.

.Fasi
. Accedere al proprio host.
+
** Su un host AIX, accedere come *root*.


. Scaricare una copia del file compresso contenente le utility host dal sito di supporto NetApp in una directory dell'host.
. Accedere alla directory contenente il download.
. Decomprimere il file ed estrarre il pacchetto software DEL toolkit SAN.
+
`tar -xvf ntap_aix_host_utilities_6.1.tar.tgz`

+
La seguente directory viene creata quando si decomprime il file: `ntap_aix_host_utilities_6.1`. Questa directory avrà una delle seguenti sottodirectory: MPIO, NON_MPIO o SAN_Tool_Kit.

. Installare il MPIO AIX:
+
`installp -aXYd /var/tmp/ntap_aix_host_utilities_6.1/MPIO NetApp.MPIO_Host_Utilities_Kit`

. Installare IL kit di strumenti SAN:
`installp -aXYd /var/tmp/ntap_aix_host_utilities_6.1/SAN_Tool_Kit NetApp.SAN_toolkit`
. Riavviare l'host.




== Toolkit SAN

L'installazione del pacchetto Utilità host NetApp installa automaticamente il toolkit. Questo kit fornisce l' `sanlun`utility, che consente di gestire LUN e HBA (host Bus Adapter). Il `sanlun` comando restituisce informazioni sui LUN mappati all'host, sul multipathing e sulle informazioni necessarie per creare gruppi iniziatori.

.Esempio
Nell'esempio seguente, il `sanlun lun show` Il comando restituisce le informazioni sul LUN.

[listing]
----
#sanlun lun show

controller(7mode)/                  device      host       lun
vserver(Cmode)    lun-pathname     filename    adapter   protocol   size   mode
--------------------------------------------------------------------------------
data_vserver      /vol/vol1/lun1    hdisk0      fcs0       FCP       60g    C
data_vserver      /vol/vol2/lun2    hdisk0      fcs0       FCP       20g    C
data_vserver      /vol/vol3/lun3    hdisk11     fcs0       FCP       20g    C
data_vserver      /vol/vol4/lun4    hdisk14     fcs0       FCP       20g    C

----


== Avvio SAN

.Prima di iniziare
Se si decide di utilizzare l'avvio SAN, questo deve essere supportato dalla configurazione. È possibile utilizzare link:https://imt.netapp.com/matrix/#welcome["Tool di matrice di interoperabilità"^]per verificare che il sistema operativo, l'HBA, il firmware dell'HBA e il BIOS di avvio dell'HBA e la versione ONTAP siano supportati.

L'avvio DELLA SAN è il processo di configurazione di un disco collegato ALLA SAN (un LUN) come dispositivo di avvio per un host AIX. È possibile impostare un LUN di avvio SAN per lavorare in un ambiente MPIO AIX che esegue le Utility host AIX con il protocollo FC o FCoE. Il metodo utilizzato per la creazione di UN LUN di avvio SAN e l'installazione di una nuova immagine del sistema operativo in un ambiente MPIO AIX può variare, a seconda del protocollo in uso.



== Multipathing

Multipathing consente di configurare più percorsi di rete tra l'host e il sistema di storage. In caso di guasto di un percorso, il traffico continua sui percorsi rimanenti. L'ambiente AIX di host Utilities utilizza la soluzione di multipathing nativa di AIX, MPIO.

Per AIX, il modulo di controllo del percorso (PCM) è responsabile del controllo di più percorsi. PCM è un codice fornito dal vendor dello storage che gestisce la gestione dei percorsi. Questa opzione viene installata e attivata come parte dell'installazione di Utility host.



=== Configurazioni non ASA

Per le configurazioni non ASA, devono essere presenti due gruppi di percorsi con priorità diverse. I percorsi con priorità più elevate sono attivi/ottimizzati. Ciò significa che vengono gestite dal controller in cui si trova l'aggregato. I percorsi con priorità più basse sono attivi ma non ottimizzati perché sono serviti da un controller diverso. I percorsi non ottimizzati vengono utilizzati solo quando i percorsi ottimizzati non sono disponibili.

.Esempio
Nell'esempio seguente viene visualizzato l'output corretto per un LUN ONTAP con due percorsi attivi/ottimizzati e due percorsi attivi/non ottimizzati.

[listing]
----
# sanlun lun show -p |grep -p hdisk78
                    ONTAP Path: vs_aix_clus:/vol/chataix_205p2_vol_en_1_7/jfs_205p2_lun_en
                           LUN: 37
                      LUN Size: 15g
                   Host Device: hdisk78
                          Mode: C
            Multipath Provider: AIX Native
        Multipathing Algorithm: round_robin
------- ---------- ------ ------- ---------- ----------
host    vserver    AIX                        AIX MPIO
path    path       MPIO   host    vserver         path
state   type       path   adapter LIF         priority
------- ---------- ------ ------- ---------- ----------
up      secondary  path0  fcs0    fc_aix_1        1
up      primary    path1  fcs0    fc_aix_2        1
up      primary    path2  fcs1    fc_aix_3        1
up      secondary  path3  fcs1    fc_aix_4        1

----


=== Tutte le configurazioni DEGLI array SAN

Tutte le configurazioni di array SAN (ASA) ottimizzano tutti i percorsi verso una determinata LUN, mantenendoli attivi. In questo modo, le performance vengono migliorate grazie alle operazioni di i/o in tutti i percorsi contemporaneamente.

.Esempio
Nell'esempio seguente viene visualizzato l'output corretto per un LUN ONTAP.


NOTE: Tutte le configurazioni DEGLI array SAN (ASA) sono supportate a partire da ONTAP 9.8 per gli host AIX.

[listing]
----
# sanlun lun show -p |grep -p hdisk78
                    ONTAP Path: vs_aix_clus:/vol/chataix_205p2_vol_en_1_7/jfs_205p2_lun_en
                           LUN: 37
                      LUN Size: 15g
                   Host Device: hdisk78
                          Mode: C
            Multipath Provider: AIX Native
        Multipathing Algorithm: round_robin
------ ------- ------ ------- --------- ----------
host   vserver  AIX                      AIX MPIO
path   path     MPIO   host    vserver     path
state  type     path   adapter LIF       priority
------ ------- ------ ------- --------- ----------
up     primary  path0  fcs0    fc_aix_1     1
up     primary  path1  fcs0    fc_aix_2     1
up     primary  path2  fcs1    fc_aix_3     1
up     primary  path3  fcs1    fc_aix_4     1
----


== Impostazioni consigliate

NetApp consiglia le seguenti impostazioni dei parametri per i LUN ONTAP. I parametri critici per i LUN ONTAP vengono impostati automaticamente dopo l'installazione del kit di utility host NetApp.

[cols="4*"]
|===
| Parametro | Ambiente | Valore per AIX | Nota 


| algoritmo | MPIO | round_robin | Impostato da host Utilities 


| hcheck_cmd | MPIO | richiesta | Impostato da host Utilities 


| hcheck_interval | MPIO | 30 | Impostato da host Utilities 


| hcheck_mode | MPIO | non attivo | Impostato da host Utilities 


| lun_reset_spt | MPIO / non MPIO | sì | Impostato da host Utilities 


| trasferimento_massimo | MPIO / non MPIO | LUN FC: 0x100000 byte | Impostato da host Utilities 


| qfull_dly | MPIO / non MPIO | ritardo di 2 secondi | Impostato da host Utilities 


| queue_depth | MPIO / non MPIO | 64 | Impostato da host Utilities 


| policy_di_riserva | MPIO / non MPIO | no_reserve | Impostato da host Utilities 


| re_timeout (disco) | MPIO / non MPIO | 30 secondi | Utilizza i valori predefiniti del sistema operativo 


| dintrk | MPIO / non MPIO | Sì | Utilizza i valori predefiniti del sistema operativo 


| fc_err_recov | MPIO / non MPIO | Fast_fail | Utilizza i valori predefiniti del sistema operativo 


| q_type | MPIO / non MPIO | semplice | Utilizza i valori predefiniti del sistema operativo 


| num_cmd_elems | MPIO / non MPIO | 1024 per AIX | FC EN1B, FC EN1C 


| num_cmd_elems | MPIO / non MPIO | 500 per AIX (standalone/fisico) 200 per VIOC | FC EN0G 
|===


== Impostazioni consigliate per MetroCluster

Per impostazione predefinita, il sistema operativo AIX applica un timeout i/o più breve quando non sono disponibili percorsi a un LUN. Questo potrebbe verificarsi in configurazioni come fabric SAN a switch singolo e configurazioni MetroCluster che presentano failover non pianificati. Per ulteriori informazioni e per le modifiche consigliate alle impostazioni predefinite, fare riferimento a. link:https://kb.netapp.com/app/answers/answer_view/a_id/1001318["NetApp KB1001318"^]



== Supporto AIX con sincronizzazione attiva SnapMirror

A partire da ONTAP 9.11.1, AIX è supportato con la sincronizzazione attiva SnapMirror. Con una configurazione AIX, il cluster primario è il cluster "attivo".

In una configurazione AIX, i failover sono disruptive. Con ogni failover, sarà necessario eseguire una nuova scansione sull'host per riprendere le operazioni di i/O.

Per configurare AIX per SM-BC, consultare l'articolo della Knowledge base link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapMirror/How_to_configure_an_AIX_host_for_SnapMirror_Business_Continuity_(SM-BC)["Come configurare un host AIX per la sincronizzazione attiva di SnapMirror"^].



== Problemi noti

Non ci sono problemi noti.
