---
sidebar: sidebar 
permalink: hu_aix_72_sanbooting_aix.html 
keywords: host utilities, aix, netapp, ontap, configure, discover, configuring, discovering 
summary: Descrive come rilevare e configurare I LUN con AIX 
---
= (AIX MPIO senza PowerVM) rilevamento e configurazione dei LUN con AIX
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Quando si utilizza AIX senza PowerVM, utilizzare il comando cfgmgr per ottenere all'host di rilevare le LUN. Non è necessario riavviare l'host per rilevare i LUN. Per confermare che l'host ha rilevato i LUN, è possibile utilizzare l'utility sanlun.


NOTE: I passaggi riportati di seguito non si applicano a un host che esegue un ambiente PowerVM.

.Fasi
. Accedere come root sull'host.
. Sull'host AIX, immettere il seguente comando per rilevare i LUN appena creati:
+
`cfgmgr`

+
Il `cfgmgr` il comando consente di:

+
** Gli iniziatori per accedere al fabric.
** Il sistema per verificare la presenza di nuovi dispositivi.
** Il sistema per creare nuove voci di dispositivo.


. Per visualizzare tutti i dischi AIX, inclusi i LUN NetApp, immettere il seguente comando:
+
`lsdev -Cc disk`

+
I LUN vengono visualizzati sull'host come dischi. È possibile utilizzare questi dischi nello stesso modo in cui si utilizzano i dischi locali sull'host. Il file ODM delle impostazioni host installato come parte delle utility host fa sì che le LUN vengano visualizzate come dischi FCP NetApp.

+
Annotare i numeri delle istanze di hdisk. Li si utilizza quando si esegue la configurazione del percorso.

+
Di seguito viene riportato il tipo di output prodotto dal comando lsdev -cc disk in un ambiente che utilizza FC.

+
[listing]
----
# lsdev -Cc disk
hdisk0 Available 08-08-00-5,0 16 Bit LVD SCSI Disk Drive
hdisk1 Available 08-08-00-8,0 16 Bit LVD SCSI Disk Drive
hdisk2 Available 04-08-02  MPIO NetApp FCP Default PCM Disk
hdisk3 Available 04-08-02  MPIO NetApp FCP Default PCM Disk
hdisk4 Available 04-08-02  MPIO NetApp FCP Default PCM Disk
hdisk5 Available 04-08-02  MPIO NetApp FCP Default PCM Disk
----
. Immettere il seguente comando per ottenere informazioni sulla configurazione:
+
`lsattr -El hdisk_name`

+
Questo comando produce il seguente output.

+
[listing]
----
# lsattr -El hdisk65
PCM   PCM/friend/NetApp   PCM Path Control Module          False
PR_key_value    none                             Persistant Reserve Key Value            True
algorithm       round_robin                      Algorithm                               True
clr_q           no                               Device CLEARS its Queue on error        True
dist_err_pcnt   0                                Distributed Error Sample Time           True
dist_tw_width   50                               Distributed Error Sample Time           True
hcheck_cmd      inquiry                          Health Check Command                    True
hcheck_interval 30                               Health Check Interval                   True
hcheck_mode     nonactive                        Health Check Mode                       True
location                                         Location Label                          True
lun_id          0x2000000000000                  Logical Unit Number ID                  False
lun_reset_spt   yes                              LUN Level Reset                         True
max_transfer    0x100000                         Maximum TRANSFER Size                   True
node_name       0x500a0980894ae0e0               FC Node Name                            False
pvid            00067fbad453a1da0000000000000000 Physical volume identifier              False
q_err           yes                              Use QERR bit                            True
q_type          simple                           Queuing TYPE                            True
qfull_dly       2                                Delay in seconds for SCSI TASK SET FULL True
queue_depth     64                               Queue DEPTH                             True
reassign_to     120                              REASSIGN time out value                 True
reserve_policy  no_reserve                       Reserve Policy                          True
rw_timeout      30                               READ/WRITE time out value               True
scsi_id         0xd10001                         SCSI ID                                 False
start_timeout   60                               START unit time out value               True
ww_name         0x500a0984994ae0e0               FC World Wide Name                      False
----
. Se la configurazione supporta ALUA, è possibile utilizzarla per impostare la priorità del percorso. Verificare che ALUA sia abilitato:
+
`lun igroup show -instance igroup_name`

+
.. Se ALUA non è abilitato, abilitarlo:
+
`igroup set igroup_name alua yes`



. Se la configurazione non supporta ALUA, è necessario eseguire l'utility dotpaths per impostare le priorità del percorso. L'utility dotpaths viene installata quando si installano le Utility host. Non utilizzare l'utility dotpaths se ALUA è attivato.
+
.. Per impostare la priorità per tutti i LUN Data ONTAP, immettere:
+
`dotpaths`

.. Per impostare la priorità per un set specifico di dischi, digitare:
+
`dotpaths [-hqv] [hdiskN ...]`

+
Utilizzare `-v` opzione per attivare la modalità dettagliata e visualizzare tutte le priorità. Utilizzare `-q` opzione per eseguire query su tutte le priorità dei dischi o su singole priorità.



. Per verificare che l'host abbia rilevato i LUN, immettere il seguente comando:
+
`# sanlun lun show`

+
.Esempio
Questo esempio mostra l'output tipico di `sanlun lun show` In un ambiente multipathing MPIO.

+
[listing]
----
sanlun lun show -p

                    ONTAP Path: fas3170-aix03:/vol/ibmbc_aix01b14_fcp_vol8/ibmbc-aix01b14_fcp_lun0
                           LUN: 8
                      LUN Size: 3g
           Controller CF State: Cluster Enabled
            Controller Partner: fas3170-aix04
                   Host Device: hdisk9
                          Mode: 7
            Multipath Provider: AIX Native
        Multipathing Algorithm: round_robin
--------- ----------- ------ ------- ---------------------------------------------- ----------
host      controller  AIX            controller                                     AIX MPIO
path      path        MPIO   host    target                                         path
state     type        path   adapter port                                           priority
--------- ----------- ------ ------- ---------------------------------------------- ----------
up        secondary   path0  fcs0    3b                                             1
up        primary     path1  fcs0    3a                                             1
up        secondary   path2  fcs0    3a                                             1
up        primary     path3  fcs0    3b                                             1
up        secondary   path4  fcs0    4b                                             1
up        secondary   path5  fcs0    4a                                             1
up        primary     path6  fcs0    4b                                             1
up        primary     path7  fcs0    4a                                             1
up        secondary   path8  fcs1    3b                                             1
up        primary     path9  fcs1    3a                                             1
up        secondary   path10 fcs1    3a                                             1
up        primary     path11 fcs1    3b                                             1
up        secondary   path12 fcs1    4b                                             1
up        secondary   path13 fcs1    4a                                             1
up        primary     path14 fcs1    4b                                             1
up        primary     path15 fcs1    4a                                             1
----

