---
sidebar: sidebar 
permalink: hu_aix_72_sanbooting_powervm_vscsi.html 
keywords: host utilities, aix, powervm, 7.2 netapp, ontap, luns, configure, discover, configuring, discovering 
summary: Descrive come utilizzare Discover e configurare LUN con PowerVM vSCSI 
---
= (PowerVM vSCSI) rilevamento e configurazione dei LUN
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Quando si utilizzano i server PowerVM vSCSI e VIO, è necessario utilizzare il login padmin e i comandi appropriati per configurare e rilevare le LUN.

.Fasi
. Accedere all'host come padmin.
. Sull'host AIX, immettere il seguente comando per rilevare i LUN appena creati:
+
`cfgdev`

+
Il comando cfgdev causa:

+
** Gli iniziatori per accedere al fabric.
** Il sistema per verificare la presenza di nuovi dispositivi.
** Il sistema consente di creare nuove voci di dispositivo in cui i nuovi LUN vengono mappati come dispositivi MPIO (Multipath i/o) Microsoft utilizzando il PCM predefinito.


. Per verificare che i dispositivi Hdisk MPIO siano stati creati, immettere il seguente comando:
+
`lsdev -type disk`

+
I LUN vengono visualizzati sull'host come dischi. È possibile utilizzare questi dischi nello stesso modo in cui si utilizzano i dischi locali sull'host.

+
Annotare i numeri delle istanze di hdisk. Li si utilizza quando si esegue la configurazione del percorso.

+
Il `lsdev -type disk` comando produce il seguente tipo di output. L'output nell'esempio seguente è troncato.

+
[listing]
----
vioserver$ lsdev -type disk NetApp
name     status      description
hdisk0   Available   16 Bit LVD SCSI Disk Drive
hdisk1   Available   16 Bit LVD SCSI Disk Drive
hdisk2   Available   MPIO NetApp FCP Default PCM Disk
hdisk3   Available   MPIO NetApp FCP Default PCM Disk
hdisk4   Available   MPIO NetApp FCP Default PCM Disk
hdisk5   Available   MPIO NetApp FCP Default PCM Disk
hdisk6   Available   MPIO NetApp FCP Default PCM Disk
----
. Recuperare le informazioni sulla configurazione:
+
`lsdev -dev hdisk_name -attr`

+
Il `lsdev -dev hdisk_name -attr` il comando produce il seguente output:

+
[listing]
----
vioserver$ lsdev -dev hdisk2 -attr
attribute value                   description                user-settable
PCM   PCM/friend/NetApp   PCM Path Control Module          False
PR_key_value    none                             Persistent Reserve Key Value            True
algorithm       round_robin                      Algorithm                               True
clr_q           no                               Device CLEARS its Queue on error        True
dist_err_pcnt   0                                Distributed Error Sample Time           True
dist_tw_width   50                               Distributed Error Sample Time           True
hcheck_cmd      inquiry                          Health Check Command                    True
hcheck_interval 30                               Health Check Interval                   True
hcheck_mode     nonactive                        Health Check Mode                       True
location                                         Location Label                          True
lun_id          0x2000000000000                  Logical Unit Number ID                  False
lun_reset_spt   yes                              LUN Level Reset                         True
max_transfer    0x100000                         Maximum TRANSFER Size                   True
node_name       0x500a0980894ae0e0               FC Node Name                            False
pvid            00067fbad453a1da0000000000000000 Physical volume identifier              False
q_err           yes                              Use QERR bit                            True
q_type          simple                           Queuing TYPE                            True
qfull_dly       2                                Delay in seconds for SCSI TASK SET FULL True
queue_depth     64                               Queue DEPTH                             True
reassign_to     120                              REASSIGN time out value                 True
reserve_policy  no_reserve                       Reserve Policy                          True
rw_timeout      30                               READ/WRITE time out value               True
scsi_id         0xd10001                         SCSI ID                                 False
start_timeout   60                               START unit time out value               True
ww_name         0x500a0984994ae0e0               FC World Wide Name                      False
----
. Se la configurazione non supporta ALUA, è necessario utilizzare l'utilità dotpath per impostare le priorità del percorso. L'utility dotpaths viene installata quando si installano le Utility host. Non utilizzare l'utility dotpaths se ALUA è attivato. Passare alla `oem_setup_env` modalità per eseguire i dotpath immettendo il seguente comando:
+
`oem_setup_env`

+
Quando si accede a. `oem_setup_env` il prompt della riga di comando passa da un simbolo del dollaro a un simbolo del cancelletto e rimane attivo `oem_setup_env` fino a quando non si arresta immettendo un comando come exit.

+
.Esempio
``# vioserver$ oem_setup_env`

. Se la configurazione supporta ALUA, è possibile utilizzarla per impostare la priorità del percorso. Verificare che ALUA sia abilitato:
+
`lun igroup show -instance igroup_name`

+
.. Se ALUA non è abilitato, abilitarlo:
+
`igroup set igroup_name alua yes`



. Se la configurazione non supporta ALUA, è necessario utilizzare l'utilità dotpath per impostare le priorità del percorso. L'utility dotpaths viene installata quando si installano le Utility host. Non utilizzare l'utility dotpaths se ALUA è attivato.
+
.. Per impostare la priorità per tutti i LUN ONTAP, immettere:
+
`dotpaths`

.. Per impostare la priorità per un set specifico di dischi, digitare:
+
`dotpaths [-hqv] [hdiskN ...]`

+
Utilizzare `-v` opzione per attivare la modalità dettagliata e visualizzare tutte le priorità. Utilizzare `-q` opzione per eseguire query su tutte le priorità dei dischi o su singole priorità.

+
Di seguito viene riportato un esempio di utilizzo dell'utilità dotpaths:

+
[listing]
----
vioserver# dotpaths -v
hdisk2 (path 0): Optimized path - Setting priority to 255
hdisk2 (path 1): Optimized path - Setting priority to 255
hdisk2 (path 2): Unoptimized path - Current priority of 1 is correct
hdisk2 (path 3): Unoptimized path - Current priority of 1 is correct
...
Path priority set and/or verified for 22 disks, 86 total paths.
vioserver#
----


. Per verificare che l'host abbia rilevato i LUN, immettere il seguente comando:
+
`# sanlun lun show -p`

+
.Esempio
Questo esempio mostra l'output tipico di `sanlun lun show -p` comando per una configurazione direct-attached. Include anche il `sanlun lun show -d hdisk9 -v` comando per visualizzare le informazioni su hdisk9. L'output di questo comando è stato troncato.

+
[listing]
----
sanlun lun show -p

                    ONTAP Path: fas3170-aix03:/vol/ibmbc_aix01b14_fcp_vol8/ibmbc-aix01b14_fcp_lun0
                           LUN: 8
                      LUN Size: 3g
           Controller CF State: Cluster Enabled
            Controller Partner: fas3170-aix04
                   Host Device: hdisk9
                          Mode: 7
            Multipath Provider: AIX Native
        Multipathing Algorithm: round_robin
--------- ----------- ------ ------- ------------- ----------
host      controller  AIX            controller    AIX MPIO
path      path        MPIO   host    target        path
state     type        path   adapter port          priority
--------- ----------- ------ ------- ------------- ----------
up        secondary   path0  fcs0    3b              1
up        primary     path1  fcs0    3a              1
up        secondary   path2  fcs0    3a              1
up        primary     path3  fcs0    3b              1
up        secondary   path4  fcs0    4b              1
up        secondary   path5  fcs0    4a              1
up        primary     path6  fcs0    4b              1
up        primary     path7  fcs0    4a              1
up        secondary   path8  fcs1    3b              1
up        primary     path9  fcs1    3a              1
up        secondary   path10 fcs1    3a              1
up        primary     path11 fcs1    3b              1
up        secondary   path12 fcs1    4b              1
up        secondary   path13 fcs1    4a              1
up        primary     path14 fcs1    4b              1
up        primary     path15 fcs1    4a              1
----
+
[listing]
----
sanlun lun show -vd hdisk10
                                                                      device          host                  lun
vserver              lun-pathname                                     filename        adapter    protocol   size    mode
------------------------------------------------------------------------------------------------------------------------
GPFS_p520_FC         /vol/GPFS_p520_FC_FlexVol_2/GPFS_p520_FC_LUN_2_4 hdisk10         fcs3       FCP        100g    C
             LUN Serial number: 1k/yM$-ia5HC
         Controller Model Name: N5600
          Vserver FCP nodename: 200200a0980c892f
          Vserver FCP portname: 200a00a0980c892f
              Vserver LIF name: GPFS_p520_FC_2
            Vserver IP address: 10.225.121.100
           Vserver volume name: GPFS_p520_FC_FlexVol_2  MSID::0x00000000000000000000000080000420
         Vserver snapshot name:
----

