---
sidebar: sidebar 
permalink: hu_citrix_7x.html 
keywords: host utilities, citrix, XenServer, 7 series, netapp, ontap, san, boot 
summary: Descrive come utilizzare Citrix XenServer 7.x con ONTAP 
---
= Utilizzo di Citrix XenServer con ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È possibile configurare le impostazioni di configurazione degli host SAN ONTAP per le release dei sistemi operativi Citrix XenServer 7 con protocolli FC, FCoE e iSCSI.



== Avvio SAN

.Di cosa hai bisogno
Se si decide di utilizzare l'avvio SAN, questo deve essere supportato dalla configurazione. È possibile utilizzare link:https://mysupport.netapp.com/matrix/imt.jsp?components=91241;&solution=236&isHWU&src=IMT["Tool di matrice di interoperabilità NetApp"^] Per verificare che il sistema operativo, l'HBA, il firmware dell'HBA, il BIOS di avvio dell'HBA e la versione di ONTAP siano supportati.

.Fasi
. Mappare il LUN di avvio SAN sull'host.
. Verificare che siano disponibili più percorsi.
+

NOTE: Più percorsi diventano disponibili dopo che il sistema operativo host è attivo e in esecuzione sui percorsi.

. Abilitare l'avvio SAN nel BIOS del server per le porte a cui è mappato il LUN di avvio SAN.
+
Per informazioni su come attivare il BIOS HBA, consultare la documentazione specifica del vendor.

. Riavviare l'host per verificare che l'avvio sia stato eseguito correttamente.




== Multipathing

Il supporto multipath in Citrix XenServer si basa sui componenti multipath di Device Mapper. I nodi Device mapper non vengono creati automaticamente per tutte le LUN presentate a XenServer e vengono forniti solo quando le LUN vengono utilizzate attivamente dall'API (Storage Management Layer). Il plug-in API di Citrix XenServer Storage Manager gestisce automaticamente l'attivazione e la disattivazione dei nodi multipath.

A causa delle incompatibilità con l'architettura Integrated multipath Management, Citrix consiglia di utilizzare l'applicazione Citrix XenCenter per la gestione della configurazione dello storage. Se è necessario eseguire una query manuale sullo stato delle tabelle Device Mapper o elencare i nodi multipath attivi del device mapper nel sistema, è possibile utilizzare `/sbin/mpathutil status` Per verificare le impostazioni dei LUN ONTAP. Per ulteriori informazioni, consultare la documentazione standard del vendor per Citrix XenServer.



=== Configurazioni non ASA

Per le configurazioni non ASA, devono essere presenti due gruppi di percorsi con priorità diverse. I percorsi con priorità più elevate sono Active/Optimized, ovvero gestiti dal controller in cui si trova l'aggregato. I percorsi con priorità più basse sono attivi ma non ottimizzati perché sono serviti da un controller diverso. I percorsi non ottimizzati vengono utilizzati solo quando i percorsi ottimizzati non sono disponibili.

.Esempio
Nell'esempio seguente viene visualizzato l'output corretto per un LUN ONTAP con due percorsi attivi/ottimizzati e due percorsi attivi/non ottimizzati:

[listing]
----
# mpathutil status
show topology
3600a098038303458772450714535317a dm-0 NETAPP  , LUN C-Mode
size=80G features='4 queue_if_no_path pg_init_retries 50 retain_attached_hw_handle' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| |- 2:0:2:0   sdc   8:32    active ready running
| |- 12:0:5:0  sdn   8:208   active ready running
| |- 2:0:6:0   sdg   8:96    active ready running
| `- 12:0:0:0  sdi   8:128   active ready running
|-+- policy='service-time 0' prio=10 status=enabled
  |- 2:0:0:0   sda   8:0     active ready running
  |- 2:0:1:0   sdb   8:16    active ready running
  |- 12:0:3:0  sd1   8:176   active ready running
  `-12:0:6:0   sdo   8:224   active ready running
[root@sanhost ~]#
----

NOTE: Un singolo LUN non deve richiedere più di quattro percorsi. La presenza di più di quattro percorsi potrebbe causare problemi di percorso durante gli errori di storage.



=== Configurazione di tutti gli array SAN

In tutte le configurazioni array SAN (ASA), tutti i percorsi verso una determinata unità logica (LUN) sono attivi e ottimizzati. Ciò significa che l'i/o può essere servito contemporaneamente attraverso tutti i percorsi, consentendo in tal modo migliori performance.

.Esempio
Nell'esempio seguente viene visualizzato l'output corretto per un LUN ONTAP con tutti e quattro i percorsi attivi/ottimizzati:

[listing]
----
# mpathutil status
show topology
3600a098038303458772450714535317a dm-0 NETAPP  , LUN C-Mode
size=80G features='4 queue_if_no_path pg_init_retries 50 retain_attached_hw_handle' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| |- 2:0:2:0   sdc   8:32    active ready running
| |- 12:0:5:0  sdn   8:208   active ready running
| |- 2:0:6:0   sdg   8:96    active ready running
| `- 12:0:0:0  sdi   8:128   active ready running
[root@sanhost ~]#
----

NOTE: Un singolo LUN non deve richiedere più di quattro percorsi. La presenza di più di quattro percorsi potrebbe causare problemi di percorso durante gli errori di storage.



=== Impostazioni consigliate

Il sistema operativo Citrix XenServer 7.x viene compilato con tutte le impostazioni necessarie per riconoscere e gestire correttamente le LUN ONTAP. Per Citrix XenServer 7.x, un zero obyte vuoto `/etc/multipath.conf` il file deve esistere, ma non è necessario apportare modifiche specifiche al file.

Abilitare il servizio multipath host da *XenCenter Management Portal* e verificare che il servizio multipath sia attivato e in esecuzione.

[listing]
----
# systemct1 status multipathd
multipathd.service - Device-Mapper Multipath Device Controller
  Loaded:  load (/usr/lib/systemd/system/multipathd.service; enabled; vendor preset: enabled)
 Drop-In:  /etc/systemd/system/multipathd.service.d
             slice.config
  Active:  active (running) since Fri YYYY-MM-DD 00:00:26 IST; 1 month 9 days ago
Main PID:  3789 (multipathd)
  CGroup:  /control.slice/multipathd.service
            3789  /sbin/multipathd
----
Non è necessario aggiungere contenuto al `/etc/multipath.conf` file, a meno che non si disponga di dispositivi che non si desidera gestire multipath o di impostazioni esistenti che sovrascrivono le impostazioni predefinite. È possibile aggiungere al `multipath.conf` file la seguente sintassi per escludere le periferiche indesiderate.

[listing]
----
# cat /etc/multipath.conf
blacklist {
     wwid    <DevId>
     devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
     devnode "^hd[a-z]"
     devnode "^cciss.*"
}
----

NOTE: Sostituire *<DevID>* con la stringa WWID del dispositivo che si desidera escludere.

.Esempio
Nell'esempio seguente per Citrix XenServer 7.x, `sda` è il disco SCSI locale che si desidera aggiungere alla blacklist.

. Eseguire il seguente comando per determinare l'ID WWID:
+
[listing]
----
# lib/udev/scsi_id -gud /dev/sda
3600a098038303458772450714535317a
----
. Aggiungere questo WWID alla lista nera in `/etc/multipath.conf`:
+
[listing]
----
#cat /etc/multipath.conf
blacklist {
  wwid    3600a098038303458772450714535317a
  devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9*]"
  devnode "^hd[a-z]"
  devnode "^cciss.*"
}
----


Fare riferimento alla configurazione di runtime del parametro multipath utilizzando `$multipathd show config` comando. Controllare sempre la configurazione in esecuzione per individuare le impostazioni legacy che potrebbero prevalere sulle impostazioni predefinite, in particolare nella sezione delle impostazioni predefinite.

La seguente tabella mostra i parametri critici *multipath* per i LUN ONTAP e i valori richiesti. Se un host è connesso a LUN di altri vendor e uno qualsiasi di questi parametri viene ignorato, è necessario correggerli con le successive stanze in *multipath.conf* che si applicano specificamente alle LUN ONTAP. In caso contrario, i LUN ONTAP potrebbero non funzionare come previsto. Le seguenti impostazioni predefinite devono essere ignorate solo previa consultazione di NetApp e/o del vendor del sistema operativo e solo quando l'impatto è pienamente compreso.

[cols="2*"]
|===
| Parametro | Impostazione 


| `detect_prio` | sì 


| `dev_loss_tmo` | "infinito" 


| `failback` | immediato 


| `fast_io_fail_tmo` | 5 


| `features` | "3 queue_if_no_path pg_init_retries 50" 


| `flush_on_last_del` | "sì" 


| `hardware_handler` | "0" 


| `path_checker` | "a" 


| `path_grouping_policy` | "group_by_prio" 


| `path_selector` | "tempo di servizio 0" 


| `polling_interval` | 5 


| `prio` | "ONTAP" 


| `product` | LUN.* 


| `retain_attached_hw_handler` | sì 


| `rr_weight` | "uniforme" 


| `user_friendly_names` | no 


| `vendor` | NETAPP 
|===
.Esempio
Nell'esempio seguente viene illustrato come correggere un valore predefinito sovrascritto. In questo caso, il file *multipath.conf* definisce i valori per *path_checker* e *detect_prio* non compatibili con le LUN ONTAP. Se non possono essere rimossi a causa di altri array SAN collegati all'host, questi parametri possono essere corretti specificamente per i LUN ONTAP con un dispositivo.

[listing]
----
# cat /etc/multipath.conf
defaults {
  path_checker readsector0
  detect_prio no
}
devices{
        device{
                vendor "NETAPP "
                product "LUN.*"
                path_checker tur
                detect_prio yes
        }
}
----

NOTE: Citrix XenServer consiglia l'utilizzo dei tool Citrix VM per tutte le macchine virtuali guest basate su Linux e Windows per una configurazione supportata.



== Problemi noti

Non vi sono problemi noti per la versione Citrix XenServer con ONTAP.
