---
sidebar: sidebar 
permalink: hu_hpux_11iv3.html 
keywords: host utilities, hp_ux, 11iv3, netapp, ontap 
summary: Descrive come utilizzare IBM AIX 7.2 e/o PowerVM VIOS 3.1 con ONTAP 
---
= Utilizzo di HP-UX 11i v3 con NetApp ONTAP
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content




== Installazione delle utility host HP-UX

È possibile scaricare il file compresso contenente i pacchetti software host Utilities dal NetApp Support Site. Una volta ottenuto il file, è necessario decomprimerlo per ottenere i pacchetti software necessari per installare le Utility host.

.Fasi
. Scaricare una copia del file compresso contenente le utility host da link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab["Sito di supporto NetApp"^] a una directory sull'host.
. Accedere alla directory contenente il download.
. Decomprimere il file.
+
`gunzip netapp_hpux_host_utilities_6.0_ia_pa.depot.gz`

. Immettere il seguente comando per installare il software:
+
`swinstall -s /netapp_hpux_host_utilities_6.0_ia_pa.depot NetApp_santoolkit`

. Riavviare l'host.




== Toolkit SAN

Il toolkit viene installato automaticamente quando si installa il pacchetto NetApp host Utilities. Questo kit fornisce `sanlun` Utility che consente di gestire LUN e HBA. Il `sanlun` Il comando restituisce le informazioni relative alle LUN mappate all'host, al multipathing e alle informazioni necessarie per creare gruppi di iniziatori.

.Esempio
Nell'esempio seguente, il `sanlun lun show` Il comando restituisce le informazioni sul LUN.

[listing]
----
#sanlun lun show

controller(7mode)/                            device                         host     lun
vserver(Cmode)    lun-pathname               filename                       adapter protocol  size  mode
--------------------------------------------------------------------------------
sanboot_unix      /vol/hpux_215_boot_en_0/goot_hpux_215_lun /dev/rdsk/c11t0d0 fcd0   FCP      150g   C
sanboot_unix      /vol/hpux_215_boot_en_0/goot_hpux_215_lun /dev/rdsk/c24t0d0 fcd1   FCP      150g   C
sanboot_unix      /vol/hpux_215_boot_en_0/goot_hpux_215_lun /dev/rdsk/c21t0d0 fcd1   FCP      150g   C
sanboot_unix      /vol/hpux_215_boot_en_0/goot_hpux_215_lun /dev/rdsk/c12t0d0 fcd0   FCP      150g   C
----


== Avvio SAN

.Di cosa hai bisogno
Se si decide di utilizzare l'avvio SAN, questo deve essere supportato dalla configurazione. È possibile utilizzare link:https://mysupport.netapp.com/matrix/imt.jsp?components=71102;&solution=1&isHWU&src=IMT["Tool di matrice di interoperabilità NetApp"^] Per verificare che il sistema operativo, l'HBA, il firmware dell'HBA, il BIOS di avvio dell'HBA e la versione di ONTAP siano supportati.

L'avvio DELLA SAN è il processo di configurazione di un disco collegato ALLA SAN (un LUN) come dispositivo di avvio per un host HP-UX. Le utility host supportano l'avvio SAN con protocolli FC e FCoE in ambienti HP-UX.



== Multipathing

Multipathing consente di configurare più percorsi di rete tra l'host e il sistema di storage. In caso di guasto di un percorso, il traffico continua sui percorsi rimanenti. Per consentire a un host di avere più percorsi verso un LUN, è necessario attivare il multipathing. Le utility host HP-UX supportano diverse soluzioni di multipathing in base alla configurazione. Di seguito viene riportata la soluzione di multipathing nativo.



=== Configurazione non ASA

Per le configurazioni non ASA, devono essere presenti due gruppi di percorsi con priorità diverse. I percorsi con priorità più elevate sono Active/Optimized, ovvero vengono serviti dal controller in cui si trova l'aggregato. I percorsi con priorità inferiori sono attivi ma non ottimizzati perché vengono serviti da un controller diverso. I percorsi non ottimizzati vengono utilizzati solo quando non sono disponibili percorsi ottimizzati.

.Esempio
Nell'esempio seguente viene visualizzato l'output corretto per un LUN ONTAP con due percorsi attivi/ottimizzati e due percorsi attivi/non ottimizzati:

[listing]
----
# sanlun lun show -p vs39:/vol/vol24_3_0/lun24_0
                    ONTAP Path: vs39:/vol/vol24_3_0/lun24_0
                           LUN: 37
                      LUN Size: 15g
                   Host Device: /dev/rdisk/disk942
                          Mode: C
              Multipath Policy: A/A
            Multipath Provider: Native
------- ---------- ------ ------- ---------- ---------- --------------
host    vserver     /dev/dsk                            HP A/A
path    path        filename          host    vserver   path failover
state   type        or hardware path adapter    LIF     priority
------- ---------- ------ ------- ---------- ---------- --------------
up       primary    /dev/dsk/c39t4d5   fcd0    hpux_3     0
up       primary    /dev/dsk/c41t4d5   fcd1    hpux_4     0
up       secondary  /dev/dsk/c40t4d5   fcd0    hpux_3     1
up       secondary  /dev/dsk/c42t4d5   fcd1    hpux_4     1
----


=== Tutte le configurazioni DEGLI array SAN

Nelle configurazioni ASA, tutti i percorsi verso una determinata LUN sono attivi e ottimizzati. In questo modo, le performance vengono migliorate grazie alle operazioni di i/o in tutti i percorsi contemporaneamente.

.Esempio
Nell'esempio seguente viene visualizzato l'output corretto per un LUN ONTAP:


NOTE: Tutte le configurazioni array SAN (ASA) sono supportate a partire da ONTAP 9.8 per HP-UX 11iv3

[listing]
----
# sanlun lun show -p vs39:/vol/hpux_vol_1_1/hpux_lun

                    ONTAP Path: vs39:/vol/hpux_vol_1_1/hpux_lun
                           LUN: 2
                      LUN Size: 30g
                   Host Device: /dev/rdisk/disk25
                          Mode: C
            Multipath Provider: None
-------- ---------- -------------------- ------- --------------
host     vserver    /dev/dsk
path     path       filename             host    vserver
state    type       or hardware path     adapter LIF
-------- ---------- -------------------- ------- --------------
up       primary    /dev/dsk/c4t0d2      fcd0    248_1c_hp
up       primary    /dev/dsk/c6t0d2      fcd0    246_1c_hp
up       primary    /dev/dsk/c10t0d2     fcd1    246_1d_hp
up       primary    /dev/dsk/c8t0d2      fcd1    248_1d_hp
----


== Impostazioni consigliate

Di seguito sono riportate alcune impostazioni dei parametri consigliate per i LUN HPUX 11i v3 e NetApp ONTAP. NetApp utilizza le impostazioni predefinite per HP-UX.

[cols="2*"]
|===
| Parametro | Utilizza il valore predefinito 


| transitori_sec | 120 


| leg_mpath_enable | VERO 


| profondità_q_max | 8 


| path_fail_secs | 120 


| load_bal_policy | Round_robin 


| lua_enabled | VERO 


| esd_secs | 30 
|===


== Problemi e limitazioni noti

[cols="4*"]
|===
| ID bug NetApp | Titolo | Descrizione | ID partner 


| 1447287 | L'evento AUFO sul cluster master isolato nella configurazione SM-BC causa un'interruzione temporanea dell'host HP-UX | Questo problema si verifica quando si verifica un evento AUFO (Unplanned failover) automatico sul cluster master isolato nella configurazione di SnapMirror Business Continuity (SM-BC). Potrebbero essere necessari più di 120 secondi per il ripristino dell'i/o sull'host HP-UX, ma ciò potrebbe non causare interruzioni dell'i/o o messaggi di errore. Questo problema causa un errore di doppio evento perché la connessione tra il cluster primario e il cluster secondario viene persa e anche la connessione tra il cluster primario e il mediatore viene persa. Questo è considerato un evento raro, a differenza di altri eventi AUFO. | NA 


| 1344935 | L'host HP-UX 11.31 segnala in modo intermittente lo stato del percorso in modo errato durante l'installazione di ASA. | Problemi di reporting del percorso con la configurazione ASA. | NA 


| 1306354 | HP-UX LVM Creation invia i/o di dimensioni del blocco superiori a 1 MB | La lunghezza massima di trasferimento SCSI di 1 MB viene applicata in tutti gli array SAN ONTAP. Per limitare la lunghezza di trasferimento massima dagli host HP-UX quando connessi a tutti gli array SAN ONTAP, è necessario impostare la dimensione i/o massima consentita dal sottosistema SCSI HP-UX su 1 MB. Per ulteriori informazioni, consultare la documentazione del fornitore HP-UX. | NA 
|===