---
sidebar: sidebar 
permalink: hu_hpux_60.html 
keywords: host utilities, unified, oracle, linux, 7.1, netapp, ontap 
summary: Viene descritto come utilizzare le utilità host unificate HP-UX 6,0 con ONTAP 
---
= Utility host HP-UX 6.0
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Le utilità host HP-UX consentono di collegare un host HP-UX allo storage NetApp.

Le utilità host HP-UX supportano più protocolli e i seguenti ambienti:

* MPIO nativo
* Veritas Dynamic Multipathing (DMP)



NOTE: Per indicare l'ambiente utilizzato, in questo documento vengono talvolta specificati "DMP" per l'ambiente Veritas DMP e "MPIO" per l'ambiente nativo HP-UX. In alcuni casi, i comandi utilizzati potrebbero variare a seconda dei driver utilizzati. In questi casi, vengono specificati sia l'ambiente che i tipi di driver.

.Di cosa hai bisogno
* Per un funzionamento affidabile, verificare che sia supportata l'intera configurazione iSCSI, FC o FCoE.


È possibile utilizzare link:https://mysupport.netapp.com/matrix/imt.jsp?components=71102;&solution=1&isHWU&src=IMT["Tool di matrice di interoperabilità NetApp"^] per verificare la configurazione.

.A proposito di questa attività
Il pacchetto software NetApp HP-UX host Utilities è disponibile sul sito link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/6.0/downloads["Sito di supporto NetApp"^] in un file compresso. Dopo aver scaricato il file, è necessario decomprimerlo prima dell'installazione.

.Fasi
. Accedere al proprio host.
. Scaricare il file HP-UX host Utilities `netapp_hpux_host_utilities_6.0_ia_pa.depot.gz` dal link:https://mysupport.netapp.com/site/["Sito di supporto NetApp"^] All'host HP-UX.
. Decomprimere `netapp_hpux_host_utilities_6.0_ia_pa.depot.gz` file:
+
`# gunzip netapp_hpux_host_utilities_6.0_ia_pa.depot.gz`

+
Il sistema inserisce il software estratto nella directory in cui è stato decompresso il file di depot.

. Installare il software:
+
`# swinstall -s /depot_path`

+
`depot_path` fornisce il percorso e il nome del file di deposito.

+
Il `swinstall` Command esegue uno script di installazione che verifica lo stato dell'installazione di HP-UX. Se il sistema soddisfa i requisiti, questo script installa `sanlun` script di utilità e diagnostica in `/opt/NetApp/santools/bin` directory.

. Verificare l'installazione:
+
`sanlun version`





== Toolkit SAN

HP-UX host Utilities è un software host NetApp che fornisce un kit di strumenti a riga di comando sull'host HP-UX. Il toolkit viene installato quando si installa il pacchetto NetApp host Utilities. Questo kit fornisce `sanlun` Che consente di gestire i LUN e gli adattatori bus host. (HBA). Il `sanlun` Il comando restituisce le informazioni relative alle LUN mappate all'host, al multipathing e alle informazioni necessarie per creare gruppi di iniziatori.

.Esempio
Nell'esempio seguente, il `sanlun lun show` Il comando restituisce le informazioni del LUN.

[listing]
----
# sanlun lun show all

controller(7mode)/ device host lun
vserver(Cmode)           lun-pathname                   filename          adapter    protocol   size   mode
------------------------------------------------------------------------------------------------------------
sanboot_unix         /vol/hpux_boot/boot_hpux_lun      /dev/rdsk/c34t0d0  fclp1      FCP        150g    C
sanboot_unix         /vol/hpux_boot/boot_hpux_lun      /dev/rdsk/c23t0d0  fclp1      FCP        150g    C
sanboot_unix         /vol/hpux_boot/boot_hpux_lun      /dev/rdsk/c12t0d0  fclp0      FCP        150g    C
sanboot_unix         /vol/hpux_boot/boot_hpux_lun      /dev/rdsk/c81t0d0  fclp0      FCP        150g    C

----

NOTE: Questo toolkit è comune a tutte le configurazioni e i protocolli delle utilità host. Di conseguenza, alcuni contenuti si applicano a una configurazione, ma non a un'altra. La presenza di componenti inutilizzati non influisce sulle prestazioni del sistema.
