---
sidebar: sidebar 
permalink: hu_hpux_60.html 
keywords: host utilities, unified, oracle, linux, 7.1, netapp, ontap 
summary: 'Viene descritto come utilizzare le utilità host HP-UX 6,0 con l"archiviazione ONTAP' 
---
= Installare le utilità host HP-UX 6,0 per l'archiviazione ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Le utility host HP-UX consentono di gestire lo storage ONTAP collegato a un host HP-UX.  NetApp consiglia vivamente di installare HP-UX Host Utilities, ma non è obbligatorio.  Le utilità migliorano la gestione e aiutano l'assistenza clienti NetApp a raccogliere informazioni sulla configurazione.

Le utility host HP-UX supportano i seguenti ambienti:

* Multipath i/o Microsoft nativo (MPIO)
* Veritas Dynamic Multipathing (DMP)


.Prima di iniziare
Per un funzionamento affidabile, utilizzare il https://imt.netapp.com/matrix/#welcome["Tool di matrice di interoperabilità"^] per verificare che la configurazione iSCSI, FC o FCoE sia supportata.

.Fasi
. Accedi al tuo host HP-UX.
. Scaricare il file HP-UX host Utilities `netapp_hpux_host_utilities_6.0_ia_pa.depot.gz` dal link:https://mysupport.netapp.com/site/["Sito di supporto NetApp"^] All'host HP-UX.
. Decomprimere `netapp_hpux_host_utilities_6.0_ia_pa.depot.gz` file:
+
[source, cli]
----
gunzip netapp_hpux_host_utilities_6.0_ia_pa.depot.gz
----
+
Il sistema inserisce il software estratto nella directory in cui è stato decompresso il file di depot.

. Installare il software:
+
[source, cli]
----
swinstall -s /depot_path
----
+
`depot_path` fornisce il percorso e il nome del file di deposito.

+
Il `swinstall` Command esegue uno script di installazione che verifica lo stato dell'installazione di HP-UX. Se il sistema soddisfa i requisiti, questo script installa `sanlun` script di utilità e diagnostica in `/opt/NetApp/santools/bin` directory.

. Verificare l'installazione:
+
[source, cli]
----
sanlun version
----




== Quali sono le prossime novità?

link:hu-hpux-sanlun-toolkit.html["Scopri di più sul SAN Toolkit"] .
