---
sidebar: sidebar 
permalink: hu_hpux_11iv3.html 
keywords: host utilities, hp_ux, 11iv3, netapp, ontap 
summary: Installare Linux Host Utilities su un host HP-UX 11i v3 per gestire le operazioni del protocollo FCP e iSCSI con LUN ONTAP . 
---
= Configurare HP-UX 11i v3 per FCP e iSCSI con storage ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Il software HP-UX Host Utilities fornisce strumenti di gestione e diagnostica per gli host HP-UX connessi allo storage ONTAP .  Quando si installano le utility host HP-UX su un host HP-UX 11i v3, è possibile utilizzare le utility host per gestire le operazioni del protocollo FCP e iSCSI con LUN ONTAP .



== Passaggio 1: Se lo si desidera, attivare l'avvio SAN

Configura l'host per utilizzare l'avvio SAN per semplificare la distribuzione e migliorare la scalabilità.  L'avvio SAN è il processo di configurazione di un disco collegato a SAN (un LUN) come dispositivo di avvio per un host HP-UX.  Le Host Utilities supportano l'avvio SAN con protocolli FC e FCoE negli ambienti HP-UX.

.Fasi
. Utilizzare link:https://mysupport.netapp.com/matrix/#welcome["Tool di matrice di interoperabilità"^]per verificare che il sistema operativo Linux, l'HBA (host Bus Adapter), il firmware HBA, il BIOS di avvio HBA e la versione ONTAP supportino l'avvio SAN.
. Seguire le best practice per la configurazione di un avvio SAN nella documentazione del fornitore HP-UX.




== Passaggio 2: installare le utility host HP-UX

NetApp consiglia vivamente di installare HP-UX Host Utilities per supportare la gestione ONTAP LUN e assistere il supporto tecnico nella raccolta dei dati di configurazione.

link:hu_hpux_60.html["Installare le utilità host HP-UX 6,0"]



== Fase 3: Verificare la configurazione multipath per l'host

Utilizzare il multipathing con HP-UX 11i v3 per gestire le LUN ONTAP .  Il multipathing consente di configurare più percorsi di rete tra l'host e il sistema di archiviazione.  Se un percorso fallisce, il traffico prosegue sui percorsi rimanenti.

Dopo aver installato HP-UX Host Utilities, verificare di aver configurato le impostazioni consigliate da NetApp per i LUN ONTAP .

.A proposito di questa attività
Le utility host HP-UX supportano Native Microsoft Multipath I/O (MPIO) e Veritas Dynamic Multipathing.  I passaggi seguenti sono per la soluzione MPIO nativa.

.Fasi
. Quando si installano le HP-UX Host Utilities, le seguenti impostazioni predefinite consigliate vengono caricate automaticamente per i LUN ONTAP .
+
.Mostra impostazioni parametri
[%collapsible]
====
[cols="2*"]
|===
| Parametro | Utilizza il valore predefinito 


| transitori_sec | 120 


| leg_mpath_enable | VERO 


| profondità_q_max | 8 


| path_fail_secs | 120 


| load_bal_policy | Round_robin 


| lua_enabled | VERO 


| esd_secs | 30 
|===
====
. Verificare le impostazioni dei parametri e lo stato del percorso dei LUN ONTAP:
+
[source, cli]
----
sanlun lun show
----
+
I parametri multipath predefiniti supportano le configurazioni ASA, AFF e FAS .  Gli output di esempio seguenti mostrano le impostazioni corrette dei parametri e lo stato del percorso per le LUN ONTAP in una configurazione ASA, AFF o FAS .

+
[role="tabbed-block"]
====
.Configurazione ASA
--
Una configurazione ASA ottimizza tutti i percorsi verso una determinata LUN, mantenendoli attivi. In questo modo, le performance vengono migliorate grazie alle operazioni di i/o in tutti i percorsi contemporaneamente.

[listing]
----
# sanlun lun show -p vs39:/vol/hpux_vol_1_1/hpux_lun

                    ONTAP Path: vs39:/vol/hpux_vol_1_1/hpux_lun
                           LUN: 2
                      LUN Size: 30g
                   Host Device: /dev/rdisk/disk25
                          Mode: C
            Multipath Provider: None
-------- ---------- -------------------- ------- --------------
host     vserver    /dev/dsk
path     path       filename             host    vserver
state    type       or hardware path     adapter LIF
-------- ---------- -------------------- ------- --------------
up       primary    /dev/dsk/c4t0d2      fcd0    248_1c_hp
up       primary    /dev/dsk/c6t0d2      fcd0    246_1c_hp
up       primary    /dev/dsk/c10t0d2     fcd1    246_1d_hp
up       primary    /dev/dsk/c8t0d2      fcd1    248_1d_hp
----
--
.Configurazione AFF o FAS
--
Una configurazione AFF o FAS deve avere due gruppi di percorsi con priorità maggiore e minore. I percorsi Active/Optimized di priorità più elevata sono serviti dal controller in cui si trova l'aggregato. I percorsi a priorità inferiore sono attivi ma non ottimizzati perché serviti da un controller diverso. I percorsi non ottimizzati vengono utilizzati solo quando non sono disponibili percorsi ottimizzati.

L'esempio seguente visualizza l'output per una LUN ONTAP con due percorsi attivi/ottimizzati e due percorsi attivi/non ottimizzati:

[listing]
----
# sanlun lun show -p vs39:/vol/vol24_3_0/lun24_0
                    ONTAP Path: vs39:/vol/vol24_3_0/lun24_0
                           LUN: 37
                      LUN Size: 15g
                   Host Device: /dev/rdisk/disk942
                          Mode: C
              Multipath Policy: A/A
            Multipath Provider: Native
------- ---------- ------ ------- ---------- ---------- --------------
host    vserver     /dev/dsk                            HP A/A
path    path        filename          host    vserver   path failover
state   type        or hardware path adapter    LIF     priority
------- ---------- ------ ------- ---------- ---------- --------------
up       primary    /dev/dsk/c39t4d5   fcd0    hpux_3     0
up       primary    /dev/dsk/c41t4d5   fcd1    hpux_4     0
up       secondary  /dev/dsk/c40t4d5   fcd0    hpux_3     1
up       secondary  /dev/dsk/c42t4d5   fcd1    hpux_4     1
----
--
====




== Passaggio 4: rivedere i problemi noti

La versione HP-UX 11i v3 con storage ONTAP presenta i seguenti problemi noti:

[cols="4*"]
|===
| ID bug NetApp | Titolo | Descrizione | ID partner 


| 1447287 | L'evento AUFO sul cluster master isolato nella configurazione di sincronizzazione attiva di SnapMirror causa un'interruzione temporanea sull'host HP-UX | Questo problema si verifica in presenza di un evento di failover automatico non pianificato (AUFO) sul cluster master isolato nella configurazione con sincronizzazione attiva di SnapMirror. Potrebbero essere necessari più di 120 secondi per il ripristino dell'i/o sull'host HP-UX, ma ciò potrebbe non causare interruzioni dell'i/o o messaggi di errore. Questo problema causa un errore di doppio evento perché la connessione tra il cluster primario e il cluster secondario viene persa e anche la connessione tra il cluster primario e il mediatore viene persa. Questo è considerato un evento raro, a differenza di altri eventi AUFO. | NA 


| 1344935 | L'host HP-UX 11.31 segnala in modo intermittente lo stato del percorso in modo errato durante l'installazione di ASA. | Problemi di reporting del percorso con la configurazione ASA. | NA 


| 1306354 | HP-UX LVM Creation invia i/o di dimensioni del blocco superiori a 1 MB | La lunghezza massima di trasferimento SCSI di 1 MB viene applicata in tutti gli array SAN ONTAP. Per limitare la lunghezza di trasferimento massima dagli host HP-UX quando connessi a tutti gli array SAN ONTAP, è necessario impostare la dimensione i/o massima consentita dal sottosistema SCSI HP-UX su 1 MB. Per ulteriori informazioni, consultare la documentazione del fornitore HP-UX. | NA 
|===


== Cosa c'è dopo?

link:hu_hpux_60_cmd.html["Scopri come utilizzare lo strumento HP-UX Host Utilities"] .
