---
sidebar: sidebar 
permalink: hu_hpux_60.html 
keywords: host utilities, unified, oracle, linux, 7.1, netapp, ontap 
summary: Descrive come utilizzare le utility host unificate Linux 7.1 con ONTAP 
---
= Utility host HP-UX 6.0
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


.Di cosa hai bisogno
* Per un funzionamento affidabile, è necessario verificare che l'intera configurazione iSCSI, FC o FCoE sia supportata.


È possibile utilizzare link:https://mysupport.netapp.com/matrix/imt.jsp?components=71102;&solution=1&isHWU&src=IMT["Tool di matrice di interoperabilità NetApp"^] per verificare la configurazione.



== Toolkit SAN

HP-UX host Utilities è un software host NetApp che fornisce un kit di strumenti a riga di comando sull'host HP-UX. Il toolkit viene installato quando si installa il pacchetto NetApp host Utilities. Questo kit fornisce `sanlun` Utility che consente di gestire LUN e HBA. Il `sanlun` Il comando restituisce le informazioni relative alle LUN mappate all'host, al multipathing e alle informazioni necessarie per creare gruppi di iniziatori.

.Esempio
Nell'esempio seguente, il `sanlun lun show` Il comando restituisce le informazioni del LUN.

[listing]
----
# sanlun lun show all

controller(7mode)/ device host lun
vserver(Cmode)           lun-pathname                   filename          adapter    protocol   size   mode
------------------------------------------------------------------------------------------------------------
sanboot_unix         /vol/hpux_boot/boot_hpux_lun      /dev/rdsk/c34t0d0  fclp1      FCP        150g    C
sanboot_unix         /vol/hpux_boot/boot_hpux_lun      /dev/rdsk/c23t0d0  fclp1      FCP        150g    C
sanboot_unix         /vol/hpux_boot/boot_hpux_lun      /dev/rdsk/c12t0d0  fclp0      FCP        150g    C
sanboot_unix         /vol/hpux_boot/boot_hpux_lun      /dev/rdsk/c81t0d0  fclp0      FCP        150g    C

----

NOTE: Questo toolkit è comune a tutte le configurazioni e protocolli delle utility host. Di conseguenza, alcuni contenuti si applicano a una configurazione, ma non a un'altra. La presenza di componenti inutilizzati non influisce sulle prestazioni del sistema.



== Installazione delle utility host HP-UX

Il pacchetto software NetApp HP-UX host Utilities è disponibile sul sito link:https://mysupport.netapp.com/site/["Sito di supporto NetApp"^] in un file compresso.

È possibile scaricare il file compresso contenente i pacchetti software di Utility host da link:https://mysupport.netapp.com/site/["Sito di supporto NetApp"^]. Dopo aver scaricato il file, è necessario decomprimerlo prima dell'installazione.

.Fasi
. Accedere all'host.
. Scaricare il file HP-UX host Utilities `netapp_hpux_host_utilities_6.0_ia_pa.depot.gz` dal link:https://mysupport.netapp.com/site/["Sito di supporto NetApp"^] All'host HP-UX.
. Decomprimere `netapp_hpux_host_utilities_6.0_ia_pa.depot.gz` immettere il seguente comando:
+
`# gunzip netapp_hpux_host_utilities_6.0_ia_pa.depot.gz`

+
Il sistema inserisce il software estratto nella directory in cui è stato decompresso il file di depot.

. Installare il software immettendo il seguente comando:
+
`# swinstall -s /depot_path`

+
`depot_path` fornisce il percorso e il nome del file di deposito.

+
Il `swinstall` Command esegue uno script di installazione che verifica lo stato dell'installazione di HP-UX. Se il sistema soddisfa i requisiti, questo script installa `sanlun` script di utilità e diagnostica in `/opt/NetApp/santools/bin` directory.

. Verificare l'installazione:
+
`sanlun version`





== Esempio di riferimento al comando



=== Elenca tutti gli iniziatori host mappati all'host

[listing]
----
# sanlun fcp show adapter -v
adapter name:      fclp2
WWPN:              10000000c985ef92
WWNN:              20000000c985ef92
driver name:       fclp
model:             AJ763-63001
model description: HP 8Gb Dual Channel PCI-e 2.0 FC HBA
serial number:     MY19034N9U
hardware version:  3
driver version:    @(#) FCLP: PCIe Fibre Channel driver (FibrChanl-02), B.11.31.1805, Feb  5 2018, FCLP_IFC (3,2)
firmware version:  2.02X2 SLI-3 (U3D2.02X2)
Number of ports:   1 of 2
port type:         Unknown
port state:        Link Down
supported speed:   8 GBit/sec
negotiated speed:  Speed not established
OS device name:    /dev/fclp2

adapter name:      fclp3
WWPN:              10000000c985ef93
WWNN:              20000000c985ef93
driver name:       fclp
model:             AJ763-63001
model description: HP 8Gb Dual Channel PCI-e 2.0 FC HBA
serial number:     MY19034N9U
hardware version:  3
driver version:    @(#) FCLP: PCIe Fibre Channel driver (FibrChanl-02), B.11.31.1805, Feb  5 2018, FCLP_IFC (3,2)
firmware version:  2.02X2 SLI-3 (U3D2.02X2)
Number of ports:   2 of 2
port type:         Unknown
port state:        Link Down
supported speed:   8 GBit/sec
negotiated speed:  Speed not established
OS device name:    /dev/fclp3
----


=== Elenca tutti i LUN mappati all'host

[listing]
----
# sanlun lun show -p -v all
\
                    ONTAP Path: vs_hp_cluster:/vol/chathpux_217_vol_en_1_10/hp_en_217_lun
                           LUN: 55
                      LUN Size: 15g
                   Host Device: /dev/rdisk/disk718
                          Mode: C
                            VG: /dev/vg_data
              Multipath Policy: A/A
            Multipath Provider: Native
-------- ---------- -------------------- ------- ---------------------------------------------- -------------
host     vserver    /dev/dsk                                                                    HP A/A
path     path       filename             host    vserver                                        path failover
state    type       or hardware path     adapter LIF                                            priority
-------- ---------- -------------------- ------- ---------------------------------------------- -------------
up       primary    /dev/dsk/c37t6d7     fclp0   hpux_7                                         0
up       primary    /dev/dsk/c22t6d7     fclp1   hpux_8                                         0
up       secondary  /dev/dsk/c36t6d7     fclp0   hpux_5                                         1
up       secondary  /dev/dsk/c44t6d7     fclp1   hpux_6                                         1

----


=== Elencare tutti i LUN mappati all'host da una SVM specifica

[listing]
----
# sanlun lun show -p -v vs_hp_cluster
                    ONTAP Path: vs_hp_cluster:/vol/chathpux_217_vol_en_1_10/hp_en_217_lun
                           LUN: 55
                      LUN Size: 15g
                   Host Device: /dev/rdisk/disk718
                          Mode: C
                            VG: /dev/vg_data
              Multipath Policy: A/A
            Multipath Provider: Native
-------- ---------- -------------------- ------- ---------------------------------------------- -------------
host     vserver    /dev/dsk                                                                    HP A/A
path     path       filename             host    vserver                                        path failover
state    type       or hardware path     adapter LIF                                            priority
-------- ---------- -------------------- ------- ---------------------------------------------- -------------
up       primary    /dev/dsk/c37t6d7     fclp0   hpux_7                                         0
up       primary    /dev/dsk/c22t6d7     fclp1   hpux_8                                         0
up       secondary  /dev/dsk/c36t6d7     fclp0   hpux_5                                         1
up       secondary  /dev/dsk/c44t6d7     fclp1   hpux_6                                         1

----


=== Elencare tutti gli attributi di un LUN assegnato all'host

[listing]
----

# sanlun lun show -p -v vs_hp_cluster:/vol/chathpux_217_vol_en_1_5/hp_en_217_lun

                    ONTAP Path: vs_hp_cluster:/vol/chathpux_217_vol_en_1_5/hp_en_217_lun
                           LUN: 49
                      LUN Size: 15g
                   Host Device: /dev/rdisk/disk712
                          Mode: C
                            VG: /dev/vg_data
              Multipath Policy: A/A
            Multipath Provider: Native
-------- ---------- -------------------- ------- ---------------------------------------------- -------------
host     vserver    /dev/dsk                                                                    HP A/A
path     path       filename             host    vserver                                        path failover
state    type       or hardware path     adapter LIF                                            priority
-------- ---------- -------------------- ------- ---------------------------------------------- -------------
up       primary    /dev/dsk/c37t6d1     fclp0   hpux_7                                         0
up       primary    /dev/dsk/c22t6d1     fclp1   hpux_8                                         0
up       secondary  /dev/dsk/c36t6d1     fclp0   hpux_5                                         1
up       secondary  /dev/dsk/c44t6d1     fclp1   hpux_6                                         1

----


=== Elencare gli attributi del LUN ONTAP in base al nome del file del dispositivo host

[listing]
----
#sanlun lun show -dv /dev/rdisk/disk716
                                                                 device             host                  lun
vserver              lun-pathname                                filename           adapter    protocol   size    mode
----------------------------------------------------------------------------------------------------------------------
vs_hp_cluster        /vol/chathpux_217_vol_en_1_14/hp_en_217_lun /dev/rdisk/disk716 0          FCP        15g     C
             LUN Serial number: 80D7l?NiNP5U
         Controller Model Name: AFF-A800
          Vserver FCP nodename: 208400a098ba7afe
          Vserver FCP portname: 207e00a098ba7afe
              Vserver LIF name: hpux_5
            Vserver IP address: 10.141.54.30
                                10.141.54.35
                                10.141.54.37
                                10.141.54.33
                                10.141.54.31
           Vserver volume name: chathpux_217_vol_en_1_14        MSID::0x00000000000000000000000080915935
         Vserver snapshot name:
----


=== Elenca tutte le WWPN LIF di destinazione SVM collegate all'host

[listing]
----
# sanlun lun show -wwpn

controller(7mode)/
vserver(Cmode)       target wwpn        lun-pathname                                  device filename
--------------------------------------------------------------------------------------------------------
vs_hp_cluster        208300a098ba7afe   /vol/chathpux_217_vol_en_1_10/hp_en_217_lun   /dev/rdsk/c22t6d7
vs_hp_cluster        208100a098ba7afe   /vol/chathpux_217_vol_en_1_10/hp_en_217_lun   /dev/rdsk/c44t6d7
vs_hp_cluster        208200a098ba7afe   /vol/chathpux_217_vol_en_1_10/hp_en_217_lun   /dev/rdsk/c37t6d7
vs_hp_cluster        207e00a098ba7afe   /vol/chathpux_217_vol_en_1_10/hp_en_217_lun   /dev/rdsk/c36t6d7
vs_hp_cluster        207d00a098ba7afe   /vol/chathpux_217_os/hp_217_os                /dev/rdsk/c18t7d4
vs_hp_cluster        207f00a098ba7afe   /vol/chathpux_217_os/hp_217_os                /dev/rdsk/c42t7d4

host adapter    lun size    mode
---------------------------------
fclp1           15g         C
fclp1           15g         C
fclp0           15g         C
fclp0           15g         C
fclp1           30g         C
fclp0           30g         C
----