---
sidebar: sidebar 
permalink: hu_luhu_71.html 
keywords: host utilities, unified, oracle, linux, 7.1, netapp, ontap 
summary: Descrive come utilizzare le utility host unificate Linux 7.1 con ONTAP 
---
= Installare Linux Unified host Utilities 7.1
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
LUHU (Linux Unified host Utilities) consente di gestire lo storage NetApp ONTAP collegato a un host Linux. NetApp consiglia vivamente di installare le utility host unificate Linux, ma non è obbligatorio. Le utility non modificano le impostazioni dell'host Linux. Le utility migliorano la gestione e assistono il supporto clienti NetApp nella raccolta di informazioni sulla configurazione.

Sono supportate le seguenti distribuzioni Linux:

* Red Hat Enterprise Linux
* SUSE Linux Enterprise Server
* Oracle Linux
* Macchina virtuale Oracle
* Citrix XenServer


.Di cosa hai bisogno
Il pacchetto software NetApp Linux Unified host Utilities è disponibile su link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["Sito di supporto NetApp"^] in un file .rpm a 32 bit o a 64 bit.

* Per un funzionamento affidabile, è necessario verificare che l'intera configurazione iSCSI, FC o FCoE sia supportata.
+
È possibile utilizzare https://mysupport.netapp.com/matrix/imt.jsp?components=65623;64703;&solution=1&isHWU&src=IMT["Tool di matrice di interoperabilità NetApp"^] per verificare la configurazione.

* È necessario installare i pacchetti di gestione HBA (host bus adapter) disponibili sul sito di supporto del vendor.
+
Il software di gestione consente ai comandi DEL toolkit SAN di raccogliere informazioni sugli HBA FC, ad esempio le WWPN. Per `sanlun fcp show adapter` per funzionare, verificare che i seguenti pacchetti siano installati correttamente:

+
** Marvell QLogic HBA – CLI QConvergeConsole
** HBA Broadcom Emulex - CLI dell'applicazione principale di OneCommand Manager
** HBA Brocade Marvell - CLI dell'utility Brocade Command


* RPM i pacchetti "libhbaapi" e "libhbalinux" disponibili per ogni distribuzione Linux devono essere installati sul sistema operativo host.



NOTE: Il software Linux Unified host Utilities non supporta i protocolli host NVMe over Fibre Channel (NVMe/FC) e NVMe over TCP (NVMe/TCP).

.Fasi
. Se si dispone di una versione di Linux Unified host Utilities attualmente installata, utilizzare il seguente comando per rimuoverla:
+
[source, cli]
----
rpm -e netapp_linux_unified_host_utilities-7-1
----
+
Per le versioni precedenti di Linux host Utilities, accedere alla directory in cui è installato il software dell'utility host e immettere il comando di disinstallazione per rimuovere il pacchetto installato.

. Scaricare il pacchetto software di utilità host unificate Linux a 32 bit o 64 bit dal link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["Sito di supporto NetApp"^] al tuo host.
. Accedere alla directory in cui è stato scaricato il pacchetto software e utilizzare il seguente comando per installarlo:
+
[source, cli]
----
rpm -ivh netapp_linux_unified_host_utilities-7-1.x86_xx.rpm
----
+
*Esempio di output*

+
[listing]
----
Verifying...                          ################################# [100%]
Preparing...                          ################################# [100%]
Updating / installing...
   1:netapp_linux_unified_host_utiliti################################# [100%]
----
. Verificare l'installazione:
+
[source, cli]
----
sanlun version
----
+
*Esempio di output*

+
[listing]
----
sanlun version 7.1.386.1644
----




== Impostazioni consigliate per i driver con kernel Linux

Quando si configura un ambiente FC che utilizza driver nativi della posta in arrivo forniti con il kernel Linux, è possibile utilizzare i valori predefiniti per i driver.



== Toolkit SAN

Linux Unified host Utilities è un software host NetApp che fornisce un kit di strumenti a riga di comando sul vostro host Linux.

Il toolkit viene installato automaticamente quando si installa il pacchetto NetApp host Utilities. Questo kit fornisce `sanlun` Utility che consente di gestire LUN e HBA. Il `sanlun` Il comando restituisce le informazioni relative alle LUN mappate all'host, al multipathing e alle informazioni necessarie per creare gruppi di iniziatori.

.Esempio
Nell'esempio seguente, il `sanlun lun show` Il comando restituisce le informazioni sul LUN.

[source, cli]
----
# sanlun lun show all
----
Output di esempio:

[listing]
----
controller(7mode/E-Series)/            device     host               lun
vserver(cDOT/FlashRay)   lun-pathname  filename   adapter  protocol  size    Product
------------------------------------------------------------------------------------
data_vserver          /vol/vol1/lun1   /dev/sdb   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol1/lun1   /dev/sdc   host15   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sdd   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sde   host15   FCP       120.0g  cDOT
----
[NOTE]
====
* Questo toolkit è comune a tutte le configurazioni e protocolli delle utility host. Di conseguenza, alcuni contenuti si applicano a una configurazione, ma non a un'altra. La presenza di componenti inutilizzati non influisce sulle prestazioni del sistema.
* IL toolkit SAN non è supportato su Citrix XenServer, Oracle VM e Red Hat Enterprise Virtualization Hypervisor.


====