---
sidebar: sidebar 
permalink: hu_luhu_71_rn.html 
keywords: host utilities, linux, 7.1, netapp, ontap, release, notes, linux 
summary: Note sulla versione per le utility host unificate Linux 7.1 
---
= Linux Unified host Utilities 7.1 - Note di release
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Le note di rilascio descrivono nuove funzionalità e miglioramenti, problemi e limitazioni noti e importanti precauzioni per la configurazione e la gestione dell'host specifico con il sistema di storage ONTAP.

Per informazioni specifiche sulle versioni e sugli aggiornamenti del sistema operativo supportati dalle utility host, consultare link:https://mysupport.netapp.com/matrix/imt.jsp?components=65623;64703;&solution=1&isHWU&src=IMT["Tool di matrice di interoperabilità NetApp"^].



== Novità

La versione 7.1 di Linux host Utilities contiene le seguenti nuove funzionalità e miglioramenti:

* Le utility host Linux sono ora denominate _Utilità host unificate Linux_ perché supportano i sistemi storage NetApp e-Series con SANtricity e i sistemi AFF, FAS e ASA con ONTAP.
+

NOTE: Qualsiasi citazione di host Utilities o Linux host Utilities in questo documento si riferisce a Linux Unified host Utilities.

* Sono ora supportati i seguenti sistemi operativi:
+
** SUSE Linux Enterprise Server serie 15
** Oracle VM serie 3.2
** Oracle Linux serie 6 e 7
** Red Hat Enterprise Linux serie 6 e 7
** SUSE Linux Enterprise Server 11 SP4
** KVM e XEN, RHEV 6.4 e 6.5
** Citrix XenServer


* Sugli host Red Hat Enterprise Linux (RHEL) 6 e RHEL 7 è ora supportato un pacchetto ottimizzato per l'impostazione dei profili server. È possibile utilizzare `tuned-adm` comando per impostare profili diversi, a seconda dell'ambiente. Ad esempio, è possibile utilizzare il profilo guest virtuale come macchina virtuale guest e il profilo storage aziendale per le configurazioni in cui vengono utilizzate le LUN degli array storage aziendali. L'utilizzo di questi pacchetti ottimizzati può comportare un miglioramento del throughput e della latenza in ONTAP.
* Aggiunge il supporto per gli adattatori FC da 32 GB di Broadcom Emulex e Marvell Qlogic.



NOTE: NetApp continua a lavorare con le utility host per aggiungere il supporto per le funzionalità dopo la release iniziale. Per informazioni aggiornate sulle funzioni supportate e sulle nuove funzionalità aggiunte, consultare la link:https://mysupport.netapp.com/matrix/imt.jsp?components=65623;64703;&solution=1&isHWU&src=IMT["Tool di matrice di interoperabilità NetApp"^].



== Risolto in questa versione

Il problema intermittente del sistema operativo host che si verifica durante l'esecuzione di `sanlun lun show -p` Il comando in SLES12SP1, OL7.2, RHEL7.2 e RHEL 6.8 è stato corretto in questa versione.



== Problemi e limitazioni noti

La versione 7.1 di Linux host Utilities presenta i seguenti problemi e limitazioni noti.

[cols="10, 30, 30"]
|===
| ID bug NetApp | Titolo | Descrizione 


| 1457017 |  `sanlun` problemi di installazione messaggi di avviso relativi a. `libdevmapper.so` e. `libnl.so` librerie. Queste avvertenze non influiscono sulla funzionalità di `sanlun` kit. | Quando si esegue il comando CLI di Linux Unified host Utilities - "sanlun fcp show adapter -v" su un host SAN, il comando non riesce e viene visualizzato un messaggio di errore che indica che le dipendenze della libreria richieste per un rilevamento HBA (host bus adapter) non possono essere
situato:

[root@hostname ~] nel sanlun fcp show adapter -v
Impossibile individuare la libreria /usr/lib64/libHBAAPI.so
Assicurarsi che il pacchetto che installa la libreria sia installato e caricato
Fare riferimento a NetApp Bugs online - link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/1508554["1508554"^]. 
|===
link:https://mysupport.netapp.com/site/bugs-online/product["NetApp Bugs Online"^] fornisce informazioni complete sui problemi più noti, incluse le soluzioni consigliate, se possibile.
