---
sidebar: sidebar 
permalink: hu_luhu_71.html 
keywords: host utilities, unified, oracle, linux, 7.1, netapp, ontap 
summary: Viene descritto come utilizzare le utilità host Linux 7,1 con ONTAP 
---
= Installa Linux Host Utilities 7.1 per l'archiviazione ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Le Linux Host Utilities aiutano a gestire lo storage ONTAP collegato a un host Linux.  NetApp consiglia vivamente di installare Linux Host Utilities, ma non è obbligatorio.  Le utilità migliorano la gestione e aiutano l'assistenza clienti NetApp a raccogliere informazioni sulla configurazione.

Linux Host Utilities 7.1 supporta i seguenti tipi di distribuzione:

* Red Hat Enterprise Linux
* SUSE Linux Enterprise Server
* Oracle Linux
* Macchina virtuale Oracle
* Citrix XenServer



NOTE: Il software delle utilità host Linux non supporta i protocolli host NVMe over Fibre Channel (NVMe/FC) e NVMe over TCP (NVMe/TCP).

.A proposito di questa attività
Quando installi Linux Host Utilities, non viene modificata alcuna impostazione sul tuo host Linux.

.Prima di iniziare
* Per un funzionamento affidabile, utilizzare illink:https://imt.netapp.com/matrix/#welcome["Tool di matrice di interoperabilità"^] per verificare che la configurazione iSCSI, FC o FCoE sia supportata.
* Installare i pacchetti di gestione dell'adattatore bus host (HBA) disponibili sul sito di supporto del fornitore.  Il software di gestione consente di `sanlun` comandi per raccogliere informazioni sugli HBA FC, come i loro WWPN.
+
Fare riferimento alla documentazione del fornitore per verificare che i seguenti pacchetti siano installati correttamente.  Questi pacchetti sono necessari per supportare il `sanlun fcp show adapter` comando:

+
** Marvell QLogic HBA – CLI QConvergeConsole
** HBA Broadcom Emulex - CLI dell'applicazione principale di OneCommand Manager
** HBA Brocade Marvell - CLI dell'utility Brocade Command


* Installare i pacchetti RPM "libhbaapi" e "libhbalinux" disponibili per ogni distribuzione Linux sul sistema operativo host Linux.


.Fasi
. Se è attualmente installata una versione di Linux Host Utilities, rimuoverla:
+
[source, cli]
----
rpm -e netapp_linux_unified_host_utilities-7-1
----
+
Per le versioni precedenti di Linux host Utilities, andare alla directory in cui è installato il software dell'utilità host e immettere il comando di disinstallazione per rimuovere il pacchetto installato.

. Scaricare il pacchetto software Linux host Utilities a 32 o 64 bit dal al proprio hostlink:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["Sito di supporto NetApp"^].
. Vai alla directory in cui hai scaricato il pacchetto software e installalo:
+
[source, cli]
----
rpm -ivh netapp_linux_unified_host_utilities-7-1.x86_xx.rpm
----
+
Dovresti vedere un output simile al seguente esempio:

+
[listing]
----
Verifying...                          ################################# [100%]
Preparing...                          ################################# [100%]
Updating / installing...
   1:netapp_linux_unified_host_utiliti################################# [100%]
----
. Verificare l'installazione:
+
[source, cli]
----
sanlun version
----
+
Dovresti vedere un output simile al seguente esempio:

+
[listing]
----
sanlun version 7.1.386.1644
----




== Quali sono le prossime novità?

* Impostazioni consigliate per i driver con kernel Linux
+
Quando si configura un ambiente FC che utilizza driver nativi della posta in arrivo forniti con il kernel Linux, è possibile utilizzare i valori predefiniti per i driver.

* link:hu-luhu-sanlun-utility.html["Scopri di più sull'utilità "sanlun""] .

