---
sidebar: sidebar 
permalink: hu_ol_64.html 
keywords: host utilities, oracle, linux, 6.4, netapp, ontap 
summary: Descrive come utilizzare Oracle Linux 6.4 con ONTAP 
---
= Utilizza Oracle Linux 6.4 con ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È possibile utilizzare le impostazioni di configurazione dell'host SAN di ONTAP per configurare Oracle Linux 6,4 con ONTAP come destinazione.



== Installare le utilità host Linux

Il pacchetto software NetApp Linux host Utilities è disponibile su link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["Sito di supporto NetApp"^]in un file .rpm a 32 bit e a 64 bit. Se non si conosce il file adatto alla configurazione, utilizzare per verificare quale file è link:https://mysupport.netapp.com/matrix/#welcome["Tool di matrice di interoperabilità"^]necessario.

NetApp consiglia vivamente di installare le utilità host Linux, ma non è obbligatorio. Le utility non modificano alcuna impostazione sul vostro host Linux. Le utility migliorano la gestione e assistono il supporto clienti NetApp nella raccolta di informazioni sulla configurazione.

Se avete installato Linux host Utilities, è necessario aggiornarlo alla versione più recente, oppure rimuoverlo e seguire questi passaggi per installare la versione più recente.

.Fasi
. Scaricare il pacchetto software Linux host Utilities a 32 o 64 bit dal al proprio hostlink:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["Sito di supporto NetApp"^].
. Installare il pacchetto software:
+
`rpm -ivh netapp_linux_unified_host_utilities-7-1.x86_64`





== Toolkit SAN

Il toolkit viene installato automaticamente quando si installa il pacchetto NetApp host Utilities. Questo kit fornisce `sanlun` Utility che consente di gestire LUN e HBA. Il `sanlun` Il comando restituisce le informazioni relative alle LUN mappate all'host, al multipathing e alle informazioni necessarie per creare gruppi di iniziatori.

.Esempio
Nell'esempio seguente, il `sanlun lun show` Il comando restituisce le informazioni sul LUN.

[source, cli]
----
# sanlun lun show all
----
Output di esempio:

[listing]
----
controller(7mode/E-Series)/            device     host               lun
vserver(cDOT/FlashRay)   lun-pathname  filename   adapter  protocol  size    Product
------------------------------------------------------------------------------------
data_vserver          /vol/vol1/lun1   /dev/sdb   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol1/lun1   /dev/sdc   host15   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sdd   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sde   host15   FCP       120.0g  cDOT
----


== Avvio SAN

.Prima di iniziare
Se si decide di utilizzare l'avvio SAN, questo deve essere supportato dalla configurazione. È possibile utilizzare link:https://imt.netapp.com/matrix/#welcome["Tool di matrice di interoperabilità"^]per verificare che il sistema operativo, l'HBA, il firmware dell'HBA e il BIOS di avvio dell'HBA e la versione ONTAP siano supportati.

.Fasi
. Mappare il LUN di avvio SAN sull'host.
. Verificare che siano disponibili più percorsi.
+

NOTE: Una volta attivato il sistema operativo host e eseguito sui percorsi, diventano disponibili più percorsi.

. Abilitare l'avvio SAN nel BIOS del server per le porte a cui è mappato il LUN di avvio SAN.
+
Per informazioni su come attivare il BIOS HBA, consultare la documentazione specifica del vendor.

. Riavviare l'host per verificare che l'avvio sia stato eseguito correttamente.




== Multipathing

Per Oracle Linux 6.4 il file /etc/multipath.conf deve esistere, ma non è necessario apportare modifiche specifiche al file. Oracle Linux 6.4 è compilato con tutte le impostazioni necessarie per riconoscere e gestire correttamente le LUN ONTAP. Per attivare ALUA Handler, attenersi alla seguente procedura:

.Fasi
. Creare un backup dell'immagine initrd.
. Aggiungere il seguente valore del parametro al kernel per far funzionare ALUA e non ALUA:
`rdloaddriver=scsi_dh_alua`
+
....
kernel /vmlinuz-3.8.13-68.1.2.el6uek.x86_64 ro root=/dev/mapper/vg_ibmx3550m421096-lv_root rd_NO_LUKSrd_LVM_LV=vg_ibmx3550m421096/lv_root LANG=en_US.UTF-8 rd_NO_MDSYSFONT=latarcyrheb-sun16 crashkernel=256M KEYBOARDTYPE=pc KEYTABLE=us rd_LVM_LV=vg_ibmx3550m421096/lv_swap rd_NO_DM rhgb quiet rdloaddriver=scsi_dh_alua
....
. Utilizzare `mkinitrd` comando per ricreare l'immagine initrd. Oracle 6x e le versioni successive utilizzano: Il comando: `mkinitrd -f /boot/ initrd-"uname -r".img uname -r`Oppure il comando: `dracut -f`
. Riavviare l'host.
. Verificare l'output del `cat /proc/cmdline` comando per assicurarsi che l'impostazione sia completa. Il `multipath -ll` comando consente di verificare le impostazioni dei LUN di ONTAP. Ci dovrebbero essere due gruppi di percorsi con priorità diverse. I percorsi con priorità più elevate sono attivi/ottimizzati. Ciò significa che vengono gestite dal controller in cui si trova l'aggregato. I percorsi con priorità più basse sono attivi ma non ottimizzati perché sono serviti da un controller diverso. I percorsi non ottimizzati vengono utilizzati solo quando i percorsi ottimizzati non sono disponibili.


.Esempio
Nell'esempio seguente viene visualizzato l'output corretto per un LUN ONTAP con due percorsi attivi/ottimizzati e due percorsi attivi/non ottimizzati:

[listing]
----
# multipath -ll
3600a09803831347657244e527766394e dm-5 NETAPP,LUN C-Mode
size=80G features='4 queue_if_no_path pg_init_retries 50 retain_attached_hw_handle' hwhandler='1 alua' wp=rw
|-+- policy='round-robin 0' prio=50 status=active
| |- 0:0:26:37 sdje 8:384   active ready running
| |- 0:0:25:37 sdik 135:64  active ready running
|-+- policy='round-robin 0' prio=10 status=enabled
  |- 0:0:18:37 sdda 70:128  active ready running
  |- 0:0:19:37 sddu 71:192  active ready running
----

NOTE: Un singolo LUN non deve richiedere più di quattro percorsi. La presenza di più di quattro percorsi potrebbe causare problemi di percorso durante gli errori di storage.



== Impostazioni consigliate

Il sistema operativo Oracle Linux 6.4 viene compilato per riconoscere le LUN ONTAP e impostare automaticamente correttamente tutti i parametri di configurazione.

Il `multipath.conf` file deve esistere per avviare il daemon multipath. Se questo file non esiste, è possibile creare un file vuoto a zero byte utilizzando il `touch /etc/multipath.conf` comando.

La prima volta che si crea il `multipath.conf` file, potrebbe essere necessario attivare e avviare i servizi multipath utilizzando i seguenti comandi:

[listing]
----
# chkconfig multipathd on
# /etc/init.d/multipathd start
----
Non è necessario aggiungere dispositivi direttamente al `multipath.conf` file, a meno che non si disponga di dispositivi che non si desidera gestire multipath o di impostazioni esistenti che sovrascrivono le impostazioni predefinite. Per escludere i dispositivi indesiderati, aggiungere al file la seguente sintassi `multipath.conf`, sostituendo <DevId> con la stringa WWID del dispositivo che si desidera escludere:

[listing]
----
blacklist {
        wwid <DevId>
        devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
        devnode "^hd[a-z]"
        devnode "^cciss.*"
}
----
.Esempio
Nell'esempio seguente, `sda` è il disco SCSI locale che si desidera aggiungere alla blacklist.

.Fasi
. Eseguire il seguente comando per determinare l'ID WWID:
+
[listing]
----
# /lib/udev/scsi_id -gud /dev/sda
360030057024d0730239134810c0cb833
----
. Aggiungi questo WWID alla "blacklist" stanza in `/etc/multipath.conf`:
+
[listing]
----
blacklist {
     wwid   360030057024d0730239134810c0cb833
     devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
     devnode "^hd[a-z]"
     devnode "^cciss.*"
}
----


È necessario controllare sempre il `/etc/multipath.conf` file, specialmente nella sezione dei valori predefiniti, per le impostazioni legacy che potrebbero sovrascrivere le impostazioni predefinite.

Nella tabella seguente vengono illustrati i `multipathd` parametri critici per i LUN ONTAP e i valori richiesti. Se un host è connesso a LUN di altri fornitori e uno di questi parametri viene sovrascritto, è necessario correggerli in seguito nel `multipath.conf` file che si applica specificamente ai LUN di ONTAP. Senza questa correzione, i LUN ONTAP potrebbero non funzionare come previsto. È necessario ignorare queste impostazioni predefinite solo in consultazione con NetApp, il fornitore del sistema operativo o entrambi, e solo quando l'impatto è pienamente compreso.

[cols="2*"]
|===
| Parametro | Impostazione 


| detect_prio | sì 


| dev_loss_tmo | "infinito" 


| failback | immediato 


| fast_io_fail_tmo | 5 


| caratteristiche | "3 queue_if_no_path pg_init_retries 50" 


| flush_on_last_del | "sì" 


| gestore_hardware | "0" 


| no_path_retry | coda 


| path_checker | "a" 


| policy_di_raggruppamento_percorsi | "group_by_prio" 


| path_selector | "round-robin 0" 


| intervallo_polling | 5 


| prio | "ONTAP" 


| prodotto | LUN.* 


| retain_attached_hw_handler | sì 


| peso_rr | "uniforme" 


| user_friendly_names | no 


| vendor | NETAPP 
|===
.Esempio
Nell'esempio seguente viene illustrato come correggere un valore predefinito sovrascritto. In questo caso, il `multipath.conf` il file definisce i valori per `path_checker` e. `detect_prio` Non compatibili con LUN ONTAP. Se non possono essere rimossi a causa di altri array SAN ancora collegati all'host, questi parametri possono essere corretti specificamente per i LUN ONTAP con un dispositivo.

[listing]
----
defaults {
 path_checker readsector0
 detect_prio no
 }
devices {
 device {
 vendor "NETAPP "
 product "LUN.*"
 path_checker tur
 detect_prio yes
 }
}
----

NOTE: Per configurare Oracle Linux 6,4 Red Hat Compatible kernel (RHCK), utilizzare il link:hu_rhel_64.html#recommended-settings["impostazioni consigliate"] per Red Hat Enterprise Linux (RHEL) 6,4.



== Mirroring ASM

Il mirroring ASM (Automatic Storage Management) potrebbe richiedere modifiche alle impostazioni del multipath Linux per consentire ad ASM di riconoscere un problema e passare a un gruppo di guasti alternativo. La maggior parte delle configurazioni ASM su ONTAP utilizza la ridondanza esterna, il che significa che la protezione dei dati viene fornita dall'array esterno e ASM non esegue il mirroring dei dati. Alcuni siti utilizzano ASM con ridondanza normale per fornire il mirroring bidirezionale, in genere su siti diversi. Per ulteriori informazioni, vederelink:https://docs.netapp.com/us-en/ontap-apps-dbs/oracle/oracle-overview.html["Database Oracle su ONTAP"^].



== Problemi noti

Oracle Linux 6,4 con ONTAP presenta i seguenti problemi noti:

[cols="3*"]
|===
| ID bug NetApp | Titolo | Descrizione 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=713555["713555"^] | I ripristini dell'adattatore QLogic vengono visualizzati su OL 6,4 e OL 5,9 con UEK2 su guasti del controller, quali takeover/giveback e reboot | Le reimpostazioni dell'adattatore QLogic si verificano sugli host OL6.4 con UEK2 (kernel-uek-2.6.39-400.17.1.el6uek) o sugli host OL5.9 con UEK2 (kernel-uek-2.6.39 400.17.1.el5uek) quando si verificano guasti al controller (come takeover, giveback e riavvii). Questi ripristini sono intermittenti. Quando si verificano questi ripristini della scheda, potrebbe verificarsi un'interruzione i/o prolungata (a volte, più di 10 minuti) fino a quando la scheda di rete non viene reimpostata correttamente e lo stato dei percorsi non viene aggiornato da dm-multipath. In /var/log/messages, quando viene premuto questo bug vengono visualizzati messaggi simili ai seguenti: Kernel: Qla2xxx [0000:11:00.0]-8018:0: RESET DELL'ADATTATORE EMESSO nexus=0:2:13. Ciò si osserva con la versione del kernel: Su OL6.4: Kernel-uek-2.6.39-400.17.1.el6uek su OL5.9: Kernel-uek-2.6.39-400.17.1.el5uek 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=715217["715217"^] | Il ritardo nel recovery di percorso sugli host OL 6,4 o OL 5,9 con UEK2 può causare la ripresa dell'i/o ritardata in caso di guasti a controller o fabric | Quando si verifica un errore del controller (failover o giveback dello storage, riavvii e così via) o un errore del fabric (disattivazione o abilitazione della porta FC) con i/o su host Oracle Linux 6.4 o Oracle Linux 5.9 con kernel UEK2, il ripristino del percorso tramite DM-multipath richiede molto tempo (4 minuti). a 10 minuti). A volte, durante il ripristino dei percorsi allo stato attivo, si verificano anche i seguenti errori del driver lpfc: Kernel: sd 0:0:8:3: [sdlt] risultato: Hostbyte=DID_ERROR driverbyte=DRIVER_OK a causa di questo ritardo nel recupero del percorso durante gli eventi di malfunzionamento, anche la ripresa i/o ritarda. Versioni OL 6.4: Device-mapper-1.02.77-9.el6 device-mapper-multipath-0.4.9-64.0.1.el6 kernel-uek-2.6.39-400.17.1.el6uek OL 5.9 versioni: Device-mapper-1.02.77-9.el5 device-mapper-multipath-0.4.9-64.0.1.el5 kernel-uek-2.6.39-400.17.1.eluek 5uek 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=709911["709911"^] | DM Multipath su OL 6,4 e OL 5,9 iSCSI con kernel UEK2 richiede molto tempo per aggiornare lo stato del percorso LUN dopo errori di storage | Nei sistemi che eseguono Oracle Linux 6 Update4 e Oracle Linux 5 Update9 iSCSI con Unbreakable Enterprise kernel Release 2 (UEK2), è stato riscontrato un problema durante gli eventi di errore dello storage in cui DM multipath (DMMP) impiega circa 15 minuti per aggiornare lo stato del percorso dei dispositivi Device Mapper (DM) (LUN). Se si esegue il comando "multipath -ll" durante questo intervallo, lo stato del percorso viene visualizzato come "failed ready running" per quel dispositivo DM (LUN). Lo stato del percorso viene aggiornato come "Active ready running". Questo problema si verifica con la seguente versione: Oracle Linux 6 Update 4: UEK2 kernel: 2.6.39-400.17.1.el6uek.x86_64 multipath: Device-mapper-multipath-0.4.9-64.0.1.el6.x86_64 iSCSI: iscsi-initiator-utils-6.2.0.873-2.0.el6.el6.x86_64 aggiornamento Oracle Linux 5: Multipath iscsi-2.6.0.4.39.400.17.1.6.2.64.0.64.16.0.64.5.0.872..x86: multipath: iscsi-.5.5....5..5.5...5.5.x86.5..5.5.5...5.5.5..5.5 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=739909["739909"^] | La chiamata di sistema SG_io ioctl non riesce sui dispositivi dm-multipath dopo un guasto FC sugli host OL6.x e OL5.x con UEK2 | Si verifica un problema sugli host Oracle Linux 6.x con kernel UEK2 e Oracle Linux 5.x con kernel UEK2. I comandi sg_* su un dispositivo multipath non funzionano con il codice di errore EAGAIN (errno) dopo un errore di fabric che causa la disattivazione di tutti i percorsi nel gruppo di percorsi attivi. Questo problema si verifica solo quando non si verifica alcun i/o sui dispositivi multipath. sg_inq -v /dev/mapper/3600a098041764937303f436c75324370 richiesta cdb: 12 00 00 00 24 00 ioctl(SG_io v3) non riuscito con os_err (errno) = 11 richiesta: Errore so pass-through: Risorsa temporaneamente non disponibile HDIO_GET_IDENTITY ioctl non riuscita: Risorsa temporaneamente non disponibile [11] richiesta SCSI e recupero delle informazioni ATA non riuscito su /dev/mapper/3600a098041764937303f436c75324370. Questo problema si verifica perché il passaggio del gruppo di percorsi ad altri gruppi attivi non viene attivato durante le chiamate ioctl() quando non si verifica alcun i/o sul dispositivo DM-multipath. Il problema è stato osservato sulle seguenti versioni dei pacchetti kernel-uek e device-mapper-multipath: Versioni di OL6.4: Kernel-uek-2.6.39-400.17.1.el6uek device-mapper-multipath-0.4.9-64.0.1.el6 versioni di OL5.9: Kernel-uek-2.6.39 64.0-400.17.1.el5uek device-mapper-multipath-0.4.9 
|===

NOTE: Per i problemi noti di Oracle Linux RHCK, consultare la link:hu_rhel_64.html#known-problems-and-limitations["problemi noti"] per RHEL 6,4.
