---
sidebar: sidebar 
permalink: hu_ol_94.html 
keywords: host utilities, oracle, linux, 9.4, netapp, ontap 
summary: Descrive come utilizzare Oracle Linux 9,4 con ONTAP 
---
= USA Oracle Linux 9,4 con ONTAP
:hardbreaks:
:toclevels: 1P
:allow-uri-read: 
:toclevels: 1P
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È possibile utilizzare le impostazioni di configurazione dell'host SAN di ONTAP per configurare Oracle Linux 9,4 con ONTAP come destinazione.



== Installare le utilità host Linux

È possibile scaricare il pacchetto software Utilità host Linux NetApp come file 64-bit.rpm dal link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["Sito di supporto NetApp"^].

NetApp consiglia vivamente di installare le utilità host Linux, ma non è obbligatorio. Le utility non modificano le impostazioni dell'host Linux. Le utility migliorano la gestione e assistono il supporto clienti NetApp nella raccolta di informazioni sulla configurazione.

.Fasi
. Scaricare il pacchetto software Linux host Utilities a 64 bit dal https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["Sito di supporto NetApp"^] al proprio host.
. Installare il pacchetto software:
+
`rpm -ivh netapp_linux_unified_host_utilities-7-1.x86_64`





== Utilizzare il kit di strumenti SAN

L'installazione del pacchetto Utilità host NetApp installa automaticamente il toolkit. Questo kit fornisce l' `sanlun`utility, che consente di gestire LUN e HBA (host Bus Adapter). Il `sanlun` comando restituisce informazioni sui LUN mappati all'host, sul multipathing e sulle informazioni necessarie per creare gruppi iniziatori.

Nell'esempio seguente, il `sanlun lun show` Il comando restituisce le informazioni sul LUN.

[listing]
----
sanlun lun show all
----
.Mostra esempio
[%collapsible]
====
[listing]
----
controller(7mode/E-Series)/                                  device          host                  lun
vserver(cDOT/FlashRay)        lun-pathname                   filename        adapter    protocol   size    product
--------------------------------------------------------------------------------------------------------
vs_coexistence_147            /vol/fc_vol_2_9/dynamic_lun    /dev/sdcm       host12     FCP        10g     cDOT
vs_coexistence_147            /vol/fc_vol_2_8/dynamic_lun    /dev/sdcl       host12     FCP        10g     cDOT
vs_coexistence_147            /vol/fc_vol_2_7/dynamic_lun    /dev/sdck       host12     FCP        10g     cDOT
vs_coexistence_147            /vol/fc_vol_2_6/dynamic_lun    /dev/sdcj       host12     FCP        10g     cDO

----
====


== Attivare l'avvio SAN

Se si decide di utilizzare l'avvio SAN, questo deve essere supportato dalla configurazione.

.Prima di iniziare
Utilizzare link:https://imt.netapp.com/matrix/#welcome["Tool di matrice di interoperabilità"^]per verificare che il sistema operativo, l'HBA, il firmware dell'HBA, il BIOS di avvio dell'HBA e la versione ONTAP siano supportati.

.Fasi
. Mappare il LUN di avvio SAN sull'host.
. Verificare che siano disponibili più percorsi.
+

NOTE: Una volta attivato il sistema operativo host e eseguito sui percorsi, diventano disponibili più percorsi.

. Abilitare l'avvio SAN nel BIOS del server per le porte a cui è mappato il LUN di avvio SAN.
+
Per informazioni su come attivare il BIOS HBA, consultare la documentazione specifica del vendor.

. Riavviare l'host per verificare che l'avvio sia stato eseguito correttamente.




== Attiva il multipathing

Puoi utilizzare multipathing con Oracle Linux 9,4 per gestire i LUN di ONTAP. Per utilizzare il multipathing, il `/etc/multipath.conf` file deve esistere. Se il `/etc/multipath.conf` file non esiste, è possibile creare un file vuoto a zero byte utilizzando il comando touch `/etc/multipath.conf`. Non è necessario apportare modifiche al `/etc/multipath.conf` file perché Oracle Linux 9,4 è compilato con tutte le impostazioni necessarie per riconoscere e gestire correttamente i LUN di ONTAP.


NOTE: Un singolo LUN non deve richiedere più di quattro percorsi. Più di quattro percorsi possono causare problemi di percorso durante gli errori di storage.



=== Tutte le configurazioni DEGLI array SAN

Tutte le configurazioni di array SAN (ASA) ottimizzano tutti i percorsi verso una determinata LUN, mantenendoli attivi. In questo modo, le performance vengono migliorate grazie alle operazioni di i/o in tutti i percorsi contemporaneamente.

.Esempio
Nell'esempio seguente viene visualizzato l'output corretto per un LUN ONTAP.

.Mostra esempio
[%collapsible]
====
[listing]
----
multipath -ll
3600a098038303634722b4d59646c4436 dm-28 NETAPP,LUN C-Mode
size=10G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
  |- 11:0:7:6   sdbz 68:208  active ready running
  |- 11:0:11:6  sddn 71:80   active ready running
  |- 11:0:15:6  sdfb 129:208 active ready running
  |- 12:0:1:6   sdgp 132:80  active ready running
----
====


=== Configurazioni non ASA

Per le configurazioni non ASA, devono essere presenti due gruppi di percorsi con priorità diverse. I percorsi con priorità più elevate sono attivi/ottimizzati. Ciò significa che vengono gestite dal controller in cui si trova l'aggregato. I percorsi con priorità più basse sono attivi ma non ottimizzati perché sono serviti da un controller diverso. I percorsi non ottimizzati vengono utilizzati solo quando i percorsi ottimizzati non sono disponibili.

.Esempio
Nell'esempio seguente viene visualizzato l'output corretto per un LUN ONTAP con due percorsi attivi/ottimizzati e due percorsi attivi/non ottimizzati.

.Mostra esempio
[%collapsible]
====
[listing]
----
multipath -ll
3600a0980383036347ffb4d59646c4436 dm-28 NETAPP,LUN C-Mode
size=10G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| |- 16:0:6:35 sdwb  69:624  active ready running
| |- 16:0:5:35 sdun  66:752  active ready running
`-+- policy='service-time 0' prio=10 status=enabled
  |- 15:0:0:35 sdaj  66:48   active ready running
  |- 15:0:1:35 sdbx  68:176  active ready running
----
====


== Impostazioni consigliate

Il sistema operativo Oracle Linux 9,4 riconosce i LUN ONTAP e imposta automaticamente tutti i parametri di configurazione correttamente per le configurazioni ASA e non ASA. È possibile ottimizzare ulteriormente le prestazioni per la configurazione host con le seguenti impostazioni consigliate.

Il `multipath.conf` file deve esistere per avviare il daemon multipath. Se questo file non esiste, è possibile creare un file vuoto a zero byte utilizzando il `touch /etc/multipath.conf` comando.

La prima volta che si crea il `multipath.conf` file, potrebbe essere necessario attivare e avviare i servizi multipath utilizzando i seguenti comandi:

[listing]
----
# systemctl enable multipathd
# systemctl start multipathd
----
Non è necessario aggiungere dispositivi direttamente al `multipath.conf` file, a meno che non si disponga di dispositivi che non si desidera gestire multipath o di impostazioni esistenti che sovrascrivono le impostazioni predefinite. È possibile escludere le periferiche indesiderate aggiungendo la seguente sintassi al `multipath.conf` file, sostituendo <DevId> con la stringa WWID del dispositivo che si desidera escludere:

[listing]
----
blacklist {
        wwid <DevId>
        devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
        devnode "^hd[a-z]"
        devnode "^cciss.*"
}
----
Nell'esempio seguente, si determina il WWID di un dispositivo e si aggiunge il dispositivo al `multipath.conf` file.

.Fasi
. Determinare il WWID:
+
[listing]
----
/lib/udev/scsi_id -gud /dev/sda
----
+
[listing]
----
360030057024d0730239134810c0cb833
----
+
`sda` È il disco SCSI locale che si desidera aggiungere alla blacklist.

. Aggiungere il `WWID` alla lista nera `/etc/multipath.conf`:
+
[listing]
----
blacklist {
     wwid   360030057024d0730239134810c0cb833
     devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
     devnode "^hd[a-z]"
     devnode "^cciss.*"
}
----


Controllare sempre il file, soprattutto nella sezione dei valori predefiniti, per verificare `/etc/multipath.conf` le impostazioni legacy che potrebbero sovrascrivere le impostazioni predefinite.

Nella tabella seguente vengono illustrati i `multipathd` parametri critici per i LUN ONTAP e i valori richiesti. Se un host è connesso a LUN di altri fornitori e uno di questi parametri viene sovrascritto, sarà necessario correggerli in seguito nel `multipath.conf` file che si applica specificamente ai LUN di ONTAP. In caso contrario, i LUN ONTAP potrebbero non funzionare come previsto. È necessario ignorare queste impostazioni predefinite solo in consultazione con NetApp e/o un fornitore del sistema operativo e solo quando l'impatto è pienamente compreso.

[cols="2*"]
|===
| Parametro | Impostazione 


| detect_prio | sì 


| dev_loss_tmo | infinito 


| failback | immediato 


| fast_io_fail_tmo | 5 


| caratteristiche | 2 tentativi pg_init_retries 50 


| flush_on_last_del | sì 


| gestore_hardware | 0 


| no_path_retry | coda 


| path_checker | ... 


| policy_di_raggruppamento_percorsi | group_by_prio 


| path_selector | tempo di servizio 0 


| intervallo_polling | 5 


| prio | ONTAP 


| prodotto | LUN 


| retain_attached_hw_handler | sì 


| peso_rr | uniforme 


| user_friendly_names | no 


| vendor | NETAPP 
|===
.Esempio
Nell'esempio riportato di seguito viene illustrato come correggere un valore predefinito sovrascritto. In questo caso, il `multipath.conf` il file definisce i valori per `path_checker` e. `no_path_retry` Non compatibili con LUN ONTAP. Se non possono essere rimossi perché altri array SAN sono ancora collegati all'host, questi parametri possono essere corretti specificamente per i LUN ONTAP con un dispositivo.

.Mostra esempio
[%collapsible]
====
[listing]
----
defaults {
 path_checker readsector0
 no_path_retry fail
 }
devices {
 device {
 vendor "NETAPP"
 product "LUN"
 no_path_retry queue
 path_checker tur
 }
}
----
====

NOTE: Per configurare Oracle Linux 9,4 Red Hat Compatible kernel (RHCK), utilizzare il link:hu_rhel_94.html#recommended-settings["impostazioni consigliate"] per Red Hat Enterprise Linux (RHEL) 9,4.



== Configurare le impostazioni KVM

Non è necessario configurare le impostazioni per una macchina virtuale basata su kernel perché il LUN è mappato all'hypervisor.



== Problemi noti

Non ci sono problemi noti per la configurazione dell'host FC per OL 9,4 con ONTAP release.
