---
sidebar: sidebar 
permalink: hu_ol_76.html 
keywords: host utilities, oracle, linux, 7.6, netapp, ontap 
summary: Descrive come utilizzare Oracle Linux 7.6 con ONTAP 
---
= Utilizza Oracle Linux 7.6 con ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È possibile utilizzare le impostazioni di configurazione dell'host SAN di ONTAP per configurare Oracle Linux 7,6 con ONTAP come destinazione.



== Installare le utilità host Linux

Il pacchetto software NetApp Linux host Utilities è disponibile su link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["Sito di supporto NetApp"^]in un file .rpm a 32 bit e a 64 bit. Se non si conosce il file adatto alla configurazione, utilizzare per verificare quale file è link:https://mysupport.netapp.com/matrix/#welcome["Tool di matrice di interoperabilità"^]necessario.

NetApp consiglia vivamente di installare le utilità host Linux, ma non è obbligatorio. Le utility non modificano alcuna impostazione sul vostro host Linux. Le utility migliorano la gestione e assistono il supporto clienti NetApp nella raccolta di informazioni sulla configurazione.

Se avete installato Linux host Utilities, è necessario aggiornarlo alla versione più recente, oppure rimuoverlo e seguire questi passaggi per installare la versione più recente.

.Fasi
. Scaricare il pacchetto software Linux host Utilities a 32 o 64 bit dal al proprio hostlink:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["Sito di supporto NetApp"^].
. Installare il pacchetto software:
+
`rpm -ivh netapp_linux_unified_host_utilities-7-1.x86_64`




NOTE: È possibile utilizzare le impostazioni di configurazione fornite in questo documento per configurare i client cloud connessi a. link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/index.html["Cloud Volumes ONTAP"^] e. link:https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/index.html["Amazon FSX per ONTAP"^].



== Toolkit SAN

Il toolkit viene installato automaticamente quando si installa il pacchetto NetApp host Utilities. Questo kit fornisce `sanlun` Utility che consente di gestire LUN e HBA. Il `sanlun` Il comando restituisce le informazioni relative alle LUN mappate all'host, al multipathing e alle informazioni necessarie per creare gruppi di iniziatori.

.Esempio
Nell'esempio seguente, il `sanlun lun show` Il comando restituisce le informazioni sul LUN.

[source, cli]
----
# sanlun lun show all
----
Output di esempio:

[listing]
----
controller(7mode/E-Series)/            device     host               lun
vserver(cDOT/FlashRay)   lun-pathname  filename   adapter  protocol  size    Product
------------------------------------------------------------------------------------
data_vserver          /vol/vol1/lun1   /dev/sdb   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol1/lun1   /dev/sdc   host15   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sdd   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sde   host15   FCP       120.0g  cDOT
----


== Avvio SAN

.Prima di iniziare
Se si decide di utilizzare l'avvio SAN, questo deve essere supportato dalla configurazione. È possibile utilizzare link:https://imt.netapp.com/matrix/#welcome["Tool di matrice di interoperabilità"^]per verificare che il sistema operativo, l'HBA, il firmware dell'HBA e il BIOS di avvio dell'HBA e la versione ONTAP siano supportati.

.Fasi
. Mappare il LUN di avvio SAN sull'host.
. Verificare che siano disponibili più percorsi.
+

NOTE: Più percorsi diventano disponibili dopo che il sistema operativo host è attivo e in esecuzione sui percorsi.

. Abilitare l'avvio SAN nel BIOS del server per le porte a cui è mappato il LUN di avvio SAN.
+
Per informazioni su come attivare il BIOS HBA, consultare la documentazione specifica del vendor.

. Riavviare l'host per verificare che l'avvio sia stato eseguito correttamente.




== Multipathing

Per Oracle Linux 7.6 il file /etc/multipath.conf deve esistere, ma non è necessario apportare modifiche specifiche al file. Oracle Linux 7.6 è compilato con tutte le impostazioni necessarie per riconoscere e gestire correttamente le LUN ONTAP.

Il `multipath -ll` comando consente di verificare le impostazioni dei LUN di ONTAP. Ci dovrebbero essere due gruppi di percorsi con priorità diverse. I percorsi con priorità più elevate sono Active/Optimized, il che significa che vengono gestiti dal controller in cui si trova l'aggregato. I percorsi con priorità più basse sono attivi ma non ottimizzati perché sono serviti da un controller diverso. I percorsi non ottimizzati vengono utilizzati solo quando i percorsi ottimizzati non sono disponibili.

.Esempio
Nell'esempio seguente viene visualizzato l'output corretto per un LUN ONTAP con due percorsi attivi/ottimizzati e due percorsi attivi/non ottimizzati:

[listing]
----
# multipath -ll
3600a09803831347657244e527766394e dm-5 NETAPP,LUN C-Mode
size=80G features='4 queue_if_no_path pg_init_retries 50 retain_attached_hw_handle' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| |- 11:0:1:0 sdj 8:144 active ready running
| |- 11:0:2:0 sdr 65:16 active ready running
|-+- policy='service-time 0' prio=10 status=enabled
|- 11:0:0:0 sdb 8:i6 active ready running
|- 12:0:0:0 sdz 65:144 active ready running
----

NOTE: Un singolo LUN non deve richiedere più di quattro percorsi. La presenza di più di quattro percorsi potrebbe causare problemi di percorso durante gli errori di storage.



== Impostazioni consigliate

Il sistema operativo Oracle Linux 7.6 viene compilato per riconoscere le LUN ONTAP e impostare automaticamente correttamente tutti i parametri di configurazione. Il `multipath.conf` file deve esistere per avviare il daemon multipath. Se questo file non esiste, è possibile creare un file vuoto a zero byte utilizzando il `touch /etc/multipath.conf` comando.

La prima volta che si crea il `multipath.conf` file, potrebbe essere necessario attivare e avviare i servizi multipath utilizzando i seguenti comandi:

[listing]
----
chkconfig multipathd on
/etc/init.d/multipathd start
----
Non è necessario aggiungere nulla direttamente al `multipath.conf` file a meno che non si disponga di dispositivi che non si desidera gestire multipath o di impostazioni esistenti che sovrascrivono le impostazioni predefinite. Per escludere i dispositivi indesiderati, aggiungere la seguente sintassi al `multipath.conf` file, sostituendo <DevId> con la stringa WWID (Worldwide Identifier) del dispositivo che si desidera escludere:

[listing]
----
blacklist {
        wwid <DevId>
        devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
        devnode "^hd[a-z]"
        devnode "^cciss.*"
}
----
Nell'esempio seguente `multipath.conf` viene determinato il WWID di una periferica e aggiunto al file.

.Fasi
. Determinare il WWID:
+
[listing]
----
/lib/udev/scsi_id -gud /dev/sda
----
+
[listing]
----
3600a098038314c4a433f5774717a3046
----
+
`sda` È il disco SCSI locale che si desidera aggiungere alla blacklist.

. Aggiungere il `WWID` alla lista nera `/etc/multipath.conf`:
+
[source, cli]
----
blacklist {
     wwid   3600a098038314c4a433f5774717a3046
     devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
     devnode "^hd[a-z]"
     devnode "^cciss.*"
}
----


Controllare sempre il `/etc/multipath.conf` file, specialmente nella sezione dei valori predefiniti, per le impostazioni legacy che potrebbero sovrascrivere le impostazioni predefinite.

Nella tabella seguente vengono illustrati i `multipathd` parametri critici per i LUN ONTAP e i valori richiesti. Se un host è connesso a LUN di altri fornitori e uno di questi parametri viene sovrascritto, è necessario correggerli in seguito nel `multipath.conf` file che si applica specificamente ai LUN di ONTAP. Senza questa correzione, i LUN ONTAP potrebbero non funzionare come previsto. È necessario ignorare queste impostazioni predefinite solo in consultazione con NetApp, il fornitore del sistema operativo o entrambi, e solo quando l'impatto è pienamente compreso.

[cols="2*"]
|===
| Parametro | Impostazione 


| detect_prio | sì 


| dev_loss_tmo | "infinito" 


| failback | immediato 


| fast_io_fail_tmo | 5 


| caratteristiche | "3 queue_if_no_path pg_init_retries 50" 


| flush_on_last_del | "sì" 


| gestore_hardware | "0" 


| path_checker | "a" 


| policy_di_raggruppamento_percorsi | "group_by_prio" 


| path_selector | "tempo di servizio 0" 


| intervallo_polling | 5 


| prio | "ONTAP" 


| prodotto | LUN.* 


| retain_attached_hw_handler | sì 


| peso_rr | "uniforme" 


| user_friendly_names | no 


| vendor | NETAPP 
|===
.Esempio
Nell'esempio seguente viene illustrato come correggere un valore predefinito sovrascritto. In questo caso, il `multipath.conf` file definisce i valori per `path_checker` e `detect_prio` che non sono compatibili con i LUN di ONTAP. Se non possono essere rimossi a causa di altri array SAN ancora collegati all'host, questi parametri possono essere corretti specificamente per i LUN ONTAP con un dispositivo.

[listing]
----
defaults {
 path_checker readsector0
 detect_prio no
 }
devices {
 device {
 vendor "NETAPP "
 product "LUN.*"
 path_checker tur
 detect_prio yes
 }
}
----

NOTE: Per configurare Oracle Linux 7,6 Red Hat Compatible kernel (RHCK), utilizzare il link:hu_rhel_76.html#recommended-settings["impostazioni consigliate"] per Red Hat Enterprise Linux (RHEL) 7,6.



== Problemi noti

Oracle Linux 7,6 con ONTAP presenta i seguenti problemi noti:

[cols="3*"]
|===
| ID bug NetApp | Titolo | Descrizione 


| 1440718 | Se si dismappa o si mappa un LUN senza eseguire una nuova scansione SCSI, i dati sull'host potrebbero danneggiarsi. | Quando si imposta il parametro di configurazione multipath 'disable_changed_wids' su YES, l'accesso al path device viene disattivato in caso di modifica dell'ID WWID. Multipath disattiva l'accesso al dispositivo di percorso fino a quando l'ID WWID del percorso non viene ripristinato all'ID WWID del dispositivo multipath. Per ulteriori informazioni, vedere link:https://kb.netapp.com/Advice_and_Troubleshooting/Flash_Storage/AFF_Series/The_filesystem_corruption_on_iSCSI_LUN_on_the_Oracle_Linux_7["Knowledge base di NetApp: La corruzione del file system sul LUN iSCSI su Oracle Linux 7"^]. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1202736["1202736"^] | I LUN potrebbero non essere disponibili durante il rilevamento dell'host a causa dello stato "non presente" delle porte remote su un host OL7U6 con adattatore QLogic QLE2742 | Durante il rilevamento dell'host, lo stato delle porte remote Fibre Channel (FC) su un host OL7U6 con un adattatore QLogic QLE2742 potrebbe entrare nello stato "Not Present" (non presente). Le porte remote con stato "non presente" potrebbero rendere non disponibili i percorsi verso i LUN. Durante il failover dello storage, la ridondanza del percorso potrebbe essere ridotta e causare un'interruzione dell'i/O. È possibile controllare lo stato della porta remota immettendo il seguente comando: Cat /sys/class/fc_remote_ports/rport-*/port_state il seguente è un esempio dell'output visualizzato: Online non presente Online 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1204078["1204078"^] | L'interruzione del kernel si verifica su Oracle Linux 7.6 con Qlogic (QLE2672) 16 GB FC HBA durante le operazioni di failover dello storage | Durante le operazioni di failover dello storage su Oracle Linux 7.6 con un HBA (host bus adapter) Qlogic QLE2672 Fibre Channel (FC), si verifica un'interruzione del kernel a causa di un panico nel kernel. Il kernel panic causa il riavvio di Oracle Linux 7.6, con conseguente interruzione dell'applicazione. Se il meccanismo kdump è attivato, il kernel panic genera un file vmcore che si trova nella directory /var/crash/. È possibile analizzare il file vmcore per determinare la causa del panico. Dopo l'interruzione del kernel, è possibile riavviare il sistema operativo host e ripristinare il sistema operativo, quindi è possibile riavviare qualsiasi applicazione secondo necessità. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1204351["1204351"^] | Durante le operazioni di failover dello storage, è possibile che Oracle Linux 7.6 venga eseguito con Qlogic(QLE2742) 32GB FC HBA | Durante le operazioni di failover dello storage su Oracle Linux 7.6 con un HBA (host bus adapter) Qlogic QLE2742 Fibre Channel (FC), potrebbe verificarsi un'interruzione del kernel a causa di un panico nel kernel. Il kernel panic causa il riavvio di Oracle Linux 7.6, con conseguente interruzione dell'applicazione. Se il meccanismo kdump è attivato, il kernel panic genera un file vmcore che si trova nella directory /var/crash/. È possibile analizzare il file vmcore per determinare la causa del panico. Dopo l'interruzione del kernel, è possibile riavviare il sistema operativo host e ripristinare il sistema operativo, quindi è possibile riavviare qualsiasi applicazione secondo necessità. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1204352["1204352"^] | Durante le operazioni di failover dello storage, è possibile che Oracle Linux 7.6 venga eseguito con Emulex (LPe32002-M2)32GB FC HBA | Durante le operazioni di failover dello storage su Oracle Linux 7.6 con un HBA (host bus adapter) Fibre Channel Emulex LPe32002-M2, potrebbe verificarsi un'interruzione del kernel a causa di un panico nel kernel. Il kernel panic causa il riavvio di Oracle Linux 7.6, con conseguente interruzione dell'applicazione. Se il meccanismo kdump è attivato, il kernel panic genera un file vmcore che si trova nella directory /var/crash/. È possibile analizzare il file vmcore per determinare la causa del panico. Dopo l'interruzione del kernel, è possibile riavviare il sistema operativo host e ripristinare il sistema operativo, quindi è possibile riavviare qualsiasi applicazione secondo necessità. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1246134["11246134"^] | Nessun progresso i/o su Oracle Linux 7.6 con kernel UEK5U2, eseguito con un HBA FC Emulex LPe16002B-M6 16G durante le operazioni di failover dello storage | Durante le operazioni di failover dello storage su Oracle Linux 7.6 con il kernel UEK5U2 in esecuzione con un HBA (host bus adapter) Fibre Channel 16G Emulex LPe16002B-M6, l'avanzamento dell'i/o potrebbe interrompersi a causa del blocco dei report. L'operazione di failover dello storage segnala il passaggio da uno stato "online" a uno "bloccato", causando un ritardo nelle operazioni di lettura e scrittura. Una volta completata correttamente l'operazione, i report non tornano allo stato "online" e continuano a rimanere nello stato "bloccato". 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1246327["1246327"^] | Stato della porta remota sull'host QLogic QLE2672 16G bloccato durante le operazioni di failover dello storage | Le porte remote Fibre Channel (FC) potrebbero essere bloccate su Red Hat Enterprise Linux (RHEL) 7.6 con l'host QLogic QLE2672 16G durante le operazioni di failover dello storage. Poiché le interfacce logiche si bloccano quando un nodo di storage è inattivo, le porte remote impostano lo stato del nodo di storage su bloccato. L'avanzamento dell'i/o potrebbe interrompersi a causa delle porte bloccate se si esegue sia un host QLogic QLE2672 16G che un HBA (host Bus Adapter) Fibre Channel (FC) da QLE2742 32GB GB. Quando il nodo di storage torna allo stato ottimale, vengono anche presentate le interfacce logiche e le porte remote devono essere in linea. Tuttavia, le porte remote potrebbero essere ancora bloccate. Questo stato bloccato viene registrato come guasto nelle LUN del layer multipath. Puoi verificare lo stato delle porte remote con il seguente comando: Cat /sys/class/fc_remote_ports/rport-*/port_stat dovresti visualizzare il seguente output: Blocked blocked blocked Online 
|===