---
sidebar: sidebar 
permalink: hu_rhel_70.html 
keywords: host utilities, red hat, rhel, linux, 7.0, netapp, ontap 
summary: Descrive come utilizzare Red Hat Enterprise Linux 7.0 con ONTAP 
---
= Configurare RHEL 7,0 per FCP e iSCSI con storage ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Il software Linux host Utilities fornisce strumenti di gestione e diagnostica per gli host Linux connessi allo storage ONTAP. Quando si installano le utilità host Linux su un host Red Hat Enterprise Linux (RHEL) 7,0, è possibile utilizzare le utilità host per gestire le operazioni dei protocolli FCP e iSCSI con i LUN ONTAP.


NOTE: Non è necessario configurare manualmente le impostazioni della macchina virtuale basata sul kernel (KVM) perché le LUN ONTAP vengono automaticamente mappate sull'hypervisor.



== Passaggio 1: Se lo si desidera, attivare l'avvio SAN

È possibile configurare l'host in modo che utilizzi l'avvio SAN per semplificare l'installazione e migliorare la scalabilità.

.Prima di iniziare
Utilizzare link:https://mysupport.netapp.com/matrix/#welcome["Tool di matrice di interoperabilità"^]per verificare che il sistema operativo Linux, l'HBA (host Bus Adapter), il firmware HBA, il BIOS di avvio HBA e la versione ONTAP supportino l'avvio SAN.

.Fasi
. Creare una LUN di avvio SAN e associarla all'host.
+
Vedere https://docs.netapp.com/us-en/ontap/san-admin/provision-storage.html["Eseguire il provisioning dello storage SAN"^].

. Abilitare l'avvio SAN nel BIOS del server per le porte a cui è mappato il LUN di avvio SAN.
+
Per informazioni su come attivare il BIOS HBA, consultare la documentazione specifica del vendor.

. Verificare che la configurazione sia stata eseguita correttamente riavviando l'host e verificando che il sistema operativo sia attivo e funzionante.




== Fase 2: Installare le utilità host Linux

NetApp consiglia vivamente di installare le utilità host Linux per supportare la gestione LUN di ONTAP e fornire assistenza tecnica nella raccolta dei dati di configurazione.

link:hu_luhu_71.html["Installare le utilità host Linux 7,1"].


NOTE: L'installazione di Linux host Utilities non modifica le impostazioni di timeout dell'host sul proprio host Linux.



== Fase 3: Verificare la configurazione multipath per l'host

È possibile utilizzare multipathing con RHEL 7,0 per gestire i LUN di ONTAP.

Per verificare che il multipathing sia configurato correttamente per l'host, verificare che il `/etc/multipath.conf` file sia definito e che siano configurate le impostazioni consigliate da NetApp per i LUN ONTAP.

.Fasi
. Verificare che il `/etc/multipath.conf` file esista:
+
[source, cli]
----
ls /etc/multipath.conf
----
+
Se il file non esiste, creare un file vuoto a zero byte:

+
[source, cli]
----
touch /etc/multipath.conf
----
. La prima volta che `multipath.conf` si crea il file, potrebbe essere necessario attivare e avviare i servizi multipath per caricare le impostazioni consigliate:
+
[source, cli]
----
systemctl enable multipathd
----
+
[source, cli]
----
systemctl start multipathd
----
. Ogni volta che si avvia l'host, il file vuoto `/etc/multipath.conf` con zero byte carica automaticamente i parametri multipath dell'host raccomandati da NetApp come impostazioni predefinite. Non è necessario apportare modifiche al `/etc/multipath.conf` file per l'host perché il sistema operativo host è compilato con i parametri multipath che riconoscono e gestiscono correttamente i LUN ONTAP.
+
La tabella seguente mostra le impostazioni dei parametri multipercorso compilati dal sistema operativo Linux nativo per i LUN ONTAP.

+
.Mostra impostazioni parametri
[%collapsible]
====
[cols="2"]
|===
| Parametro | Impostazione 


| detect_prio | sì 


| dev_loss_tmo | "infinito" 


| failback | immediato 


| fast_io_fail_tmo | 5 


| caratteristiche | "3 queue_if_no_path pg_init_retries 50" 


| flush_on_last_del | "sì" 


| gestore_hardware | "0" 


| no_path_retry | coda 


| path_checker | "a" 


| policy_di_raggruppamento_percorsi | "group_by_prio" 


| path_selector | "tempo di servizio 0" 


| intervallo_polling | 5 


| prio | "ONTAP" 


| prodotto | LUN.* 


| retain_attached_hw_handler | sì 


| peso_rr | "uniforme" 


| user_friendly_names | no 


| vendor | NETAPP 
|===
====
. Verificare le impostazioni dei parametri e lo stato del percorso dei LUN ONTAP:
+
[source, cli]
----
multipath -ll
----
+
I parametri multipath predefiniti supportano le configurazioni ASA, AFF e FAS. In queste configurazioni, una singola LUN ONTAP non deve richiedere più di quattro percorsi. Se sono presenti più di quattro percorsi, potrebbero verificarsi problemi con i percorsi durante un errore di storage.

+
I seguenti output di esempio mostrano le impostazioni corrette dei parametri e lo stato del percorso per i LUN ONTAP in una configurazione ASA, AFF o FAS.

+
[role="tabbed-block"]
====
.Configurazione ASA
--
Una configurazione ASA ottimizza tutti i percorsi verso una determinata LUN, mantenendoli attivi. In questo modo, le performance vengono migliorate grazie alle operazioni di i/o in tutti i percorsi contemporaneamente.

[listing]
----
# multipath -ll
3600a09803831347657244e527766394e dm-5 NETAPP,LUN C-Mode
size=80G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 3:0:7:9    sdco 69:192  active ready running
  |- 3:0:8:9    sddi 71:0    active ready running
  |- 14:0:8:9   sdjq 65:320  active ready running
  `- 14:0:7:9   sdiw 8:256   active ready running
----
--
.Configurazione AFF o FAS
--
Una configurazione AFF o FAS deve avere due gruppi di percorsi con priorità maggiore e minore. I percorsi Active/Optimized di priorità più elevata sono serviti dal controller in cui si trova l'aggregato. I percorsi a priorità inferiore sono attivi ma non ottimizzati perché serviti da un controller diverso. I percorsi non ottimizzati vengono utilizzati solo quando non sono disponibili percorsi ottimizzati.

L'esempio seguente visualizza l'output per una LUN ONTAP con due percorsi attivi/ottimizzati e due percorsi attivi/non ottimizzati:

[listing]
----
# multipath -ll
3600a09803831347657244e527766394e dm-5 NETAPP,LUN C-Mode
size=80G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| |- 3:0:3:0    sdd  8:48    active ready running
| |- 3:0:4:0    sdx  65:112  active ready running
`-+- policy='service-time 0' prio=10 status=enabled
  |- 14:0:2:0   sdfk 130:96  active ready running
  `- 14:0:5:0   sdgz 132:240 active ready running
----
--
====




== Passaggio 4: Se si desidera, escludere un dispositivo dal multipathing

Se necessario, è possibile escludere un dispositivo dal multipathing aggiungendo il WWID per il dispositivo indesiderato alla stanza "blacklist" per il `multipath.conf` file.

.Fasi
. Determinare il WWID:
+
[source, cli]
----
# /lib/udev/scsi_id -gud /dev/sda
----
+
"sda" è il disco SCSI locale che si desidera aggiungere alla blacklist.

+
Un esempio di WWID è `360030057024d0730239134810c0cb833`.

. Aggiungere il WWID alla "blacklist" stanza:
+
[listing]
----
blacklist {
	     wwid   360030057024d0730239134810c0cb833
        devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
        devnode "^hd[a-z]"
        devnode "^cciss.*"
}
----




== Passaggio 5: Personalizzare i parametri multipath per i LUN ONTAP

Se l'host è connesso a LUN di altri fornitori e le impostazioni dei parametri multipath vengono sovrascritte, è necessario correggerle aggiungendo più avanti nel `multipath.conf` file che si applicano specificamente ai LUN di ONTAP. In caso contrario, i LUN di ONTAP potrebbero non funzionare come previsto.

Controllare il file, in particolare nella sezione dei valori predefiniti, per verificare `/etc/multipath.conf` le impostazioni che potrebbero sovrascrivere <<multipath-parameter-settings,impostazioni predefinite per i parametri multipath>>.


CAUTION: Non sovrascrivere le impostazioni dei parametri consigliate per i LUN ONTAP. Queste impostazioni sono necessarie per ottenere prestazioni ottimali della configurazione host. Per ulteriori informazioni, contattare l'assistenza NetApp, il fornitore del sistema operativo o entrambi.

Nell'esempio seguente viene illustrato come correggere un valore predefinito sovrascritto. In questo esempio, il `multipath.conf` file definisce i valori per `path_checker` e `no_path_retry` che non sono compatibili con i LUN ONTAP e non è possibile rimuovere questi parametri perché gli array di storage ONTAP sono ancora collegati all'host. È invece possibile correggere i valori per `path_checker` e `no_path_retry` aggiungendo una stanza di dispositivo al `multipath.conf` file che si applica specificamente ai LUN di ONTAP.

[listing, subs="+quotes"]
----
defaults {
   path_checker      *readsector0*
   no_path_retry     *fail*
}

devices {
   device {
      vendor          "NETAPP"
      product         "LUN.*"
      no_path_retry   *queue*
      path_checker    *tur*
   }
}
----


== Fase 6: Esaminare i problemi noti

La versione RHEL 7,0 con storage ONTAP presenta i seguenti problemi noti:

[cols="3*"]
|===
| ID bug NetApp | Titolo | Descrizione 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=844417["844417"^] | L'host Emulex 16G FC (LPe16002B-M6) si blocca durante l'i/o con operazioni di failover dello storage | Si potrebbe osservare un crash dell'host 16G FC Emulex (LPe16002B-M6) durante le operazioni di i/o con failover dello storage. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=811587["811587"^] | L'host Emulex 16G FC (LPe16002B-M6) si blocca durante l'i/o con operazioni di failover dello storage | Si potrebbe osservare un crash dell'host 16G FC Emulex (LPe16002B-M6) durante le operazioni di i/o con failover dello storage. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=803071["803071"^] | L'host Emulex 16G FC (LPe16002B-M6) si blocca durante l'i/o con operazioni di failover dello storage | Si potrebbe osservare un crash dell'host 16G FC Emulex (LPe16002B-M6) durante le operazioni di i/o con failover dello storage. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=820163["820163"^] | Blocco host QLogic o errori di percorso osservati durante le operazioni di i/o con failover dello storage | Durante le operazioni di i/o con failover dello storage, è possibile osservare un blocco host o errori di percorso sull'host QLogic. In tali scenari, potrebbe essere visualizzato il seguente messaggio: "Timeout cmd della mailbox, cmd=0x54, mb[0]=0x54 e firmware dump saved to temp buffer" che causa un errore di blocco/percorso dell'host. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=799323["799323"^] | Blocco host Emulex FCoE (OCe10102-FX-D) o errori di percorso osservati durante i/o con operazioni di failover dello storage | Durante le operazioni di i/o con failover dello storage, è possibile osservare un blocco dell'host o errori di percorso sull'host Emulex 10G FCoE (OCe10102-FX-D). In tali scenari, potrebbe essere visualizzato il seguente messaggio: "Il pool di buffer del driver è vuoto, io busied e SCSI Layer i/o Abort Request Status" (Stato richiesta di interruzione i/o livello SCSI), che porta a errori di host hung/path. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=849212["849212"^] | Durante le operazioni di i/o con failover dello storage, si osservano interruzioni dell'host Emulex 16G FC (LPe16002B-M6) o errori di percorso | Durante le operazioni di i/o con failover dello storage, è possibile osservare un blocco dell'host o errori di percorso sull'host Emulex 16G FC (LPe16002B-M6). In tali scenari, potrebbe essere visualizzato il seguente messaggio: "RSCN timeout Data and iotag x1301 is out of range: Max iotag" (dati timeout RSCN e iotag x1301 fuori intervallo: Max iotag), che porta a errori di host hung/path. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=836800["836800"^] | Anaconda visualizza un messaggio di errore di accesso iSCSI, anche se gli accessi sono riusciti durante l'installazione del sistema operativo RHEL 7.0 | Quando si installa root(/) su un LUN iSCSI multipath'd, l'indirizzo IP per le interfacce Ethernet viene specificato nella riga di comando del kernel in modo che gli indirizzi IP vengano assegnati prima dell'avvio del servizio iSCSI. Tuttavia, dracut non può assegnare indirizzi IP a tutte le porte Ethernet durante l'avvio, prima dell'avvio del servizio iSCSI. In questo modo, l'accesso iSCSI non riesce sulle interfacce senza indirizzi IP. Il servizio iSCSI tenterà di effettuare il login più volte, causando un ritardo nel tempo di avvio del sistema operativo. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=836875["836875"^] | Gli indirizzi IP non vengono sempre assegnati durante l'avvio di un sistema operativo RHEL 7.0 installato su un LUN iSCSI multipath | Durante l'installazione di RHEL 7.0, la schermata di installazione di anaconda mostra che l'accesso iSCSI a più IP di destinazione non è riuscito anche se gli accessi iSCSI sono riusciti. Anaconda visualizza il seguente messaggio di errore: "Node Login Failed" (accesso nodo non riuscito). Questo errore viene visualizzato solo quando si selezionano più indirizzi IP di destinazione per l'accesso iSCSI. Per continuare l'installazione del sistema operativo, fare clic sul pulsante "ok". Questo bug non ostacola l'installazione del sistema operativo iSCSI o RHEL 7.0. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=836657["836657"^] | Anaconda non aggiunge l'argomento bootdev nella riga del cmd del kernel per impostare l'indirizzo IP per il sistema operativo RHEL 7.0 installato sul LUN iSCSI multipath'd | Anaconda non aggiunge un argomento bootdev nella riga di comando del kernel in cui si imposta l'indirizzo IPv4 durante l'installazione del sistema operativo RHEL 7.0 su un LUN iSCSI multipath'd. Ciò impedisce l'assegnazione di indirizzi IP a qualsiasi interfaccia Ethernet configurata per stabilire sessioni iSCSI con il sottosistema di storage durante l'avvio di RHEL 7.0. Poiché le sessioni iSCSI non vengono stabilite, il LUN root non viene rilevato all'avvio del sistema operativo e quindi l'avvio del sistema operativo non riesce. 
|===


== Quali sono le prossime novità?

* link:hu_luhu_71_cmd.html["Informazioni sull'utilizzo dello strumento Linux host Utilities"].
* Informazioni sul mirroring ASM.
+
Il mirroring ASM (Automatic Storage Management) potrebbe richiedere modifiche alle impostazioni del multipath Linux per consentire ad ASM di riconoscere un problema e passare a un gruppo di guasti alternativo. La maggior parte delle configurazioni ASM su ONTAP utilizza la ridondanza esterna, il che significa che la protezione dei dati viene fornita dall'array esterno e ASM non esegue il mirroring dei dati. Alcuni siti utilizzano ASM con ridondanza normale per fornire il mirroring bidirezionale, in genere su siti diversi. Per ulteriori informazioni, vederelink:https://docs.netapp.com/us-en/ontap-apps-dbs/oracle/oracle-overview.html["Database Oracle su ONTAP"^].


