---
sidebar: sidebar 
permalink: hu_rhel_70.html 
keywords: host utilities, red hat, rhel, linux, 7.0, netapp, ontap 
summary: Descrive come utilizzare Red Hat Enterprise Linux 7.0 con ONTAP 
---
= Utilizza Red Hat Enterprise Linux 7.0 con ONTAP
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content




== Installare le utility host unificate Linux

Il pacchetto software NetApp Linux Unified host Utilities è disponibile su link:https://mysupport.netapp.com/NOW/cgi-bin/software/?product=Host+Utilities+-+SAN&platform=Linux["Sito di supporto NetApp"^] in un file .rpm a 32 bit e a 64 bit. Se non si conosce il file appropriato per la configurazione, utilizzare link:https://mysupport.netapp.com/matrix/#welcome["Tool di matrice di interoperabilità NetApp"^] per verificare quale si desidera.

NetApp consiglia vivamente di installare le utility host unificate Linux, ma non è obbligatorio. Le utility non modificano le impostazioni dell'host Linux. Le utility migliorano la gestione e assistono il supporto clienti NetApp nella raccolta di informazioni sulla configurazione.

.Di cosa hai bisogno
Se si dispone di una versione di Linux Unified host Utilities attualmente installata, è necessario aggiornarla oppure rimuoverla e procedere come segue per installare la versione più recente.

. Scaricare il pacchetto software di utilità host unificate Linux a 32 bit o 64 bit dal link:https://mysupport.netapp.com/NOW/cgi-bin/software/?product=Host+Utilities+-+SAN&platform=Linux["Sito di supporto NetApp"^] Al tuo host.
. Utilizzare il seguente comando per installare il pacchetto software:
+
`rpm -ivh netapp_linux_unified_host_utilities-7-1.x86_64`




NOTE: È possibile utilizzare le impostazioni di configurazione fornite in questo documento per configurare i client cloud connessi a. link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/index.html["Cloud Volumes ONTAP"^] e. link:https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/index.html["Amazon FSX per ONTAP"^].



== Toolkit SAN

Il toolkit viene installato automaticamente quando si installa il pacchetto NetApp host Utilities. Questo kit fornisce `sanlun` Utility che consente di gestire LUN e HBA. Il `sanlun` Il comando restituisce le informazioni relative alle LUN mappate all'host, al multipathing e alle informazioni necessarie per creare gruppi di iniziatori.

.Esempio
Nell'esempio seguente, il `sanlun lun show` Il comando restituisce le informazioni sul LUN.

[source, cli]
----
# sanlun lun show all
----
Output di esempio:

[listing]
----
controller(7mode/E-Series)/            device     host               lun
vserver(cDOT/FlashRay)   lun-pathname  filename   adapter  protocol  size    Product
-------------------------------------------------------------------------
data_vserver          /vol/vol1/lun1   /dev/sdb   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol1/lun1   /dev/sdc   host15   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sdd   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sde   host15   FCP       120.0g  cDOT
----


== Avvio SAN

.Di cosa hai bisogno
Se si decide di utilizzare l'avvio SAN, questo deve essere supportato dalla configurazione. È possibile utilizzare link:https://mysupport.netapp.com/matrix/imt.jsp?components=68128;&solution=1&isHWU&src=IMT["Tool di matrice di interoperabilità NetApp"^] Per verificare che il sistema operativo, l'HBA, il firmware dell'HBA, il BIOS di avvio dell'HBA e la versione di ONTAP siano supportati.

.Fasi
. Mappare il LUN di avvio SAN sull'host.
. Verificare che siano disponibili più percorsi.
+

NOTE: Una volta attivato il sistema operativo host e eseguito sui percorsi, diventano disponibili più percorsi.

. Abilitare l'avvio SAN nel BIOS del server per le porte a cui è mappato il LUN di avvio SAN.
+
Per informazioni su come attivare il BIOS HBA, consultare la documentazione specifica del vendor.

. Riavviare l'host per verificare che l'avvio sia stato eseguito correttamente.




== Multipathing

Per Red Hat Enterprise Linux (RHEL) 7.0 il file /etc/multipath.conf deve esistere, ma non è necessario apportare modifiche specifiche al file. RHEL 7.0 è compilato con tutte le impostazioni necessarie per riconoscere e gestire correttamente le LUN ONTAP.

È possibile utilizzare `multipath -ll` Per verificare le impostazioni dei LUN ONTAP. Le sezioni seguenti forniscono un output multipath di esempio per un LUN mappato a figure ASA e non ASA.



=== Tutte le configurazioni DEGLI array SAN

Nelle configurazioni ASA, tutti i percorsi verso una determinata LUN sono attivi e ottimizzati. In questo modo, le performance vengono migliorate grazie alle operazioni di i/o in tutti i percorsi contemporaneamente.

.Esempio
Nell'esempio seguente viene visualizzato l'output corretto per un LUN ONTAP:

[listing]
----
# multipath -ll
3600a09803831347657244e527766394e dm-5 NETAPP,LUN C-Mode
size=80G  features='4 queue_if_no_path pg_init_retries 50 retain_attached_hw_handle' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 11:0:7:1    sdfi   130:64   active ready running
  |- 11:0:9:1    sdiy  8:288     active ready running
  |- 11:0:10:1  sdml 69:464   active ready running
  |- 11:0:11:1  sdpt  131:304  active ready running
----

NOTE: Non utilizzare un numero eccessivo di percorsi per una singola LUN. Non devono essere necessari più di quattro percorsi. Più di otto percorsi potrebbero causare problemi di percorso durante gli errori dello storage.



=== Configurazione non ASA

Per le configurazioni non ASA, devono essere presenti due gruppi di percorsi con priorità diverse. I percorsi con priorità più elevate sono Active/Optimized, ovvero vengono serviti dal controller in cui si trova l'aggregato. I percorsi con priorità inferiori sono attivi ma non ottimizzati perché vengono serviti da un controller diverso. I percorsi non ottimizzati vengono utilizzati solo quando non sono disponibili percorsi ottimizzati.

.Esempio
Nell'esempio seguente viene visualizzato l'output corretto per un LUN ONTAP con due percorsi attivi/ottimizzati e due percorsi attivi/non ottimizzati:

[listing]
----
# multipath -ll
3600a09803831347657244e527766394e dm-5 NETAPP,LUN C-Mode
size=80G features='4 queue_if_no_path pg_init_retries 50 retain_attached_hw_handle’ hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| |- 11:0:1:0 sdj  8:144  active ready running
| |- 11:0:2:0 sdr  65:16  active ready running
`-+- policy='service-time 0' prio=10 status=enabled
  |- 11:0:0:0 sdb  8:i6   active ready running
  |- 12:0:0:0 sdz  65:144 active ready running
----

NOTE: Non utilizzare un numero eccessivo di percorsi per una singola LUN. Non devono essere necessari più di quattro percorsi. Più di otto percorsi potrebbero causare problemi di percorso durante gli errori dello storage.



== Impostazioni consigliate

Il sistema operativo RHEL 7.0 viene compilato per riconoscere i LUN ONTAP e impostare automaticamente tutti i parametri di configurazione correttamente per la configurazione ASA e non ASA.

Il `multipath.conf` il file deve esistere per l'avvio del daemon multipath, ma è possibile creare un file vuoto a zero byte utilizzando il seguente comando:

`touch /etc/multipath.conf`

La prima volta che si crea questo file, potrebbe essere necessario attivare e avviare i servizi multipath:

[listing]
----
# systemctl enable multipathd
# systemctl start multipathd
----
* Non è necessario aggiungere nulla direttamente a `multipath.conf` file, a meno che non si disponga di periferiche che non si desidera gestire con multipath o che non si dispongano di impostazioni che sovrascrivono le impostazioni predefinite.
* Per escludere le periferiche indesiderate, aggiungere la seguente sintassi a `multipath.conf` file .
+
[listing]
----
blacklist {
        wwid <DevId>
        devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
        devnode "^hd[a-z]"
        devnode "^cciss.*"
}
----
+
Sostituire `<DevId>` con `WWID` stringa del dispositivo che si desidera escludere.

+
.Esempio
In questo esempio, determineremo il WWID di un dispositivo e aggiungeremo al `multipath.conf` file.

+
.Fasi
.. Eseguire il seguente comando per determinare l'ID WWID:
+
[listing]
----
# /lib/udev/scsi_id -gud /dev/sda
360030057024d0730239134810c0cb833
----
+
`sda` È il disco SCSI locale che dobbiamo aggiungere alla blacklist.

.. Aggiungere il `WWID` alla lista nera `/etc/multipath.conf`:
+
[listing]
----
blacklist {
     wwid   360030057024d0730239134810c0cb833
     devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
     devnode "^hd[a-z]"
     devnode "^cciss.*"
}
----




Controllare sempre il `/etc/multipath.conf` file per le impostazioni legacy, in particolare nella sezione delle impostazioni predefinite, che potrebbero prevalere sulle impostazioni predefinite.

La tabella seguente mostra la criticità `multipathd` Parametri per i LUN ONTAP e i valori richiesti. Se un host è connesso a LUN di altri vendor e uno qualsiasi di questi parametri viene ignorato, sarà necessario correggerli nelle successive stanze di `multipath.conf` File che si applicano specificamente alle LUN ONTAP. In caso contrario, i LUN ONTAP potrebbero non funzionare come previsto. Questi valori predefiniti devono essere ignorati solo previa consultazione di NetApp e/o di un vendor del sistema operativo e solo quando l'impatto è pienamente compreso.

[cols="2*"]
|===
| Parametro | Impostazione 


| detect_prio | sì 


| dev_loss_tmo | "infinito" 


| failback | immediato 


| fast_io_fail_tmo | 5 


| caratteristiche | "3 queue_if_no_path pg_init_retries 50" 


| flush_on_last_del | "sì" 


| gestore_hardware | "0" 


| no_path_retry | coda 


| path_checker | "a" 


| policy_di_raggruppamento_percorsi | "group_by_prio" 


| path_selector | "tempo di servizio 0" 


| intervallo_polling | 5 


| prio | "ONTAP" 


| prodotto | LUN.* 


| retain_attached_hw_handler | sì 


| peso_rr | "uniforme" 


| user_friendly_names | no 


| vendor | NETAPP 
|===
.Esempio
Nell'esempio seguente viene illustrato come correggere un valore predefinito sovrascritto. In questo caso, il `multipath.conf` il file definisce i valori per `path_checker` e. `no_path_retry` Non compatibili con LUN ONTAP. Se non possono essere rimossi a causa di altri array SAN ancora collegati all'host, questi parametri possono essere corretti specificamente per i LUN ONTAP con un dispositivo.

[listing]
----
defaults {
   path_checker      readsector0
   no_path_retry      fail
}

devices {
   device {
      vendor         "NETAPP  "
      product         "LUN.*"
      no_path_retry     queue
      path_checker      tur
   }
}
----


=== Impostazioni KVM

È possibile utilizzare le impostazioni consigliate anche per configurare la macchina virtuale basata su kernel (KVM). Non sono necessarie modifiche per configurare KVM poiché il LUN viene mappato all'hypervisor.



== Problemi e limitazioni noti

[cols="4*"]
|===
| ID bug NetApp | Titolo | Descrizione | ID Bugzilla 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=844417["844417"^] | L'host Emulex 16G FC (LPe16002B-M6) si blocca durante l'i/o con operazioni di failover dello storage | Si potrebbe osservare un crash dell'host 16G FC Emulex (LPe16002B-M6) durante le operazioni di i/o con failover dello storage. | link:https://bugzilla.redhat.com/show_bug.cgi?id=1131393["1131393"^] 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=811587["811587"^] | L'host Emulex 16G FC (LPe16002B-M6) si blocca durante l'i/o con operazioni di failover dello storage | Si potrebbe osservare un crash dell'host 16G FC Emulex (LPe16002B-M6) durante le operazioni di i/o con failover dello storage. | link:https://bugzilla.redhat.com/show_bug.cgi?id=1079735["1079735"^] 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=803071["803071"^] | L'host Emulex 16G FC (LPe16002B-M6) si blocca durante l'i/o con operazioni di failover dello storage | Si potrebbe osservare un crash dell'host 16G FC Emulex (LPe16002B-M6) durante le operazioni di i/o con failover dello storage. | link:https://bugzilla.redhat.com/show_bug.cgi?id=1067895["1067895"^] 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=820163["820163"^] | Blocco host QLogic o errori di percorso osservati durante le operazioni di i/o con failover dello storage | Durante le operazioni di i/o con failover dello storage, è possibile osservare un blocco host o errori di percorso sull'host QLogic. In tali scenari, potrebbe essere visualizzato il seguente messaggio: "Timeout cmd della mailbox, cmd=0x54, mb[0]=0x54 e firmware dump saved to temp buffer" che causa un errore di blocco/percorso dell'host. | link:https://bugzilla.redhat.com/show_bug.cgi?id=1090378["1090378"^] 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=799323["799323"^] | Blocco host Emulex FCoE (OCe10102-FX-D) o errori di percorso osservati durante i/o con operazioni di failover dello storage | Durante le operazioni di i/o con failover dello storage, è possibile osservare un blocco dell'host o errori di percorso sull'host Emulex 10G FCoE (OCe10102-FX-D). In tali scenari, potrebbe essere visualizzato il seguente messaggio: "Il pool di buffer del driver è vuoto, io busied e SCSI Layer i/o Abort Request Status" (Stato richiesta di interruzione i/o livello SCSI), che porta a errori di host hung/path. | link:https://bugzilla.redhat.com/show_bug.cgi?id=1061755["1061755"^] 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=849212["849212"^] | Durante le operazioni di i/o con failover dello storage, si osservano interruzioni dell'host Emulex 16G FC (LPe16002B-M6) o errori di percorso | Durante le operazioni di i/o con failover dello storage, è possibile osservare un blocco dell'host o errori di percorso sull'host Emulex 16G FC (LPe16002B-M6). In tali scenari, potrebbe essere visualizzato il seguente messaggio: "RSCN timeout Data and iotag x1301 is out of range: Max iotag" (dati timeout RSCN e iotag x1301 fuori intervallo: Max iotag), che porta a errori di host hung/path. | link:https://bugzilla.redhat.com/show_bug.cgi?id=1109274["1109274"^] 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=836800["836800"^] | Anaconda visualizza un messaggio di errore di accesso iSCSI, anche se gli accessi sono riusciti durante l'installazione del sistema operativo RHEL 7.0 | Quando si installa root(/) su un LUN iSCSI multipath'd, l'indirizzo IP per le interfacce Ethernet viene specificato nella riga di comando del kernel in modo che gli indirizzi IP vengano assegnati prima dell'avvio del servizio iSCSI. Tuttavia, dracut non può assegnare indirizzi IP a tutte le porte Ethernet durante l'avvio, prima dell'avvio del servizio iSCSI. In questo modo, l'accesso iSCSI non riesce sulle interfacce senza indirizzi IP. Il servizio iSCSI tenterà di effettuare il login più volte, causando un ritardo nel tempo di avvio del sistema operativo. | link:https://bugzilla.redhat.com/show_bug.cgi?id=1114966["1114966"^] 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=836875["836875"^] | Gli indirizzi IP non vengono sempre assegnati durante l'avvio di un sistema operativo RHEL 7.0 installato su un LUN iSCSI multipath | Durante l'installazione di RHEL 7.0, la schermata di installazione di anaconda mostra che l'accesso iSCSI a più IP di destinazione non è riuscito anche se gli accessi iSCSI sono riusciti. Anaconda visualizza il seguente messaggio di errore: "Node Login Failed" (accesso nodo non riuscito). Questo errore viene visualizzato solo quando si selezionano più indirizzi IP di destinazione per l'accesso iSCSI. Per continuare l'installazione del sistema operativo, fare clic sul pulsante "ok". Questo bug non ostacola l'installazione del sistema operativo iSCSI o RHEL 7.0. | link:https://bugzilla.redhat.com/show_bug.cgi?id=1114820["1114820"^] 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=836657["836657"^] | Anaconda non aggiunge l'argomento bootdev nella riga del cmd del kernel per impostare l'indirizzo IP per il sistema operativo RHEL 7.0 installato sul LUN iSCSI multipath'd | Anaconda non aggiunge un argomento bootdev nella riga di comando del kernel in cui si imposta l'indirizzo IPv4 durante l'installazione del sistema operativo RHEL 7.0 su un LUN iSCSI multipath'd. Ciò impedisce l'assegnazione di indirizzi IP a qualsiasi interfaccia Ethernet configurata per stabilire sessioni iSCSI con il sottosistema di storage durante l'avvio di RHEL 7.0. Poiché le sessioni iSCSI non vengono stabilite, il LUN root non viene rilevato all'avvio del sistema operativo e quindi l'avvio del sistema operativo non riesce. | link:https://bugzilla.redhat.com/show_bug.cgi?id=1114464["1114464"^] 
|===