---
sidebar: sidebar 
permalink: hu_rhel_75.html 
keywords: host utilities, red hat, rhel, linux, 7.5, netapp, ontap 
summary: Descrive come utilizzare Red Hat Enterprise Linux 7.5 con ONTAP 
---
= Configurare RHEL 7,5 per FCP e iSCSI con storage ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Il software Linux host Utilities fornisce strumenti di gestione e diagnostica per gli host Linux connessi allo storage ONTAP. Quando si installano le utilità host Linux su un host Red Hat Enterprise Linux (RHEL) 7,5, è possibile utilizzare le utilità host per gestire le operazioni dei protocolli FCP e iSCSI con i LUN ONTAP.


NOTE: Non è necessario configurare manualmente le impostazioni della macchina virtuale basata sul kernel (KVM) perché le LUN ONTAP vengono automaticamente mappate sull'hypervisor.



== Passaggio 1: Se lo si desidera, attivare l'avvio SAN

È possibile configurare l'host in modo che utilizzi l'avvio SAN per semplificare l'installazione e migliorare la scalabilità.

.Prima di iniziare
Utilizzare link:https://mysupport.netapp.com/matrix/#welcome["Tool di matrice di interoperabilità"^]per verificare che il sistema operativo Linux, l'HBA (host Bus Adapter), il firmware HBA, il BIOS di avvio HBA e la versione ONTAP supportino l'avvio SAN.

.Fasi
. link:https://docs.netapp.com/us-en/ontap/san-admin/provision-storage.html["Crea un LUN di avvio SAN e mappalo all'host"^].
. Abilitare l'avvio SAN nel BIOS del server per le porte a cui è mappato il LUN di avvio SAN.
+
Per informazioni su come attivare il BIOS HBA, consultare la documentazione specifica del vendor.

. Verificare che la configurazione sia stata eseguita correttamente riavviando l'host e verificando che il sistema operativo sia attivo e funzionante.




== Fase 2: Installare le utilità host Linux

NetApp consiglia vivamente di installare le utilità host Linux per supportare la gestione LUN di ONTAP e fornire assistenza tecnica nella raccolta dei dati di configurazione.

link:hu_luhu_71.html["Installare le utilità host Linux 7,1"].


NOTE: L'installazione di Linux host Utilities non modifica le impostazioni di timeout dell'host sul proprio host Linux.



== Fase 3: Verificare la configurazione multipath per l'host

È possibile utilizzare multipathing con RHEL 7,5 per gestire i LUN di ONTAP.

Per verificare che il multipathing sia configurato correttamente per l'host, verificare che il `/etc/multipath.conf` file sia definito e che siano configurate le impostazioni consigliate da NetApp per i LUN ONTAP.

.Fasi
. Verificare che il `/etc/multipath.conf` file esista:
+
[source, cli]
----
ls /etc/multipath.conf
----
+
Se il file non esiste, creare un file vuoto a zero byte:

+
[source, cli]
----
touch /etc/multipath.conf
----
. La prima volta che `multipath.conf` si crea il file, potrebbe essere necessario attivare e avviare i servizi multipath per caricare le impostazioni consigliate:
+
[source, cli]
----
systemctl enable multipathd
----
+
[source, cli]
----
systemctl start multipathd
----
. Ogni volta che si avvia l'host, il file vuoto `/etc/multipath.conf` con zero byte carica automaticamente i parametri multipath dell'host raccomandati da NetApp come impostazioni predefinite. Non è necessario apportare modifiche al `/etc/multipath.conf` file per l'host perché il sistema operativo host è compilato con i parametri multipath che riconoscono e gestiscono correttamente i LUN ONTAP.
+
La tabella seguente mostra le impostazioni dei parametri multipercorso compilati dal sistema operativo Linux nativo per i LUN ONTAP.

+
.Mostra impostazioni parametri
[%collapsible]
====
[cols="2"]
|===
| Parametro | Impostazione 


| detect_prio | sì 


| dev_loss_tmo | "infinito" 


| failback | immediato 


| fast_io_fail_tmo | 5 


| caratteristiche | "3 queue_if_no_path pg_init_retries 50" 


| flush_on_last_del | "sì" 


| gestore_hardware | "0" 


| no_path_retry | coda 


| path_checker | "a" 


| policy_di_raggruppamento_percorsi | "group_by_prio" 


| path_selector | "tempo di servizio 0" 


| intervallo_polling | 5 


| prio | "ONTAP" 


| prodotto | LUN.* 


| retain_attached_hw_handler | sì 


| peso_rr | "uniforme" 


| user_friendly_names | no 


| vendor | NETAPP 
|===
====
. Verificare le impostazioni dei parametri e lo stato del percorso dei LUN ONTAP:
+
[source, cli]
----
multipath -ll
----
+
I parametri multipath predefiniti supportano le configurazioni ASA, AFF e FAS. In queste configurazioni, una singola LUN ONTAP non deve richiedere più di quattro percorsi. Se sono presenti più di quattro percorsi, potrebbero verificarsi problemi con i percorsi durante un errore di storage.

+
I seguenti output di esempio mostrano le impostazioni corrette dei parametri e lo stato del percorso per i LUN ONTAP in una configurazione ASA, AFF o FAS.

+
[role="tabbed-block"]
====
.Configurazione ASA
--
Una configurazione ASA ottimizza tutti i percorsi verso una determinata LUN, mantenendoli attivi. In questo modo, le performance vengono migliorate grazie alle operazioni di i/o in tutti i percorsi contemporaneamente.

[listing]
----
# multipath -ll
3600a09803831347657244e527766394e dm-5 NETAPP,LUN C-Mode
size=80G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 3:0:7:9    sdco 69:192  active ready running
  |- 3:0:8:9    sddi 71:0    active ready running
  |- 14:0:8:9   sdjq 65:320  active ready running
  `- 14:0:7:9   sdiw 8:256   active ready running
----
--
.Configurazione AFF o FAS
--
Una configurazione AFF o FAS deve avere due gruppi di percorsi con priorità maggiore e minore. I percorsi Active/Optimized di priorità più elevata sono serviti dal controller in cui si trova l'aggregato. I percorsi a priorità inferiore sono attivi ma non ottimizzati perché serviti da un controller diverso. I percorsi non ottimizzati vengono utilizzati solo quando non sono disponibili percorsi ottimizzati.

L'esempio seguente visualizza l'output per una LUN ONTAP con due percorsi attivi/ottimizzati e due percorsi attivi/non ottimizzati:

[listing]
----
# multipath -ll
3600a09803831347657244e527766394e dm-5 NETAPP,LUN C-Mode
size=80G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| |- 3:0:3:0    sdd  8:48    active ready running
| |- 3:0:4:0    sdx  65:112  active ready running
`-+- policy='service-time 0' prio=10 status=enabled
  |- 14:0:2:0   sdfk 130:96  active ready running
  `- 14:0:5:0   sdgz 132:240 active ready running
----
--
====




== Passaggio 4: Se si desidera, escludere un dispositivo dal multipathing

Se necessario, è possibile escludere un dispositivo dal multipathing aggiungendo il WWID per il dispositivo indesiderato alla stanza "blacklist" per il `multipath.conf` file.

.Fasi
. Determinare il WWID:
+
[source, cli]
----
/lib/udev/scsi_id -gud /dev/sda
----
+
"sda" è il disco SCSI locale che si desidera aggiungere alla blacklist.

+
Un esempio di WWID è `360030057024d0730239134810c0cb833`.

. Aggiungere il WWID alla "blacklist" stanza:
+
[source, cli]
----
blacklist {
	     wwid   360030057024d0730239134810c0cb833
        devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
        devnode "^hd[a-z]"
        devnode "^cciss.*"
}
----




== Passaggio 5: Personalizzare i parametri multipath per i LUN ONTAP

Se l'host è connesso a LUN di altri fornitori e le impostazioni dei parametri multipath vengono sovrascritte, è necessario correggerle aggiungendo più avanti nel `multipath.conf` file che si applicano specificamente ai LUN di ONTAP. In caso contrario, i LUN di ONTAP potrebbero non funzionare come previsto.

Controllare il file, in particolare nella sezione dei valori predefiniti, per verificare `/etc/multipath.conf` le impostazioni che potrebbero sovrascrivere <<multipath-parameter-settings,impostazioni predefinite per i parametri multipath>>.


CAUTION: Non sovrascrivere le impostazioni dei parametri consigliate per i LUN ONTAP. Queste impostazioni sono necessarie per ottenere prestazioni ottimali della configurazione host. Per ulteriori informazioni, contattare l'assistenza NetApp, il fornitore del sistema operativo o entrambi.

Nell'esempio seguente viene illustrato come correggere un valore predefinito sovrascritto. In questo esempio, il `multipath.conf` file definisce i valori per `path_checker` e `no_path_retry` che non sono compatibili con i LUN ONTAP e non è possibile rimuovere questi parametri perché gli array di storage ONTAP sono ancora collegati all'host. È invece possibile correggere i valori per `path_checker` e `no_path_retry` aggiungendo una stanza di dispositivo al `multipath.conf` file che si applica specificamente ai LUN di ONTAP.

[listing, subs="+quotes"]
----
defaults {
   path_checker      *readsector0*
   no_path_retry     *fail*
}

devices {
   device {
      vendor          "NETAPP"
      product         "LUN"
      no_path_retry   *queue*
      path_checker    *tur*
   }
}
----


== Fase 6: Esaminare i problemi noti

La versione RHEL 7,5 con storage ONTAP presenta i seguenti problemi noti:

[cols="3*"]
|===
| ID bug NetApp | Titolo | Descrizione 


| 1440718 | Se si dismappa o si mappa un LUN senza eseguire una nuova scansione SCSI, i dati sull'host potrebbero danneggiarsi. | Quando si imposta il parametro di configurazione multipath 'disable_changed_wids' su YES, l'accesso al path device viene disattivato in caso di modifica dell'ID WWID. Multipath disattiva l'accesso al dispositivo di percorso fino a quando l'ID WWID del percorso non viene ripristinato all'ID WWID del dispositivo multipath. Per ulteriori informazioni, vedere link:https://kb.netapp.com/Advice_and_Troubleshooting/Flash_Storage/AFF_Series/The_filesystem_corruption_on_iSCSI_LUN_on_the_Oracle_Linux_7["Knowledge base di NetApp: La corruzione del file system sul LUN iSCSI su Oracle Linux 7"^]. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1139053["1139053"^] | L'interruzione del kernel si verifica su RHEL7.5 con QLogic QLE2672 16 GB FC durante le operazioni di failover dello storage | Durante le operazioni di failover dello storage sul kernel RHEL7U5 con adattatore bus host Fibre Channel QLogic QLE2672 da 16 GB, il kernel si disgregazione a causa di un panico nel kernel. Il kernel panic causa il riavvio di RHEL 7.5, con conseguente interruzione dell'applicazione. Il kernel panic genera il file vmcore nella directory /var/crash/se kdump è configurato. Il file vmcore viene utilizzato per comprendere la causa dell'errore. In questo caso, il panico è stato osservato nel modulo "get_next_timer_interrupt+440" che viene registrato nel file vmcore con la seguente stringa: " [Exception RIP: Get_next_timer_interrupt+440]" dopo l'interruzione del kernel, è possibile ripristinare il sistema operativo riavviando il sistema operativo host e riavviando l'applicazione secondo necessità. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1138536["1138536"^] | L'interruzione del kernel si verifica su RHEL7U5 con QLogic QLE2742 32 GB FC durante le operazioni di failover dello storage | Durante le operazioni di failover dello storage sul kernel Red Hat Enterprise Linux (RHEL) RHEL7U5 con QLogic QLE2742 HBA, il kernel si disgregazione a causa di un panico nel kernel. Il kernel panic causa il riavvio del sistema operativo, causando un'interruzione dell'applicazione. Il kernel panic genera il file vmcore nella directory /var/crash/ se kdump è configurato. Quando il kernel panica, è possibile utilizzare il file vmcore per esaminare il motivo del guasto. L'esempio seguente mostra un panic nel modulo bget_next_timer_interrupt+440b. Il panic viene registrato nel file vmcore con la seguente stringa: " [Exception RIP: Get_next_timer_interrupt+440]" Potete ripristinare il sistema operativo riavviando il sistema operativo host e riavviando l'applicazione secondo necessità. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1148090["1148090"^] | L'interruzione del kernel si verifica su RHEL 7.5 con QLogic QLE2742 32 GB FC HBA durante le operazioni di failover dello storage | Durante le operazioni di failover dello storage sul kernel Red Hat Enterprise Linux (RHEL) 7.5 con un HBA (host bus adapter) QLogic QLE2742 Fibre Channel (FC), si verifica un'interruzione del kernel a causa di un panico nel kernel. Il kernel panic causa il riavvio di RHEL 7.5, con conseguente interruzione dell'applicazione. Se il meccanismo kdump è attivato, il kernel panic genera un file vmcore che si trova nella directory /var/crash/. È possibile analizzare il file vmcore per determinare la causa del panico. In questo caso, quando si verifica il failover dello storage con l'evento QLogic QLE2742 HBA, il modulo "native_queed_spin_lock_slowpath+464" è interessato. È possibile individuare l'evento nel file vmcore individuando la seguente stringa: " [Exception RIP: Native_queed_spin_lock_slowpath+464]" dopo l'interruzione del kernel, è possibile riavviare il sistema operativo host e ripristinare il sistema operativo, quindi riavviare le applicazioni secondo necessità. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1146898["1146898"^] | L'interruzione del kernel si verifica su RHEL 7.5 con HBA Emulex durante le operazioni di failover dello storage | Durante le operazioni di failover dello storage su un sistema Red Hat Enterprise Linux (RHEL) 7.5 con HBA (host bus adapter) FC Emulex LPe32002-M2 da 32 GB, si verifica un'interruzione nel kernel. L'interruzione del kernel causa un riavvio del sistema operativo, che a sua volta causa un'interruzione dell'applicazione. Se si configura kdump, l'interruzione del kernel genera il file vmcore nella directory /var/crash/. È possibile utilizzare il file vmcore per determinare la causa dell'errore. Nell'esempio seguente, è possibile vedere l'interruzione nel modulo "lpfc_hba_clean_txcmplq+368". Questa interruzione viene registrata nel file vmcore con la seguente stringa: " [Exception RIP: Lpfc_hba_clean_txcmplq+368]" dopo l'interruzione del kernel, riavviare il sistema operativo host per ripristinare il sistema operativo. Riavviare l'applicazione secondo necessità. 
|===


== Quali sono le prossime novità?

* link:hu_luhu_71_cmd.html["Informazioni sull'utilizzo dello strumento Linux host Utilities"].
* Informazioni sul mirroring ASM.
+
Il mirroring ASM (Automatic Storage Management) potrebbe richiedere modifiche alle impostazioni del multipath Linux per consentire ad ASM di riconoscere un problema e passare a un gruppo di guasti alternativo. La maggior parte delle configurazioni ASM su ONTAP utilizza la ridondanza esterna, il che significa che la protezione dei dati viene fornita dall'array esterno e ASM non esegue il mirroring dei dati. Alcuni siti utilizzano ASM con ridondanza normale per fornire il mirroring bidirezionale, in genere su siti diversi. Per ulteriori informazioni, vederelink:https://docs.netapp.com/us-en/ontap-apps-dbs/oracle/oracle-overview.html["Database Oracle su ONTAP"^].


