---
sidebar: sidebar 
permalink: hu_rhel_80.html 
keywords: host utilities, red hat, rhel, linux, 8.0, netapp, ontap 
summary: Descrive come utilizzare Red Hat Enterprise Linux 8.0 con ONTAP 
---
= Utilizza Red Hat Enterprise Linux 8.0 con ONTAP
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content




== Installare le utility host unificate Linux

Il pacchetto software NetApp Linux Unified host Utilities è disponibile su link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab["Sito di supporto NetApp"^] in un file .rpm a 64 bit.

NetApp consiglia vivamente di installare le utility host unificate Linux, ma non è obbligatorio. Le utility non modificano le impostazioni dell'host Linux. Le utility migliorano la gestione e assistono il supporto clienti NetApp nella raccolta di informazioni sulla configurazione.

.Di cosa hai bisogno
Se si dispone di una versione di Linux Unified host Utilities attualmente installata, eseguire l'aggiornamento o la rimozione, quindi attenersi alla procedura descritta di seguito per installare la versione più recente.

.Fasi
. Scaricare il pacchetto software 64-bit Linux Unified host Utilities dal https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab["Sito di supporto NetApp"^] al tuo host.
. Installare il pacchetto software:
+
`rpm -ivh netapp_linux_unified_host_utilities-7-1.x86_64`




NOTE: È possibile utilizzare le impostazioni di configurazione fornite in questo documento per configurare i client cloud connessi a. link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/index.html["Cloud Volumes ONTAP"^] e. link:https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/index.html["Amazon FSX per ONTAP"^].



== Toolkit SAN

Il toolkit viene installato automaticamente quando si installa il pacchetto NetApp host Utilities. Questo kit fornisce `sanlun` Utility che consente di gestire LUN e HBA. Il `sanlun` Il comando restituisce le informazioni relative alle LUN mappate all'host, al multipathing e alle informazioni necessarie per creare gruppi di iniziatori.

.Esempio
Nell'esempio seguente, il `sanlun lun show` Il comando restituisce le informazioni sul LUN.

[listing]
----
# sanlun lun show all
----
Output di esempio:

[listing]
----
controller(7mode/E-Series)/            device     host               lun
vserver(cDOT/FlashRay)   lun-pathname  filename   adapter  protocol  size    Product
-------------------------------------------------------------------------
data_vserver          /vol/vol1/lun1   /dev/sdb   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol1/lun1   /dev/sdc   host15   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sdd   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sde   host15   FCP       120.0g  cDOT
----


== Avvio SAN

.Di cosa hai bisogno
Se si decide di utilizzare l'avvio SAN, questo deve essere supportato dalla configurazione. È possibile utilizzare link:https://mysupport.netapp.com/matrix/imt.jsp?components=91241;&solution=236&isHWU&src=IMT["Tool di matrice di interoperabilità NetApp"^] Per verificare che il sistema operativo, l'HBA, il firmware dell'HBA, il BIOS di avvio dell'HBA e la versione di ONTAP siano supportati.

.Fasi
. Mappare il LUN di avvio SAN sull'host.
. Verificare che siano disponibili più percorsi.
+

NOTE: Una volta attivato il sistema operativo host e eseguito sui percorsi, diventano disponibili più percorsi.

. Abilitare l'avvio SAN nel BIOS del server per le porte a cui è mappato il LUN di avvio SAN.
+
Per informazioni su come attivare il BIOS HBA, consultare la documentazione specifica del vendor.

. Riavviare l'host per verificare che l'avvio sia stato eseguito correttamente.




== Multipathing

Per Red Hat Enterprise Linux (RHEL) 8.0 il file /etc/multipath.conf deve esistere, ma non è necessario apportare modifiche specifiche al file. RHEL 8.0 è compilato con tutte le impostazioni necessarie per riconoscere e gestire correttamente le LUN ONTAP.

È possibile utilizzare `multipath -ll` Per verificare le impostazioni dei LUN ONTAP. Le sezioni seguenti forniscono un output multipath di esempio per un LUN mappato a figure ASA e non ASA.



=== Tutte le configurazioni DEGLI array SAN

Nelle configurazioni ASA, tutti i percorsi verso una determinata LUN sono attivi e ottimizzati. In questo modo, le performance vengono migliorate grazie alle operazioni di i/o in tutti i percorsi contemporaneamente.

.Esempio
Nell'esempio seguente viene visualizzato l'output corretto per un LUN ONTAP:

[listing]
----
# multipath -ll
3600a098038303634722b4d59646c4436 dm-28 NETAPP,LUN C-Mode
size=80G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 11:0:7:1    sdfi   130:64   active ready running
  |- 11:0:9:1    sdiy  8:288     active ready running
  |- 11:0:10:1  sdml 69:464   active ready running
  |- 11:0:11:1  sdpt  131:304  active ready running
----

NOTE: Non utilizzare un numero eccessivo di percorsi per una singola LUN. Non devono essere necessari più di quattro percorsi. Più di otto percorsi potrebbero causare problemi di percorso durante gli errori dello storage.



=== Configurazione non ASA

Per le configurazioni non ASA, devono essere presenti due gruppi di percorsi con priorità diverse. I percorsi con priorità più elevate sono Active/Optimized, ovvero vengono serviti dal controller in cui si trova l'aggregato. I percorsi con priorità inferiori sono attivi ma non ottimizzati perché vengono serviti da un controller diverso. I percorsi non ottimizzati vengono utilizzati solo quando non sono disponibili percorsi ottimizzati.

.Esempio
Nell'esempio seguente viene visualizzato l'output corretto per un LUN ONTAP con due percorsi attivi/ottimizzati e due percorsi attivi/non ottimizzati:

[listing]
----
# multipath -ll
3600a098038303634722b4d59646c4436 dm-28 NETAPP,LUN C-Mode
size=80G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 11:0:7:1    sdfi   130:64   active ready running
  |- 11:0:9:1    sdiy  8:288     active ready running
  |- 11:0:10:1  sdml 69:464   active ready running
  |- 11:0:11:1  sdpt  131:304  active ready running
----

NOTE: Non utilizzare un numero eccessivo di percorsi per una singola LUN. Non devono essere necessari più di quattro percorsi. Più di otto percorsi potrebbero causare problemi di percorso durante gli errori dello storage.



== Impostazioni consigliate

Il sistema operativo RHEL 8.0 viene compilato per riconoscere i LUN ONTAP e impostare automaticamente tutti i parametri di configurazione correttamente per la configurazione ASA e non ASA.

Il `multipath.conf` il file deve esistere per l'avvio del daemon multipath, ma è possibile creare un file vuoto a zero byte utilizzando il seguente comando:

`touch /etc/multipath.conf`

La prima volta che si crea questo file, potrebbe essere necessario attivare e avviare i servizi multipath:

[listing]
----
# systemctl enable multipathd
# systemctl start multipathd
----
* Non è necessario aggiungere nulla direttamente a `multipath.conf` file, a meno che non si disponga di periferiche che non si desidera gestire con multipath o che non si dispongano di impostazioni che sovrascrivono le impostazioni predefinite.
* Per escludere le periferiche indesiderate, aggiungere la seguente sintassi a `multipath.conf` file .
+
[listing]
----
blacklist {
        wwid <DevId>
        devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
        devnode "^hd[a-z]"
        devnode "^cciss.*"
}
----
+
Sostituire `<DevId>` con `WWID` stringa del dispositivo che si desidera escludere.



.Esempio
In questo esempio, `sda` È il disco SCSI locale da aggiungere alla blacklist.

.Fasi
. Eseguire il seguente comando per determinare l'ID WWID:
+
[listing]
----
# /lib/udev/scsi_id -gud /dev/sda
360030057024d0730239134810c0cb833
----
. Aggiungere il `WWID` alla lista nera `/etc/multipath.conf`:
+
[listing]
----
blacklist {
     wwid   360030057024d0730239134810c0cb833
     devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
     devnode "^hd[a-z]"
     devnode "^cciss.*"
}
----


Controllare sempre il `/etc/multipath.conf` file per le impostazioni legacy, in particolare nella sezione delle impostazioni predefinite, che potrebbero prevalere sulle impostazioni predefinite.

La tabella seguente mostra la criticità `multipathd` Parametri per i LUN ONTAP e i valori richiesti. Se un host è connesso a LUN di altri vendor e uno qualsiasi di questi parametri viene ignorato, sarà necessario correggerli nelle successive stanze di `multipath.conf` File che si applicano specificamente alle LUN ONTAP. In caso contrario, i LUN ONTAP potrebbero non funzionare come previsto. Questi valori predefiniti devono essere ignorati solo previa consultazione di NetApp e/o di un vendor del sistema operativo e solo quando l'impatto è pienamente compreso.

[cols="2*"]
|===
| Parametro | Impostazione 


| detect_prio | sì 


| dev_loss_tmo | "infinito" 


| failback | immediato 


| fast_io_fail_tmo | 5 


| caratteristiche | "2 pg_init_retries 50" 


| flush_on_last_del | "sì" 


| gestore_hardware | "0" 


| no_path_retry | coda 


| path_checker | "a" 


| policy_di_raggruppamento_percorsi | "group_by_prio" 


| path_selector | "tempo di servizio 0" 


| intervallo_polling | 5 


| prio | "ONTAP" 


| prodotto | LUN.* 


| retain_attached_hw_handler | sì 


| peso_rr | "uniforme" 


| user_friendly_names | no 


| vendor | NETAPP 
|===
.Esempio
Nell'esempio seguente viene illustrato come correggere un valore predefinito sovrascritto. In questo caso, il `multipath.conf` il file definisce i valori per `path_checker` e. `no_path_retry` Non compatibili con LUN ONTAP. Se non possono essere rimossi a causa di altri array SAN ancora collegati all'host, questi parametri possono essere corretti specificamente per i LUN ONTAP con un dispositivo.

[listing]
----
defaults {
   path_checker      readsector0
   no_path_retry      fail
}

devices {
   device {
      vendor         "NETAPP  "
      product         "LUN.*"
      no_path_retry     queue
      path_checker      tur
   }
}
----


=== Impostazioni KVM

È possibile utilizzare le impostazioni consigliate anche per configurare la macchina virtuale basata su kernel (KVM). Non sono necessarie modifiche per configurare KVM poiché il LUN viene mappato all'hypervisor.



== Problemi e limitazioni noti

[cols="4*"]
|===
| ID bug NetApp | Titolo | Descrizione | ID Bugzilla 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1238719["1238719"^] | Interruzione del kernel su RHEL8 con QLogic QLE2672 16 GB FC durante le operazioni di failover dello storage | Durante le operazioni di failover dello storage su un kernel Red Hat Enterprise Linux (RHEL) 8 con un HBA QLogic QLE2672. L'interruzione del kernel causa il riavvio del sistema operativo. Il riavvio causa l'interruzione dell'applicazione e genera il file vmcore nella directory /var/crash/se kdump è configurato. Utilizzare il file vmcore per identificare la causa dell'errore. In questo caso, l'interruzione si verifica nel modulo "kmem_cache_alloc+160". Viene registrato nel file vmcore con la seguente stringa: "[Exception RIP: Kmem_cache_alloc+160]". Riavviare il sistema operativo host per ripristinare il sistema operativo, quindi riavviare l'applicazione. | link:https://bugzilla.redhat.com/show_bug.cgi?id=1710009["1710009"^] 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1226783["1226783"^] | Il sistema operativo RHEL8 si avvia in "modalità di emergenza" quando più di 204 dispositivi SCSI sono mappati su tutti gli HBA (host bus adapter) Fibre Channel (FC) | Se un host viene mappato con più di 204 dispositivi SCSI durante un processo di riavvio del sistema operativo, il sistema operativo RHEL8 non riesce ad avviarsi in "modalità normale" e passa in "modalità di emergenza". Ciò comporta l'indisponibilità della maggior parte dei servizi host. | link:https://bugzilla.redhat.com/show_bug.cgi?id=1690356["1690356"^] 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1230882["1230882"^] | La creazione di una partizione su un dispositivo iSCSI multipath durante l'installazione di RHEL8 non è possibile. | I dispositivi multipath iSCSI SAN LUN non sono elencati nella selezione del disco durante l'installazione di RHEL 8. Di conseguenza, il servizio multipath non è abilitato sul dispositivo di boot SAN. | link:https://bugzilla.redhat.com/show_bug.cgi?id=1709995["1709995"^] 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1235998["1235998"^] | Il comando "rescan-scsi-bus.sh -a" non esegue la scansione di più di 328 dispositivi | Se un host Red Hat Enterprise Linux 8 esegue la mappatura con più di 328 dispositivi SCSI, il comando del sistema operativo host "rescan-scsi-bus.sh -a" esegue la scansione solo di 328 dispositivi. L'host non rileva i dispositivi mappati rimanenti. | link:https://bugzilla.redhat.com/show_bug.cgi?id=1709995["1709995"^] 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1231087["1231087"^] | Le porte remote transitano in uno stato bloccato su RHEL8 con Emulex LPe16002 16 GB FC durante le operazioni di failover dello storage | Le porte remote transitano in uno stato bloccato su RHEL8 con Emulex LPe16002 16 GB Fibre Channel (FC) durante le operazioni di failover dello storage. Quando il nodo di storage torna a uno stato ottimale, vengono visualizzati anche i file LIF e lo stato della porta remota deve essere "online". A volte, lo stato della porta remota potrebbe continuare a essere "bloccato" o "non presente". Questo stato può portare a un percorso "guasto" verso le LUN nel layer multipath | link:https://bugzilla.redhat.com/show_bug.cgi?id=1702005["1702005"^] 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1231098["1231098"^] | Le porte remote transitano nello stato bloccato su RHEL8 con Emulex LPe32002 32 GB FC durante le operazioni di failover dello storage | Le porte remote transitano in uno stato bloccato su RHEL8 con Emulex LPe32002 32GBFibre Channel (FC) durante le operazioni di failover dello storage. Quando il nodo di storage torna a uno stato ottimale, vengono visualizzati anche i file LIF e lo stato della porta remota deve essere "online". A volte, lo stato della porta remota potrebbe continuare a essere "bloccato" o "non presente". Questo stato può portare a un percorso "guasto" verso le LUN nel layer multipath. | link:https://bugzilla.redhat.com/show_bug.cgi?id=1705573["1705573"^] 
|===