---
sidebar: sidebar 
permalink: hu_rhel_810.html 
keywords: host utilities, red hat, rhel, linux, 8.10, netapp, ontap, rhel 
summary: Descrive come utilizzare Red Hat Enterprise Linux 8,10 con ONTAP 
---
= Utilizzate Red Hat Enterprise Linux 8,10 con ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È possibile utilizzare le impostazioni di configurazione dell'host SAN di ONTAP per configurare Red Hat Enterprise Linux (RHEL) 8,10 con ONTAP come destinazione.



== Installare le utility host unificate Linux

È possibile scaricare il pacchetto software NetApp Linux Unified host Utilities come file 64-bit.rpm dal link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["Sito di supporto NetApp"^].

NetApp consiglia vivamente di installare le utility host unificate Linux, ma non è obbligatorio. Le utility non modificano le impostazioni dell'host Linux. Le utility migliorano la gestione e assistono il supporto clienti NetApp nella raccolta di informazioni sulla configurazione.

.Fasi
. Scaricare il pacchetto software 64-bit Linux Unified host Utilities dal https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["Sito di supporto NetApp"^] al tuo host.
. Installare il pacchetto software:
+
`rpm -ivh netapp_linux_unified_host_utilities-7-1.x86_64`





== Kit di strumenti SAN

Il kit di strumenti viene installato automaticamente quando si installa il pacchetto di utilità host NetApp. Questo kit fornisce `sanlun` Utility che consente di gestire LUN e HBA (host bus adapter). Il `sanlun` Il comando restituisce le informazioni relative alle LUN mappate all'host, al multipathing e alle informazioni necessarie per creare gruppi di iniziatori.

Nell'esempio seguente, il `sanlun lun show` Il comando restituisce le informazioni sul LUN.

[listing]
----
# sanlun lun show all
----
.Output di esempio:
[listing]
----
controller(7mode/E-Series)/                               device       host                  lun
vserver(cDOT/FlashRay)     lun-pathname                   filename     adapter    protocol   size    product
---------------------------------------------------------------------------------------------------------------
vs_25_2742                 /vol/fc_vol_1_0/dynamic_lun   /dev/sdh      host9      FCP        10g     cDOT
vs_25_2742                 /vol/fc_vol_1_1/dynamic_lun   /dev/sdb      host9      FCP        10g     cDOT
vs_25_2742                 /vol/fc_vol_1_3/dynamic_lun   /dev/sdg      host9      FCP        10g     cDOT
vs_25_2742                 /vol/fc_vol_1_4/dynamic_lun   /dev/sdt      host9      FCP        10g     cDOT

----


== Avvio SAN

.Di cosa hai bisogno
Se si decide di utilizzare l'avvio SAN, questo deve essere supportato dalla configurazione. È possibile utilizzare link:https://mysupport.netapp.com/matrix/imt["Tool di matrice di interoperabilità NetApp"^] Per verificare che il sistema operativo, l'HBA, il firmware dell'HBA, il BIOS di avvio dell'HBA e la versione di ONTAP siano supportati.

.Fasi
. Mappare il LUN di avvio SAN sull'host.
. Verificare che siano disponibili più percorsi.
+

NOTE: Più percorsi diventano disponibili dopo che il sistema operativo host è attivo e in esecuzione sui percorsi.

. Abilitare l'avvio SAN nel BIOS del server per le porte a cui è mappato il LUN di avvio SAN.
+
Per informazioni su come attivare il BIOS HBA, consultare la documentazione specifica del vendor.

. Riavviare l'host per verificare che l'avvio sia stato eseguito correttamente.




== Multipathing

Per RHEL 8,10, il `/etc/multipath.conf` il file deve esistere, ma non è necessario apportare modifiche specifiche al file. RHEL 8,10 è compilato con tutte le impostazioni necessarie per riconoscere e gestire correttamente i LUN ONTAP.

È possibile utilizzare `multipath -ll` Per verificare le impostazioni dei LUN ONTAP.

Nelle sezioni seguenti vengono forniti esempi di output multipath per una LUN mappata a figure ASA e non ASA.



=== Tutte le configurazioni DEGLI array SAN

Tutte le configurazioni di array SAN (ASA) ottimizzano tutti i percorsi verso una determinata LUN, mantenendoli attivi. In questo modo, le performance vengono migliorate grazie alle operazioni di i/o in tutti i percorsi contemporaneamente.

.Esempio
Nell'esempio seguente viene visualizzato l'output corretto per un LUN ONTAP.

[listing]
----
# multipath -ll
3600a098038314778375d53694b536e53 dm-16 NETAPP, LUN C-Mode
size=160G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 14:0:0:0   sda  8:0    active ready running
  |- 15:0:8:0   sdcf 69:48  active ready running
  |- 15:0:0:0   sdaq 66:160 active ready running
  `- 14:0:9:0   sdv  65:80  active ready running
----

NOTE: Un singolo LUN non deve richiedere più di quattro percorsi. La presenza di più di quattro percorsi potrebbe causare problemi di percorso durante gli errori di storage.



=== Configurazioni non ASA

Per le configurazioni non ASA, devono essere presenti due gruppi di percorsi con priorità diverse. I percorsi con priorità più elevate sono Active/Optimized, ovvero gestiti dal controller in cui si trova l'aggregato. I percorsi con priorità più basse sono attivi ma non ottimizzati perché sono serviti da un controller diverso. I percorsi non ottimizzati vengono utilizzati solo quando i percorsi ottimizzati non sono disponibili.

.Esempio
Nell'esempio seguente viene visualizzato l'output corretto per un LUN ONTAP con due percorsi attivi/ottimizzati e due percorsi attivi/non ottimizzati.

[listing]
----
# multipath -ll
3600a098038314837352453694b542f4a dm-0 NETAPP,LUN C-Mode
size=160G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| |- 14:0:3:0 sdbk 67:224 active ready running
| `- 15:0:2:0 sdbl 67:240 active ready running
`-+- policy='service-time 0' prio=10 status=enabled
  |- 14:0:0:0 sda  8:0    active ready running
  `- 15:0:1:0 sdv  65:80  active ready running
----

NOTE: Un singolo LUN non deve richiedere più di quattro percorsi. La presenza di più di quattro percorsi potrebbe causare problemi di percorso durante gli errori di storage.



== Impostazioni consigliate

Il sistema operativo RHEL 8,10 riconosce i LUN ONTAP e imposta automaticamente tutti i parametri di configurazione per le configurazioni ASA e non ASA. È possibile ottimizzare ulteriormente le prestazioni per la configurazione host con le seguenti impostazioni consigliate.

Il `multipath.conf` file deve esistere per avviare il daemon multipath. Se questo file non esiste, è possibile creare un file vuoto a zero byte utilizzando il `touch /etc/multipath.conf` comando.

La prima volta che si crea il `multipath.conf` file, potrebbe essere necessario attivare e avviare i servizi multipath utilizzando i seguenti comandi:

[listing]
----
# systemctl enable multipathd
# systemctl start multipathd
----
Non è necessario aggiungere dispositivi direttamente al `multipath.conf` file, a meno che non si disponga di dispositivi che non si desidera gestire multipath o di impostazioni esistenti che sovrascrivono le impostazioni predefinite. È possibile escludere le periferiche indesiderate aggiungendo la seguente sintassi al `multipath.conf` file, sostituendo <DevId> con la stringa WWID del dispositivo che si desidera escludere:

[listing]
----
blacklist {
        wwid <DevId>
        devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
        devnode "^hd[a-z]"
        devnode "^cciss.*"
}
----
Nell'esempio seguente, si determina il WWID di un dispositivo e si aggiunge il dispositivo al `multipath.conf` file.

.Fasi
. Determinare il WWID:
+
[listing]
----
/lib/udev/scsi_id -gud /dev/sda
----
+
[listing]
----
360030057024d0730239134810c0cb833
----
+
`sda` È il disco SCSI locale che si desidera aggiungere alla blacklist.

. Aggiungere il `WWID` alla lista nera `/etc/multipath.conf`:
+
[listing]
----
blacklist {
     wwid   360030057024d0730239134810c0cb833
     devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
     devnode "^hd[a-z]"
     devnode "^cciss.*"
}
----


Controllare sempre il file, soprattutto nella sezione dei valori predefiniti, per verificare `/etc/multipath.conf` le impostazioni legacy che potrebbero sovrascrivere le impostazioni predefinite.

Nella tabella seguente vengono illustrati i `multipathd` parametri critici per i LUN ONTAP e i valori richiesti. Se un host è connesso a LUN di altri fornitori e uno di questi parametri viene sovrascritto, sarà necessario correggerli in seguito nel `multipath.conf` file che si applica specificamente ai LUN di ONTAP. In caso contrario, i LUN ONTAP potrebbero non funzionare come previsto. È necessario ignorare queste impostazioni predefinite solo in consultazione con NetApp e/o un fornitore del sistema operativo e solo quando l'impatto è pienamente compreso.

[cols="2*"]
|===
| Parametro | Impostazione 


| detect_prio | sì 


| dev_loss_tmo | "infinito" 


| failback | immediato 


| fast_io_fail_tmo | 5 


| caratteristiche | "2 pg_init_retries 50" 


| flush_on_last_del | "sì" 


| gestore_hardware | "0" 


| no_path_retry | coda 


| path_checker | "a" 


| policy_di_raggruppamento_percorsi | "group_by_prio" 


| path_selector | "tempo di servizio 0" 


| intervallo_polling | 5 


| prio | "ONTAP" 


| prodotto | LUN.* 


| retain_attached_hw_handler | sì 


| peso_rr | "uniforme" 


| user_friendly_names | no 


| vendor | NETAPP 
|===
.Esempio
Nell'esempio seguente viene illustrato come correggere un valore predefinito sovrascritto. In questo caso, il `multipath.conf` il file definisce i valori per `path_checker` e. `no_path_retry` Non compatibili con LUN ONTAP. Se non possono essere rimossi perché altri array SAN sono ancora collegati all'host, questi parametri possono essere corretti specificamente per i LUN ONTAP con un dispositivo.

[listing]
----
defaults {
   path_checker      readsector0
   no_path_retry     fail
}

devices {
   device {
      vendor         "NETAPP  "
      product         "LUN.*"
      no_path_retry    queue
      path_checker     tur
   }
}
----


== Configurare le impostazioni KVM

Non è necessario configurare le impostazioni per una macchina virtuale basata su kernel perché il LUN è mappato all'hypervisor.



== Problemi noti

Non ci sono problemi noti per RHEL 8,10.
