---
sidebar: sidebar 
permalink: hu_rhel_82.html 
keywords: host utilities, red hat, rhel, linux, 8.2, netapp, ontap 
summary: Descrive come utilizzare Red Hat Enterprise Linux 8.2 con ONTAP 
---
= Utilizza Red Hat Enterprise Linux 8.2 con ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È possibile utilizzare le impostazioni di configurazione dell'host SAN di ONTAP per configurare Red Hat Enterprise Linux 8,2 con ONTAP come destinazione.



== Installare le utility host unificate Linux

Il pacchetto software NetApp Linux Unified host Utilities è disponibile su link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["Sito di supporto NetApp"^] in un file .rpm a 64 bit.

NetApp consiglia vivamente di installare le utility host unificate Linux, ma non è obbligatorio. Le utility non modificano le impostazioni dell'host Linux. Le utility migliorano la gestione e assistono il supporto clienti NetApp nella raccolta di informazioni sulla configurazione.

.Di cosa hai bisogno
Se si dispone di una versione di Linux Unified host Utilities attualmente installata, eseguire l'aggiornamento o la rimozione, quindi attenersi alla procedura descritta di seguito per installare la versione più recente.

.Fasi
. Scaricare il pacchetto software 64-bit Linux Unified host Utilities dal https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["Sito di supporto NetApp"^] al tuo host.
. Installare il pacchetto software:
+
`rpm -ivh netapp_linux_unified_host_utilities-7-1.x86_64`





== Toolkit SAN

Il toolkit viene installato automaticamente quando si installa il pacchetto NetApp host Utilities. Questo kit fornisce `sanlun` Utility che consente di gestire LUN e HBA. Il `sanlun` Il comando restituisce le informazioni relative alle LUN mappate all'host, al multipathing e alle informazioni necessarie per creare gruppi di iniziatori.

.Esempio
Nell'esempio seguente, il `sanlun lun show` Il comando restituisce le informazioni sul LUN.

[source, cli]
----
# sanlun lun show all
----
Output di esempio:

[listing]
----
controller(7mode/E-Series)/            device     host               lun
vserver(cDOT/FlashRay)   lun-pathname  filename   adapter  protocol  size    Product
-------------------------------------------------------------------------
data_vserver          /vol/vol1/lun1   /dev/sdb   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol1/lun1   /dev/sdc   host15   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sdd   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sde   host15   FCP       120.0g  cDOT
----


== Avvio SAN

.Di cosa hai bisogno
Se si decide di utilizzare l'avvio SAN, questo deve essere supportato dalla configurazione. È possibile utilizzare link:https://mysupport.netapp.com/matrix/imt.jsp?components=96167;&solution=236&isHWU&src=IMT["Tool di matrice di interoperabilità NetApp"^] Per verificare che il sistema operativo, l'HBA, il firmware dell'HBA, il BIOS di avvio dell'HBA e la versione di ONTAP siano supportati.

.Fasi
. Mappare il LUN di avvio SAN sull'host.
. Verificare che siano disponibili più percorsi.
+

NOTE: Una volta attivato il sistema operativo host e eseguito sui percorsi, diventano disponibili più percorsi.

. Abilitare l'avvio SAN nel BIOS del server per le porte a cui è mappato il LUN di avvio SAN.
+
Per informazioni su come attivare il BIOS HBA, consultare la documentazione specifica del vendor.

. Riavviare l'host per verificare che l'avvio sia stato eseguito correttamente.




== Multipathing

Per Red Hat Enterprise Linux (RHEL) 8,2 `/etc/multipath.conf` il file deve esistere, ma non è necessario apportare modifiche specifiche al file. RHEL 8,2 è compilato con tutte le impostazioni necessarie per riconoscere e gestire correttamente i LUN ONTAP.

È possibile utilizzare `multipath -ll` Per verificare le impostazioni dei LUN ONTAP. Le sezioni seguenti forniscono un output multipath di esempio per un LUN mappato a figure ASA e non ASA.



=== Tutte le configurazioni DEGLI array SAN

In tutte le configurazioni di array SAN (ASA), tutti i percorsi verso una determinata LUN sono attivi e ottimizzati. In questo modo, le performance vengono migliorate grazie alle operazioni di i/o in tutti i percorsi contemporaneamente.

.Esempio
Nell'esempio seguente viene visualizzato l'output corretto per un LUN ONTAP:

[listing]
----
# multipath -ll
3600a098038303634722b4d59646c4436 dm-28 NETAPP,LUN C-Mode
size=80G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 11:0:7:1    sdfi   130:64   active ready running
  |- 11:0:9:1    sdiy   8:288    active ready running
  |- 11:0:10:1   sdml   69:464   active ready running
  |- 11:0:11:1   sdpt   131:304  active ready running
----

NOTE: Non utilizzare un numero eccessivo di percorsi per una singola LUN. Non devono essere necessari più di quattro percorsi. Più di otto percorsi potrebbero causare problemi di percorso durante gli errori dello storage.



=== Configurazioni non ASA

Per le configurazioni non ASA, devono essere presenti due gruppi di percorsi con priorità diverse. I percorsi con priorità più elevate sono Active/Optimized, ovvero vengono serviti dal controller in cui si trova l'aggregato. I percorsi con priorità inferiori sono attivi ma non ottimizzati perché vengono serviti da un controller diverso. I percorsi non ottimizzati vengono utilizzati solo quando i percorsi ottimizzati non sono disponibili.

.Esempio
Nell'esempio seguente viene visualizzato l'output corretto per un LUN ONTAP con due percorsi attivi/ottimizzati e due percorsi attivi/non ottimizzati:

[listing]
----
# multipath -ll
3600a098038303634722b4d59646c4436 dm-28 NETAPP,LUN C-Mode
size=80G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| |- 16:0:6:35 sdwb 69:624 active ready running
| |- 16:0:5:35 sdun 66:752 active ready running
`-+- policy='service-time 0' prio=10 status=enabled
|- 15:0:0:35 sdaj 66:48 active ready running
|- 15:0:1:35 sdbx 68:176 active ready running

----

NOTE: Non utilizzare un numero eccessivo di percorsi per una singola LUN. Non devono essere necessari più di quattro percorsi. Più di otto percorsi potrebbero causare problemi di percorso durante gli errori dello storage.



== Impostazioni consigliate

Il sistema operativo RHEL 8.2 viene compilato per riconoscere le LUN ONTAP e impostare automaticamente tutti i parametri di configurazione correttamente.

Il `multipath.conf` file deve esistere per avviare il daemon multipath. Se questo file non esiste, è possibile creare un file vuoto a zero byte utilizzando il seguente comando:

`touch /etc/multipath.conf`

La prima volta che si crea il `multipath.conf` file, potrebbe essere necessario attivare e avviare i servizi multipath utilizzando i seguenti comandi:

[listing]
----
# chkconfig multipathd on
# /etc/init.d/multipathd start
----
Non è necessario aggiungere nulla direttamente al `multipath.conf` file, a meno che non si disponga di dispositivi che non si desidera gestire multipath o di impostazioni esistenti che sovrascrivono le impostazioni predefinite. Per escludere i dispositivi indesiderati, aggiungere al `multipath.conf` file la seguente sintassi, sostituendo <DevId> con la stringa WWID del dispositivo che si desidera escludere:

[listing]
----
blacklist {
        wwid <DevId>
        devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
        devnode "^hd[a-z]"
        devnode "^cciss.*"
}
----
.Esempio
In questo esempio, determineremo il WWID di un dispositivo e aggiungeremo al `multipath.conf` file.

.Fasi
. Eseguire il seguente comando per determinare l'ID WWID:
+
[listing]
----
# /lib/udev/scsi_id -gud /dev/sda
360030057024d0730239134810c0cb833
----
+
`sda` È il disco SCSI locale che dobbiamo aggiungere alla blacklist.

. Aggiungere il `WWID` alla lista nera `/etc/multipath.conf`:
+
[listing]
----
blacklist {
     wwid   360030057024d0730239134810c0cb833
     devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
     devnode "^hd[a-z]"
     devnode "^cciss.*"
}
----


Controllare sempre il `/etc/multipath.conf` file per le impostazioni legacy, in particolare nella sezione delle impostazioni predefinite, che potrebbero prevalere sulle impostazioni predefinite.

Nella tabella seguente vengono illustrati i `multipathd` parametri critici per i LUN ONTAP e i valori richiesti. Se un host è connesso a LUN di altri fornitori e uno di questi parametri viene sovrascritto, sarà necessario correggerli in seguito nel `multipath.conf` file che si applica specificamente ai LUN di ONTAP. In caso contrario, i LUN ONTAP potrebbero non funzionare come previsto. È necessario ignorare queste impostazioni predefinite solo in consultazione con NetApp, il fornitore del sistema operativo o entrambi, e solo quando l'impatto è pienamente compreso.

[cols="2*"]
|===
| Parametro | Impostazione 


| detect_prio | sì 


| dev_loss_tmo | "infinito" 


| failback | immediato 


| fast_io_fail_tmo | 5 


| caratteristiche | "2 pg_init_retries 50" 


| flush_on_last_del | "sì" 


| gestore_hardware | "0" 


| no_path_retry | coda 


| path_checker | "a" 


| policy_di_raggruppamento_percorsi | "group_by_prio" 


| path_selector | "tempo di servizio 0" 


| intervallo_polling | 5 


| prio | "ONTAP" 


| prodotto | LUN.* 


| retain_attached_hw_handler | sì 


| peso_rr | "uniforme" 


| user_friendly_names | no 


| vendor | NETAPP 
|===
.Esempio
Nell'esempio seguente viene illustrato come correggere un valore predefinito sovrascritto. In questo caso, il `multipath.conf` il file definisce i valori per `path_checker` e. `no_path_retry` Non compatibili con LUN ONTAP. Se non possono essere rimossi a causa di altri array SAN ancora collegati all'host, questi parametri possono essere corretti specificamente per i LUN ONTAP con un dispositivo.

[listing]
----
defaults {
   path_checker      readsector0
   no_path_retry      fail
}

devices {
   device {
      vendor         "NETAPP  "
      product         "LUN.*"
      no_path_retry     queue
      path_checker      tur
   }
}
----


=== Impostazioni KVM

È possibile utilizzare le impostazioni consigliate anche per configurare la macchina virtuale basata su kernel (KVM). Non sono necessarie modifiche per configurare KVM poiché il LUN viene mappato all'hypervisor.



== Problemi noti

Non ci sono problemi noti per RHEL 8,2 con la versione ONTAP.
