---
sidebar: sidebar 
permalink: hu_sanhost_index.html 
keywords: san, host, utility, software, netapp 
summary: 'Informazioni sulle ultime informazioni sulle versioni di SAN host Utility e accesso alla procedura di installazione per la configurazione dell"host.' 
---
= Informazioni sulle utilità host SAN
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Informazioni sulle ultime informazioni sulle versioni di SAN host Utility e accesso alla procedura di installazione per la configurazione dell'host.

Sul sito di assistenza NetApp sono disponibili diversi pacchetti software di utilità host SAN. NetApp consiglia di utilizzare il software utilità host SAN, se disponibile per l'host SAN.

Il software AIX, HP-UX, Linux e Solaris host Utilities fornisce un toolkit della riga di comando. Il toolkit consente di gestire i LUN ONTAP e gli HBA (host Bus Adapter). L'assistenza clienti NetApp può anche utilizzare le utilità host SAN per raccogliere informazioni sulla configurazione in caso di problemi che richiedono assistenza. Il toolkit viene installato automaticamente quando si installa il pacchetto software host Utilities.

Le utilità host di Windows consentono di collegare un computer host di Windows ai sistemi di archiviazione NetApp. Il software include un programma di installazione che consente di impostare i parametri necessari del registro di Windows e dell'HBA. In questo modo, l'host Windows gestisce correttamente il comportamento del sistema storage per le piattaforme ONTAP ed e-Series.


NOTE: Per un funzionamento affidabile dopo l'installazione, utilizzare il link:https://imt.netapp.com/matrix/#welcome["Tool di matrice di interoperabilità"^] per verificare che l'host supporti la configurazione completa di NVMe over Fabrics (tra cui NVMe over TCP e NVMe over Fibre Channel), iSCSI, FC o FCoE.
