---
sidebar: sidebar 
permalink: hu_solaris_62_cmd.html 
keywords: host utilities, unified, solaris, 6.2, netapp, ontap 
summary: Viene descritto come utilizzare le utilità host Solaris 6,2 con ONTAP 
---
= Riferimento comandi Solaris host Utilities 6,2
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È possibile utilizzare il riferimento comandi di esempio di Solaris host Utilities 6,2 per una convalida end-to-end della configurazione di archiviazione NetApp utilizzando lo strumento Utilità host.



== Elenca tutti gli iniziatori host mappati all'host

È possibile recuperare un elenco di tutti gli iniziatori host mappati a un host.

[source, cli]
----
# sanlun fcp show adapter -v
----
*Esempio di output*

[listing]
----
adapter name:      qlc3
WWPN:              21000024ff17a301
WWNN:              20000024ff17a301
driver name:       qlc
model:             7335902
model description: 7115462, Oracle Storage Dual-Port 32 Gb Fibre Channel PCIe HBA
serial number:     463916R+1720333838
hardware version:  Not Available
driver version:    210226-5.10
firmware version:  8.08.04
Number of ports:   1 of 2
port type:         Fabric
port state:        Operational
supported speed:   8 GBit/sec, 16 GBit/sec, 32 GBit/sec
negotiated speed:  32 GBit/sec
OS device name:    /dev/cfg/c7

adapter name:      qlc2
WWPN:              21000024ff17a300
WWNN:              20000024ff17a300
driver name:       qlc
model:             7335902
model description: 7115462, Oracle Storage Dual-Port 32 Gb Fibre Channel PCIe HBA
serial number:     463916R+1720333838
hardware version:  Not Available
driver version:    210226-5.10
firmware version:  8.08.04
Number of ports:   2 of 2
port type:         Fabric
port state:        Operational
supported speed:   8 GBit/sec, 16 GBit/sec, 32 GBit/sec
negotiated speed:  16 GBit/sec
OS device name:    /dev/cfg/c6
----


== Elenca tutti i LUN mappati all'host

È possibile recuperare un elenco di tutti i LUN mappati a un host.

[source, cli]
----
# sanlun lun show -p -v all
----
*Esempio di output*

[listing]
----

                    ONTAP Path: data_vserver:/vol1/lun1
                           LUN: 1
                      LUN Size: 10g
                   Host Device: /dev/rdsk/c0t600A0980383044485A3F4E694E4F775Ad0s2
                          Mode: C
            Multipath Provider: Sun Microsystems
              Multipath Policy: Native

----


== Elenca tutti i LUN mappati all'host da una SVM specifica/ Elenca tutti gli attributi di una LUN specifica mappata all'host

È possibile recuperare un elenco di tutte le LUN mappate a un host da una determinata SVM.

[source, cli]
----
# sanlun lun show -p -v sanboot_unix`
----
*Esempio di output*

[listing]
----
ONTAP Path: sanboot_unix:/vol/sol_boot/sanboot_lun
                           LUN: 0
                      LUN Size: 180.0g

----


== Elencare gli attributi del LUN ONTAP in base al nome del file del dispositivo host

È possibile recuperare un elenco di tutti gli attributi del LUN ONTAP specificando un nome file del dispositivo host.

[source, cli]
----
# sanlun lun show all
----
*Esempio di output*

[listing]
----
controller(7mode/E-Series)/                                         device
vserver(cDOT/FlashRay)       lun-pathname                           filename
---------------------------------------------------------------------------------------------------------------
sanboot_unix                 /vol/sol_193_boot/chatsol_193_sanboot /dev/rdsk/c0t600A098038304437522B4E694E4A3043d0s2

host adapter    protocol lun size   product
---------------------------------------------
qlc3            FCP      180.0g     cDOT
----