---
sidebar: sidebar 
permalink: hu_solaris_62_rn.html 
keywords: host utilities, solaris, 6.2 netapp, ontap 
summary: Note sulla versione per Solaris host Utilities 6.2 
---
= Note sulla versione di Solaris host Utilities 6.2
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Le note di rilascio descrivono nuove funzioni e miglioramenti, problemi risolti nella versione corrente, problemi e limitazioni noti e importanti precauzioni relative alla configurazione e alla gestione dell'host Solaris specifico con il sistema di storage ONTAP.

Per informazioni specifiche sulle versioni e sugli aggiornamenti del sistema operativo supportati dalle utility host, consultare link:https://mysupport.netapp.com/matrix/imt.jsp?components=85803;&solution=1&isHWU&src=IMT["Tool di matrice di interoperabilità NetApp"^].



== Problemi e limitazioni noti

È necessario conoscere i seguenti problemi e limitazioni noti che potrebbero influire sulle prestazioni dell'host specifico.

[cols="3"]
|===
| ID bug | Titolo | Descrizione 


| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/BURT/1385189["1385189"^] | Modifiche al binding del driver FC per Solaris 11.4 richieste in HUK 6.2 | Raccomandazioni per Solaris 11,4 e HUK:
Il binding del driver FC viene modificato da `ssd(4D)` a. `sd(4D)`. Spostare la configurazione in `ssd.conf` a. `sd.conf` Come indicato in Oracle (ID documento 2595926.1). Il comportamento varia a seconda dei sistemi Solaris 11,4 appena installati e dei sistemi aggiornati da 11,3 o versioni precedenti. 
|===
link:https://mysupport.netapp.com/site/["NetApp Bugs Online"^] fornisce informazioni complete sui problemi più noti, incluse le soluzioni consigliate, se possibile. Alcune combinazioni di parole chiave e tipi di bug che è possibile utilizzare includono quanto segue:

* FCP Generale: Visualizza i bug FC e HBA (host Bus Adapter) non associati a un host specifico.
* FCP - Solaris

