---
sidebar: sidebar 
permalink: hu_solaris_62.html 
keywords: host utilities, unified, oracle, linux, 7.1, netapp, ontap 
summary: Viene descritto come utilizzare le utilità host Solaris 6,2 con ONTAP 
---
= Installare le utilità host Solaris 6,2 per l'archiviazione ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Le utilità host Solaris consentono di gestire lo storage ONTAP collegato a un host Solaris.

Solaris host Utilities 6.2 supporta diversi ambienti Solaris e diversi protocolli. Gli ambienti principali delle utility host sono:

* Sistema operativo nativo con MPxIO con protocollo Fibre Channel (FC) o iSCSI su un sistema che utilizza un processore SPARC o x86/64.
* Veritas Dynamic Multipathing (DMP) con il protocollo FC o iSCSI su un sistema che utilizza un processore SPARC o il protocollo iSCSI su un sistema che utilizza un processore x86/64.


Solaris host Utilities 6,2 continua a supportare le seguenti versioni di Solaris:

* Solaris serie 11.x.
* Solaris serie 10.x.


.Prima di iniziare
* Per un funzionamento affidabile, verificare che sia supportata l'intera configurazione iSCSI, FC o FCoE.


È possibile utilizzare link:https://imt.netapp.com/matrix/#welcome["Tool di matrice di interoperabilità"^]per verificare la configurazione.


NOTE: Il pacchetto software NetApp Solaris host Utilities è disponibile sul sito link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/6.2/downloads["Sito di supporto NetApp"^] in un formato di file compresso per il processore. È possibile scaricare il pacchetto software Utility host per il proprio ambiente dal sito di supporto.

.Fasi
. Accedere all'host come root.
. Scaricare una copia del file compresso contenente le utility host da link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/6.2/downloads["Sito di supporto NetApp"^] a una directory sull'host.
+
Al momento della preparazione di questa documentazione, i file compressi venivano chiamati:

+
** CPU SPARC: `netapp_solaris_host_utilities_6_2_sparc.tar.gz`
** CPU x86/x64: `netapp_solaris_host_utilities_6_2_amd.tar.gz`


. Accedere alla directory contenente il download.
. Decomprimere il file utilizzando `gunzip` comando:
+
`# gunzip netapp_solaris_host_utilities_6_2_sparc.tar.gz`

. Decomprimere il file utilizzando il `tar xvf` comando:
+
`# tar xvf netapp_solaris_host_utilities_6_2_sparc.tar`

. Aggiungere i pacchetti estratti dal file tar al proprio host utilizzando il `pkgadd` comando .
+
I pacchetti vengono aggiunti a. `/opt/NTAP/SANToolkit/bin` directory.

+
Nell'esempio seguente viene utilizzato il `pkgadd` comando per installare il pacchetto di installazione di Solaris:

+
`# pkgadd -d ./NTAPSANTool.pkg`

. Verificare che il toolkit sia stato installato correttamente utilizzando `pkginfo` o il `ls - al` comando.
+
[listing]
----
# ls -alR /opt/NTAP/SANToolkit
/opt/NTAP/SANToolkit:
total 1038
drwxr-xr-x   3 root     sys            4 Jul 22  2019 .
drwxr-xr-x   3 root     sys            3 Jul 22  2019 ..
drwxr-xr-x   2 root     sys            6 Jul 22  2019 bin
-r-xr-xr-x   1 root     sys       432666 Sep 13  2017 NOTICES.PDF

/opt/NTAP/SANToolkit/bin:
total 7962
drwxr-xr-x   2 root     sys            6 Jul 22  2019 .
drwxr-xr-x   3 root     sys            4 Jul 22  2019 ..
-r-xr-xr-x   1 root     sys      2308252 Sep 13  2017 host_config
-r-xr-xr-x   1 root     sys          995 Sep 13  2017 san_version
-r-xr-xr-x   1 root     sys      1669204 Sep 13  2017 sanlun
-r-xr-xr-x   1 root     sys          677 Sep 13  2017 vidpid.dat

# (cd /usr/share/man/man1; ls -al host_config.1 sanlun.1)
-r-xr-xr-x   1 root     sys        12266 Sep 13  2017 host_config.1
-r-xr-xr-x   1 root     sys         9044 Sep 13  2017 sanlun.1
----
. Al termine, configurare i parametri host per l'ambiente utilizzando `/opt/NTAP/SANToolkit/bin/host_config` comando:
+
** MPIXIO
** Veritas DMP


. Verificare l'installazione:
+
`sanlun version`





== Abilitare il toolkit SAN

Solaris host Utilities è un software host NetApp che fornisce un toolkit della riga di comando sull'host Oracle Solaris. Il toolkit viene installato quando si installa il pacchetto NetApp host Utilities. Questo kit fornisce `sanlun` Utility che consente di gestire LUN e HBA (host Bus Adapter). Il `sanlun` Il comando restituisce le informazioni relative alle LUN mappate all'host, al multipathing e alle informazioni necessarie per creare gruppi di iniziatori.

.Esempio
Nell'esempio seguente, il `sanlun lun show` Il comando restituisce le informazioni del LUN.

[listing]
----
#sanlun lun show all
controller(7mode)/ device host lun
vserver(Cmode)                     lun-pathname       filename                                       adapter protocol size mode
-----------------------------------------------------------------------------------------------------------------------------------
data_vserver                     /vol/vol1/lun1     /dev/rdsk/c0t600A098038304437522B4E694E49792Dd0s2 qlc3   FCP       10g cDOT
data_vserver                     /vol/vol0/lun2     /dev/rdsk/c0t600A098038304437522B4E694E497938d0s2 qlc3   FCP       10g cDOT
data_vserver                     /vol/vol2/lun3     /dev/rdsk/c0t600A098038304437522B4E694E497939d0s2 qlc3   FCP       10g cDOT
data_vserver                     /vol/vol3/lun4     /dev/rdsk/c0t600A098038304437522B4E694E497941d0s2 qlc3   FCP       10g cDOT


----

NOTE: Questo toolkit è comune a tutte le configurazioni e i protocolli delle utilità host. Di conseguenza, tutti i componenti non si applicano a ogni configurazione. I componenti inutilizzati non influiscono sulle prestazioni del sistema. Il SAN Toolkit è supportato sulle versioni AIX e PowerVM/VIOS.
