---
sidebar: sidebar 
permalink: hu_solaris_62.html 
keywords: host utilities, unified, oracle, linux, 7.1, netapp, ontap 
summary: Viene descritto come utilizzare le utilità host Solaris 6,2 con ONTAP 
---
= Installare le utilità host Solaris 6,2 per l'archiviazione ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Le Solaris Host Utilities aiutano a gestire lo storage ONTAP collegato a un host Solaris e supportano il supporto tecnico nella raccolta dei dati di configurazione.

Solaris Host Utilities supporta diversi ambienti Solaris e più protocolli di trasporto.  Questi sono gli ambienti principali di Solaris Host Utilities:

* Il sistema operativo nativo con MPxIO e protocollo Fibre Channel (FC) o iSCSI su un sistema che utilizza un processore SPARC o un processore x86/64.
* Veritas Dynamic Multipathing (DMP) con il protocollo FC o iSCSI su un sistema che utilizza un processore SPARC o il protocollo iSCSI su un sistema che utilizza un processore x86/64.


Solaris Host Utilities 6.2 supporta le seguenti serie Solaris:

* Solaris 11.x
* Solaris 10.x


.Prima di iniziare
Verificare che la configurazione iSCSI, FC o FCoE sia supportata.  Puoi usare illink:https://imt.netapp.com/matrix/#welcome["Tool di matrice di interoperabilità"^] per verificare la tua configurazione.

.Fasi
. Accedi al tuo host come root.
. Scaricare una copia del file compresso contenente le Utilità Host dallink:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/6.2/downloads["Sito di supporto NetApp"^] in una directory sul tuo host Solaris:
+
[role="tabbed-block"]
====
.CPU SPARC
--
[source, cli]
----
netapp_solaris_host_utilities_6_2_sparc.tar.gz
----
--
.Processore x86/x64
--
[source, cli]
----
netapp_solaris_host_utilities_6_2_amd.tar.gz
----
--
====
. Vai alla directory sul tuo host Solaris che contiene il download.
. Decomprimere il file utilizzando `gunzip` comando:
+
[source, cli]
----
gunzip netapp_solaris_host_utilities_6_2_sparc.tar.gz
----
. Estrarre il file utilizzando il `tar xvf` comando:
+
[source, cli]
----
tar xvf netapp_solaris_host_utilities_6_2_sparc.tar
----
. Aggiungi i pacchetti estratti dal file tar al tuo host
+
[source, cli]
----
pkgadd
----
+
I pacchetti vengono aggiunti a. `/opt/NTAP/SANToolkit/bin` directory.

+
Nell'esempio seguente viene utilizzato il `pkgadd` comando per installare il pacchetto di installazione di Solaris:

+
[source, cli]
----
pkgadd -d ./NTAPSANTool.pkg
----
. Per confermare che il toolkit è stato installato correttamente, utilizzare uno dei seguenti comandi:
+
[source, cli]
----
pkginfo
----
+
[source, cli]
----
ls - al
----
+
.Mostra esempi di output
[%collapsible]
====
[listing]
----
# ls -alR /opt/NTAP/SANToolkit
/opt/NTAP/SANToolkit:
total 1038
drwxr-xr-x   3 root     sys            4 Jul 22  2019 .
drwxr-xr-x   3 root     sys            3 Jul 22  2019 ..
drwxr-xr-x   2 root     sys            6 Jul 22  2019 bin
-r-xr-xr-x   1 root     sys       432666 Sep 13  2017 NOTICES.PDF

/opt/NTAP/SANToolkit/bin:
total 7962
drwxr-xr-x   2 root     sys            6 Jul 22  2019 .
drwxr-xr-x   3 root     sys            4 Jul 22  2019 ..
-r-xr-xr-x   1 root     sys      2308252 Sep 13  2017 host_config
-r-xr-xr-x   1 root     sys          995 Sep 13  2017 san_version
-r-xr-xr-x   1 root     sys      1669204 Sep 13  2017 sanlun
-r-xr-xr-x   1 root     sys          677 Sep 13  2017 vidpid.dat

# (cd /usr/share/man/man1; ls -al host_config.1 sanlun.1)
-r-xr-xr-x   1 root     sys        12266 Sep 13  2017 host_config.1
-r-xr-xr-x   1 root     sys         9044 Sep 13  2017 sanlun.1
----
====
. Configurare i parametri host per l'ambiente MPxIO o Veritas DMP:
+
[source, cli]
----
/opt/NTAP/SANToolkit/bin/host_config
----
. Verificare l'installazione:
+
[source, cli]
----
sanlun version
----




== Quali sono le prossime novità?

link:hu-solaris-san-toolkit.html["Scopri di più sul SAN Toolkit"] .
