---
sidebar: sidebar 
permalink: hu_sles_12SP3.html 
keywords: host utilities, suse linux enterprise server 12 SP3, suse, linux, 12 SP3, netapp, ontap 
summary: Descrive come utilizzare SUSE Linux Enterprise Server 12 SP3 con ONTAP 
---
= Utilizza SUSE Linux Enterprise Server 12 SP3 con ONTAP
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
È possibile utilizzare le impostazioni di configurazione dell'host SAN di ONTAP per configurare SUSE Linux Enterprise Server 12 SP3 con ONTAP come destinazione.



== Installare le utility host unificate Linux

Il pacchetto software NetApp Linux Unified host Utilities è disponibile su link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["Sito di supporto NetApp"^] in un file .rpm a 32 bit e a 64 bit. Se non si conosce il file appropriato per la configurazione, utilizzare link:https://mysupport.netapp.com/matrix/#welcome["Tool di matrice di interoperabilità NetApp"^] per verificare quale si desidera.

NetApp consiglia vivamente di installare le utility host unificate Linux, ma non è obbligatorio. Le utility non modificano le impostazioni dell'host Linux. Le utility migliorano la gestione e assistono il supporto clienti NetApp nella raccolta di informazioni sulla configurazione.

.Di cosa hai bisogno
Se si dispone di una versione di Linux Unified host Utilities attualmente installata, è necessario aggiornarla oppure rimuoverla e procedere come segue per installare la versione più recente.

. Scaricare il pacchetto software di utilità host unificate Linux a 32 bit o 64 bit dal link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["Sito di supporto NetApp"^] Al tuo host.
. Utilizzare il seguente comando per installare il pacchetto software:
+
`rpm -ivh netapp_linux_unified_host_utilities-7-1.x86_64`




NOTE: È possibile utilizzare le impostazioni di configurazione fornite in questo documento per configurare i client cloud connessi a. link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/index.html["Cloud Volumes ONTAP"^] e. link:https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/index.html["Amazon FSX per ONTAP"^].



== Toolkit SAN

Il toolkit viene installato automaticamente quando si installa il pacchetto NetApp host Utilities. Questo kit fornisce `sanlun` Utility che consente di gestire LUN e HBA. Il `sanlun` Il comando restituisce le informazioni relative alle LUN mappate all'host, al multipathing e alle informazioni necessarie per creare gruppi di iniziatori.

.Esempio
Nell'esempio seguente, il `sanlun lun show` Il comando restituisce le informazioni sul LUN.

[source, cli]
----
# sanlun lun show all
----
Output di esempio:

[listing]
----
controller(7mode/E-Series)/            device     host               lun
vserver(cDOT/FlashRay)   lun-pathname  filename   adapter  protocol  size    Product
-------------------------------------------------------------------------
data_vserver          /vol/vol1/lun1   /dev/sdb   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol1/lun1   /dev/sdc   host15   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sdd   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sde   host15   FCP       120.0g  cDOT
----


== Avvio SAN

.Di cosa hai bisogno
Se si decide di utilizzare l'avvio SAN, questo deve essere supportato dalla configurazione. È possibile utilizzare link:https://mysupport.netapp.com/matrix/imt.jsp?components=80043;&solution=1&isHWU&src=IMT["Tool di matrice di interoperabilità NetApp"^] Per verificare che il sistema operativo, l'HBA, il firmware dell'HBA, il BIOS di avvio dell'HBA e la versione di ONTAP siano supportati.

.Fasi
. Mappare il LUN di avvio SAN sull'host.
. Verificare che siano disponibili più percorsi.
+

NOTE: Una volta attivato il sistema operativo host e eseguito sui percorsi, diventano disponibili più percorsi.

. Abilitare l'avvio SAN nel BIOS del server per le porte a cui è mappato il LUN di avvio SAN.
+
Per informazioni su come attivare il BIOS HBA, consultare la documentazione specifica del vendor.

. Riavviare l'host per verificare che l'avvio sia stato eseguito correttamente.




== Multipathing

Per SUSE Linux Enterprise Server 12 SP3 il file /etc/multipath.conf deve esistere, ma non è necessario apportare modifiche specifiche al file. SUSE Linux Enterprise Server 12 SP3 viene compilato con tutte le impostazioni necessarie per riconoscere e gestire correttamente le LUN ONTAP.

È possibile utilizzare `multipath -ll` Per verificare le impostazioni dei LUN ONTAP. Le sezioni seguenti forniscono un output multipath di esempio per un LUN mappato a figure ASA e non ASA.



=== Tutte le configurazioni DEGLI array SAN

In tutte le configurazioni di array SAN (ASA), tutti i percorsi verso una determinata LUN sono attivi e ottimizzati. In questo modo, le performance vengono migliorate grazie alle operazioni di i/o in tutti i percorsi contemporaneamente.

.Esempio
Nell'esempio seguente viene visualizzato l'output corretto per un LUN ONTAP:

[listing]
----
# multipath -ll
3600a0980383034466b2b4a3775474859 dm-3 NETAPP,LUN C-Mode
size=20G features='4 queue_if_no_path pg_init_retries 50 retain_attached_hw_handle' hwhandler='1 alua' wp=rw
|-+- policy='round-robin 0' prio=50 status=active
| |- 1:0:8:1  sdb 8:16 active ready running
| `- 2:0:8:1  sdd 8:48 active ready running
`-+- policy='round-robin 0' prio=10 status=enabled
  |- 1:0:9:1  sdc 8:32 active ready running
  `- 2:0:9:1  sde 8:64 active ready running
----

NOTE: Non utilizzare un numero eccessivo di percorsi per una singola LUN. Non devono essere necessari più di quattro percorsi. Più di otto percorsi potrebbero causare problemi di percorso durante gli errori dello storage.



=== Configurazioni non ASA

Per le configurazioni non ASA, devono essere presenti due gruppi di percorsi con priorità diverse. I percorsi con priorità più elevate sono Active/Optimized, ovvero vengono serviti dal controller in cui si trova l'aggregato. I percorsi con priorità inferiori sono attivi ma non ottimizzati perché vengono serviti da un controller diverso. I percorsi non ottimizzati vengono utilizzati solo quando non sono disponibili percorsi ottimizzati.

.Esempio
Nell'esempio seguente viene visualizzato l'output corretto per un LUN ONTAP con due percorsi attivi/ottimizzati e due percorsi attivi/non ottimizzati:

[listing]
----
# multipath -ll
3600a09803831347657244e527766394e dm-5 NETAPP,LUN C-Mode
size=80G features='4 queue_if_no_path pg_init_retries 50 retain_attached_hw_handler' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| |- 11:0:1:0 sdj 8:144 active ready running
| |- 11:0:2:0 sdr 65:16 active ready running
`-+- policy='service-time 0' prio=10 status=enabled
|- 11:0:0:0 sdb 8:i6 active ready running
|- 12:0:0:0 sdz 65:144 active ready running
----

NOTE: Non utilizzare un numero eccessivo di percorsi per una singola LUN. Non devono essere necessari più di quattro percorsi. Più di otto percorsi potrebbero causare problemi di percorso durante gli errori dello storage.



== Impostazioni consigliate

Il sistema operativo SUSE Linux Enterprise Server 12 SP3 viene compilato per riconoscere le LUN ONTAP e impostare automaticamente tutti i parametri di configurazione correttamente.
Il `multipath.conf` il file deve esistere per l'avvio del daemon multipath, ma è possibile creare un file vuoto a zero byte utilizzando il seguente comando:

`touch /etc/multipath.conf`

La prima volta che si crea questo file, potrebbe essere necessario attivare e avviare i servizi multipath:

[listing]
----
# systemctl enable multipathd
# systemctl start multipathd
----
* Non è necessario aggiungere nulla direttamente a `multipath.conf` file, a meno che non si disponga di periferiche che non si desidera gestire con multipath o che non si dispongano di impostazioni che sovrascrivono le impostazioni predefinite.
* Per escludere le periferiche indesiderate, aggiungere la seguente sintassi a `multipath.conf` file .
+
[listing]
----
blacklist {
        wwid <DevId>
        devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
        devnode "^hd[a-z]"
        devnode "^cciss.*"
}
----
+
Sostituire `<DevId>` con `WWID` stringa del dispositivo che si desidera escludere.

+
.Esempio
In questo esempio, determineremo il WWID di un dispositivo e aggiungeremo al `multipath.conf` file.

+
.Fasi
.. Eseguire il seguente comando per determinare l'ID WWID:
+
[listing]
----
# /lib/udev/scsi_id -gud /dev/sda
360030057024d0730239134810c0cb833
----
+
`sda` È il disco SCSI locale che dobbiamo aggiungere alla blacklist.

.. Aggiungere il `WWID` alla lista nera `/etc/multipath.conf`:
+
[listing]
----
blacklist {
     wwid   360030057024d0730239134810c0cb833
     devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
     devnode "^hd[a-z]"
     devnode "^cciss.*"
}
----




Controllare sempre il `/etc/multipath.conf` file per le impostazioni legacy, in particolare nella sezione delle impostazioni predefinite, che potrebbero prevalere sulle impostazioni predefinite.

La tabella seguente mostra la criticità `multipathd` Parametri per i LUN ONTAP e i valori richiesti. Se un host è connesso a LUN di altri vendor e uno qualsiasi di questi parametri viene ignorato, sarà necessario correggerli nelle successive stanze di `multipath.conf` File che si applicano specificamente alle LUN ONTAP. In caso contrario, i LUN ONTAP potrebbero non funzionare come previsto. Questi valori predefiniti devono essere ignorati solo previa consultazione di NetApp e/o di un vendor del sistema operativo e solo quando l'impatto è pienamente compreso.

[cols="2*"]
|===
| Parametro | Impostazione 


| detect_prio | sì 


| dev_loss_tmo | "infinito" 


| failback | immediato 


| fast_io_fail_tmo | 5 


| caratteristiche | "2 pg_init_retries 50" 


| flush_on_last_del | "sì" 


| gestore_hardware | "0" 


| no_path_retry | coda 


| path_checker | "a" 


| policy_di_raggruppamento_percorsi | "group_by_prio" 


| path_selector | "tempo di servizio 0" 


| intervallo_polling | 5 


| prio | "ONTAP" 


| prodotto | LUN.* 


| retain_attached_hw_handler | sì 


| peso_rr | "uniforme" 


| user_friendly_names | no 


| vendor | NETAPP 
|===
.Esempio
Nell'esempio seguente viene illustrato come correggere un valore predefinito sovrascritto. In questo caso, il `multipath.conf` il file definisce i valori per `path_checker` e. `no_path_retry` Non compatibili con LUN ONTAP. Se non possono essere rimossi a causa di altri array SAN ancora collegati all'host, questi parametri possono essere corretti specificamente per i LUN ONTAP con un dispositivo.

[listing]
----
defaults {
 path_checker readsector0
 no_path_retry fail
}
devices {
 device {
 vendor "NETAPP "
 product "LUN.*"
 no_path_retry queue
 path_checker tur
 }
}
----


== Problemi noti

La versione SLES 15 SP3 con ONTAP presenta i seguenti problemi noti:

[cols="4*"]
|===
| ID bug NetApp | Titolo | Descrizione | ID Bugzilla 


| link:https://https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1089555["1089555"^] | Interruzione del kernel osservata nella versione del kernel SLES12 SP3 con Emulex LPe16002 16 GB FC durante l'operazione di failover dello storage | Durante le operazioni di failover dello storage sulla versione del kernel SLES12 SP3 con Emulex LPe16002 HBA, potrebbe verificarsi un'interruzione del kernel. L'interruzione del kernel richiede un riavvio del sistema operativo, che a sua volta causa un'interruzione dell'applicazione. Se kdump è configurato, l'interruzione del kernel genera un file vmcore sotto /var/crash/directory. È possibile esaminare la causa del guasto nel file vmcore. Esempio: Nel caso osservato, l'interruzione del kernel è stata osservata nel modulo "lpfc_sli_ringtxcmpl_put+51" ed è registrata nel file vmcore – Exception RIP: Lpfc_sli_ringtxcmpl_put+51. Ripristinare il sistema operativo dopo l'interruzione del kernel riavviando il sistema operativo host e riavviando l'applicazione. | link:http://bugzilla.suse.com/show_bug.cgi?id=1042847["1042847"^] 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1089561["1089561"^] | Interruzione del kernel osservata nella versione del kernel SLES12 SP3 con Emulex LPe32002 32 GB FC durante le operazioni di failover dello storage | Durante le operazioni di failover dello storage sulla versione del kernel SLES12 SP3 con Emulex LPe32002 HBA, potrebbe verificarsi un'interruzione del kernel. L'interruzione del kernel richiede un riavvio del sistema operativo, che a sua volta causa un'interruzione dell'applicazione. Se kdump è configurato, l'interruzione del kernel genera un file vmcore sotto /var/crash/directory. È possibile esaminare la causa del guasto nel file vmcore. Esempio: Nel caso osservato, l'interruzione del kernel è stata osservata nel modulo "lpfc_sli_free_hbq+76" e viene registrato nel file vmcore – Exception RIP: Lpfc_sli_free_hbq+76. Ripristinare il sistema operativo dopo l'interruzione del kernel riavviando il sistema operativo host e riavviando l'applicazione. | link:http://bugzilla.suse.com/show_bug.cgi?id=1042807["1042807"^] 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1117248["1117248"^] | Interruzione del kernel osservata su SLES12SP3 con QLogic QLE2562 8 GB FC durante le operazioni di failover dello storage | Durante le operazioni di failover dello storage sul kernel Sles12sp3 (kernel-default-4.4.82-6.3.1) con QLogic QLE2562 HBA, è stata osservata la rottura del kernel a causa di un panico nel kernel. Il kernel panic causa il riavvio del sistema operativo, causando un'interruzione dell'applicazione. Il kernel panic genera il file vmcore nella directory /var/crash/ se kdump è configurato. In caso di kernel panic, il file vmcore può essere utilizzato per comprendere la causa del guasto. Esempio: In questo caso, il panico è stato osservato nel modulo "blk_Finish_Request+289". Viene registrato nel file vmcore con la seguente stringa: "Exception RIP: blk_Finish_Request+289" dopo l'interruzione del kernel, è possibile ripristinare il sistema operativo riavviando il sistema operativo host. È possibile riavviare l'applicazione secondo necessità. | link:http://bugzilla.suse.com/show_bug.cgi?id=1062496["1062496"^] 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1117261["1117261"^] | Interruzione del kernel osservata su SLES12SP3 con Qlogic QLE2662 16 GB FC durante le operazioni di failover dello storage | Durante le operazioni di failover dello storage sul kernel Sles12sp3 (kernel-default-4.4.82-6.3.1) con Qlogic QLE2662 HBA, si potrebbe osservare un'interruzione del kernel. Ciò richiede un riavvio del sistema operativo che causa l'interruzione dell'applicazione. L'interruzione del kernel genera un file vmcore nella directory /var/crash/ se kdump è configurato. Il file vmcore può essere utilizzato per comprendere la causa dell'errore. Esempio: In questo caso l'interruzione del kernel è stata osservata nel modulo "Unknown or invalid address" (Indirizzo sconosciuto o non valido) e viene registrato nel file vmcore con la seguente stringa - Exception RIP: Unknown or invalid address (RIP eccezione: Indirizzo sconosciuto o non valido). Dopo l'interruzione del kernel, il sistema operativo può essere ripristinato riavviando il sistema operativo host e riavviando l'applicazione secondo necessità. | link:http://bugzilla.suse.com/show_bug.cgi?id=1062508["1062508"^] 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1117274["1117274"^] | Interruzione del kernel osservata su SLES12SP3 con Emulex LPe16002 16 GB FC durante le operazioni di failover dello storage | Durante le operazioni di failover dello storage sul kernel Sles12sp3 (kernel-default-4.4.87-3.1) con Emulex LPe16002 HBA, si potrebbe osservare un'interruzione del kernel. Ciò richiede un riavvio del sistema operativo che causa l'interruzione dell'applicazione. L'interruzione del kernel genera un file vmcore nella directory /var/crash/ se kdump è configurato. Il file vmcore può essere utilizzato per comprendere la causa dell'errore. Esempio: In questo caso è stata osservata un'interruzione del kernel nel modulo "raw_spin_lock_irqSave+30" e viene registrato nel file vmcore con la seguente stringa: – Exception RIP: _Raw_spin_lock_irqSave+30. Dopo l'interruzione del kernel, il sistema operativo può essere ripristinato riavviando il sistema operativo host e riavviando l'applicazione secondo necessità. | link:http://bugzilla.suse.com/show_bug.cgi?id=1062514["1062514"^] 
|===