---
sidebar: sidebar 
permalink: hu_vsphere_8.html 
keywords: host utilities, veritas, infoscale, 8.x, netapp, ontap, vmware, vspehere 
summary: È possibile configurare le impostazioni degli host SAN ONTAP per VMware vSphere 8.x con i protocolli FC, FCoE e iSCSI. 
---
= Utilizzo di VMware vSphere 8.x con NetApp ONTAP
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
È possibile configurare le impostazioni degli host SAN ONTAP per VMware vSphere 8.x con i protocolli FC, FCoE e iSCSI.



== Avvio DI hypervisor SAN

.Di cosa hai bisogno
Se si decide di utilizzare l'avvio SAN, questo deve essere supportato dalla configurazione. È possibile utilizzare https://mysupport.netapp.com/matrix/imt.jsp?components=65623;64703;&solution=1&isHWU&src=IMT["Tool di matrice di interoperabilità NetApp"^] Per verificare che il sistema operativo, l'HBA, il firmware dell'HBA, il BIOS di avvio dell'HBA e la versione di ONTAP siano supportati.

.Fasi
. Mappare il LUN di avvio SAN sull'host.
. Verificare che siano disponibili più percorsi.
+

NOTE: Una volta attivato il sistema operativo host e eseguito sui percorsi, diventano disponibili più percorsi.

. Abilitare l'avvio SAN nel BIOS del server per le porte a cui è mappato il LUN di avvio SAN.
+
Per informazioni su come attivare il BIOS HBA, consultare la documentazione specifica del vendor.

. Riavviare l'host per verificare che l'avvio sia stato eseguito correttamente.




== Multipathing

ESXi fornisce un modulo multipathing estensibile chiamato NMP (Native Multipathing Plug-in) che gestisce i plug-in secondari, i SATP (Storage Array Type Plugin) e i PSP (Path Selection Plugin). Per impostazione predefinita, queste regole SATP sono disponibili in ESXi.

Per lo storage NetApp ONTAP, `VMW_SATP_ALUA` il plug-in viene utilizzato per impostazione predefinita con `VMW_PSP_RR` Come policy di selezione del percorso (PSP). Per confermare, utilizzare il seguente comando:

[listing]
----
`esxcli storage nmp satp rule list -s VMW_SATP_ALUA`
----
Output di esempio:

[listing]
----
Name           Device  Vendor    Model         Driver  Transport  Options
---------------------------------------------------------------------------------
VMW_SATP_ALUA          LSI       INF-01-00                        reset_on_attempted_reserve  system
VMW_SATP_ALUA          NETAPP                                     reset_on_attempted_reserve  system

Rule Group  Claim Options  Default PSP  PSP Options     Description
------------------------------------------------------------------
tpgs_on        VMW_PSP_MRU                  NetApp E-Series arrays with ALUA support
tpgs_on        VMW_PSP_RR                   NetApp arrays with ALUA support
----


=== Configurazione non ASA

Per le configurazioni non ASA, devono essere presenti due gruppi di percorsi con priorità diverse. I percorsi con priorità più elevate sono Active/Optimized, ovvero vengono serviti dal controller in cui si trova l'aggregato. I percorsi con priorità inferiori sono attivi ma non ottimizzati perché vengono serviti da un controller diverso. I percorsi non ottimizzati vengono utilizzati solo quando non sono disponibili percorsi ottimizzati.

.Esempio
Nell'esempio seguente viene visualizzato l'output corretto per un LUN ONTAP con due percorsi attivi/ottimizzati e due percorsi attivi/non ottimizzati:

[listing]
----
# esxcli storage nmp device list -d naa.600a0980383148693724545244395855
----
Output di esempio:

[listing]
----
naa.600a0980383148693724545244395855
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a0980383148693724545244395855)
   Storage Array Type: VMW_SATP_ALUA
   Storage Array Type Device Config: {implicit_support=on; explicit_support=off; explicit_allow=on; alua_followover=on; action_OnRetryErrors=off; {TPG_id=1000,TPG_state=ANO}{TPG_id=1001,TPG_state=AO}}
   Path Selection Policy: VMW_PSP_RR
   Path Selection Policy Device Config: {policy=rr,iops=1000,bytes=10485760,useANO=0; lastPathIndex=1: NumIOsPending=0,numBytesPending=0}
   Path Selection Policy Device Custom Config:
   Working Paths: vmhba4:C0:T0:L11, vmhba3:C0:T0:L11
   Is USB: false
----
[listing]
----
# esxcli storage nmp path list -d naa.600a0980383148693724545244395855
----
Output di esempio:

[listing, subs="+quotes"]
----
fc.20000024ff7f4a51:21000024ff7f4a51-fc.2009d039ea3ab21f:2003d039ea3ab21f-naa.600a0980383148693724545244395855
   Runtime Name: vmhba4:C0:T0:L11
   Device: naa.600a0980383148693724545244395855
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a0980383148693724545244395855)
   Group State: active
   Array Priority: 0
   Storage Array Type Path Config: {TPG_id=1001,*TPG_state=AO*,RTP_id=4,RTP_health=UP}
   Path Selection Policy Path Config: PSP VMW_PSP_RR does not support path configuration.

fc.20000024ff7f4a50:21000024ff7f4a50-fc.2009d039ea3ab21f:2002d039ea3ab21f-naa.600a0980383148693724545244395855
   Runtime Name: vmhba3:C0:T0:L11
   Device: naa.600a0980383148693724545244395855
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a0980383148693724545244395855)
   Group State: active
   Array Priority: 0
   Storage Array Type Path Config: {TPG_id=1001,*TPG_state=AO*,RTP_id=3,RTP_health=UP}
   Path Selection Policy Path Config: PSP VMW_PSP_RR does not support path configuration.

fc.20000024ff7f4a51:21000024ff7f4a51-fc.2009d039ea3ab21f:2001d039ea3ab21f-naa.600a0980383148693724545244395855
   Runtime Name: vmhba4:C0:T3:L11
   Device: naa.600a0980383148693724545244395855
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a0980383148693724545244395855)
   Group State: active unoptimized
   Array Priority: 0
   Storage Array Type Path Config: {TPG_id=1000,*TPG_state=ANO*,RTP_id=2,RTP_health=UP}
   Path Selection Policy Path Config: PSP VMW_PSP_RR does not support path configuration.

fc.20000024ff7f4a50:21000024ff7f4a50-fc.2009d039ea3ab21f:2000d039ea3ab21f-naa.600a0980383148693724545244395855
   Runtime Name: vmhba3:C0:T3:L11
   Device: naa.600a0980383148693724545244395855
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a0980383148693724545244395855)
   Group State: active unoptimized
   Array Priority: 0
   Storage Array Type Path Config: {TPG_id=1000,*TPG_state=ANO*,RTP_id=1,RTP_health=UP}
   Path Selection Policy Path Config: PSP VMW_PSP_RR does not support path configuration.
----


=== Tutte le configurazioni DEGLI array SAN

Nelle configurazioni ASA, tutti i percorsi verso una determinata LUN sono attivi e ottimizzati. In questo modo, le performance vengono migliorate grazie alle operazioni di i/o in tutti i percorsi contemporaneamente.

.Esempio
Nell'esempio seguente viene visualizzato l'output corretto per un LUN ONTAP:

[listing]
----
esxcli storage nmp device list -d naa.600a098038304759563f4e7837574453
----
Output di esempio:

[listing]
----
naa.600a098038314962485d543078486c7a
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a098038314962485d543078486c7a)
   Storage Array Type: VMW_SATP_ALUA
   Storage Array Type Device Config: {implicit_support=on; explicit_support=off; explicit_allow=on; alua_followover=on; action_OnRetryErrors=off; {TPG_id=1001,TPG_state=AO}{TPG_id=1000,TPG_state=AO}}
   Path Selection Policy: VMW_PSP_RR
   Path Selection Policy Device Config: {policy=rr,iops=1000,bytes=10485760,useANO=0; lastPathIndex=3: NumIOsPending=0,numBytesPending=0}
   Path Selection Policy Device Custom Config:
   Working Paths: vmhba4:C0:T0:L14, vmhba4:C0:T1:L14, vmhba3:C0:T0:L14, vmhba3:C0:T1:L14
   Is USB: false

----
[listing]
----
# esxcli storage nmp path list -d naa.600a098038314962485d543078486c7a
----
Output di esempio:

[listing, subs="+quotes"]
----
fc.200034800d756a75:210034800d756a75-fc.2018d039ea936319:2015d039ea936319-naa.600a098038314962485d543078486c7a
   Runtime Name: vmhba4:C0:T0:L14
   Device: naa.600a098038314962485d543078486c7a
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a098038314962485d543078486c7a)
   Group State: active
   Array Priority: 0
   Storage Array Type Path Config: {TPG_id=1000,*TPG_state=AO*,RTP_id=2,RTP_health=UP}
   Path Selection Policy Path Config: PSP VMW_PSP_RR does not support path configuration.

fc.200034800d756a75:210034800d756a75-fc.2018d039ea936319:2017d039ea936319-naa.600a098038314962485d543078486c7a
   Runtime Name: vmhba4:C0:T1:L14
   Device: naa.600a098038314962485d543078486c7a
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a098038314962485d543078486c7a)
   Group State: active
   Array Priority: 0
   Storage Array Type Path Config: {TPG_id=1001,*TPG_state=AO*,RTP_id=4,RTP_health=UP}
   Path Selection Policy Path Config: PSP VMW_PSP_RR does not support path configuration.

fc.200034800d756a74:210034800d756a74-fc.2018d039ea936319:2014d039ea936319-naa.600a098038314962485d543078486c7a
   Runtime Name: vmhba3:C0:T0:L14
   Device: naa.600a098038314962485d543078486c7a
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a098038314962485d543078486c7a)
   Group State: active
   Array Priority: 0
   Storage Array Type Path Config: {TPG_id=1000,*TPG_state=AO*,RTP_id=1,RTP_health=UP}
   Path Selection Policy Path Config: PSP VMW_PSP_RR does not support path configuration.

fc.200034800d756a74:210034800d756a74-fc.2018d039ea936319:2016d039ea936319-naa.600a098038314962485d543078486c7a
   Runtime Name: vmhba3:C0:T1:L14
   Device: naa.600a098038314962485d543078486c7a
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a098038314962485d543078486c7a)
   Group State: active
   Array Priority: 0
   Storage Array Type Path Config: {TPG_id=1001,*TPG_state=AO*,RTP_id=3,RTP_health=UP}
   Path Selection Policy Path Config: PSP VMW_PSP_RR does not support path configuration.
----


== VVol

I volumi virtuali (vVol) sono un tipo di oggetto VMware che corrisponde a un disco macchina virtuale (VM), alle relative istantanee e ai cloni rapidi.

Gli strumenti ONTAP per VMware vSphere includono il provider VASA per ONTAP, che fornisce il punto di integrazione per un VMware vCenter per sfruttare lo storage basato su vVol. Quando si implementa l'appliance di virtualizzazione aperta (OVA) degli strumenti ONTAP, questa viene automaticamente registrata nel server vCenter e attiva il provider VASA.

Quando si crea un datastore vVols utilizzando l'interfaccia utente di vCenter, questo guida alla creazione di FlexVols come storage di backup per il datastore. Gli host ESXi accedono ai vVol all'interno degli archivi dati vVol utilizzando un endpoint del protocollo (PE). Negli ambienti SAN, viene creata una LUN da 4 MB su ogni FlexVol nel datastore per l'utilizzo come PE. Una SAN PE è un'unità logica amministrativa (ALU). I vVol sono unità logiche sussidiarie (SLU).

I requisiti standard e le Best practice per gli ambienti SAN si applicano quando si utilizza vVol, inclusi (a titolo esemplificativo) i seguenti:

* Creare almeno una LIF SAN su ciascun nodo per SVM che si intende utilizzare. La procedura consigliata consiste nel creare almeno due per nodo, ma non più del necessario.
* Elimina ogni singolo punto di guasto. Utilizzare più interfacce di rete VMkernel su diverse subnet di rete che utilizzano il raggruppamento NIC quando vengono utilizzati più switch virtuali oppure utilizzare più NIC fisiche collegate a più switch fisici per fornire ha e un throughput maggiore.
* Configurare lo zoning, le VLAN o entrambe secondo necessità per la connettività host.
* Verificare che tutti gli iniziatori richiesti siano collegati ai LIF di destinazione sulla SVM desiderata.



NOTE: È necessario implementare i tool ONTAP per VMware vSphere per abilitare il provider VASA. Il provider VASA gestirà tutte le impostazioni di iGroup per te, pertanto non è necessario creare o gestire iGroups in un ambiente vVol.

NetApp sconsiglia di modificare le impostazioni vVol da quelle predefinite.

Fare riferimento a. https://mysupport.netapp.com/matrix/imt.jsp?components=65623;64703;&solution=1&isHWU&src=IMT["Tool di matrice di interoperabilità NetApp"^] Per versioni specifiche dei tool ONTAP o per il provider VASA legacy per le versioni specifiche di vSphere e ONTAP.

Per informazioni dettagliate sul provisioning e sulla gestione dei vVol, fare riferimento alla documentazione relativa ai tool ONTAP per VMware vSphere, link:https://docs.netapp.com/us-en/netapp-solutions/hybrid-cloud/vsphere_ontap_ontap_for_vsphere.html["TR-4597"^], e. link:https://www.netapp.com/pdf.html?item=/media/13555-tr4400pdf.pdf["TR-4400"^].



== Impostazioni consigliate



=== Blocco ATS

Il blocco ATS è *obbligatorio* per lo storage compatibile con VAAI e per VMFS5 aggiornato ed è necessario per una corretta interoperabilità e performance i/o dello storage condiviso VMFS ottimali con le LUN ONTAP. Per ulteriori informazioni sull'attivazione del blocco ATS, consultare la documentazione VMware.

[cols="4*"]
|===
| Impostazioni | Predefinito | Consigliato da ONTAP | Descrizione 


| HardwareAcceleratedLocking | 1 | 1 | Consente di utilizzare il blocco ATS (Atomic Test and Set) 


| IOPS dei dischi | 1000 | 1 | IOPS Limit (limite IOPS): Per impostazione predefinita, la PSP Round Robin ha un limite IOPS di 1000. In questo caso predefinito, viene utilizzato un nuovo percorso dopo l'emissione di 1000 operazioni di i/O. 


| Disk/QFullSampleSize | 0 | 32 | Il numero di condizioni DI CODA PIENO o OCCUPATO necessario prima che ESXi inizi a rallentare. 
|===

NOTE: Abilitare `Space-alloc` Impostazione per tutti i LUN mappati a VMware vSphere per `UNMAP` al lavoro. Per ulteriori informazioni, consultare la documentazione ONTAP.



=== Timeout del sistema operativo guest

È possibile configurare manualmente le macchine virtuali con le impostazioni del sistema operativo guest consigliate. Dopo aver ottimizzato gli aggiornamenti, è necessario riavviare il guest per rendere effettive le modifiche.

*Valori di timeout GOS:*

[cols="2*"]
|===
| Tipo di sistema operativo guest | Timeout 


| Varianti di Linux | timeout disco = 60 


| Windows | timeout disco = 60 


| Solaris | timeout del disco = 60 tentativi di occupato = 300 tentativi non pronti = 300 tentativi di ripristino = 30 massimo acceleratore = 32 minuti acceleratore = 8 
|===


=== Validare vSphere tunable

È possibile utilizzare il seguente comando per verificare `HardwareAcceleratedLocking` impostazione.

`esxcli system settings  advanced list --option /VMFS3/HardwareAcceleratedLocking`

[listing, subs="+quotes"]
----
   Path: /VMFS3/HardwareAcceleratedLocking
   Type: integer
   Int Value: *1*
   Default Int Value: 1
   Min Value: 0
   Max Value: 1
   String Value:
   Default String Value:
   Valid Characters:
   Description: Enable hardware accelerated VMFS locking (requires compliant hardware). Please see http://kb.vmware.com/kb/2094604 before disabling this option.
----


=== Convalidare l'impostazione Disk IOPS (IOPS disco)

È possibile utilizzare il seguente comando per verificare l'impostazione degli IOPS.

`esxcli storage nmp device list -d naa.600a098038304731783f506670553355`

[listing, subs="+quotes"]
----
naa.600a098038304731783f506670553355
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a098038304731783f506670553355)
   Storage Array Type: VMW_SATP_ALUA
   Storage Array Type Device Config: {implicit_support=on; explicit_support=off; explicit_allow=on; alua_followover=on; action_OnRetryErrors=off; {TPG_id=1000,TPG_state=ANO}{TPG_id=1001,TPG_state=AO}}
   Path Selection Policy: VMW_PSP_RR
   Path Selection Policy Device Config: {policy=rr,*iops=1*,bytes=10485760,useANO=0; lastPathIndex=0: NumIOsPending=0,numBytesPending=0}
   Path Selection Policy Device Custom Config:
   Working Paths: vmhba4:C0:T0:L82, vmhba3:C0:T0:L82
   Is USB: false
----


=== Validare QFullSampleSize

È possibile utilizzare il seguente comando per verificare QFullSampleSize.

`esxcli system settings  advanced list --option /Disk/QFullSampleSize`

[listing, subs="+quotes"]
----
   Path: /Disk/QFullSampleSize
   Type: integer
   Int Value: *32*
   Default Int Value: 0
   Min Value: 0
   Max Value: 64
   String Value:
   Default String Value:
   Valid Characters:
   Description: Default I/O samples to monitor for detecting non-transient queue full condition. Should be nonzero to enable queue depth throttling. Device specific QFull options will take precedence over this value if set.
----


== Problemi noti

[cols="10,30,30"]
|===
| ID bug NetApp | Titolo | Descrizione 


| 1543660 | L'errore i/o si verifica quando le macchine virtuali Linux che utilizzano gli adattatori vNVMe incontrano una lunga finestra APD (All Paths Down)  a| 
Le macchine virtuali Linux che eseguono vSphere 8.x e versioni successive e che utilizzano adattatori virtuali NVMe (vNVME) riscontrano un errore i/o perché l'operazione di ripetizione vNVMe è disattivata per impostazione predefinita. Per evitare interruzioni sulle macchine virtuali Linux che eseguono kernel meno recenti durante un All Paths Down (APD) o un carico i/o pesante, VMware ha introdotto un "VSCSIDisableNvmeRetry" sintonizzabile per disattivare l'operazione di ripetizione di vNVMe.

|===
.Link correlati
* link:https://docs.netapp.com/us-en/netapp-solutions/virtualization/vsphere_ontap_ontap_for_vsphere.html["TR-4597-VMware vSphere con ONTAP"^]
* link:https://kb.vmware.com/s/article/2031038["Supporto di VMware vSphere 5.x, 6.x e 7.x con NetApp MetroCluster (2031038)"^]
* link:https://kb.vmware.com/s/article/83370["NetApp ONTAP con NetApp SnapMirror Business Continuity (SM-BC) con cluster di storage metro VMware vSphere (vMSC)"^]

