---
sidebar: sidebar 
permalink: hu_wuhu_71.html 
keywords: windows, host, utilities, 7.1, hba, fibre, channel, SANtricity, netapp, san, host, e-series, platform 
summary: 'Le utilità host Windows includono un programma di installazione che imposta i parametri richiesti del Registro di sistema e dell"HBA di Windows in modo che l"host Windows gestisca correttamente i comportamenti del sistema storage per le piattaforme ONTAP ed e-Series.' 
---
= Installa Windows Host Utilities 7.1 per l'archiviazione ONTAP
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Le utilità host di Windows consentono di collegare un computer host di Windows ai sistemi di archiviazione NetApp.

Le utilità host di Windows supportano le seguenti versioni di Windows:

* Windows 2022
* Windows 2019
* Windows 2016
* Windows 2012R2
* Windows 2012


Le utilità host Windows includono un programma di installazione che imposta i parametri richiesti del Registro di sistema di Windows e dell'HBA (host Bus Adapter) in modo che un host Windows possa gestire correttamente i comportamenti del sistema storage per le piattaforme ONTAP ed e-Series.

Quando si installa il software host Utilities, il programma di installazione imposta i parametri necessari del registro di Windows e dell'HBA.

I seguenti programmi e file vengono installati sul computer host di Windows. La directory predefinita è `C:\Program Files\NetApp\Windows Host Utilities`.

|===
| Programma | Scopo 


| `emulexhba.reg` | Programma per la risoluzione dei problemi; eseguire questo programma solo se richiesto dal personale di supporto tecnico. 


| `\NetAppQCLI\fcconfig.exe` | Utilizzato dal programma di installazione per impostare i parametri HBA. 


| `\NetAppQCLI\fcconfig.ini` | Utilizzato dal programma di installazione per impostare i parametri HBA. 


| `\NetAppQCLI\*.*` | Utilizzato dal programma di installazione per impostare i parametri QLogic FC HBA. 


| `san_version.exe` | Visualizza la versione delle utilità host e degli HBA FC. 
|===
Le utilità host supportano diverse configurazioni host di Windows, protocolli e opzioni di multipathing. Consultare la https://mysupport.netapp.com/matrix/["Tool di matrice di interoperabilità"^] per l'elenco aggiornato delle configurazioni supportate.



== Passaggio 1: verifica le configurazioni dell'host e del sistema di archiviazione

Prima di installare le utilità host di Windows per <<supported-windows-versions-71,Versione di Windows supportata>>, verificare che la configurazione del sistema host e del sistema di archiviazione siano supportate.

.Fasi
. Verificare la configurazione supportata in http://mysupport.netapp.com/matrix["Tool di matrice di interoperabilità"^] .
. Controllare gli hotfix richiesti per la versione dell'host Windows Server inlink:https://docs.netapp.com/us-en/ontap-sanhost/index.html["Documentazione Windows per host SAN"] .
+
Ad esempio, illink:https://docs.netapp.com/us-en/ontap-sanhost/hu_windows_2022.html["Configurare Windows Server 2022 per l'archiviazione ONTAP"] la documentazione fornisce le istruzioni per l'installazione degli hotfix di Windows per Windows Server 2022.

. link:https://docs.netapp.com/us-en/ontap/san-admin/verify-license-fc-iscsi-task.html["Aggiungere la licenza iSCSI o FCP"^] .
+

NOTE: I protocolli FC e iSCSI non richiedono licenze sui sistemi di archiviazione E-Series che utilizzano SANtricity Storage Manager.

. Avviare il servizio di destinazione.
. Verificare il cablaggio.
+
Fare riferimento al https://docs.netapp.com/us-en/ontap/san-config/index.html["Riferimento alla configurazione SAN"^] per informazioni dettagliate sul cablaggio e sulla configurazione.





== Passaggio 2: configurare gli HBA e gli switch FC

Installare e configurare uno o più HBA (host bus adapter) FC supportati per le connessioni FC al sistema storage.

Il programma di installazione delle utility host di Windows imposta le impostazioni HBA FC richieste.


CAUTION: Si consiglia di consentire solo al programma di installazione di Windows Host Utilities di impostare i parametri HBA.  Ciò garantisce che l'host Windows possa gestire correttamente i comportamenti del sistema di archiviazione per le piattaforme ONTAP .

.Fasi
. Installare uno o più HBA FC supportati seguendo le istruzioni fornite dal fornitore dell'HBA.
. Ottenere i driver HBA supportati e le utility di gestione e installarli in base alle istruzioni fornite dal fornitore HBA.
. https://docs.netapp.com/us-en/ontap/san-management/index.html["Collegare gli HBA agli switch FC o direttamente al sistema di storage"^] .
. https://docs.netapp.com/us-en/ontap/san-config/fibre-channel-fcoe-zoning-concept.html["Crea zone sullo switch FC in base alla documentazione dello switch FC"^] .
. Per ONTAP, suddividere in zone lo switch in base al WWPN.  Assicurarsi di utilizzare il WWPN delle interfacce logiche (LIF) e non il WWPN delle porte fisiche sui controller di archiviazione. Fare riferimento al  https://docs.netapp.com/us-en/ontap/san-config/index.html["Riferimento alla configurazione SAN"^] per maggiori informazioni.




== Passaggio 3: installare le utilità host di Windows

Il programma di installazione installa il pacchetto Windows Host Utilities e imposta il registro di Windows e le impostazioni HBA.

.A proposito di questa attività
Facoltativamente, è possibile includere il supporto multipathing quando si installa il pacchetto software Windows Host Utilities.  Il programma di installazione richiede le seguenti opzioni:

* Scegliere `MPIO` Se si dispone di più percorsi dall'host o dalla macchina virtuale di Windows al sistema di storage.
* Scegliere `no MPIO` solo se si utilizza un singolo percorso verso il sistema di archiviazione.


È anche possibile scegliere il supporto multipathing tramite un prompt della riga di comando di Windows.

Per i guest Hyper-V, i dischi raw (pass-through) non vengono visualizzati nel sistema operativo guest se si sceglie il supporto multipathing.  È possibile utilizzare dischi raw o MPIO, ma non è possibile utilizzare entrambi nel sistema operativo guest.


CAUTION: Se non si installa il software MPIO, il sistema operativo Windows potrebbe vedere ciascun percorso come un disco separato. Questo può causare il danneggiamento dei dati.


NOTE: Windows XP o Windows Vista in esecuzione su una macchina virtuale Hyper-V non supporta MPIO.

.Fasi
È possibile installare Host Utilities in modo interattivo oppure tramite la riga di comando di Windows.  Il nuovo pacchetto di installazione di Host Utilities deve trovarsi in un percorso accessibile all'host Windows.

[role="tabbed-block"]
====
.Installazione interattiva
--
Installare il pacchetto software Host Utilities in modo interattivo eseguendo il programma di installazione Host Utilities e seguendo le istruzioni.

. Scaricare il file eseguibile da https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["Sito di supporto NetApp"^].
. Passare alla directory da cui è stato scaricato il file eseguibile.
. Eseguire `netapp_windows_host_utilities_7.1_x64` archiviare e seguire le istruzioni visualizzate sullo schermo.
. Riavviare l'host Windows quando richiesto.


--
.Installa in modo non interattivo
--
Eseguire un'installazione non interattiva di Host Utilities utilizzando la riga di comando di Windows.  Il sistema si riavvia automaticamente al termine dell'installazione.

. Immettere il seguente comando al prompt dei comandi di Windows:
+
[source, cli]
----
msiexec /i installer.msi /quiet MULTIPATHING= {0 | 1} [INSTALLDIR=inst_path]
----
+
** `installer` è il nome di `.msi` File per l'architettura della CPU
** MULTIPATHING specifica se è installato il supporto MPIO. I valori consentiti sono "0" per no, "1" per sì
** `inst_path` È il percorso in cui sono installati i file delle utility host. Il percorso predefinito è `C:\Program Files\NetApp\Windows Host Utilities\`.





NOTE: Per visualizzare le opzioni standard di Microsoft Installer (MSI) per la registrazione e altre funzioni, immettere `msiexec /help` Al prompt dei comandi di Windows. Ad esempio, il comando `msiexec /i install.msi /quiet /l*v <install.log> LOGVERBOSE=1` visualizza le informazioni di registrazione.

--
====


== Quali sono le prossime novità?

link:hu_wuhu_hba_settings.html["Configurare le impostazioni del registro per Windows Host Utilities"] .
