---
sidebar: sidebar 
permalink: hu_wuhu_upgrade.html 
keywords: windows, host, utilities, 7.1, hba, fibre, channel, SANtricity, netapp, san, host, e-series, platform 
summary: 'Le utilità host Windows includono un programma di installazione che imposta i parametri richiesti del Registro di sistema e dell"HBA di Windows in modo che l"host Windows gestisca correttamente i comportamenti del sistema storage per le piattaforme ONTAP ed e-Series.' 
---
= Aggiornare Windows Host Utilities per l'archiviazione ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È possibile aggiornare il software Windows Host Utilities nella configurazione di archiviazione ONTAP seguendo le istruzioni di installazione in modo interattivo oppure utilizzando la riga di comando di Windows.  È necessario installare il nuovo software di installazione Windows Host Utilities in un percorso accessibile all'host Windows.

[role="tabbed-block"]
====
.Aggiornamento interattivo
--
Aggiornare il software Windows Host Utilities in modo interattivo eseguendo il programma di installazione di Host Utilities e seguendo le istruzioni.

.Fasi
. Passare alla directory in cui è stato scaricato il file eseguibile.
. Eseguire il file eseguibile e seguire le istruzioni visualizzate.
. Riavviare l'host Windows quando richiesto.
. Al termine del riavvio, controllare la versione dell'utility host:
+
.. Aprire *pannello di controllo*.
.. Accedere a *programmi e funzionalità* e controllare la versione dell'utility host.




--
.Aggiorna in modo non interattivo
--
Eseguire un aggiornamento software non interattivo di Windows Host Utilities utilizzando la riga di comando di Windows.

.Fasi
. Digitare il seguente comando al prompt dei comandi di Windows:
+
[source, cli]
----
msiexec /i installer.msi /quiet MULTIPATHING= {0 | 1} [INSTALLDIR=inst_path]
----
+
** `installer` è il nome di `.msi` File per l'architettura della CPU.
** MULTIPATHING specifica se è installato il supporto Microsoft Multipath i/o (MPIO). I valori consentiti sono "0" per no e "1" per sì.
** `inst_path` È il percorso in cui sono installati i file delle utility host. Il percorso predefinito è `C:\Program Files\NetApp\Windows Host Utilities\`.





NOTE: Per visualizzare le opzioni standard di Microsoft Installer (MSI) per la registrazione e altre funzioni, immettere `msiexec /help` Al prompt dei comandi di Windows. Ad esempio, il `msiexec /i install.msi /quiet /l*v <install.log> LOGVERBOSE=1` visualizza le informazioni di registrazione.

Il sistema si riavvia automaticamente al termine dell'installazione.

--
====