---
sidebar: sidebar 
permalink: hu_wuhu_71.html 
keywords: windows, host, utilities, 7.1, hba, fibre, channel, SANtricity, netapp, san, host, e-series, platform 
summary: 'Le utilità host Windows includono un programma di installazione che imposta i parametri richiesti del Registro di sistema e dell"HBA di Windows in modo che l"host Windows gestisca correttamente i comportamenti del sistema storage per le piattaforme ONTAP ed e-Series.' 
---
= Installare le utilità host Windows 7,1
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Le utilità host di Windows consentono di collegare un computer host di Windows ai sistemi di archiviazione NetApp.

Le utilità host di Windows supportano le seguenti versioni di Windows:

* Windows 2022
* Windows 2019
* Windows 2016
* Windows 2012R2
* Windows 2012


Le utilità host Windows includono un programma di installazione che imposta i parametri richiesti del Registro di sistema di Windows e dell'HBA (host Bus Adapter) in modo che un host Windows possa gestire correttamente i comportamenti del sistema storage per le piattaforme ONTAP ed e-Series.

Quando si installa il software host Utilities, il programma di installazione imposta i parametri necessari del registro di Windows e dell'adattatore bus host (HBA).

I seguenti programmi e file vengono installati sul computer host di Windows. La directory predefinita è `C:\Program Files\NetApp\Windows Host Utilities`.

|===
| Programma | Scopo 


| `emulexhba.reg` | Programma per la risoluzione dei problemi; eseguire questo programma solo se richiesto dal personale di supporto tecnico. 


| `\NetAppQCLI\fcconfig.exe` | Utilizzato dal programma di installazione per impostare i parametri HBA. 


| `\NetAppQCLI\fcconfig.ini` | Utilizzato dal programma di installazione per impostare i parametri HBA. 


| `\NetAppQCLI\*.*` | Utilizzato dal programma di installazione per impostare i parametri QLogic FC HBA. 


| `san_version.exe` | Visualizza la versione delle utilità host e degli HBA FC. 
|===
Le utilità host supportano diverse configurazioni host di Windows, protocolli e opzioni di multipathing. Consultare la https://mysupport.netapp.com/matrix/["Tool di matrice di interoperabilità"^] per l'elenco aggiornato delle configurazioni supportate.



== Verifica delle configurazioni dell'host e del sistema di storage

Prima di installare le Utility host, verificare che la versione delle Utility host supporti la configurazione del sistema host e storage in modo che il software venga installato correttamente.

.Fasi
. Verificare la configurazione supportata in http://mysupport.netapp.com/matrix["Tool di matrice di interoperabilità"^] .
. Controllare le correzioni rapide richieste per il rispettivo host su link:https://docs.netapp.com/us-en/ontap-sanhost/index.html["Documentazione Windows per host SAN"].
+

NOTE: Il link:https://docs.netapp.com/us-en/ontap-sanhost/hu_windows_2022.html["Utilizzo di Windows Server 2022 con ONTAP"] il documento fornisce le istruzioni su link:https://docs.netapp.com/us-en/ontap-sanhost/hu_windows_2022.html#installing-windows-hotfixes["Installazione degli hotfix di Windows"] Per Windows Server 2022. Fare riferimento ai documenti Windows nella categoria configurazioni host per trovare le informazioni relative alle correzioni rapide per le versioni precedenti del server Windows.

. Aggiungere la licenza iSCSI o FCP e avviare il servizio di destinazione.
+

NOTE: I protocolli FC e iSCSI non richiedono alcuna licenza per i sistemi storage e-Series che utilizzano SANtricity Storage Manager.

. Verificare il cablaggio
+
Vedere https://docs.netapp.com/us-en/ontap/san-config/index.html["Riferimento alla configurazione SAN"^] Documentazione relativa alla versione di ONTAP o. https://docs.netapp.com/us-en/e-series/install-hw-cabling/index.html["Cablaggio hardware e-Series"^] per informazioni dettagliate sul cablaggio e sulla configurazione.





== Configurare gli HBA e gli switch FC

Installare e configurare uno o più HBA (host Bus Adapter) FC supportati per le connessioni FC a un sistema di storage.

Il programma di installazione delle utility host di Windows imposta le impostazioni HBA FC richieste.


NOTE: Non modificare manualmente le impostazioni dell'HBA.

.Fasi
. Installare uno o più HBA FC supportati seguendo le istruzioni fornite dal fornitore dell'HBA.
. Ottenere i driver HBA supportati e le utility di gestione e installarli in base alle istruzioni fornite dal fornitore HBA.
. Collegare gli HBA agli switch FC o direttamente al sistema storage.
. Creare zone sullo switch FC in base alla documentazione dello switch FC.
. Per ONTAP, impostare lo switch in base al nome della porta universale (WWPN). Assicurarsi di utilizzare il WWPN dei LIF e non le porte fisiche dei controller di storage. Vedere https://docs.netapp.com/us-en/ontap/san-config/index.html["Riferimento alla configurazione SAN"^] documentazione per ulteriori informazioni.




== Installare le utility host

Il programma di installazione installa il pacchetto Utility host e imposta il registro di sistema di Windows e le impostazioni HBA.

È necessario specificare se includere il supporto multipathing quando si installa il pacchetto software Utilità host di Windows. Il programma di installazione richiede di scegliere la seguente opzione. È inoltre possibile eseguire un'installazione silenziosa (non assistita) dal prompt dei comandi di Windows.

.Supporto multipathing
* Scegliere `MPIO` Se si dispone di più percorsi dall'host o dalla macchina virtuale di Windows al sistema di storage.
* Scegliere `no MPIO` solo se si utilizza un singolo percorso per il sistema storage.


La selezione di Microsoft Multipath i/o (MPIO) non è disponibile per i sistemi Windows XP e Windows Vista; multipath i/o non è supportato su questi sistemi operativi guest. Per i guest Hyper-V, i dischi raw (pass-through) non vengono visualizzati nel sistema operativo guest se si sceglie il supporto multipathing. È possibile utilizzare dischi raw o MPIO, ma non entrambi nel sistema operativo guest.

È possibile installare le utilità host in modo interattivo o utilizzando la riga di comando. Il nuovo pacchetto di installazione di Utility host deve trovarsi in un percorso accessibile dall'host di Windows. Seguire le istruzioni per l'installazione interattiva delle utilità host o dalla riga di comando di Windows.

[role="tabbed-block"]
====
.Installazione interattiva
--
.Fasi
Per installare il pacchetto software Utility host in modo interattivo, è necessario eseguire il programma di installazione Utility host e seguire le istruzioni.

.Fasi
. Scaricare il file eseguibile da https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["Sito di supporto NetApp"^].
. Passare alla directory da cui è stato scaricato il file eseguibile.
. Eseguire `netapp_windows_host_utilities_7.1_x64` archiviare e seguire le istruzioni visualizzate sullo schermo.
. Riavviare l'host Windows quando richiesto.


--
.Installare da una riga di comando
--
È possibile eseguire un'installazione silenziosa (non presidiata) delle utility host immettendo i comandi appropriati al prompt dei comandi di Windows. Il sistema si riavvia automaticamente al termine dell'installazione.

.Fasi
. Immettere il seguente comando al prompt dei comandi di Windows:
+
`msiexec /i installer.msi /quiet MULTIPATHING= {0 | 1} [INSTALLDIR=inst_path]`

+
** `installer` è il nome di `.msi` File per l'architettura della CPU
** MULTIPATHING specifica se è installato il supporto MPIO. I valori consentiti sono "0" per no, "1" per sì
** `inst_path` È il percorso in cui sono installati i file delle utility host. Il percorso predefinito è `C:\Program Files\NetApp\Windows Host Utilities\`.





NOTE: Per visualizzare le opzioni standard di Microsoft Installer (MSI) per la registrazione e altre funzioni, immettere `msiexec /help` Al prompt dei comandi di Windows. Ad esempio, il comando `msiexec /i install.msi /quiet /l*v <install.log> LOGVERBOSE=1` visualizza le informazioni di registrazione.

--
====