---
sidebar: sidebar 
permalink: hu_wuhu_troubleshoot.html 
keywords: windows, host, utilities, 7.1, hba, fibre, channel, SANtricity, netapp, san, host, e-series, platform 
summary: 'Le utilità host Windows includono un programma di installazione che imposta i parametri richiesti del Registro di sistema e dell"HBA di Windows in modo che l"host Windows gestisca correttamente i comportamenti del sistema storage per le piattaforme ONTAP ed e-Series.' 
---
= Risoluzione dei problemi relativi a Windows Host Utilities con configurazione di archiviazione ONTAP
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Utilizzare le tecniche generali di risoluzione dei problemi per analizzare i problemi che potrebbero verificarsi per una configurazione di archiviazione Windows Host Utilities con ONTAP .  Dovresti anche controllare illink:hu-wuhu-release-notes.html["Note sulla versione delle utilità host di Windows"] per problemi noti e relative soluzioni.

Di seguito è riportato un elenco delle diverse aree che è possibile esaminare per individuare potenziali problemi di interoperabilità:

* Per identificare potenziali problemi di interoperabilità, verificare che le utilità host supportino la combinazione di software del sistema operativo host, hardware host, software ONTAP e hardware del sistema di storage. Per ulteriori informazioni, vedere la http://mysupport.netapp.com/matrix["Tool di matrice di interoperabilità"^] .
* Verificare di disporre della configurazione iSCSI corretta.
* Se i LUN iSCSI non sono disponibili dopo un riavvio, verificare che la destinazione sia elencata come persistente nella scheda *destinazioni persistenti* della GUI dell'iniziatore iSCSI di Microsoft.
* Se le applicazioni che utilizzano i LUN visualizzano errori all'avvio, verificare che le applicazioni siano configurate in modo da dipendere dal servizio iSCSI.
* Per i percorsi FC agli storage controller che eseguono ONTAP, verificare che gli switch FC siano sottoposti a zoning usando i WWPN delle LIF di destinazione, non i WWPN delle porte fisiche del nodo.
* Rivedere illink:hu-wuhu-release-notes.html["Note di rilascio"] affinché Windows Host Utilities verifichi la presenza di problemi noti.  Le note di rilascio includono un elenco di problemi noti e limitazioni.
* Consultare le informazioni sulla risoluzione dei problemi contenute nella https://docs.netapp.com/us-en/ontap/san-admin/index.html["Amministrazione SAN di ONTAP"^] documentazione.
* Cerca https://mysupport.netapp.com/site/bugs-online/product["NetApp Bugs Online"^] per i problemi rilevati di recente.
+
** Nel campo tipo di bug in Ricerca avanzata, selezionare *iSCSI - Windows*, quindi selezionare *Vai*. Ripetere la ricerca per tipo di bug *FCP -Windows*.


* Raccogliere informazioni sul sistema.
* Annotare eventuali messaggi di errore visualizzati sulla console del sistema di storage o dell'host.
* Raccogliere i file di log dell'host e del sistema di storage.
* Annotare i sintomi del problema e le eventuali modifiche apportate all'host o al sistema di storage prima che si verificasse il problema.
* Se non riesci a risolvere il problema, contatta il supporto tecnico di NetApp per ricevere assistenza.

