---
sidebar: sidebar 
permalink: hu_wuhu_repair_remove.html 
keywords: windows, host, utilities, 7.1, hba, fibre, channel, SANtricity, netapp, san, host, e-series, platform 
summary: 'Le utilità host Windows includono un programma di installazione che imposta i parametri richiesti del Registro di sistema e dell"HBA di Windows in modo che l"host Windows gestisca correttamente i comportamenti del sistema storage per le piattaforme ONTAP ed e-Series.' 
---
= Riparare e rimuovere le utilità host di Windows per l'archiviazione ONTAP
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Utilizzare l'opzione *Ripara* nel programma di installazione Host Utilities per aggiornare le impostazioni dell'adattatore bus host (HBA) e del registro di sistema di Windows.  È anche possibile rimuovere completamente Host Utilities, in modo interattivo o dalla riga di comando di Windows.

[role="tabbed-block"]
====
.Riparare o rimuovere in modo interattivo
--
L'opzione *Ripara* aggiorna il registro di sistema di Windows e gli HBA FC con le impostazioni richieste. È inoltre possibile rimuovere completamente le utility host.

.Fasi
. Aprire Windows *programmi e funzionalità* (Windows Server 2012 R2, Windows Server 2016, Windows Server 2019 e Windows 2022).
. Selezionare *NetApp Utilità host Windows*.
. Selezionare *Cambia*.
. Selezionare *Repair* (Riparazione) o *Remove* (Rimuovi), in base alle necessità.
. Seguire le istruzioni visualizzate.


--
.Riparare o rimuovere in modo non interattivo
--
L'opzione *Ripara* aggiorna il registro di sistema di Windows e gli HBA FC con le impostazioni richieste. È inoltre possibile rimuovere completamente le utility host da una riga di comando di Windows.

.Fasi
. Ripristina utilità host Windows:
+
[source, cli]
----
msiexec /f installer.msi [/quiet]
----
+
** `/f` ripara l'installazione.
** `installer.msi` È il nome del programma di installazione di Windows host Utilities sul sistema.
** `/quiet` elimina tutti i feedback e riavvia automaticamente il sistema senza chiedere conferma al completamento del comando.




--
====