---
permalink: legal_notices.html 
sidebar: sidebar 
keywords: legal, notices, copyright, trademarks, patents 
summary: 'Le note legali forniscono l"accesso a dichiarazioni di copyright, marchi, brevetti e altro ancora.' 
---
= Note legali
:allow-uri-read: 


[role="lead"]
Le note legali forniscono l'accesso a dichiarazioni di copyright, marchi, brevetti e altro ancora.



== Copyright

http://www.netapp.com/us/legal/copyright.aspx[]



== Marchi

NETAPP, il logo NETAPP e i marchi elencati nella pagina dei marchi NetApp sono marchi di NetApp, Inc. Altri nomi di società e prodotti potrebbero essere marchi dei rispettivi proprietari.

http://www.netapp.com/us/legal/netapptmlist.aspx[]



== Brevetti

Un elenco aggiornato dei brevetti di proprietà di NetApp è disponibile all'indirizzo:

https://www.netapp.com/us/media/patents-page.pdf[]



== Direttiva sulla privacy

https://www.netapp.com/us/legal/privacypolicy/index.aspx[]



== Open source

Fornisce informazioni sul copyright e sulle licenze di terze parti utilizzate in questo prodotto.

* link:./media/Notices-AIX61-2023.pdf["Avviso per AIX"^]
* link:./media/Linux_Unified_Host_Utilities.pdf["Avviso per Linux"^]
* link:./media/Solaris_Host_Utilities-2017.09.12-01.25.35.pdf["Avviso per Solaris"^]
* link:./media/Windows_Unified_Host_Utilities_(WUHU)Notice.pdf["Avviso per Windows"^]

