---
sidebar: sidebar 
permalink: nvme_rhel_81.html 
keywords: nvme, linux, rhel, red hat, enterprise 
summary: Descrive come configurare NVMe/FC per RHEL 8.1 con ONTAP 
---
= Configurazione host NVMe/FC per RHEL 8,1 con ONTAP
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
NVMe/FC è supportato su ONTAP 9,6 o versioni successive per Red Hat Enterprise Linux (RHEL) 8,1. Un host RHEL 8,1 può eseguire traffico NVMe e SCSI tramite le stesse porte dell'adattatore FC Initiator. Vedere link:https://hwu.netapp.com/Home/Index["Hardware Universe"^] Per un elenco di controller e adattatori FC supportati.

Vedere link:https://mysupport.netapp.com/matrix/["Tool di matrice di interoperabilità NetApp"^] per l'elenco aggiornato delle configurazioni supportate.



== Limitazioni note

* Gli script NVMe/FC di connessione automatica nativi non sono disponibili in `nvme-cli` pacchetto. È possibile utilizzare lo script esterno di connessione automatica fornito dal fornitore dell'HBA (host Bus Adapter).
* Il multipath NVMe è disattivato per impostazione predefinita. Pertanto, è necessario attivarlo manualmente.
* Per impostazione predefinita, il bilanciamento del carico round-robin non è attivato. È possibile attivare questa funzionalità scrivendo un `udev` regola.
* L'avvio SAN che utilizza il protocollo NVMe-of non è attualmente supportato.




== Abilitare NVMe/FC

Puoi usare la seguente procedura per attivare NVMe/FC.

.Fasi
. Installare Red Hat Enterprise Linux 8.1 sul server.
. Al termine dell'installazione, verificare che il kernel RHEL specificato sia in esecuzione:
+
[listing]
----
# uname -r
4.18.0-147.el8.x86_64
----
+
Vedere link:https://mysupport.netapp.com/matrix/["Tool di matrice di interoperabilità NetApp"^] per l'elenco più aggiornato delle versioni supportate.

. Installare `nvme-cli-1.8.1-3.el8` pacchetto:
+
[listing]
----
# rpm -qa|grep nvme-cli
nvme-cli-1.8.1-3.el8.x86_64
----
. Abilita multipath NVMe nel kernel:
+
[listing]
----
# grubby –args=nvme_core.multipath=Y –update-kernel /boot/vmlinuz-4.18.0-147.el8.x86_64
----
. Aggiungere la seguente stringa come regola udev separata in `/lib/udev/rules.d/71-nvme-iopolicy-netapp-ONTAP.rules`. Ciò consente il bilanciamento del carico round-robin per NVMe Multipath:
+
[listing]
----
# Enable round-robin for NetApp ONTAP
ACTION==”add”, SUBSYSTEM==”nvme-subsystem”, ATTR{model}==”NetApp ONTAP Controller”, ATTR{iopolicy}=”round-robin
----
. Sull'host RHEL 8,1, controllare la stringa NQN dell'host su `/etc/nvme/hostnqn` E verificare che corrisponda alla stringa NQN dell'host per il sottosistema corrispondente sull'array ONTAP:
+
[listing]
----
# cat /etc/nvme/hostnqn
nqn.2014-08.org.nvmexpress:uuid:75953f3b-77fe-4e03-bf3c-09d5a156fbcd
----
+
[listing]
----
*> vserver nvme subsystem host show -vserver vs_nvme_10
Vserver Subsystem Host NQN
------- --------- -------------------------------------- -----------
rhel_141_nvme_ss_10_0
nqn.2014-08.org.nvmexpress:uuid:75953f3b-77fe-4e03-bf3c-09d5a156fbcd
----
+

NOTE: Se le stringhe NQN host non corrispondono, utilizzare `vserver modify` Comando per aggiornare la stringa NQN dell'host sul sottosistema di array ONTAP corrispondente in modo che corrisponda alla stringa NQN dell'host da `/etc/nvme/hostnqn` sull'host.

. Riavviare l'host.




== Configurare l'adattatore Broadcom FC per NVMe/FC

Per configurare un adattatore FC Broadcom, attenersi alla seguente procedura.

.Fasi
. Verificare di utilizzare l'adattatore supportato. Vedere link:https://mysupport.netapp.com/matrix/["Tool di matrice di interoperabilità NetApp"^] per l'elenco più aggiornato delle schede supportate.
+
[listing]
----
# cat /sys/class/scsi_host/host*/modelname
LPe32002-M2
LPe32002-M2
----
+
[listing]
----
# cat /sys/class/scsi_host/host*/modeldesc
Emulex LightPulse LPe32002-M2 2-Port 32Gb Fibre Channel Adapter
Emulex LightPulse LPe32002-M2 2-Port 32Gb Fibre Channel Adapter
----
. Copiare e installare il driver di uscita Broadcom lpfc e gli script di connessione automatica:
+
[listing]
----
# tar -xvzf elx-lpfc-dd-rhel8-12.4.243.20-ds-1.tar.gz
# cd elx-lpfc-dd-rhel8-12.4.2453.20-ds-1
# ./elx_lpfc_install-sh -i -n
----
+

NOTE: I driver nativi forniti con il sistema operativo sono denominati driver inbox. Se si scaricano i driver outbox (driver non inclusi in una versione del sistema operativo), nel download viene incluso uno script di connessione automatica che deve essere installato come parte del processo di installazione dei driver.

. Riavviare l'host.
. Verificare di utilizzare il firmware Broadcom lpfc, il driver outbox e le versioni del pacchetto di connessione automatica consigliati:
+
[listing]
----
# cat /sys/class/scsi_host/host*/fwrev
12.4.243.20, sil-4.2.c
12.4.243.20, sil-4.2.c
----
+
[listing]
----
# cat /sys/module/lpfc/version
0:12.4.243.20
----
+
[listing]
----
# rpm -qa | grep nvmefc
nvmefc-connect-12.6.61.0-1.noarch
----
. Verificare che `lpfc_enable_fc4_type` è impostato su 3:
+
[listing]
----
# cat /sys/module/lpfc/parameters/lpfc_enable_fc4_type
3
----
. Verificare che le porte dell'iniziatore siano attive e in esecuzione:
+
[listing]
----
# cat /sys/class/fc_host/host*/port_name
0x10000090fae0ec61
0x10000090fae0ec62
----
+
[listing]
----
# cat /sys/class/fc_host/host*/port_state
Online
Online
----
. Verifica che le porte initiator NVMe/FC siano abilitate e in esecuzione e puoi vedere le LIF di destinazione:
+
[listing]
----
# cat /sys/class/scsi_host/host*/nvme_info
NVME Initiator Enabled
XRI Dist lpfc0 Total 6144 NVME 2947 SCSI 2977 ELS 250
NVME LPORT lpfc0 WWPN x10000090fae0ec61 WWNN x20000090fae0ec61 DID x012000 ONLINE
NVME RPORT WWPN x202d00a098c80f09 WWNN x202c00a098c80f09 DID x010201 TARGET DISCSRVC ONLINE
NVME RPORT WWPN x203100a098c80f09 WWNN x202c00a098c80f09 DID x010601 TARGET DISCSRVC ONLINE
NVME Statistics
…
----




== Abilita 1MB i/o Size per Broadcom NVMe/FC

ONTAP riporta un MDTS (MAX Data Transfer Size) di 8 nei dati del controller di identificazione, il che significa che la dimensione massima della richiesta di i/o può essere fino a 1 MB. Tuttavia, per emettere richieste di i/o di dimensione 1 MB per un host Broadcom NVMe/FC, è necessario aumentare `lpfc` valore di `lpfc_sg_seg_cnt` parametro a 256 dal valore predefinito di 64.

.Fasi
. Impostare `lpfc_sg_seg_cnt` parametro a 256.
+
[listing]
----
# cat /etc/modprobe.d/lpfc.conf
options lpfc lpfc_sg_seg_cnt=256
----
. Eseguire un `dracut -f` e riavviare l'host.
. Verificare che `lpfc_sg_seg_cnt` è 256.
+
[listing]
----
# cat /sys/module/lpfc/parameters/lpfc_sg_seg_cnt
256
----



NOTE: Non applicabile agli host Qlogic NVMe/FC.



== Validare NVMe/FC

Per validare NVMe/FC, è possibile utilizzare la seguente procedura.

.Fasi
. Verificare le seguenti impostazioni NVMe/FC.
+
[listing]
----
# cat /sys/module/nvme_core/parameters/multipath
Y
----
+
[listing]
----
# cat /sys/class/nvme-subsystem/nvme-subsys*/model
NetApp ONTAP Controller
NetApp ONTAP Controller
----
+
[listing]
----
# cat /sys/class/nvme-subsystem/nvme-subsys*/iopolicy
round-robin
round-robin
----
. Verificare che gli spazi dei nomi siano stati creati.
+
[listing]
----
# nvme list
Node SN Model Namespace Usage Format FW Rev
---------------- -------------------- -----------------------
/dev/nvme0n1 80BADBKnB/JvAAAAAAAC NetApp ONTAP Controller 1 53.69 GB / 53.69 GB 4 KiB + 0 B FFFFFFFF
----
. Verificare lo stato dei percorsi ANA.
+
[listing]
----
# nvme list-subsys/dev/nvme0n1
Nvme-subsysf0 – NQN=nqn.1992-08.com.netapp:sn.341541339b9511e8a9b500a098c80f09:subsystem.rhel_141_nvme_ss_10_0
\
+- nvme0 fc traddr=nn-0x202c00a098c80f09:pn-0x202d00a098c80f09 host_traddr=nn-0x20000090fae0ec61:pn-0x10000090fae0ec61 live optimized
+- nvme1 fc traddr=nn-0x207300a098dfdd91:pn-0x207600a098dfdd91 host_traddr=nn-0x200000109b1c1204:pn-0x100000109b1c1204 live inaccessible
+- nvme2 fc traddr=nn-0x207300a098dfdd91:pn-0x207500a098dfdd91 host_traddr=nn-0x200000109b1c1205:pn-0x100000109b1c1205 live optimized
+- nvme3 fc traddr=nn-0x207300a098dfdd91:pn-0x207700a098dfdd91 host traddr=nn-0x200000109b1c1205:pn-0x100000109b1c1205 live inaccessible
----
. Verificare il plug-in NetApp per i dispositivi ONTAP.
+
[listing]
----

# nvme netapp ontapdevices -o column
Device   Vserver  Namespace Path             NSID   UUID   Size
-------  -------- -------------------------  ------ ----- -----
/dev/nvme0n1   vs_nvme_10       /vol/rhel_141_vol_10_0/rhel_141_ns_10_0    1        55baf453-f629-4a18-9364-b6aee3f50dad   53.69GB

# nvme netapp ontapdevices -o json
{
   "ONTAPdevices" : [
   {
        Device" : "/dev/nvme0n1",
        "Vserver" : "vs_nvme_10",
        "Namespace_Path" : "/vol/rhel_141_vol_10_0/rhel_141_ns_10_0",
         "NSID" : 1,
         "UUID" : "55baf453-f629-4a18-9364-b6aee3f50dad",
         "Size" : "53.69GB",
         "LBA_Data_Size" : 4096,
         "Namespace_Size" : 13107200
    }
]
----

