---
sidebar: sidebar 
permalink: nvme_sles15_sp1.html 
keywords: nvme, linux, suse, sles, 15, sp1, server, enterprise 
summary: Descrive come configurare NVMe/FC per SUSE Linux Enterprise Server 15 SP1 con ONTAP 
---
= Configurazione host NVMe/FC per SUSE Linux Enterprise Server 15 SP1 con ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È possibile configurare NVMe su Fibre Channel (NVMe/FC) su host che eseguono SUSE Linux Enterprise Server 15 SP1 e ONTAP come destinazione.

NVMe/FC è supportato su ONTAP 9.6 o versioni successive per le seguenti versioni di SLES:

* SLES15 SP1
+
L'host SLES15 SP1 può eseguire traffico NVMe/FC e FCP attraverso le stesse porte dell'adattatore per iniziatori Fibre Channel. Vedere link:https://hwu.netapp.com/Home/Index["Hardware Universe"^] Per un elenco di controller e adattatori FC supportati.

+
Per l'elenco più aggiornato delle configurazioni e delle versioni supportate, vedere link:https://mysupport.netapp.com/matrix/["Matrice di interoperabilità NetApp"^].

* Gli script nativi di connessione automatica NVMe/FC sono inclusi nel pacchetto nvme-cli. È possibile utilizzare il driver lpfc inbox nativo su SLES15 SP1.




== Limitazioni note

L'avvio SAN che utilizza il protocollo NVMe-of non è attualmente supportato.



== Abilitare NVMe/FC su SLES15 SP1

. Eseguire l'aggiornamento al kernel MU SLES15 SP2 consigliato
. Eseguire l'aggiornamento alla versione consigliata di nvme-cli MU.
+
Questo pacchetto nvme-cli contiene gli script nativi di connessione automatica NVMe/FC, pertanto non è necessario installare gli script esterni di connessione automatica NVMe/FC forniti da Broadcom sull'host SLES15 SP1. Questo pacchetto include anche la regola udev di ONTAP che consente il bilanciamento del carico round-robin per il multipath NVMe e il plug-in NetApp per i dispositivi ONTAP.

+
[listing]
----
# rpm -qa | grep nvme-cli
nvme-cli-1.8.1-6.9.1.x86_64
----
. Sull'host SLES15 SP1, controllare la stringa NQN dell'host su `/etc/nvme/hostnqn` E verificare che corrisponda alla stringa NQN host per il sottosistema corrispondente sull'array ONTAP. Ad esempio:
+
[listing]
----
# cat /etc/nvme/hostnqn
nqn.2014-08.org.nvmexpress:uuid:75953f3b-77fe-4e03-bf3c-09d5a156fbcd
----
+
[listing]
----
*> vserver nvme subsystem host show -vserver vs_nvme_10
Vserver Subsystem Host NQN
------- --------- -------------------------------------- -----------
sles_117_nvme_ss_10_0
nqn.2014-08.org.nvmexpress:uuid:75953f3b-77fe-4e03-bf3c-09d5a156fbcd
----
. Riavviare l'host.




== Configurare Broadcom FC Adapter per NVMe/FC

. Verificare di utilizzare l'adattatore supportato. Per l'elenco più aggiornato degli adattatori supportati, consultare link:https://mysupport.netapp.com/matrix/["Matrice di interoperabilità NetApp"^].
+
[listing]
----
# cat /sys/class/scsi_host/host*/modelname
LPe32002-M2
LPe32002-M2
----
+
[listing]
----
# cat /sys/class/scsi_host/host*/modeldesc
Emulex LightPulse LPe32002-M2 2-Port 32Gb Fibre Channel Adapter
Emulex LightPulse LPe32002-M2 2-Port 32Gb Fibre Channel Adapter
----
. Verificare di utilizzare il firmware Broadcom lpfc consigliato e le versioni dei driver inbox nativi.
+
[listing]
----
# cat /sys/class/scsi_host/host*/fwrev
12.4.243.17, sil-4.2.c
12.4.243.17, sil-4.2.c
----
+
[listing]
----
# cat /sys/module/lpfc/version
0:12.6.0.0
----
. Verificare che lpfc_ENABLE_fc4_TYPE sia impostato su 3.
+
[listing]
----
# cat /sys/module/lpfc/parameters/lpfc_enable_fc4_type
3
----
. Verificare che le porte dell'iniziatore siano attive e in esecuzione.
+
[listing]
----
# cat /sys/class/fc_host/host*/port_name
0x10000090fae0ec61
0x10000090fae0ec62
----
+
[listing]
----
# cat /sys/class/fc_host/host*/port_state
Online
Online
----
. Verificare che le porte NVMe/FC Initiator siano attivate, in esecuzione e in grado di visualizzare le LIF di destinazione.
+
[listing]
----
# cat /sys/class/scsi_host/host*/nvme_info
NVME Initiator Enabled
XRI Dist lpfc0 Total 6144 NVME 2947 SCSI 2977 ELS 250
NVME LPORT lpfc0 WWPN x10000090fae0ec61 WWNN x20000090fae0ec61 DID x012000 ONLINE
NVME RPORT WWPN x202d00a098c80f09 WWNN x202c00a098c80f09 DID x010201 TARGET DISCSRVC ONLINE
NVME RPORT WWPN x203100a098c80f09 WWNN x202c00a098c80f09 DID x010601 TARGET DISCSRVC ONLINE
NVME Statistics
…
----




== Validare NVMe/FC

. Verificare le seguenti impostazioni NVMe/FC.
+
[listing]
----
# cat /sys/module/nvme_core/parameters/multipath
Y
----
+
[listing]
----
# cat /sys/class/nvme-subsystem/nvme-subsys*/model
NetApp ONTAP Controller
NetApp ONTAP Controller
----
+
[listing]
----
# cat /sys/class/nvme-subsystem/nvme-subsys*/iopolicy
round-robin
round-robin
----
. Verificare che gli spazi dei nomi siano stati creati.
+
[listing]
----
# nvme list
Node SN Model Namespace Usage Format FW Rev
---------------- -------------------- -----------------------
/dev/nvme0n1 80BADBKnB/JvAAAAAAAC NetApp ONTAP Controller 1 53.69 GB / 53.69 GB 4 KiB + 0 B FFFFFFFF
----
. Verificare lo stato dei percorsi ANA.
+
[listing]
----
# nvme list-subsys/dev/nvme0n1
Nvme-subsysf0 – NQN=nqn.1992-08.com.netapp:sn.341541339b9511e8a9b500a098c80f09:subsystem.sles_117_nvme_ss_10_0
\
+- nvme0 fc traddr=nn-0x202c00a098c80f09:pn-0x202d00a098c80f09 host_traddr=nn-0x20000090fae0ec61:pn-0x10000090fae0ec61 live optimized
+- nvme1 fc traddr=nn-0x207300a098dfdd91:pn-0x207600a098dfdd91 host_traddr=nn-0x200000109b1c1204:pn-0x100000109b1c1204 live inaccessible
+- nvme2 fc traddr=nn-0x207300a098dfdd91:pn-0x207500a098dfdd91 host_traddr=nn-0x200000109b1c1205:pn-0x100000109b1c1205 live optimized
+- nvme3 fc traddr=nn-0x207300a098dfdd91:pn-0x207700a098dfdd91 host traddr=nn-0x200000109b1c1205:pn-0x100000109b1c1205 live inaccessible
----
. Verificare il plug-in NetApp per i dispositivi ONTAP.
+
[listing]
----
# nvme netapp ontapdevices -o column
Device   Vserver  Namespace Path             NSID   UUID   Size
-------  -------- -------------------------  ------ ----- -----
/dev/nvme0n1   vs_nvme_10       /vol/sles_117_vol_10_0/sles_117_ns_10_0    1        55baf453-f629-4a18-9364-b6aee3f50dad   53.69GB

# nvme netapp ontapdevices -o json
{
   "ONTAPdevices" : [
   {
        Device" : "/dev/nvme0n1",
        "Vserver" : "vs_nvme_10",
        "Namespace_Path" : "/vol/sles_117_vol_10_0/sles_117_ns_10_0",
         "NSID" : 1,
         "UUID" : "55baf453-f629-4a18-9364-b6aee3f50dad",
         "Size" : "53.69GB",
         "LBA_Data_Size" : 4096,
         "Namespace_Size" : 13107200
    }
]
----
+
== problemi noti



Non ci sono problemi noti.



== Abilita 1MB i/o Size per Broadcom NVMe/FC

ONTAP riporta un MDTS (MAX Data Transfer Size) di 8 nei dati del controller di identificazione, il che significa che la dimensione massima della richiesta di i/o può essere fino a 1 MB. Tuttavia, per emettere richieste di i/o di dimensione 1 MB per un host Broadcom NVMe/FC, è necessario aumentare `lpfc` valore di `lpfc_sg_seg_cnt` parametro a 256 dal valore predefinito di 64.

.Fasi
. Impostare `lpfc_sg_seg_cnt` parametro a 256.
+
[listing]
----
# cat /etc/modprobe.d/lpfc.conf
options lpfc lpfc_sg_seg_cnt=256
----
. Eseguire un `dracut -f` e riavviare l'host.
. Verificare che `lpfc_sg_seg_cnt` è 256.
+
[listing]
----
# cat /sys/module/lpfc/parameters/lpfc_sg_seg_cnt
256
----



NOTE: Non applicabile agli host Qlogic NVMe/FC.



== LPFC verbose Logging

Impostare il driver lpfc per NVMe/FC.

.Fasi
. Impostare `lpfc_log_verbose` Impostazione del driver su uno dei seguenti valori per registrare gli eventi NVMe/FC.
+
[listing]
----
#define LOG_NVME 0x00100000 /* NVME general events. */
#define LOG_NVME_DISC 0x00200000 /* NVME Discovery/Connect events. */
#define LOG_NVME_ABTS 0x00400000 /* NVME ABTS events. */
#define LOG_NVME_IOERR 0x00800000 /* NVME IO Error events. */
----
. Dopo aver impostato i valori, eseguire `dracut-f` comandare e riavviare l'host.
. Verificare le impostazioni.
+
[listing]
----
# cat /etc/modprobe.d/lpfc.conf options lpfc lpfc_log_verbose=0xf00083

# cat /sys/module/lpfc/parameters/lpfc_log_verbose 15728771
----

