---
sidebar: sidebar 
permalink: nvme-aix.html 
keywords: nvme, linux, rhel, red hat, enterprise, aix, ontap 
summary: Come configurare NVMe/FC host per AIX con ONTAP 
---
= Configurare AIX con NVMe-oF per l'archiviazione ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Gli host IBM AIX e Virtual I/O Server (VIOS)/PowerVM supportano il protocollo NVMe/FC con Asymmetric Namespace Access (ANA).  ANA è equivalente al multipathing ALUA (Asymmetric Logical Unit Access) negli ambienti iSCSI e FCP.

Per ulteriori dettagli sulle configurazioni supportate, vederelink:https://mysupport.netapp.com/matrix/["Tool di matrice di interoperabilità (IMT)"^] .

.A proposito di questa attività
È possibile utilizzare il supporto e le funzionalità seguenti con la configurazione host NVMe-oF per gli host AIX.  Prima di iniziare il processo di configurazione, è opportuno esaminare anche le limitazioni note.

* Supporto disponibile:
+
** A partire da ONTAP 9.13.1, il supporto NVMe/FC è stato aggiunto per IBM AIX 7.2 TL5 SP6, AIX 7.3 TL1 SP2 e VIOS 3.1.4.21 con supporto di avvio SAN per stack fisici e virtuali.  Per ulteriori informazioni sulla configurazione del supporto di avvio SAN, consultare la documentazione IBM.
** NVMe/FC è supportato dai server IBM Power9 e Power10.
** Per i dispositivi NVMe non è richiesto un PCM (Path Control Module) separato, come il supporto Host Utilities per AIX SCSI Multipath I/O (MPIO).
** Il supporto della virtualizzazione con NetApp (VIOS/PowerVM) viene introdotto con VIOS 3.1.4.21. Questo è _solo_ supportato tramite la modalità di virtualizzazione dello storage NPIV (N_PortID Virtualization) utilizzando il server Power10 IBM.


* Limitazioni note:
+
** Gli HBA Qlogic/Marvel 32G FC su un host AIX non supportano NVMe/FC.
** L'avvio SAN non è supportato per i dispositivi NVMe/FC che utilizzano il server IBM Power9.




.Prima di iniziare
* Verificare di disporre di adattatori Emulex FC da 32 GB (EN1A, EN1B, EN1L, EN1M) o adattatori FC da 64 GB (EN1N, EN1P) con firmware dell'adattatore 12.4.257.30 e versioni successive.
* Se si dispone di una configurazione MetroCluster, NetApp consiglia di modificare il tempo APD (All Path Down) predefinito AIX NVMe/FC per supportare gli eventi di switchover non pianificati MetroCluster per evitare che il sistema operativo AIX applichi un timeout i/o più breve. Per ulteriori informazioni e per le modifiche consigliate alle impostazioni predefinite, fare riferimento a bug NetApp online - link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/1553249["1553249"^].
* A seconda della versione di AIX, il timeout di transizione di accesso allo spazio dei nomi asimmetrico (ANATT) per il sistema operativo host AIX è di 30 o 60 secondi per impostazione predefinita.  Se l'ANATT predefinito per l'host è 30 secondi, è necessario installare un IBM Interim Fix (ifix) dal sito Web IBM che imposti l'ANATT su 60 secondi per garantire che tutti i flussi di lavoro ONTAP non siano disgreganti.
+
[NOTE]
====
Per il supporto NVMe/FC AIX, è necessario installare un ifix sulla versione GA del sistema operativo AIX.  L'ifix non è richiesto per il sistema operativo VIOS/PowerVM.

È necessario installare gli ifix su una versione AIX senza ifix precedentemente installati relativi a `devices.pciex.pciexclass.010802.rte` sul sistema.  Gli ifix installati in precedenza potrebbero entrare in conflitto con la nuova installazione.

====
+
[role="tabbed-block"]
====
.Imposta ANATT su 60 secondi
--
L'ANATT predefinito per le versioni AIX livello 72-TL5-SP6-2320 e AIX livello 73-TL1-SP2-2320 è 30 secondi.  IBM fornisce un ifix che imposta l'ANATT a 60 secondi.  L'ifix è disponibile tramite l'ID caso IBM TS018079082 ed è possibile installarlo per le seguenti versioni di AIX:

** Per AIX livello 72-TL5-SP6-2320, installare `IJ46710s6a.230509.epkg.Z` pacchetto.
** Per AIX livello 73-TL1-SP2-2320, installare `IJ46711s2a.230509.epkg.Z` pacchetto.


--
.L'ANATT predefinito è 60 secondi
--
L'ANATT predefinito è 60 secondi per le seguenti versioni di AIX:

** Livello AIX 73-TL2-SP3-2446
** Livello AIX 73-TL2-SP2-2420
** Livello AIX 72-TL5-SP8-2420


--
.Facoltativamente, impostare ANATT su 120 secondi
--
IBM fornisce un ifix che imposta l'ANATT a 120 secondi.  Impostando ANATT su 120 secondi, si migliorano le prestazioni durante gli eventi di failover dell'archiviazione ONTAP .  L'ifix è disponibile tramite l'ID caso IBM TS012877410 ed è possibile installarlo per le seguenti versioni di AIX:

** Per il livello AIX 73-TL3-SP0-2446, installare `IJ53487s0a.250130.epkg.Z` pacchetto.
** Per il livello AIX 72-TL5-SP9-2446, installare `IJ53445s9a.250130.epkg.Z` pacchetto.


--
====
+
[NOTE]
====
La versione minima del firmware del server per i server Power9 per il supporto NVMe/FC è FW 950.

La versione minima del firmware del server per i server Power10 per il supporto NVMe/FC è FW 1010.

====
+
Per ulteriori informazioni sulla gestione degli ifix, consulta link:http://www-01.ibm.com/support/docview.wss?uid=isg3T1012104["Gestione delle correzioni interinali su AIX"^].





== Passaggio 1: confermare la configurazione multipath per l'host

Quando si installa il sistema operativo AIX, IBM MPIO utilizzato per il multipathing NVMe è abilitato per impostazione predefinita.

.Fasi
. Verificare che il multipathing NVMe sia abilitato:
+
[source, cli]
----
lsmpio -l hdisk1
----
+
.Mostra esempio
[%collapsible]
====
[listing]
----
name     path_id  status   path_status  parent  connection
hdisk1  8         Enabled  Sel,Opt       nvme12  fcnvme0, 9
hdisk1  9         Enabled  Sel,Non       nvme65  fcnvme1, 9
hdisk1  10        Enabled  Sel,Opt       nvme37  fcnvme1, 9
hdisk1  11        Enabled  Sel,Non       nvme60  fcnvme0, 9
----
====




== Passaggio 2: configurare NVMe/FC

È necessario configurare NVMe/FC per gli adattatori Broadcom/Emulex su VIOS perché il supporto del protocollo NVMe/FC è disabilitato nel Virtual Fibre Channel (vFC) su VIOS.  Per impostazione predefinita, il supporto del protocollo NVMe/FC è abilitato nell'FC fisico.

.Fasi
. link:https://mysupport.netapp.com/matrix/["Verifica di utilizzare l'adattatore supportato"^] .
. Recuperare un elenco di adattatori virtuali:
+
[source, cli]
----
lsmap -all -npiv
----
+
.Mostra esempio
[%collapsible]
====
[listing]
----
Name          Physloc                            ClntID ClntName       ClntOS
------------- ---------------------------------- ------ -------------- -------
vfchost0      U9105.22A.785DB61-V2-C2                 4 s1022-iop-mcc- AIX
Status:LOGGED_IN
FC name:fcs4                    FC loc code:U78DA.ND0.WZS01UY-P0-C7-T0
Ports logged in:3
Flags:0xea<LOGGED_IN,STRIP_MERGE,SCSI_CLIENT,NVME_CLIENT>
VFC client name:fcs0            VFC client DRC:U9105.22A.785DB61-V4-C2
----
====
. Abilitare il supporto per il protocollo NVMe/FC su un adattatore eseguendo `ioscli vfcctrl` Comando su VIOS:
+
[source, cli]
----
vfcctrl -enable -protocol nvme -vadapter vfchost0
----
+
.Output di esempio
[listing]
----
The "nvme" protocol for "vfchost0" is enabled.
----
. Verificare che il supporto sia stato attivato sulla scheda di rete:
+
[source, cli]
----
lsattr -El vfchost0
----
+
.Mostra esempio
[%collapsible]
====
[listing]
----
alt_site_wwpn       WWPN to use - Only set after migration   False
current_wwpn  0     WWPN to use - Only set after migration   False
enable_nvme   yes   Enable or disable NVME protocol for NPIV True
label               User defined label                       True
limit_intr    false Limit NPIV Interrupt Sources             True
map_port      fcs4  Physical FC Port                         False
num_per_nvme  0     Number of NPIV NVME queues per range     True
num_per_range 0     Number of NPIV SCSI queues per range     True
----
====
. Abilitare il protocollo NVMe/FC per tutti gli adattatori:
+
.. Modificare il `dflt_enabl_nvme` valore attributo di `viosnpiv0` pseudo dispositivo a. `yes`.
.. Impostare `enable_nvme` valore attributo a. `yes` Per tutti i dispositivi host VFC.
+
[source, cli]
----
chdev -l viosnpiv0 -a dflt_enabl_nvme=yes
----
+
[source, cli]
----
lsattr -El viosnpiv0
----
+
.Mostra esempio
[%collapsible]
====
[listing]
----
bufs_per_cmd    10  NPIV Number of local bufs per cmd                    True
dflt_enabl_nvme yes Default NVME Protocol setting for a new NPIV adapter True
num_local_cmds  5   NPIV Number of local cmds per channel                True
num_per_nvme    8   NPIV Number of NVME queues per range                 True
num_per_range   8   NPIV Number of SCSI queues per range                 True
secure_va_info  no  NPIV Secure Virtual Adapter Information              True
----
====


. Attivare il protocollo NVMe/FC per gli adattatori selezionati modificando il `enable_nvme` Valore dell'attributo del dispositivo host VFC su `yes`.
. Verificare che `FC-NVMe Protocol Device` è stato creato sul server:
+
[source, cli]
----
lsdev |grep fcnvme
----
+
.Esempio di output
[listing]
----
fcnvme0       Available 00-00-02    FC-NVMe Protocol Device
fcnvme1       Available 00-01-02    FC-NVMe Protocol Device
----
. Registrare l'NQN host dal server:
+
[source, cli]
----
lsattr -El fcnvme0
----
+
.Mostra esempio
[%collapsible]
====
[listing]
----
attach     switch                                                               How this adapter is connected  False
autoconfig available                                                            Configuration State            True
host_nqn   nqn.2014-08.org.nvmexpress:uuid:64e039bd-27d2-421c-858d-8a378dec31e8 Host NQN (NVMe Qualified Name) True
----
====
+
[source, cli]
----
lsattr -El fcnvme1
----
+
.Mostra esempio
[%collapsible]
====
[listing]
----
attach     switch                                                               How this adapter is connected  False
autoconfig available                                                            Configuration State            True
host_nqn   nqn.2014-08.org.nvmexpress:uuid:64e039bd-27d2-421c-858d-8a378dec31e8 Host NQN (NVMe Qualified Name) True
----
====
. Controllare l'NQN host e verificare che corrisponda alla stringa NQN host per il sottosistema corrispondente sull'array ONTAP:
+
[source, cli]
----
vserver nvme subsystem host show -vserver vs_s922-55-lpar2
----
+
.Output di esempio
[listing]
----
Vserver         Subsystem                Host NQN
------- --------- ----------------------------------------------------------
vs_s922-55-lpar2 subsystem_s922-55-lpar2 nqn.2014-08.org.nvmexpress:uuid:64e039bd-27d2-421c-858d-8a378dec31e8
----
. Verificare che le porte dell'iniziatore siano attive e in esecuzione e che siano visualizzate le LIF di destinazione.




== Passaggio 3: convalida NVMe/FC

Verificare che gli spazi dei nomi ONTAP siano corretti per la configurazione NVMe/FC.

.Fasi
. Verificare che gli spazi dei nomi ONTAP si riflettano correttamente sull'host:
+
[source, cli]
----
lsdev -Cc disk |grep NVMe
----
+
.Output di esempio
[listing]
----
hdisk1  Available 00-00-02 NVMe 4K Disk
----
. Facoltativamente, controllare lo stato del multipathing:
+
[source, cli]
----
lsmpio -l hdisk1
----
+
.Mostra esempio
[%collapsible]
====
[listing]
----
name     path_id  status   path_status  parent  connection
hdisk1  8        Enabled  Sel,Opt      nvme12  fcnvme0, 9
hdisk1  9        Enabled  Sel,Non      nvme65  fcnvme1, 9
hdisk1  10       Enabled  Sel,Opt      nvme37  fcnvme1, 9
hdisk1  11       Enabled  Sel,Non      nvme60  fcnvme0, 9
----
====




== Passaggio 4: rivedere i problemi noti

La configurazione host NVMe/FC per AIX con storage ONTAP presenta i seguenti problemi noti:

[cols="10,30,30"]
|===
| ID Burt | Titolo | Descrizione 


| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/BURT/1553249["1553249"^] | AIX NVMe/FC - tempo APD predefinito da modificare per supportare gli eventi di switchover non pianificati MCC | Per impostazione predefinita, i sistemi operativi AIX utilizzano un valore di timeout APD (All Path Down) di 20 sec per NVMe/FC.  Tuttavia, i flussi di lavoro di switchover automatici non pianificati (AUSO) e di switchover avviati da tiebreaker di ONTAP MetroCluster potrebbero richiedere un po' più di tempo della finestra di timeout APD, causando errori di i/O. 


| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/BURT/1546017["1546017"^] | AIX NVMe/FC ha un valore massimo di 60 secondi, invece di 120 secondi, come annunciato da ONTAP | ONTAP annuncia il timeout di transizione ANA (Asymmetric namespace access) nel controller Identify a 120 sec. Attualmente, con ifix, AIX legge il timeout di transizione ANA dal controller Identify, ma in effetti lo blocca a 60 sec se supera tale limite. 


| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/BURT/1541386["1541386"^] | AIX NVMe/FC raggiunge EIO dopo la scadenza ANATT | Per qualsiasi evento di failover dello storage (SFO), se la transizione ANA(Asymmetric namespace access) supera il limite di timeout di transizione ANA su un determinato percorso, l'host NVMe/FC AIX non riesce con un errore di i/o nonostante siano disponibili percorsi alternativi per lo spazio dei nomi. 


| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/BURT/1541380["1541380"^] | AIX NVMe/FC attende la scadenza di ANATT metà/completa prima di riprendere i/o dopo ANA AEN | IBM AIX NVMe/FC non supporta alcune notifiche asincrone pubblicate da ONTAP. Questa gestione ANA non ottimale comporterà performance non ottimali durante le operazioni SFO. 
|===


== Passaggio 5: risoluzione dei problemi

Prima di risolvere eventuali errori NVMe/FC, verificare di eseguire una configurazione conforme alink:https://mysupport.netapp.com/matrix/["IMT"^] specifiche.  Se continui ad avere problemi, contattalink:https://mysupport.netapp.com["Supporto NetApp"^] .
