---
sidebar: sidebar 
permalink: nvme_windows_2016.html 
keywords: nvme, windows, enterprise 
summary: 'È possibile configurare NVMe over Fibre Channel (NVMe/FC) sugli host che eseguono Windows Server 2016 per il funzionamento con le LUN ONTAP.' 
---
= Configurare Windows Server 2016 con NVMe/FC per ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È possibile configurare NVMe over Fibre Channel (NVMe/FC) sugli host che eseguono Windows Server 2016 per il funzionamento con le LUN ONTAP.

.A proposito di questa attività
Puoi utilizzare il seguente supporto con la configurazione host NVMe/FC per Windows 2016. Prima di avviare il processo di configurazione, è inoltre necessario esaminare le limitazioni note.


NOTE: È possibile utilizzare le impostazioni di configurazione fornite in questa procedura per configurare i client cloud connessi a link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/index.html["Cloud Volumes ONTAP"^] e link:https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/index.html["Amazon FSX per ONTAP"^].

* Supporto disponibile:
+
A partire da ONTAP 9,7, NVMe/FC è supportato per Windows Server 2016.

+
Per un elenco degli adattatori e dei controller FC supportati, vedere link:https://hwu.netapp.com/Home/Index["Hardware Universe"^]. Per l'elenco aggiornato delle configurazioni e delle versioni supportate, vedere link:https://mysupport.netapp.com/matrix/["Tool di matrice di interoperabilità"^].

* Limitazioni note:
+
Il cluster di failover Windows non è supportato con NVMe/FC perché al momento ONTAP non supporta le prenotazioni persistenti con NVMe/FC.

+

NOTE: Broadcom offre un driver esterno per Windows NVMe/FC, un driver SCSI ⇄ NVMe traslazionale e non un vero driver NVMe/FC. L'overhead traslazionale non influisce necessariamente sulle performance, ma annulla i vantaggi in termini di performance di NVMe/FC. Di conseguenza, le prestazioni NVMe/FC e FCP sono identiche sui server Windows, a differenza di altri sistemi operativi come Linux, dove le prestazioni NVMe/FC sono significativamente migliori rispetto al protocollo FCP.





== Abilitare NVMe/FC

Attivare FC/NVMe sull'host Windows Initiator.

.Fasi
. Installare l'utilità Emulex HBA Manager sull'host Windows.
. Su ciascuna porta HBA Initiator, impostare i seguenti parametri del driver HBA:
+
** EnableNVMe = 1
** NVMEMode = 0


. Riavviare l'host.




== Configurare l'adattatore FC Broadcom

L'iniziatore Broadcom può servire traffico NVMe/FC e FCP tramite le stesse porte adattatore FC 32G. Per FCP ed FC/NVMe, è necessario utilizzare il modulo DSM (Device Specific Module) Microsft come opzione MPIO (Microsoft Multipath i/o).

A `+hostnqn+` è associato ogni porta HBA (host Bus Adapter) per l'adattatore Broadcom con FC/NVMe in un ambiente Windows. La `+hostnqn+` è formattata come illustrato nell'esempio seguente:

....
nqn.2017-01.com.broadcom:ecd:nvmf:fc:100000109b1b9765
nqn.2017-01.com.broadcom:ecd:nvmf:fc:100000109b1b9766
....


=== Attiva MPIO per dispositivi NVMe

È necessario abilitare MPIO per dispositivi NVMe per completare la configurazione NVMe sull'host Windows.

.Fasi
. Installare link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["Windows host Utility Kit 7.1"] Per impostare i parametri del driver comuni a FC e NVMe.
. Aprire le proprietà MPIO.
. Dalla scheda *Discover Multi-paths*, aggiungere l'ID dispositivo elencato per NVMe.
+
MPIO è consapevole dei dispositivi NVMe, visibili sotto la gestione dei dischi.

. Aprire *Disk Management* e accedere a *Disk Properties*.
. Dalla scheda *MPIO*, selezionare *Dettagli*.
. Impostare le seguenti impostazioni di Microsoft DSM:
+
** PathVerifiedPeriod: *10*
** PathVerifyEnabled: *Enable*
** RetryCount: *6*
** RetryInterval: *1*
** PDORemovedPeriod: *130*


. Selezionare la policy MPIO *Round Robin with Subset*.
. Modificare i valori del Registro di sistema:
+
[listing]
----
HKLM\SYSTEM\CurrentControlSet\Services\mpio\Parameters\PathRecoveryInterval DWORD -> 30

HKLM\SYSTEM\CurrentControlSet\Services\mpio \Parameters\ UseCustomPathRecoveryInterval  DWORD-> 1
----
. Riavviare l'host.




== Validare NVMe/FC

Verificare che i sottosistemi NVMe siano stati rilevati e che gli spazi dei nomi ONTAP siano corretti per la configurazione NVMe-of.

.Fasi
. Verificare che "tipo di porta" sia `+FC+NVMe+`:
+
`listhba`

+
.Mostra esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
Port WWN       : 10:00:00:10:9b:1b:97:65
Node WWN       : 20:00:00:10:9b:1b:97:65
Fabric Name    : 10:00:c4:f5:7c:a5:32:e0
Flags          : 8000e300
Host Name      : INTEROP-57-159
Mfg            : Emulex Corporation
Serial No.     : FC71367217
Port Number    : 0
Mode           : Initiator
PCI Bus Number : 94
PCI Function   : 0
*Port Type*      : *FC+NVMe*
Model          : LPe32002-M2

Port WWN       : 10:00:00:10:9b:1b:97:66
Node WWN       : 20:00:00:10:9b:1b:97:66
Fabric Name    : 10:00:c4:f5:7c:a5:32:e0
Flags          : 8000e300
Host Name      : INTEROP-57-159
Mfg            : Emulex Corporation
Serial No.     : FC71367217
Port Number    : 1
Mode           : Initiator
PCI Bus Number : 94
PCI Function   : 1
Port Type      : FC+NVMe
Model          : LPe32002-M2
----
====
. Verificare che i sottosistemi NVMe/FC siano stati rilevati:
+
** `+nvme-list+`
+
.Mostra esempio
[%collapsible]
====
[listing]
----
NVMe Qualified Name     :  nqn.1992-08.com.netapp:sn.a3b74c32db2911eab229d039ea141105:subsystem.win_nvme_interop-57-159
Port WWN                :  20:09:d0:39:ea:14:11:04
Node WWN                :  20:05:d0:39:ea:14:11:04
Controller ID           :  0x0180
Model Number            :  NetApp ONTAP Controller
Serial Number           :  81CGZBPU5T/uAAAAAAAB
Firmware Version        :  FFFFFFFF
Total Capacity          :  Not Available
Unallocated Capacity    :  Not Available

NVMe Qualified Name     :  nqn.1992-08.com.netapp:sn.a3b74c32db2911eab229d039ea141105:subsystem.win_nvme_interop-57-159
Port WWN                :  20:06:d0:39:ea:14:11:04
Node WWN                :  20:05:d0:39:ea:14:11:04
Controller ID           :  0x0181
Model Number            :  NetApp ONTAP Controller
Serial Number           :  81CGZBPU5T/uAAAAAAAB
Firmware Version        :  FFFFFFFF
Total Capacity          :  Not Available
Unallocated Capacity    :  Not Available
Note: At present Namespace Management is not supported by NetApp Arrays.
----
====
** `nvme-list`
+
.Mostra esempio
[%collapsible]
====
[listing]
----
NVMe Qualified Name     :  nqn.1992-08.com.netapp:sn.a3b74c32db2911eab229d039ea141105:subsystem.win_nvme_interop-57-159
Port WWN                :  20:07:d0:39:ea:14:11:04
Node WWN                :  20:05:d0:39:ea:14:11:04
Controller ID           :  0x0140
Model Number            :  NetApp ONTAP Controller
Serial Number           :  81CGZBPU5T/uAAAAAAAB
Firmware Version        :  FFFFFFFF
Total Capacity          :  Not Available
Unallocated Capacity    :  Not Available

NVMe Qualified Name     :  nqn.1992-08.com.netapp:sn.a3b74c32db2911eab229d039ea141105:subsystem.win_nvme_interop-57-159
Port WWN                :  20:08:d0:39:ea:14:11:04
Node WWN                :  20:05:d0:39:ea:14:11:04
Controller ID           :  0x0141
Model Number            :  NetApp ONTAP Controller
Serial Number           :  81CGZBPU5T/uAAAAAAAB
Firmware Version        :  FFFFFFFF
Total Capacity          :  Not Available
Unallocated Capacity    :  Not Available

Note: At present Namespace Management is not supported by NetApp Arrays.
----
====


. Verificare che gli spazi dei nomi siano stati creati:
+
`+nvme-list-ns+`

+
.Mostra esempio
[%collapsible]
====
[listing]
----
Active Namespaces (attached to controller 0x0141):

                                       SCSI           SCSI           SCSI
   NSID           DeviceName        Bus Number    Target Number     OS LUN
-----------  --------------------  ------------  ---------------   ---------
0x00000001   \\.\PHYSICALDRIVE9         0               1              0
0x00000002   \\.\PHYSICALDRIVE10        0               1              1
0x00000003   \\.\PHYSICALDRIVE11        0               1              2
0x00000004   \\.\PHYSICALDRIVE12        0               1              3
0x00000005   \\.\PHYSICALDRIVE13        0               1              4
0x00000006   \\.\PHYSICALDRIVE14        0               1              5
0x00000007   \\.\PHYSICALDRIVE15        0               1              6
0x00000008   \\.\PHYSICALDRIVE16        0               1              7

----
====

