---
sidebar: sidebar 
permalink: nvme-rockylinux-89.html 
keywords: nvme, linux, rocky linux, enterprise 
summary: 'Come configurare l"host NVMe-oF per Rocky Linux 8.9 con ONTAP' 
---
= Configurare Rocky Linux 8.9 con NVMe-oF per l'archiviazione ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Gli host Rocky Linux 8.9 supportano i protocolli NVMe/FC e NVMe/TCP con Asymmetric Namespace Access (ANA). ANA è equivalente al multipathing ALUA (Asymmetric Logical Unit Access) negli ambienti iSCSI e FCP ed è implementato utilizzando la funzionalità multipath NVMe integrata nel kernel.

Per ulteriori informazioni sulle configurazioni supportate, vedere link:https://mysupport.netapp.com/matrix/["Tool di matrice di interoperabilità"^].

.A proposito di questa attività
È possibile utilizzare il supporto e le funzionalità seguenti con la configurazione host NVMe-oF per Rocky Linux 8.9. Prima di avviare il processo di configurazione, è inoltre necessario esaminare le limitazioni note.

* Supporto disponibile:
+
** Supporto di NVMe over TCP (NVMe/TCP) oltre a NVMe over Fibre Channel (NVMe/FC). Il plug-in NetApp nel pacchetto nativo `nvme-cli` mostra i dettagli ONTAP per i namespace NVMe/FC e NVMe/TCP.
** Esecuzione di traffico NVMe e SCSI sullo stesso host. Ad esempio, è possibile configurare dm-multipath per i dispositivi SCSI mpath su LUN SCSI e utilizzare NVMe multipath per configurare i dispositivi dello spazio dei nomi NVMe-oF sull'host.


* Limitazioni note:
+
** Per impostazione predefinita, il multipath NVMe nel kernel è disabilitato per gli host Rocky Linux 8.9 NVMe-oF. Pertanto, è necessario attivarlo manualmente.
** Sugli host Rocky Linux 8.9, NVMe/TCP è una funzionalità di anteprima tecnologica a causa di problemi aperti. Per ulteriori informazioni, fare riferimento alla https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/8/html-single/8.9_release_notes/index#technology-preview_file-systems-and-storage["Note di rilascio di Rocky Linux 8.9"^] .
** L'avvio SAN che utilizza il protocollo NVMe-of non è attualmente supportato.






== Passaggio 1: Se lo si desidera, attivare l'avvio SAN

È possibile configurare l'host in modo che utilizzi l'avvio SAN per semplificare l'installazione e migliorare la scalabilità.

.Prima di iniziare
Utilizzare link:https://mysupport.netapp.com/matrix/#welcome["Tool di matrice di interoperabilità"^]per verificare che il sistema operativo Linux, l'HBA (host Bus Adapter), il firmware HBA, il BIOS di avvio HBA e la versione ONTAP supportino l'avvio SAN.

.Fasi
. https://docs.netapp.com/us-en/ontap/san-admin/create-nvme-namespace-subsystem-task.html["Crea uno spazio dei nomi di avvio SAN e mappalo all'host"^].
. Abilitare l'avvio SAN nel BIOS del server per le porte su cui è mappato lo spazio dei nomi di avvio SAN.
+
Per informazioni su come attivare il BIOS HBA, consultare la documentazione specifica del vendor.

. Verificare che la configurazione sia stata eseguita correttamente riavviando l'host e verificando che il sistema operativo sia attivo e funzionante.




== Passaggio 2: convalidare le versioni del software

Utilizzare la seguente procedura per convalidare le versioni minime supportate del software Rocky Linux 8.9.

.Fasi
. Installa Rocky Linux 8.9 sul server. Al termine dell'installazione, verifica di utilizzare il kernel Rocky Linux 8.9 specificato:
+
[source, cli]
----
uname -r
----
+
L'esempio seguente mostra una versione del kernel di Rocky Linux:

+
[listing]
----
5.14.0-570.12.1.el9_6.x86_64
----
. Installare `nvme-cli` pacchetto:
+
[source, cli]
----
rpm -qa|grep nvme-cli
----
+
L'esempio seguente mostra una versione del pacchetto nvme-cli:

+
[listing]
----
nvme-cli-2.11-5.el9.x86_64
----
. Installare `libnvme` pacchetto:
+
[source, cli]
----
rpm -qa|grep libnvme
----
+
L'esempio seguente mostra un  `libnvme` versione del pacchetto:

+
[listing]
----
libnvme-1.11.1-1.el9.x86_64
----
. Sull'host Rocky Linux, controlla la stringa hostnqn in  `/etc/nvme/hostnqn` :
+
[source, cli]
----
cat /etc/nvme/hostnqn
----
+
L'esempio seguente mostra un  `hostnqn` versione:

+
[listing]
----
nqn.2014-08.org.nvmexpress:uuid:4c4c4544-0056-5410-8048-b9c04f425633
----
. Verificare che il `hostnqn` la stringa corrisponde a. `hostnqn` Stringa per il sottosistema corrispondente sull'array ONTAP:
+
[source, cli]
----
::> vserver nvme subsystem host show -vserver vs_coexistence_LPE36002
----
+
.Mostra esempio
[%collapsible]
====
[listing]
----
Vserver Subsystem Priority  Host NQN
------- --------- --------  ------------------------------------------------
vs_coexistence_LPE36002
        nvme
                  regular   nqn.2014-08.org.nvmexpress:uuid:4c4c4544-0056-5410-8048-b9c04f425633
        nvme_1
                  regular   nqn.2014-08.org.nvmexpress:uuid:4c4c4544-0056-5410-8048-b9c04f425633
        nvme_2
                  regular   nqn.2014-08.org.nvmexpress:uuid:4c4c4544-0056-5410-8048-b9c04f425633
        nvme_3
                  regular   nqn.2014-08.org.nvmexpress:uuid:4c4c4544-0056-5410-8048-b9c04f425633
4 entries were displayed.
----
====
+

NOTE: Se il `hostnqn` le stringhe non corrispondono, utilizzare `vserver modify` per aggiornare `hostnqn` Stringa sul sottosistema di array ONTAP corrispondente a `hostnqn` stringa da `/etc/nvme/hostnqn` sull'host.





== Passaggio 3: configurare NVMe/FC

È possibile configurare NVMe/FC con adattatori FC Broadcom/Emulex FC o Marvell/Qlogic. È inoltre necessario rilevare manualmente i sottosistemi e gli spazi dei nomi NVMe/TCP.

[role="tabbed-block"]
====
.Broadcom/Emulex
Configurare NVMe/FC per un adattatore Broadcom/Emulex.

--
.Fasi
. Verificare di utilizzare il modello di adattatore supportato:
+
.. Visualizza i nomi dei modelli:
+
[source, cli]
----
cat /sys/class/scsi_host/host*/modelname
----
+
Viene visualizzato il seguente output:

+
[listing]
----
LPe36002-M64
LPe36002-M64
----
.. Visualizza le descrizioni dei modelli:
+
[source, cli]
----
cat /sys/class/scsi_host/host*/modeldesc
----
+
Dovresti vedere un output simile al seguente esempio:

+
[listing]
----
Emulex LightPulse LPe36002-M64 2-Port 64Gb Fibre Channel Adapter
Emulex LightPulse LPe36002-M64 2-Port 64Gb Fibre Channel Adapter
----


. Verificare di utilizzare il Broadcom consigliato `lpfc` firmware e driver della posta in arrivo:
+
.. Visualizza la versione del firmware:
+
[source, cli]
----
cat /sys/class/scsi_host/host*/fwrev
----
+
L'esempio seguente mostra le versioni del firmware:

+
[listing]
----
14.4.317.10, sli-4:6:d
14.4.317.10, sli-4:6:d
----
.. Visualizza la versione del driver in arrivo:
+
[source, cli]
----
cat /sys/module/lpfc/version`
----
+
L'esempio seguente mostra la versione del driver:

+
[listing]
----
0:14.4.0.2
----


+
Per l'elenco aggiornato dei driver della scheda di rete supportati e delle versioni del firmware, vedere link:https://mysupport.netapp.com/matrix/["Tool di matrice di interoperabilità"^].

. Verificare che l'output previsto di `lpfc_enable_fc4_type` sia impostato su `3`:
+
[source, cli]
----
cat /sys/module/lpfc/parameters/lpfc_enable_fc4_type
----
. Verificare che sia possibile visualizzare le porte dell'iniziatore:
+
[source, cli]
----
cat /sys/class/fc_host/host*/port_name
----
+
L'esempio seguente mostra le identità delle porte:

+
[listing]
----
0x100000109bf044b1
0x100000109bf044b2
----
. Verificare che le porte dell'iniziatore siano in linea:
+
[source, cli]
----
cat /sys/class/fc_host/host*/port_state
----
+
Viene visualizzato il seguente output:

+
[listing]
----
Online
Online
----
. Verificare che le porte iniziatore NVMe/FC siano abilitate e che le porte di destinazione siano visibili:
+
[source, cli]
----
cat /sys/class/scsi_host/host*/nvme_info
----
+
.Mostra esempio
[%collapsible]
=====
[listing, subs="+quotes"]
----
NVME Initiator Enabled
XRI Dist lpfc2 Total 6144 IO 5894 ELS 250
NVME LPORT lpfc2 WWPN x100000109bf044b1 WWNN x200000109bf044b1 DID x022a00 *ONLINE*
NVME RPORT       WWPN x202fd039eaa7dfc8 WWNN x202cd039eaa7dfc8 DID x021310 *TARGET DISCSRVC ONLINE*
NVME RPORT       WWPN x202dd039eaa7dfc8 WWNN x202cd039eaa7dfc8 DID x020b10 *TARGET DISCSRVC ONLINE*

NVME Statistics
LS: Xmt 0000000810 Cmpl 0000000810 Abort 00000000
LS XMIT: Err 00000000  CMPL: xb 00000000 Err 00000000
Total FCP Cmpl 000000007b098f07 Issue 000000007aee27c4 OutIO ffffffffffe498bd
        abort 000013b4 noxri 00000000 nondlp 00000058 qdepth 00000000 wqerr 00000000 err 00000000
FCP CMPL: xb 000013b4 Err 00021443

NVME Initiator Enabled
XRI Dist lpfc3 Total 6144 IO 5894 ELS 250
NVME LPORT lpfc3 WWPN x100000109bf044b2 WWNN x200000109bf044b2 DID x021b00 *ONLINE*
NVME RPORT       WWPN x2033d039eaa7dfc8 WWNN x202cd039eaa7dfc8 DID x020110 *TARGET DISCSRVC ONLINE*
NVME RPORT       WWPN x2032d039eaa7dfc8 WWNN x202cd039eaa7dfc8 DID x022910 *TARGET DISCSRVC ONLINE*

NVME Statistics
LS: Xmt 0000000840 Cmpl 0000000840 Abort 00000000
LS XMIT: Err 00000000  CMPL: xb 00000000 Err 00000000
Total FCP Cmpl 000000007afd4434 Issue 000000007ae31b83 OutIO ffffffffffe5d74f
        abort 000014a5 noxri 00000000 nondlp 0000006a qdepth 00000000 wqerr 00000000 err 00000000
FCP CMPL: xb 000014a5 Err 0002149a
----
=====


--
.Marvell/QLogic
--
Configurare NVMe/FC per un adattatore Marvell/QLogic.


NOTE: Il driver nativo qla2xxx della posta in arrivo incluso nel kernel di Rocky Linux dispone delle correzioni più recenti. Queste correzioni sono essenziali per il supporto di ONTAP.

.Fasi
. Verificare che siano in esecuzione le versioni del firmware e del driver dell'adattatore supportate:
+
[source, cli]
----
cat /sys/class/fc_host/host*/symbolic_name
----
+
L'esempio seguente mostra le versioni del driver e del firmware:

+
[listing]
----
QLE2742 FW:v9.14.00 DVR:v10.02.09.200-k
QLE2742 FW:v9.14.00 DVR:v10.02.09.200-k
----
. Verificare che `ql2xnvmeenable` è impostato. Ciò consente all'adattatore Marvell di funzionare come iniziatore NVMe/FC:
+
[source, cli]
----
cat /sys/module/qla2xxx/parameters/ql2xnvmeenable
----
+
L'uscita prevista è 1.



--
====


== Passaggio 4: facoltativamente, abilitare 1 MB I/O

È possibile abilitare richieste di I/O di dimensione pari a 1 MB per NVMe/FC configurate con una scheda Broadcom. ONTAP segnala una dimensione massima di trasferimento dati (MDTS) di 8 nei dati di Identify Controller. Ciò significa che le dimensioni massime delle richieste i/o possono essere fino a 1MB MB. Per inviare richieste di I/O di dimensione pari a 1 MB, è necessario aumentare il valore lpfc del parametro  `lpfc_sg_seg_cnt` parametro a 256 dal valore predefinito di 64.


NOTE: Questi passaggi non si applicano agli host Qlogic NVMe/FC.

.Fasi
. Impostare il `lpfc_sg_seg_cnt` parametro su 256:
+
[listing]
----
cat /etc/modprobe.d/lpfc.conf
----
+
[listing]
----
options lpfc lpfc_sg_seg_cnt=256
----
. Eseguire il `dracut -f` comando e riavviare l'host.
. Verificare che il valore per `lpfc_sg_seg_cnt` sia 256:
+
[listing]
----
cat /sys/module/lpfc/parameters/lpfc_sg_seg_cnt
----




== Passaggio 5: configurare NVMe/TCP

Il protocollo NVMe/TCP non supporta tale `auto-connect` operazione. Invece, puoi rilevare i sottosistemi NVMe/TCP e gli spazi dei nomi eseguendo manualmente le operazioni NVMe/TCP `connect` o `connect-all` .



== Passaggio 6: convalida NVMe-oF

Verificare che lo stato multipath NVMe in-kernel, lo stato ANA e i namespace ONTAP siano corretti per la configurazione NVMe-of.

.Fasi
. Verificare che il multipath NVMe nel kernel sia attivato:
+
[source, cli]
----
cat /sys/module/nvme_core/parameters/multipath
----
+
Viene visualizzato il seguente output:

+
[listing]
----
Y
----
. Verificare che le impostazioni NVMe-of appropriate (ad esempio, modello impostato su controller NetApp ONTAP e ipopolicy per il bilanciamento del carico impostato su round-robin) per i rispettivi spazi dei nomi ONTAP si riflettano correttamente sull'host:
+
.. Visualizza i sottosistemi:
+
[source, cli]
----
cat /sys/class/nvme-subsystem/nvme-subsys*/model
----
+
Viene visualizzato il seguente output:

+
[listing]
----
NetApp ONTAP Controller
NetApp ONTAP Controller
----
.. Visualizza la politica:
+
[source, cli]
----
cat /sys/class/nvme-subsystem/nvme-subsys*/iopolicy
----
+
Viene visualizzato il seguente output:

+
[listing]
----
round-robin
round-robin
----


. Verificare che gli spazi dei nomi siano stati creati e rilevati correttamente sull'host:
+
[source, cli]
----
nvme list
----
+
.Mostra esempio
[%collapsible]
====
[listing]
----
Node         SN                   Model
---------------------------------------------------------
/dev/nvme4n1 81Ix2BVuekWcAAAAAAAB	NetApp ONTAP Controller


Namespace Usage    Format             FW             Rev
-----------------------------------------------------------
1                 21.47 GB / 21.47 GB	4 KiB + 0 B   FFFFFFFF
----
====




== Fase 7: Esaminare i problemi noti

La configurazione host NVMe-oF per Rocky Linux 8.9 con versione ONTAP presenta il seguente problema noto:

[cols="20,40,40"]
|===
| ID bug NetApp | Titolo | Descrizione 


| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/BURT/1479047["1479047"^] | Gli host Rocky Linux 8.9 NVMe-oF creano controller di rilevamento persistenti duplicati | Sugli host NVMe over Fabrics (NVMe-of), è possibile utilizzare il comando "nvme Discover -p" per creare controller di rilevamento persistenti (PDC). Quando si utilizza questo comando, è necessario creare un solo PDC per ogni combinazione initiator-target. Tuttavia, se si esegue Rocky Linux 8.9 su un host NVMe-oF, viene creato un PDC duplicato ogni volta che viene eseguito "nvme discover -p". Ciò comporta un utilizzo non necessario delle risorse sia sull'host che sulla destinazione. 
|===