---
sidebar: sidebar 
permalink: nvme_sles15_sp6.html 
keywords: nvme, linux, suse, sles, 15, SP6, server, enterprise 
summary: Viene descritto come configurare NVMe/FC per SUSE Linux Enterprise Server 15 SP6 con ONTAP. 
---
= Configurazione host NVMe-of per SUSE Linux Enterprise Server 15 SP6 con ONTAP
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
NVMe over Fabrics (NVMe-of), incluso NVMe over Fibre Channel (NVMe/FC) e altri tipi di trasporto, è supportato per SUSE Linux Enterprise Server 15 SP6 con Asymmetric Namespace Access (ANA). Negli ambienti NVMe-of, ANA è l'equivalente del multipathing ALUA in ambienti iSCSI e FCP ed è implementato con multipath NVMe nel kernel.

È disponibile il seguente supporto per la configurazione host NVMe-of per SUSE Linux Enterprise Server 15 SP6 con ONTAP:

* Esecuzione di traffico NVMe e SCSI sullo stesso host. Ad esempio, è possibile configurare dm-multipath per i dispositivi SCSI per i LUN SCSI `mpath` e utilizzare NVMe Multipath per configurare i dispositivi con namespace NVMe-of sull'host.
* Supporto di NVMe over TCP (NVMe/TCP) e NVMe/FC. In questo modo, il plug-in NetApp nel pacchetto nativo `nvme-cli` ha la capacità di visualizzare i dettagli ONTAP per i namespace sia NVMe/FC che NVMe/TCP.


Per ulteriori informazioni sulle configurazioni supportate, vedere link:https://mysupport.netapp.com/matrix/["Tool di matrice di interoperabilità"^].



== Caratteristiche

* Supporto per l'autenticazione NVMe sicura e in-band
* Supporto per controller di rilevamento persistente (PDC) utilizzando un NQN di rilevamento univoco
* Supporto crittografia TLS 1,3 per NVMe/TCP




== Limitazioni note

* L'avvio SAN che utilizza il protocollo NVMe-of non è attualmente supportato.
* Il supporto dell'utilità host NetApp `sanlun` non è disponibile per NVMe-of su un host SUSE Linux Enterprise Server 15 SP6. Potrai invece fare affidamento sul plug-in NetApp incluso nel pacchetto nativo `nvme-cli` per tutti i trasporti NVMe-of.




== Configurare NVMe/FC

È possibile configurare NVMe/FC con adattatori FC Broadcom/Emulex o Marvell/Qlogic per SUSE Linux Enterprise Server 15 SP6 con configurazione ONTAP.

[role="tabbed-block"]
====
.Broadcom/Emulex
--
Configurare NVMe/FC per un adattatore FC Broadcom/Emulex.

.Fasi
. Verificare di utilizzare il modello di scheda consigliato:
+
[listing]
----
cat /sys/class/scsi_host/host*/modelname
----
+
.Output di esempio
[listing]
----
LPe32002 M2
LPe32002-M2
----
. Verificare la descrizione del modello dell'adattatore:
+
[listing]
----
cat /sys/class/scsi_host/host*/modeldesc
----
+
.Output di esempio
[listing]
----
Emulex LightPulse LPe32002-M2 2-Port 32Gb Fibre Channel Adapter
Emulex LightPulse LPe32002-M2 2-Port 32Gb Fibre Channel Adapter
----
. Verificare che si stiano utilizzando le versioni del firmware dell'HBA (host Bus Adapter) Emulex consigliate:
+
[listing]
----
cat /sys/class/scsi_host/host*/fwrev
----
+
.Output di esempio
[listing]
----
14.2.673.40, sli-4:2:c
14.2.673.40, sli-4:2:c
----
. Verificare di utilizzare la versione consigliata del driver LPFC:
+
[listing]
----
cat /sys/module/lpfc/version
----
+
.Output di esempio
[listing]
----
0:14.4.0.1
----
. Verificare che sia possibile visualizzare le porte dell'iniziatore:
+
[listing]
----
cat /sys/class/fc_host/host*/port_name
----
+
.Output di esempio
[listing]
----
0x10000090fae0ec88
0x10000090fae0ec89
----
. Verificare che le porte dell'iniziatore siano in linea:
+
[listing]
----
cat /sys/class/fc_host/host*/port_state
----
+
.Output di esempio
[listing]
----
Online
Online
----
. Verificare che le porte iniziatore NVMe/FC siano abilitate e che le porte di destinazione siano visibili:
+
[listing]
----
cat /sys/class/scsi_host/host*/nvme_info
----
+
Nell'esempio seguente, una porta iniziatore è abilitata e connessa con due LIF di destinazione.

+
.Mostra output di esempio
[%collapsible]
=====
[listing, subs="+quotes"]
----
NVME Initiator Enabled
XRI Dist lpfc0 Total 6144 IO 5894 ELS 250
NVME LPORT lpfc0 WWPN x10000090fae0ec88 WWNN x20000090fae0ec88 DID x0a1300 *ONLINE*
NVME RPORT WWPN x2070d039ea359e4a WWNN x206bd039ea359e4a DID x0a0a05 *TARGET DISCSRVC
ONLINE*
NVME Statistics
LS: Xmt 00000003ba Cmpl 00000003ba Abort 00000000
LS XMIT: Err 00000000 CMPL: xb 00000000 Err 00000000
Total FCP Cmpl 0000000014e3dfb8 Issue 0000000014e308db OutIO ffffffffffff2923
 abort 00000845 noxri 00000000 nondlp 00000063 qdepth 00000000 wqerr 00000003 err 00000000
FCP CMPL: xb 00000847 Err 00027f33
NVME Initiator Enabled
XRI Dist lpfc1 Total 6144 IO 5894 ELS 250
NVME LPORT lpfc1 WWPN x10000090fae0ec89 WWNN x20000090fae0ec89 DID x0a1200 *ONLINE*
NVME RPORT WWPN x2071d039ea359e4a WWNN x206bd039ea359e4a DID x0a0305 *TARGET DISCSRVC
ONLINE*
NVME Statistics
LS: Xmt 00000003ba Cmpl 00000003ba Abort 00000000
LS XMIT: Err 00000000 CMPL: xb 00000000 Err 00000000
Total FCP Cmpl 0000000014e39f78 Issue 0000000014e2b832 OutIO ffffffffffff18ba
 abort 0000082d noxri 00000000 nondlp 00000028 qdepth 00000000 wqerr 00000007 err 00000000
FCP CMPL: xb 0000082d Err 000283bb
----
=====


--
.Marvell/QLogic
--
Il driver inbox qla2xxx nativo incluso nel kernel di SUSE Linux Enterprise Server 15 SP6 presenta le correzioni più recenti. Queste correzioni sono essenziali per il supporto di ONTAP.

Configurare NVMe/FC per un adattatore Marvell/QLogic.

.Fasi
. Verificare che siano in esecuzione le versioni del firmware e del driver dell'adattatore supportate:
+
[listing]
----
cat /sys/class/fc_host/host*/symbolic_name
----
+
.Output di esempio
[listing]
----
QLE2742 FW:v9.14.01 DVR: v10.02.09.200-k
QLE2742 FW:v9.14.01 DVR: v10.02.09.200-k
----
. Verificare che il `ql2xnvmeenable` il parametro è impostato su 1:
+
[listing]
----
cat /sys/module/qla2xxx/parameters/ql2xnvmeenable
----
+
Il valore previsto è 1.



--
====


=== Abilita dimensione i/o 1 MB (opzionale)

ONTAP segnala una dimensione massima di trasferimento dati (MDTS) pari a 8 nei dati Identify Controller.  Ciò significa che la dimensione massima della richiesta di I/O può arrivare fino a 1 MB.  Per emettere richieste di I/O di dimensione 1 MB per un host Broadcom NVMe/FC, è necessario aumentare il `lpfc` valore del `lpfc_sg_seg_cnt` parametro a 256 dal valore predefinito di 64.


NOTE: Questi passaggi non si applicano agli host Qlogic NVMe/FC.

.Fasi
. Impostare il `lpfc_sg_seg_cnt` parametro su 256:
+
[source, cli]
----
cat /etc/modprobe.d/lpfc.conf
----
+
Dovresti vedere un output simile al seguente esempio:

+
[listing]
----
options lpfc lpfc_sg_seg_cnt=256
----
. Eseguire il `dracut -f` comando e riavviare l'host.
. Verificare che il valore per `lpfc_sg_seg_cnt` sia 256:
+
[source, cli]
----
cat /sys/module/lpfc/parameters/lpfc_sg_seg_cnt
----




=== Verifica dei servizi NVMe

A partire da SUSE Linux Enterprise Server 15 SP6, i `nvmefc-boot-connections.service` servizi di avvio e `nvmf-autoconnect.service` inclusi nel pacchetto NVMe/FC `nvme-cli` sono automaticamente abilitati all'avvio durante l'avvio del sistema. Al termine dell'avvio del sistema, è necessario verificare che i servizi di avvio siano stati abilitati.

.Fasi
. Verificare che `nvmf-autoconnect.service` sia attivato:
+
`systemctl status nvmf-autoconnect.service`

+
.Mostra output di esempio
[%collapsible]
====
[listing]
----
nvmf-autoconnect.service - Connect NVMe-oF subsystems automatically during boot
  Loaded: loaded (/usr/lib/systemd/system/nvmf-autoconnect.service; enabled; vendor preset: disabled)
  Active: inactive (dead) since Thu 2024-05-25 14:55:00 IST; 11min ago
Process: 2108 ExecStartPre=/sbin/modprobe nvme-fabrics (code=exited, status=0/SUCCESS)
Process: 2114 ExecStart=/usr/sbin/nvme connect-all (code=exited, status=0/SUCCESS)
Main PID: 2114 (code=exited, status=0/SUCCESS)

systemd[1]: Starting Connect NVMe-oF subsystems automatically during boot...
nvme[2114]: traddr=nn-0x201700a098fd4ca6:pn-0x201800a098fd4ca6 is already connected
systemd[1]: nvmf-autoconnect.service: Deactivated successfully.
systemd[1]: Finished Connect NVMe-oF subsystems automatically during boot.
----
====
. Verificare che `nvmefc-boot-connections.service` sia attivato:
+
`systemctl status nvmefc-boot-connections.service`

+
.Mostra output di esempio
[%collapsible]
====
[listing]
----
nvmefc-boot-connections.service - Auto-connect to subsystems on FC-NVME devices found during boot
   Loaded: loaded (/usr/lib/systemd/system/nvmefc-boot-connections.service; enabled; vendor preset: enabled)
   Active: inactive (dead) since Thu 2024-05-25 14:55:00 IST; 11min ago
 Main PID: 1647 (code=exited, status=0/SUCCESS)

systemd[1]: Starting Auto-connect to subsystems on FC-NVME devices found during boot...
systemd[1]: nvmefc-boot-connections.service: Succeeded.
systemd[1]: Finished Auto-connect to subsystems on FC-NVME devices found during boot.
----
====




== Configurare NVMe/TCP

NVMe/TCP non dispone di funzionalità di connessione automatica. Invece, puoi rilevare i sottosistemi NVMe/TCP e gli spazi dei nomi eseguendo manualmente le operazioni NVMe/TCP `connect` o `connect-all` .

.Fasi
. Verificare che la porta iniziatore possa recuperare i dati della pagina del registro di rilevamento attraverso le LIF NVMe/TCP supportate:
+
[listing]
----
nvme discover -t tcp -w <host-traddr> -a <traddr>
----
+
.Mostra output di esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
Discovery Log Number of Records 8, Generation counter 18
=====Discovery Log Entry 0======
trtype: tcp
adrfam: ipv4
subtype: *current discovery subsystem*
treq: not specified
portid: 4
trsvcid: 8009
subnqn: nqn.1992-08.com.netapp:sn.8b5ee9199ff411eea468d039ea36a106:discovery
traddr: 192.168.211.67
eflags: *explicit discovery connections, duplicate discovery information*
sectype: *none*
=====Discovery Log Entry 1======
trtype: tcp
adrfam: ipv4
subtype: *current discovery subsystem*
treq: not specified
portid: 2
trsvcid: 8009
subnqn: nqn.1992-08.com.netapp:sn.8b5ee9199ff411eea468d039ea36a106:discovery
traddr: 192.168.111.67
eflags: *explicit discovery connections, duplicate discovery information*
sectype: *none*
=====Discovery Log Entry 2======
trtype: tcp
adrfam: ipv4
subtype: *current discovery subsystem*
treq: not specified
portid: 3
trsvcid: 8009
subnqn: nqn.1992-08.com.netapp:sn.8b5ee9199ff411eea468d039ea36a106:discovery
traddr: 192.168.211.66
eflags: *explicit discovery connections, duplicate discovery information*
sectype: *none*
=====Discovery Log Entry 3======
trtype: tcp
adrfam: ipv4
subtype: *current discovery subsystem*
treq: not specified
portid: 1
trsvcid: 8009
subnqn: nqn.1992-08.com.netapp:sn.8b5ee9199ff411eea468d039ea36a106:discovery
traddr: 192.168.111.66
eflags: *explicit discovery connections, duplicate discovery information*
sectype: *none*
=====Discovery Log Entry 4======
trtype: tcp
adrfam: ipv4
subtype: nvme subsystem
treq: not specified
portid: 4
trsvcid: 4420
subnqn: nqn.1992-08.com.netapp:sn.8b5ee9199ff411eea468d039ea36a106:subsystem.nvme_tcp_1
traddr: 192.168.211.67
eflags: none
sectype: none
=====Discovery Log Entry 5======
trtype: tcp
adrfam: ipv4
subtype: nvme subsystem
treq: not specified
portid: 2
trsvcid: 4420
subnqn: nqn.1992-08.com.netapp:sn.8b5ee9199ff411eea468d039ea36a106:subsystem.nvme_tcp_1
traddr: 192.168.111.67
eflags: none
sectype: none
=====Discovery Log Entry 6======
trtype: tcp
adrfam: ipv4
subtype: nvme subsystem
treq: not specified
portid: 3
trsvcid: 4420
subnqn: nqn.1992-08.com.netapp:sn.8b5ee9199ff411eea468d039ea36a106:subsystem.nvme_tcp_1
traddr: 192.168.211.66
eflags: none
sectype: none
=====Discovery Log Entry 7======
trtype: tcp
adrfam: ipv4
subtype: nvme subsystem
treq: not specified
portid: 1
trsvcid: 4420
subnqn: nqn.1992-08.com.netapp:sn.8b5ee9199ff411eea468d039ea36a106:subsystem.nvme_tcp_1
traddr: 192.168.111.66
eflags: none
sectype: none
----
====
. Verifica che tutte le altre combinazioni di LIF iniziatore NVMe/TCP siano in grado di recuperare con successo i dati della pagina del log di rilevamento:
+
[listing]
----
nvme discover -t tcp -w <host-traddr> -a <traddr>
----
+
.Output di esempio
[listing]
----
nvme discover -t tcp -w 192.168.111.79 -a 192.168.111.66
nvme discover -t tcp -w 192.168.111.79 -a 192.168.111.67
nvme discover -t tcp -w 192.168.211.79 -a 192.168.211.66
nvme discover -t tcp -w 192.168.211.79 -a 192.168.211.67
----
. Eseguire `nvme connect-all` Command tra tutti i LIF target initiator NVMe/TCP supportati nei nodi:
+
[listing]
----
nvme connect-all -t tcp -w <host-traddr> -a <traddr>
----
+
.Output di esempio
[listing]
----
nvme connect-all -t tcp -w 192.168.111.79 -a 192.168.111.66
nvme connect-all -t tcp -w 192.168.111.79 -a 192.168.111.67
nvme connect-all -t tcp -w 192.168.211.79 -a 192.168.211.66
nvme connect-all -t tcp -w 192.168.211.79 -a 192.168.211.67
----
+

NOTE: A partire da SUSE Linux Enterprise Server 15 SP6, l'impostazione predefinita per il timeout NVMe/TCP `ctrl-loss-tmo` è disattivata. Ciò significa che non esiste alcun limite al numero di tentativi (tentativi indefiniti) e non è necessario configurare manualmente una durata di timeout specifica `ctrl-loss-tmo` quando si utilizzano i `nvme connect` comandi o `nvme connect-all` (opzione `-l`). Inoltre, i controller NVMe/TCP non riscontrano timeout in caso di errore di percorso e rimangono connessi a tempo indeterminato.





== Validare NVMe-of

Utilizzare la seguente procedura per convalidare NVMe-of per una configurazione SUSE Linux Enterprise Server 15 SP6 con ONTAP.

.Fasi
. Verifica che il multipath NVMe in-kernel sia abilitato:
+
[listing]
----
cat /sys/module/nvme_core/parameters/multipath
----
+
Il valore previsto è "Y".

. Verificare che l'host disponga del modello di controller corretto per gli spazi dei nomi ONTAP NVMe:
+
[listing]
----
cat /sys/class/nvme-subsystem/nvme-subsys*/model
----
+
.Output di esempio
[listing]
----
NetApp ONTAP Controller
NetApp ONTAP Controller
----
. Verifica della policy i/o NVMe per il rispettivo controller i/o ONTAP NVMe:
+
[listing]
----
cat /sys/class/nvme-subsystem/nvme-subsys*/iopolicy
----
+
.Output di esempio
[listing]
----
round-robin
round-robin
----
. Verificare che gli spazi dei nomi ONTAP siano visibili all'host:
+
[listing]
----
nvme list -v
----
+
.Mostra output di esempio
[%collapsible]
====
[listing]
----
Subsystem        Subsystem-NQN                                                                         Controllers
---------------- ------------------------------------------------------------------------------------- ---------------------
nvme-subsys0     nqn.1992- 08.com.netapp:sn.0501daf15dda11eeab68d039eaa7a232:subsystem.unidir_dhcha p  nvme0, nvme1, nvme2, nvme3

Device   SN                   MN                                       FR       TxPort Asdress        Subsystem    Namespaces
-------- -------------------- ---------------------------------------- -------- ---------------------------------------------
nvme0    81LGgBUqsI3EAAAAAAAE NetApp ONTAP Controller   FFFFFFFF tcp traddr=192.168.111.66,trsvcid=4420,host_traddr=192.168.111.79 nvme-subsys0 nvme0n1
nvme1    81LGgBUqsI3EAAAAAAAE NetApp ONTAP Controller   FFFFFFFF tcp traddr=192.168.111.67,trsvcid=4420,host_traddr=192.168.111.79 nvme-subsys0 nvme0n1
nvme2    81LGgBUqsI3EAAAAAAAE NetApp ONTAP Controller   FFFFFFFF tcp traddr=192.168.211.66,trsvcid=4420,host_traddr=192.168.211.79 nvme-subsys0 nvme0n1
nvme3    81LGgBUqsI3EAAAAAAAE NetApp ONTAP Controller   FFFFFFFF tcp traddr=192.168.211.67,trsvcid=4420,host_traddr=192.168.211.79 nvme-subsys0 nvme0n1
Device        Generic     NSID       Usage                 Format         Controllers
------------ ------------ ---------- -------------------------------------------------------------
/dev/nvme0n1 /dev/ng0n1   0x1     1.07  GB /   1.07  GB    4 KiB +  0 B   nvme0, nvme1, nvme2, nvme3
----
====
. Verificare che lo stato del controller di ciascun percorso sia attivo e che abbia lo stato ANA corretto:
+
[listing]
----
nvme list-subsys /dev/<subsystem_name>
----
+
[role="tabbed-block"]
====
.NVMe/FC
--
[listing]
----
nvme list-subsys /dev/nvme2n1
----
.Mostra output di esempio
[%collapsible]
=====
[listing, subs="+quotes"]
----
nvme-subsys2 - NQN=nqn.1992-
08.com.netapp:sn.06303c519d8411eea468d039ea36a106:subs
ystem.nvme
 hostnqn=nqn.2014-08.org.nvmexpress:uuid:4c4c4544-
0056-5410-8048-c6c04f425633
 iopolicy=round-robin
\
+- nvme4 *fc* traddr=nn-0x208fd039ea359e4a:pn-0x210dd039ea359e4a,host_traddr=nn-0x2000f4c7aa0cd7ab:pn-0x2100f4c7aa0cd7ab *live optimized*
+- nvme6 *fc* traddr=nn-0x208fd039ea359e4a:pn-0x210ad039ea359e4a,host_traddr=nn-0x2000f4c7aa0cd7aa:pn-0x2100f4c7aa0cd7aa *live optimized*

----
=====
--
.NVMe/TCP
--
[listing]
----
nvme list-subsys
----
.Mostra output di esempio
[%collapsible]
=====
[listing, subs="+quotes"]
----
nvme-subsys1 - NQN=nqn.1992-08.com.netapp:sn.8b5ee9199ff411eea468d039ea36a106:subsystem.nvme_tcp_1
 hostnqn=nqn.2014-08.org.nvmexpress:uuid:4c4c4544-0035-5910-804b-b2c04f444d33
 iopolicy=round-robin
\
+- nvme4 *tcp* traddr=192.168.111.66,trsvcid=4420,host_traddr=192.168.111.79,src_addr=192.168.111.79 *live*
+- nvme3 *tcp* traddr=192.168.211.66,trsvcid=4420,host_traddr=192.168.211.79,src_addr=192.168.111.79 *live*
+- nvme2 *tcp* traddr=192.168.111.67,trsvcid=4420,host_traddr=192.168.111.79,src_addr=192.168.111.79 *live*
+- nvme1 *tcp* traddr=192.168.211.67,trsvcid=4420,host_traddr=192.168.211.79,src_addr=192.168.111.79 *live*
----
=====
--
====
. Verificare che il plug-in NetApp visualizzi i valori corretti per ciascun dispositivo dello spazio dei nomi ONTAP:
+
[role="tabbed-block"]
====
.Colonna
--
[listing]
----
nvme netapp ontapdevices -o column
----
.Output di esempio
[listing]
----
Device           Vserver    Namespace Path                       NSID UUID                                   Size
---------------- ---------- ------------------------------------ ------------------------------------------- --------
/dev/nvme0n1     vs_192     /vol/fcnvme_vol_1_1_0/fcnvme_ns      1    c6586535-da8a-40fa-8c20-759ea0d69d33   20GB

----
--
.JSON
--
[listing]
----
nvme netapp ontapdevices -o json
----
.Mostra output di esempio
[%collapsible]
=====
[listing]
----
{
"ONTAPdevices":[
{
"Device":"/dev/nvme0n1",
"Vserver":"vs_192",
"Namespace_Path":"/vol/fcnvme_vol_1_1_0/fcnvme_ns",
"NSID":1,
"UUID":"c6586535-da8a-40fa-8c20-759ea0d69d33",
"Size":"20GB",
"LBA_Data_Size":4096,
"Namespace_Size":262144
}
]
}
----
=====
--
====




== Creare un controller di rilevamento permanente

A partire da ONTAP 9.11,1, è possibile creare un controller di rilevamento persistente (PDC) per un host SUSE Linux Enterprise Server 15 SP6. È necessario un PDC per rilevare automaticamente un'operazione di aggiunta o rimozione di un sottosistema NVMe e le modifiche ai dati della pagina del log di rilevamento.

.Fasi
. Verificare che i dati della pagina del log di rilevamento siano disponibili e possano essere recuperati attraverso la combinazione di porta Initiator e LIF di destinazione:
+
[listing]
----
nvme discover -t <trtype> -w <host-traddr> -a <traddr>
----
+
.Mostra output di esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
Discovery Log Number of Records 8, Generation counter 18
=====Discovery Log Entry 0======
trtype: tcp
adrfam: ipv4
subtype: *current discovery subsystem*
treq: not specified
portid: 4
trsvcid: 8009
subnqn: nqn.1992-08.com.netapp:sn.8b5ee9199ff411eea468d039ea36a106:discovery
traddr: 192.168.211.67
eflags: *explicit discovery connections, duplicate discovery information*
sectype: *none*
=====Discovery Log Entry 1======
trtype: tcp
adrfam: ipv4
subtype: *current discovery subsystem*
treq: not specified
portid: 2
trsvcid: 8009
subnqn: nqn.1992-08.com.netapp:sn.8b5ee9199ff411eea468d039ea36a106:discovery
traddr: 192.168.111.67
eflags: *explicit discovery connections, duplicate discovery information*
sectype: *none*
=====Discovery Log Entry 2======
trtype: tcp
adrfam: ipv4
subtype: *current discovery subsystem*
treq: not specified
portid: 3
trsvcid: 8009
subnqn: nqn.1992-08.com.netapp:sn.8b5ee9199ff411eea468d039ea36a106:discovery
traddr: 192.168.211.66
eflags: *explicit discovery connections, duplicate discovery information*
sectype: *none*
=====Discovery Log Entry 3======
trtype: tcp
adrfam: ipv4
subtype: *current discovery subsystem*
treq: *not specified*
portid: 1
trsvcid: 8009
subnqn: nqn.1992-08.com.netapp:sn.8b5ee9199ff411eea468d039ea36a106:discovery
traddr: 192.168.111.66
eflags: *explicit discovery connections, duplicate discovery information*
sectype: *none*
=====Discovery Log Entry 4======
trtype: tcp
adrfam: ipv4
subtype: nvme subsystem
treq: not specified
portid: 4
trsvcid: 4420
subnqn: nqn.1992-08.com.netapp:sn.8b5ee9199ff411eea468d039ea36a106:subsystem.nvme_tcp_1
traddr: 192.168.211.67
eflags: none
sectype: none
=====Discovery Log Entry 5======
trtype: tcp
adrfam: ipv4
subtype: nvme subsystem
treq: not specified
portid: 2
trsvcid: 4420
subnqn: nqn.1992-08.com.netapp:sn.8b5ee9199ff411eea468d039ea36a106:subsystem.nvme_tcp_1
traddr: 192.168.111.67
eflags: none
sectype: none
=====Discovery Log Entry 6======
trtype: tcp
adrfam: ipv4
subtype: nvme subsystem
treq: not specified
portid: 3
trsvcid: 4420
subnqn: nqn.1992-08.com.netapp:sn.8b5ee9199ff411eea468d039ea36a106:subsystem.nvme_tcp_1
traddr: 192.168.211.66
eflags: none
sectype: none
=====Discovery Log Entry 7======
trtype: tcp
adrfam: ipv4
subtype: nvme subsystem
treq: not specified
portid: 1
trsvcid: 4420
subnqn: nqn.1992-08.com.netapp:sn.8b5ee9199ff411eea468d039ea36a106:subsystem.nvme_tcp_1
traddr: 192.168.111.66
eflags: none
sectype: none

----
====
. Creare un PDC per il sottosistema di rilevamento:
+
[listing]
----
nvme discover -t <trtype> -w <host-traddr> -a <traddr> -p
----
+
.Output di esempio
[listing]
----
nvme discover -t tcp -w 192.168.111.79 -a 192.168.111.666 -p
----
. Dal controller ONTAP, verificare che il PDC sia stato creato:
+
[listing]
----
vserver nvme show-discovery-controller -instance -vserver <vserver_name>
----
+
.Mostra output di esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
vserver nvme show-discovery-controller -instance -vserver vs_nvme79
Vserver Name: vs_CLIENT116 Controller ID: 00C0h
Discovery Subsystem NQN: *nqn.1992-*
*08.com.netapp:sn.48391d66c0a611ecaaa5d039ea165514:discovery* Logical Interface UUID: d23cbb0a-c0a6-11ec-9731-d039ea165abc Logical Interface:
CLIENT116_lif_4a_1
Node: A400-14-124
Host NQN: nqn.2014-08.org.nvmexpress:uuid:12372496-59c4-4d1b-be09-74362c0c1afc
Transport Protocol: nvme-tcp
Initiator Transport Address: 192.168.1.16
Host Identifier: 59de25be738348f08a79df4bce9573f3 Admin Queue Depth: 32
Header Digest Enabled: false Data Digest Enabled: false
Vserver UUID: 48391d66-c0a6-11ec-aaa5-d039ea165514
----
====




== Configurare l'autenticazione in banda protetta

A partire da ONTAP 9.12,1, l'autenticazione sicura in banda è supportata su NVMe/TCP e NVMe/FC tra un host SUSE Linux Enterprise Server 15 SP6 e un controller ONTAP.

Per impostare l'autenticazione protetta, ogni host o controller deve essere associato a un `DH-HMAC-CHAP` Key, ossia una combinazione del NQN dell'host o controller NVMe e di un segreto di autenticazione configurato dall'amministratore. Per autenticare il proprio peer, un host o un controller NVMe deve riconoscere la chiave associata al peer.

È possibile impostare un'autenticazione protetta in banda utilizzando il CLI o un file JSON di configurazione. Se è necessario specificare chiavi dhchap diverse per sottosistemi diversi, è necessario utilizzare un file di configurazione JSON.

[role="tabbed-block"]
====
.CLI
--
Configurare l'autenticazione in banda protetta utilizzando la CLI.

.Fasi
. Ottenere l'NQN dell'host:
+
[listing]
----
cat /etc/nvme/hostnqn
----
. Generare la chiave dhchap per l'host SUSE Linux Enterprise Server 15 SP6.
+
L'output seguente descrive i `gen-dhchap-key` parametri dei comandi:

+
[listing]
----
nvme gen-dhchap-key -s optional_secret -l key_length {32|48|64} -m HMAC_function {0|1|2|3} -n host_nqn
•	-s secret key in hexadecimal characters to be used to initialize the host key
•	-l length of the resulting key in bytes
•	-m HMAC function to use for key transformation
0 = none, 1- SHA-256, 2 = SHA-384, 3=SHA-512
•	-n host NQN to use for key transformation
----
+
Nell'esempio seguente, viene generata una chiave casuale dhCHAP con HMAC impostato su 3 (SHA-512).

+
[listing]
----
nvme gen-dhchap-key -m 3 -n nqn.2014-08.org.nvmexpress:uuid:d3ca725a- ac8d-4d88-b46a-174ac235139b
DHHC-1:03:J2UJQfj9f0pLnpF/ASDJRTyILKJRr5CougGpGdQSysPrLu6RW1fGl5VSjbeDF1n1DEh3nVBe19nQ/LxreSBeH/bx/pU=:
----
. Sul controller ONTAP, aggiungere l'host e specificare entrambe le chiavi dhchap:
+
[listing]
----
vserver nvme subsystem host add -vserver <svm_name> -subsystem <subsystem> -host-nqn <host_nqn> -dhchap-host-secret <authentication_host_secret> -dhchap-controller-secret <authentication_controller_secret> -dhchap-hash-function {sha-256|sha-512} -dhchap-group {none|2048-bit|3072-bit|4096-bit|6144-bit|8192-bit}
----
. Un host supporta due tipi di metodi di autenticazione, unidirezionale e bidirezionale. Sull'host, connettersi al controller ONTAP e specificare le chiavi dhchap in base al metodo di autenticazione scelto:
+
[listing]
----
nvme connect -t tcp -w <host-traddr> -a <tr-addr> -n <host_nqn> -S <authentication_host_secret> -C <authentication_controller_secret>
----
. Convalidare `nvme connect authentication` comando verificando le chiavi dhchap dell'host e del controller:
+
.. Verificare le chiavi dhchap dell'host:
+
[listing]
----
cat /sys/class/nvme-subsystem/<nvme-subsysX>/nvme*/dhchap_secret
----
+
.Mostra output di esempio per una configurazione unidirezionale
[%collapsible]
=====
[listing]
----
cat /sys/class/nvme-subsystem/nvme-subsys1/nvme*/dhchap_secret
DHHC-1:03:je1nQCmjJLUKD62mpYbzlpuw0OIws86NB96uNO/t3jbvhp7fjyR9bIRjOHg8wQtye1JCFSMkBQH3pTKGdYR1OV9gx00=:
DHHC-1:03:je1nQCmjJLUKD62mpYbzlpuw0OIws86NB96uNO/t3jbvhp7fjyR9bIRjOHg8wQtye1JCFSMkBQH3pTKGdYR1OV9gx00=:
DHHC-1:03:je1nQCmjJLUKD62mpYbzlpuw0OIws86NB96uNO/t3jbvhp7fjyR9bIRjOHg8wQtye1JCFSMkBQH3pTKGdYR1OV9gx00=:
DHHC-1:03:je1nQCmjJLUKD62mpYbzlpuw0OIws86NB96uNO/t3jbvhp7fjyR9bIRjOHg8wQtye1JCFSMkBQH3pTKGdYR1OV9gx00=:
----
=====
.. Verificare i tasti dhchap del controller:
+
[listing]
----
cat /sys/class/nvme-subsystem/<nvme-subsysX>/nvme*/dhchap_ctrl_secret
----
+
.Mostra output di esempio per una configurazione bidirezionale
[%collapsible]
=====
[listing]
----
cat /sys/class/nvme-subsystem/nvme-subsys6/nvme*/dhchap_ctrl_secret
DHHC-1:03:WorVEV83eYO53kV4Iel5OpphbX5LAphO3F8fgH3913tlrkSGDBJTt3crXeTUB8fCwGbPsEyz6CXxdQJi6kbn4IzmkFU=:
DHHC-1:03:WorVEV83eYO53kV4Iel5OpphbX5LAphO3F8fgH3913tlrkSGDBJTt3crXeTUB8fCwGbPsEyz6CXxdQJi6kbn4IzmkFU=:
DHHC-1:03:WorVEV83eYO53kV4Iel5OpphbX5LAphO3F8fgH3913tlrkSGDBJTt3crXeTUB8fCwGbPsEyz6CXxdQJi6kbn4IzmkFU=:
DHHC-1:03:WorVEV83eYO53kV4Iel5OpphbX5LAphO3F8fgH3913tlrkSGDBJTt3crXeTUB8fCwGbPsEyz6CXxdQJi6kbn4IzmkFU=:
----
=====




--
.File JSON
--
Quando sulla configurazione del controller ONTAP sono disponibili più sottosistemi NVMe, è possibile utilizzare il `/etc/nvme/config.json` file con il `nvme connect-all` comando.

Per generare il file JSON, è possibile utilizzare l' `-o`opzione . Per ulteriori opzioni di sintassi, consultare le pagine del manuale di NVMe Connect-all.

.Fasi
. Configurare il file JSON:
+
.Mostra output di esempio
[%collapsible]
=====
[listing]
----
cat /etc/nvme/config.json
[
 {
    "hostnqn":"nqn.2014-08.org.nvmexpress:uuid:12372496-59c4-4d1b-be09-74362c0c1afc",
    "hostid":"3ae10b42-21af-48ce-a40b-cfb5bad81839",
    "dhchap_key":"DHHC-1:03:Cu3ZZfIz1WMlqZFnCMqpAgn/T6EVOcIFHez215U+Pow8jTgBF2UbNk3DK4wfk2EptWpna1rpwG5CndpOgxpRxh9m41w=:"
 },
 {
    "hostnqn":"nqn.2014-08.org.nvmexpress:uuid:12372496-59c4-4d1b-be09-74362c0c1afc",
    "subsystems":[
        {
            "nqn":"nqn.1992-08.com.netapp:sn.48391d66c0a611ecaaa5d039ea165514:subsystem.subsys_CLIENT116",
            "ports":[
               {
                    "transport":"tcp",
                    "traddr":" 192.168.111.66 ",
                    "host_traddr":" 192.168.111.79",
                    "trsvcid":"4420",
                    "dhchap_ctrl_key":"DHHC-
1:01:0h58bcT/uu0rCpGsDYU6ZHZvRuVqsYKuBRS0Nu0VPx5HEwaZ:"
               },
               {
                    "transport":"tcp",
                    "traddr":" 192.168.111.66 ",
                    "host_traddr":" 192.168.111.79",
                    "trsvcid":"4420",
                    "dhchap_ctrl_key":"DHHC-
1:01:0h58bcT/uu0rCpGsDYU6ZHZvRuVqsYKuBRS0Nu0VPx5HEwaZ:"
               },
               {
                    "transport":"tcp",
                   "traddr":" 192.168.111.66 ",
                    "host_traddr":" 192.168.111.79",
                    "trsvcid":"4420",
                    "dhchap_ctrl_key":"DHHC-
1:01:0h58bcT/uu0rCpGsDYU6ZHZvRuVqsYKuBRS0Nu0VPx5HEwaZ:"
               },
               {
                    "transport":"tcp",
                    "traddr":" 192.168.111.66 ",
                    "host_traddr":" 192.168.111.79",
                    "trsvcid":"4420",
                    "dhchap_ctrl_key":"DHHC-
1:01:0h58bcT/uu0rCpGsDYU6ZHZvRuVqsYKuBRS0Nu0VPx5HEwaZ:"
               }
           ]
       }
   ]
 }
]
----
+

=====
+

NOTE: Nell'esempio precedente, `dhchap_key` corrisponde a `dhchap_secret` e `dhchap_ctrl_key` corrisponde a `dhchap_ctrl_secret`.

. Connettersi al controller ONTAP utilizzando il file di configurazione JSON:
+
[listing]
----
nvme connect-all -J /etc/nvme/config.json
----
+
.Mostra output di esempio
[%collapsible]
=====
[listing]
----
traddr=192.168.111.66 is already connected
traddr=192.168.211.66 is already connected
traddr=192.168.111.66 is already connected
traddr=192.168.211.66 is already connected
traddr=192.168.111.66 is already connected
traddr=192.168.211.66 is already connected
traddr=192.168.111.67 is already connected
traddr=192.168.211.67 is already connected
traddr=192.168.111.67 is already connected
traddr=192.168.211.67 is already connected
traddr=192.168.111.67 is already connected
traddr=192.168.111.67 is already connected
----
=====
. Verificare che i segreti dhchap siano stati abilitati per i rispettivi controller per ciascun sottosistema:
+
.. Verificare le chiavi dhchap dell'host:
+
[listing]
----
cat /sys/class/nvme-subsystem/nvme-subsys0/nvme0/dhchap_secret
----
+
.Output di esempio
[listing]
----
DHHC-1:01:NunEWY7AZlXqxITGheByarwZdQvU4ebZg9HOjIr6nOHEkxJg:
----
.. Verificare i tasti dhchap del controller:
+
[listing]
----
cat /sys/class/nvme-subsystem/nvme-subsys0/nvme0/dhchap_ctrl_secret
----
+
.Output di esempio
[listing]
----
DHHC-
1:03:2YJinsxa2v3+m8qqCiTnmgBZoH6mIT6G/6f0aGO8viVZB4VLNLH4z8CvK7pVYxN6S5fOAtaU3DNi12rieRMfdbg3704=:
----




--
====


== Configurare Transport Layer Security

Transport Layer Security (TLS) fornisce una crittografia end-to-end sicura per le connessioni NVMe tra host NVMe-of e un array ONTAP. A partire da ONTAP 9.16,1, è possibile configurare TLS 1,3 utilizzando l'interfaccia CLI e una chiave precondivisa (PSK) configurata.

.A proposito di questa attività
Eseguire i passaggi descritti in questa procedura sull'host SUSE Linux Enterprise Server, tranne nei casi in cui è specificato che un passaggio deve essere eseguito sul controller ONTAP.

.Fasi
. Verificare che sul computer host siano installati i seguenti pacchetti ktls-utils, openssl e libopenssl:
+
.. `rpm -qa | grep ktls`
+
.Output di esempio
[listing]
----
ktls-utils-0.10+12.gc3923f7-150600.1.2.x86_64
----
.. `rpm -qa | grep ssl`
+
.Output di esempio
[listing]
----
openssl-3-3.1.4-150600.5.7.1.x86_64
libopenssl1_1-1.1.1w-150600.5.3.1.x86_64
libopenssl3-3.1.4-150600.5.7.1.x86_64
----


. Verificare di disporre della configurazione corretta per `/etc/tlshd.conf`:
+
[listing]
----
cat /etc/tlshd.conf
----
+
.Mostra output di esempio
[%collapsible]
====
[listing, subs="+quotes"]
----
[debug]
loglevel=0
tls=0
nl=0
[authenticate]
*keyrings=.nvme*
[authenticate.client]
#x509.truststore= <pathname>
#x509.certificate= <pathname>
#x509.private_key= <pathname>
[authenticate.server]
#x509.truststore= <pathname>
#x509.certificate= <pathname>
#x509.private_key= <pathname>
----
====
. Abilitare `tlshd` per l'avvio all'avvio del sistema:
+
[listing]
----
systemctl enable tlshd
----
. Verificare che il `tlshd` daemon sia in esecuzione:
+
[listing]
----
systemctl status tlshd
----
+
.Mostra output di esempio
[%collapsible]
====
[listing]
----
tlshd.service - Handshake service for kernel TLS consumers
   Loaded: loaded (/usr/lib/systemd/system/tlshd.service; enabled; preset: disabled)
   Active: active (running) since Wed 2024-08-21 15:46:53 IST; 4h 57min ago
     Docs: man:tlshd(8)
Main PID: 961 (tlshd)
   Tasks: 1
     CPU: 46ms
   CGroup: /system.slice/tlshd.service
       └─961 /usr/sbin/tlshd
Aug 21 15:46:54 RX2530-M4-17-153 tlshd[961]: Built from ktls-utils 0.11-dev on Mar 21 2024 12:00:00
----
====
. Generare TLS PSK utilizzando `nvme gen-tls-key` :
+
.. `cat /etc/nvme/hostnqn`
+
.Output di esempio
[listing]
----
nqn.2014-08.org.nvmexpress:uuid:e58eca24-faff-11ea-8fee-3a68dd3b5c5f
----
.. `nvme gen-tls-key --hmac=1 --identity=1 --subsysnqn=nqn.1992-08.com.netapp:sn.1d59a6b2416b11ef9ed5d039ea50acb3:subsystem.sles15`
+
.Output di esempio
[listing]
----
NVMeTLSkey-1:01:dNcby017axByCko8GivzOO9zGlgHDXJCN6KLzvYoA+NpT1uD:
----


. Sull'array ONTAP, aggiungere il TLS PSK al sottosistema ONTAP:
+
[listing]
----
vserver nvme subsystem host add -vserver sles15_tls -subsystem sles15 -host-nqn nqn.2014-08.org.nvmexpress:uuid:e58eca24-faff-11ea-8fee-3a68dd3b5c5f -tls-configured-psk NVMeTLSkey-1:01:dNcby017axByCko8GivzOO9zGlgHDXJCN6KLzvYoA+NpT1uD:
----
. Sull'host SUSE Linux Enterprise Server, inserire il TLS PSK nel portachiavi del kernel dell'host:
+
[listing]
----
nvme check-tls-key --identity=1 --subsysnqn =nqn.1992-08.com.netapp:sn.1d59a6b2416b11ef9ed5d039ea50acb3:subsystem.sles15 --keydata=NVMeTLSkey-1:01:dNcby017axByCko8GivzOO9zGlgHDXJCN6KLzvYoA+NpT1uD: --insert
----
+
.Output di esempio
[listing]
----
Inserted TLS key 22152a7e
----
+

NOTE: Il PSK viene visualizzato come "NVMe1R01" perché utilizza "Identity v1" dall'algoritmo di handshake TLS. Identity v1 è l'unica versione supportata da ONTAP.

. Verificare che TLS PSK sia inserito correttamente:
+
[listing]
----
cat /proc/keys | grep NVMe
----
+
.Output di esempio
[listing]
----
22152a7e I--Q---     1 perm 3b010000     0     0 psk       NVMe1R01 nqn.2014-08.org.nvmexpress:uuid:ffa0c815-e28b-4bb1-8d4c-7c6d5e610bfc nqn.1992-08.com.netapp:sn.1d59a6b2416b11ef9ed5d039ea50acb3:subsystem.sles15 UoP9dEfvuCUzzpS0DYxnshKDapZYmvA0/RJJ8JAqmAo=: 32
----
. Sull'host SUSE Linux Enterprise Server, connettersi al sottosistema ONTAP utilizzando il TLS PSK inserito:
+
.. `nvme connect -t tcp -w 20.20.10.80 -a 20.20.10.14 -n nqn.1992-08.com.netapp:sn.1d59a6b2416b11ef9ed5d039ea50acb3:subsystem.sles15 --tls_key=0x22152a7e --tls`
+
.Output di esempio
[listing]
----
connecting to device: nvme0
----
.. `nvme list-subsys`
+
.Output di esempio
[listing]
----
nvme-subsys0 - NQN=nqn.1992-08.com.netapp:sn.1d59a6b2416b11ef9ed5d039ea50acb3:subsystem.sles15
               hostnqn=nqn.2014-08.org.nvmexpress:uuid:ffa0c815-e28b-4bb1-8d4c-7c6d5e610bfc
               iopolicy=round-robin
\
 +- nvme0 tcp traddr=20.20.10.14,trsvcid=4420,host_traddr=20.20.10.80,src_addr=20.20.10.80 live
----


. Aggiungere la destinazione e verificare la connessione TLS al sottosistema ONTAP specificato:
+
`nvme subsystem controller show -vserver sles15_tls -subsystem sles15 -instance`

+
.Mostra output di esempio
[%collapsible]
====
[listing]
----
  (vserver nvme subsystem controller show)
                       Vserver Name: sles15_tls
                          Subsystem: sles15
                      Controller ID: 0040h
                  Logical Interface: sles15t_e1a_1
                               Node: A900-17-174
                           Host NQN: nqn.2014-08.org.nvmexpress:uuid:ffa0c815-e28b-4bb1-8d4c-7c6d5e610bfc
                 Transport Protocol: nvme-tcp
        Initiator Transport Address: 20.20.10.80
                    Host Identifier: ffa0c815e28b4bb18d4c7c6d5e610bfc
               Number of I/O Queues: 4
                   I/O Queue Depths: 128, 128, 128, 128
                  Admin Queue Depth: 32
              Max I/O Size in Bytes: 1048576
          Keep-Alive Timeout (msec): 5000
                       Vserver UUID: 1d59a6b2-416b-11ef-9ed5-d039ea50acb3
                     Subsystem UUID: 9b81e3c5-5037-11ef-8a90-d039ea50ac83
             Logical Interface UUID: 8185dcac-5035-11ef-8abb-d039ea50acb3
              Header Digest Enabled: false
                Data Digest Enabled: false
       Authentication Hash Function: -
Authentication Diffie-Hellman Group: -
                Authentication Mode: none
       Transport Service Identifier: 4420
                       TLS Key Type: configured
                   TLS PSK Identity: NVMe1R01 nqn.2014-08.org.nvmexpress:uuid:ffa0c815-e28b-4bb1-8d4c-7c6d5e610bfc nqn.1992-08.com.netapp:sn.1d59a6b2416b11ef9ed5d039ea50acb3:subsystem.sles15 UoP9dEfvuCUzzpS0DYxnshKDapZYmvA0/RJJ8JAqmAo=
                         TLS Cipher: TLS-AES-128-GCM-SHA256
----
====




== Problemi noti

Non ci sono problemi noti.
