---
settings:
  name: ONTAP SAN Host Utilities
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: it-it,us-en,de-de,es-es,fr-fr,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Host SAN e client cloud di ONTAP
    url: "/index.html"
  - title: Informazioni sulle configurazioni degli host SAN
    url: "/overview.html"
  - title: Installare LE utilità host SAN
    entries:
    - title: Informazioni sulle utilità host SAN
      url: "/hu_sanhost_index.html"
    - title: Utility host AIX
      entries:
      - title: Note di rilascio
        url: "/hu-aix-release-notes.html"
      - title: Installare le utilità host AIX
        entries:
        - title: Installa AIX Host Utilities 8.0
          url: "/hu-aix-80.html"
        - title: Installare le utilità host AIX 7,0
          url: "/hu-aix-70.html"
        - title: Installa AIX Host Utilities 6.1
          url: "/hu_aix_61.html"
      - title: Scopri di più sul kit di pedaggio AIX SAN
        url: "/hu-aix-san-toolkit.html"
      - title: Riferimento ai comandi di AIX Host Utilities
        url: "/hu-aix-command-reference.html"
    - title: Utility host HP-UX
      entries:
      - title: Note di rilascio
        url: "/hu-hpux-release-notes.html"
      - title: Installare le utilità host HP-UX 6,0
        url: "/hu_hpux_60.html"
      - title: Scopri di più sul SAN Toolkit
        url: "/hu-hpux-sanlun-toolkit.html"
      - title: Scopri di più sul riferimento ai comandi HP-UX
        url: "/hu_hpux_60_cmd.html"
    - title: Utility host Linux
      entries:
      - title: Note di rilascio
        url: "/hu-luhu-release-notes.html"
      - title: Installare le utilità host Linux
        entries:
        - title: Installa Linux Host Utilities 8.0
          url: "/hu-luhu-80.html"
        - title: Installare le utilità host Linux 7,1
          url: "/hu_luhu_71.html"
      - title: Scopri di più sull'utilità sanlun
        url: "/hu-luhu-sanlun-utility.html"
      - title: Riferimento ai comandi di Linux Host Utilities
        url: "/hu-luhu-command-reference.html"
    - title: Utility host Solaris
      entries:
      - title: Note di rilascio
        url: "/hu-solaris-release-notes.html"
      - title: Installare le utility host di Solaris
        entries:
        - title: Installa Solaris Host Utilities 8.0
          url: "/hu-solaris-80.html"
        - title: Installa Solaris Host Utilities 6.2
          url: "/hu_solaris_62.html"
      - title: Scopri di più sul SAN Toolkit
        url: "/hu-solaris-san-toolkit.html"
      - title: Scopri di più sul riferimento ai comandi Solaris
        url: "/hu-solaris-command-reference.html"
    - title: Utilità host Windows
      entries:
      - title: Note di rilascio
        url: "/hu-wuhu-release-notes.html"
      - title: Installare le utilità host di Windows
        entries:
        - title: Installa Windows Host Utilities 8.0
          url: "/hu-wuhu-80.html"
        - title: Installare le utilità host Windows 7,2
          url: "/hu_wuhu_72.html"
        - title: Installare le utilità host Windows 7,1
          url: "/hu_wuhu_71.html"
      - title: Esaminare la configurazione di Windows Host Utilities
        url: "/hu-wuhu-configuration.html"
      - title: Aggiornare le utilità host di Windows
        url: "/hu_wuhu_upgrade.html"
      - title: Riparare e rimuovere le utilità host di Windows
        url: "/hu_wuhu_repair_remove.html"
      - title: Risolvere i problemi
        url: "/hu_wuhu_troubleshoot.html"
  - title: Configurare gli host con FCP e iSCSI
    entries:
    - title: Panoramica
      url: "/hu_fcp_scsi_index.html"
    - title: AIX e PowerVM/VIOS
      entries:
      - title: 7.3/4.x
        url: "/hu-aix-73.html"
      - title: 7.2/3.1
        url: "/hu_aix_72.html"
      - title: '7.1'
        url: "/hu_aix_71.html"
    - title: CentOS
      entries:
      - title: CentOS 8.x
        url: "/hu-centos-8x.html"
    - title: Citrix
      entries:
      - title: Xenserver 8.4
        url: "/hu_citrix_84.html"
      - title: Hypervisor 8.2
        url: "/hu_citrix_82.html"
    - title: ESXi
      entries:
      - title: VMware vSphere 8
        url: "/hu_vsphere_8.html"
      - title: VMware vSphere 7
        url: "/hu_vsphere_7.html"
      - title: VMware vSphere 6.5 e 6.7
        url: "/hu_vsphere_6.html"
    - title: HP-UX
      entries:
      - title: 11i v3
        url: "/hu_hpux_11iv3.html"
    - title: Oracle Linux
      pdf-filename: OL-FCP
      entries:
      - title: 9.x
        url: "/hu-ol-9x.html"
      - title: 8.x
        url: "/hu-ol-8x.html"
    - title: Proxmox
      entries:
      - title: VE 9.x
        url: "/hu-proxmox-ve-9x.html"
      - title: VE 8.x
        url: "/hu-proxmox-ve-8x.html"
    - title: RHEL
      entries:
      - title: 10.x
        url: "/hu-rhel-10x.html"
        pdf-filename: RHEL-10-FCP
      - title: 9.x
        url: "/hu-rhel-9x.html"
        pdf-filename: RHEL-9-FCP
      - title: 8.x
        pdf-filename: RHEL-8-FCP
        url: "/hu-rhel-8x.html"
    - title: Rocky Linux
      entries:
      - title: 10.x
        pdf-filename: RL-10-FCP
        url: "/hu-rockylinux-10x.html"
      - title: 9.x
        pdf-filename: RL-9-FCP
        url: "/hu-rockylinux-9x.html"
      - title: 8.x
        pdf-filename: RL-8-FCP
        url: "/hu-rockylinux-8x.html"
    - title: Solaris
      entries:
      - title: '11.4'
        url: "/hu-solaris-114.html"
      - title: '11.3'
        url: "/hu_solaris_113.html"
    - title: SUSE Linux Enterprise Server
      entries:
      - title: SUSE Linux Enterprise Server 15
        pdf-filename: SLES-15-FCP
        url: "/hu-sles-15spx.html"
    - title: Ubuntu
      pdf-filename: Ubuntu-FCP
      entries:
      - title: '24,04'
        url: "/hu_ubuntu_2404.html"
      - title: '22.04'
        url: "/hu_ubuntu_2204.html"
      - title: '20,04'
        url: "/hu_ubuntu_2004.html"
    - title: Veritas
      entries:
      - title: Infoscale 9
        url: "/hu-veritas-9x.html"
      - title: Infobscale 8
        url: "/hu-veritas-8x.html"
      - title: Infobscale 7
        url: "/hu-veritas-7x.html"
      - title: Storage Foundation 6
        url: "/hu_veritas_6x.html"
    - title: Windows
      pdf-filename: Windows-FCP
      entries:
      - title: '2025'
        url: "/hu-windows-2025.html"
      - title: '2022'
        url: "/hu_windows_2022.html"
      - title: '2019'
        url: "/hu_windows_2019.html"
      - title: '2016'
        url: "/hu_windows_2016.html"
      - title: 2012 R2
        url: "/hu_windows_2012r2.html"
  - title: Configurare gli host con NVMe-of
    entries:
    - title: Scopri di più sulla configurazione degli host NVMe-oF
      url: "/hu-nvme-index.html"
    - title: AIX
      url: "/nvme-aix.html"
    - title: ESXi
      entries:
      - title: VMware vSphere 8
        url: "/nvme-esxi-8.html"
      - title: VMware vSphere 7
        url: "/nvme-esxi-7.html"
    - title: Oracle Linux
      pdf-filename: NVMeoF OL
      entries:
      - title: Supporto e funzionalità ONTAP
        url: "/nvme-ol-supported-features.html"
      - title: 9.x
        url: "/nvme-ol-9x.html"
      - title: 8.x
        url: "/nvme-ol-8x.html"
      - title: 7.x
        url: "/nvme-ol-7x.html"
    - title: Proxmox
      pdf-filename: NVMeoF Proxmox
      entries:
      - title: Supporto e funzionalità ONTAP
        url: "/nvme-proxmox-supported-features.html"
      - title: VE 9.x
        url: "/nvme-proxmox-ve-9x.html"
      - title: VE 8.x
        url: "/nvme-proxmox-ve-8x.html"
    - title: RHEL
      pdf-filename: NVMeoF RHEL
      entries:
      - title: Supporto e funzionalità ONTAP
        url: "/nvme-rhel-supported-features.html"
      - title: 10.x
        url: "/nvme-rhel-10x.html"
      - title: 9.x
        url: "/nvme-rhel-9x.html"
      - title: 8.x
        url: "/nvme-rhel-8x.html"
    - title: Rocky Linux
      entries:
      - title: Supporto e funzionalità ONTAP
        url: "/nvme-rockylinux-supported-features.html"
      - title: 10.x
        url: "/nvme-rockylinux-10x.html"
      - title: 9.x
        url: "/nvme-rockylinux-9x.html"
      - title: 8.x
        url: "/nvme-rockylinux-8x.html"
    - title: SUSE Linux Enterprise Server
      entries:
      - title: Supporto e funzionalità ONTAP
        url: "/nvme-sles-supported-features.html"
      - title: 15 SPx
        url: "/nvme-sles15-spx.html"
    - title: Ubuntu
      entries:
      - title: '24,04'
        url: "/nvme-ubuntu-2404.html"
      - title: '22.04'
        url: "/nvme-ubuntu-2204.html"
    - title: Windows
      entries:
      - title: '2025'
        url: "/nvme-windows-2025.html"
      - title: '2022'
        url: "/nvme-windows-2022.html"
      - title: '2019'
        url: "/nvme-windows-2019.html"
      - title: '2016'
        url: "/nvme-windows-2016.html"
      - title: 2012 R2
        url: "/nvme-windows-2012r2.html"
    - title: Risolvere i problemi
      url: "/troubleshoot.html"
  - title: Note legali
    url: "/legal-notices.html"
product-family:
  name: ONTAP
  repo: ontap-family
