= 
:allow-uri-read: 


. Se la configurazione di archiviazione include MetroCluster o SnapMirror ActiveSync, modifica le impostazioni predefinite:
+
[role="tabbed-block"]
====
.MetroCluster
--
Per impostazione predefinita, il sistema operativo AIX impone un timeout I/O più breve quando non sono disponibili percorsi verso una LUN.  Ciò potrebbe verificarsi in configurazioni che includono un fabric SAN a switch singolo e in configurazioni MetroCluster in cui si verificano failover non pianificati.  Per ulteriori informazioni e modifiche consigliate alle impostazioni predefinite, consultare l'articolo della Knowledge Baselink:https://kb.netapp.com/on-prem/ontap/mc/MC-KBs/What_are_AIX_Host_support_considerations_in_a_MetroCluster_configuration["Quali sono le considerazioni sul supporto dell'host AIX in una configurazione MetroCluster ?"^] .

--
.Sincronizzazione attiva SnapMirror
--
SnapMirror active sync è supportata per un host AIX. Il comportamento del supporto varia a seconda della release di ONTAP:

** A partire da ONTAP 9.19.1, la SnapMirror active sync è supportata nella configurazione Active/Active, consentendo operazioni di SnapMirror active sync non interruttive. Vedere l'articolo della Knowledge Base link:https://kb.netapp.com/on-prem/ontap/DP/SnapMirror/SnapMirror-KBs/SnapMirror_active_sync_support_for_AIX%3A_behavior_by_ONTAP_release_and_migration_guidance["SnapMirror supporto per la sincronizzazione attiva su AIX: comportamento per release ONTAP e guida alla migrazione"^].
** Per ONTAP 9.11.1 fino a 9.18.1, la sincronizzazione attiva di SnapMirror è supportata nella configurazione Active/Standby. Vedere l'articolo della Knowledge Base link:https://kb.netapp.com/on-prem/ontap/DP/SnapMirror/SnapMirror-KBs/How_to_configure_AIX_Host_for_SnapMirror_active_sync_in_ONTAP["Come configurare un host AIX per la SnapMirror active sync in ONTAP 9.11.1 a 9.18.1"^].


--
====

