= 
:allow-uri-read: 


Per verificare che il multipathing sia configurato correttamente per l'host, verificare che il `/etc/multipath.conf` file sia definito e che siano configurate le impostazioni consigliate da NetApp per i LUN ONTAP.

.Fasi
. Individua il file  `/etc/multipath.conf`.
+
Se il file di riferimento `/etc/multipath.conf` non contiene i parametri di configurazione specifici del dispositivo NetApp, aggiungili utilizzando il seguente file personalizzato `.conf drop-in`. Puoi trovare questo file in `/etc/multipath/conf.d/`:

+

NOTE: Non apportare modifiche al file  `/etc/multipath.conf` perché il contenuto del file potrebbe essere sovrascritto durante un aggiornamento di sistema.

+
.Mostra il contenuto del file
[%collapsible]
====
[source, cli]
----
$sudo tee -a /etc/multipath/conf.d/custom.conf >/dev/null <<'EOF'

defaults {
    polling_interval 5
}

blacklist {
    wwid <Insert_LUN_wwid_string>
    devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
    devnode "^hd[a-z]"
    devnode "^cciss.*"
}

devices {
    device {
    vendor "NETAPP"
    product "LUN.*"
    user_friendly_names no
    path_checker "tur"
    prio "ontap"
    detect_prio yes
    path_grouping_policy "group_by_prio"
    path_selector "service-time 0"
    failback immediate
    fast_io_fail_tmo 5
    dev_loss_tmo infinity
    no_path_retry queue
    features "3 queue_if_no_path pg_init_retries 50"
    flush_on_last_del yes
    hardware_handler "0"
    retain_attached_hw_handler yes
    rr_weight uniform
  }
}

EOF
----
====
. La prima volta che configuri il multipath, potresti dover abilitare e avviare i servizi multipath per caricare le impostazioni consigliate:
+
[source, cli]
----
systemctl enable multipathd
----
+
[source, cli]
----
systemctl start multipathd
----
. Ogni volta che avvii l'host, il file  `/etc/multipath/conf.d/custom.conf` carica automaticamente i parametri multipath consigliati da NetApp come impostazioni predefinite.
+
La tabella seguente mostra le impostazioni dei parametri multipercorso compilati dal sistema operativo Linux nativo per i LUN ONTAP.

+
.Mostra impostazioni parametri
[%collapsible]
====
[[multipath-parameter-settings]]
[cols="2"]
|===
| Parametro | Impostazione 


| detect_prio | sì 


| dev_loss_tmo | "infinito" 


| failback | immediato 


| fast_io_fail_tmo | 5 


| caratteristiche | "3 queue_if_no_path pg_init_retries 50" 


| flush_on_last_del | "sì" 


| gestore_hardware | "0" 


| no_path_retry | coda 


| path_checker | "a" 


| policy_di_raggruppamento_percorsi | "group_by_prio" 


| path_selector | "tempo di servizio 0" 


| intervallo_polling | 5 


| prio | "ONTAP" 


| prodotto | LUN 


| retain_attached_hw_handler | sì 


| peso_rr | "uniforme" 


| user_friendly_names | no 


| vendor | NETAPP 
|===
====
. Verificare le impostazioni dei parametri e lo stato del percorso dei LUN ONTAP:
+
[source, cli]
----
/sbin/mpathutil status
----
+
I parametri multipath predefiniti supportano le configurazioni ASA, AFF e FAS . In queste configurazioni, una singola LUN ONTAP non dovrebbe richiedere più di quattro percorsi. Avere più di quattro percorsi può causare problemi in caso di guasto dell'archiviazione.

+
I seguenti output di esempio mostrano le impostazioni corrette dei parametri e lo stato del percorso per i LUN ONTAP in una configurazione ASA, AFF o FAS.

+
[role="tabbed-block"]
====
.Configurazione ASA
--
Una configurazione ASA ottimizza tutti i percorsi verso una determinata LUN, mantenendoli attivi. In questo modo, le performance vengono migliorate grazie alle operazioni di i/o in tutti i percorsi contemporaneamente.

.Mostra esempio
[%collapsible]
=====
[listing]
----
/usr/sbin/mpathutil status
show topology
create: 3600a098038315045572b5930646f4b63 dm-1 NETAPP  ,LUN C-Mode
size=9.0G features='4 queue_if_no_path pg_init_retries 50 retain_attached_hw_handle' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 15:0:0:0  sdb  8:16    active ready running
  |- 15:0:1:0  sdc  8:32    active ready running
  |- 16:0:0:0  sdcf 69:48   active ready running
  `- 16:0:1:0  sdcg 69:64   active ready running
----
=====
--
.Configurazione AFF o FAS
--
Una configurazione AFF o FAS deve avere due gruppi di percorsi con priorità maggiore e minore. I percorsi Active/Optimized di priorità più elevata sono serviti dal controller in cui si trova l'aggregato. I percorsi a priorità inferiore sono attivi ma non ottimizzati perché serviti da un controller diverso. I percorsi non ottimizzati vengono utilizzati solo quando non sono disponibili percorsi ottimizzati.

L'esempio seguente visualizza l'output per una LUN ONTAP con due percorsi attivi/ottimizzati e due percorsi attivi/non ottimizzati:

.Mostra esempio
[%collapsible]
=====
[listing]
----
/usr/sbin/mpathutil status
show topology
create: 3600a098038315045572b5930646f4b63 dm-1 NETAPP  ,LUN C-Mode
size=9.0G features='4 queue_if_no_path pg_init_retries 50 retain_attached_hw_handle' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
  |- 15:0:0:0  sdb  8:16    active ready running
  `- 15:0:1:0  sdc  8:32    active ready running
`-+- policy='service-time 0' prio=50 status=active
     |- 16:0:0:0  sdcf 69:48   active ready running
     `- 16:0:1:0  sdcg 69:64   active ready running
----
=====
--
====

