= 
:allow-uri-read: 


Assicurati che iSCSI sia configurato correttamente per il tuo host.

.A proposito di questa attività
Eseguire i seguenti passaggi sull'host iSCSI.

.Fasi
. Verificare che il pacchetto iSCSI initiator (open-iscsi) sia installato:
+
[source, cli]
----
$apt list |grep open-iscsi
----
+
Dovresti vedere un output simile al seguente esempio:

+
[listing]
----
open-iscsi/stable,now 2.1.11-1+deb13u1 amd64
----
. Verificare il nome del nodo iSCSI initiator, che si trova nel file  `/etc/iscsi/initiatorname.iscsi`:
+
[source, cli]
----
InitiatorName=iqn.YYYY-MM.com.<vendor>:<host_name>
----
. Configura il parametro di timeout della sessione iSCSI situato nel file  `/etc/iscsi/iscsid.conf`:
+
[source, cli]
----
node.session.timeo.replacement_timeout = 5
----
+
Il parametro  `replacement_timeout`iSCSI controlla per quanto tempo il livello iSCSI deve attendere che un percorso o una sessione scaduti si ristabiliscano prima di interrompere qualsiasi comando su di esso. Dovresti impostare il valore di  `replacement_timeout`a 5 nel file di configurazione iSCSI.

. Abilitare il servizio iSCSI:
+
[source, cli]
----
$systemctl enable iscsid
----
. Avvia il servizio iSCSI:
+
[source, cli]
----
$systemctl start iscsid
----
. Verificare che il servizio iSCSI sia in esecuzione:
+
[source, cli]
----
$systemctl status iscsid
----
+
.Mostra esempio
[%collapsible]
====
[listing]
----
● iscsid.service - iSCSI initiator daemon (iscsid)
     Loaded: loaded (/usr/lib/systemd/system/iscsid.service; disabled; preset: enabled)
     Active: active (running) since Fri 2026-02-20 22:14:34 IST; 2 days ago
 Invocation: 37a44a6ebd3a4e3898dcc6c408b85bec
TriggeredBy: ● iscsid.socket
       Docs: man:iscsid(8)
    Process: 4985 ExecStartPre=/usr/lib/open-iscsi/startup-checks.sh (code=exited, status=0/SUCCESS)
    Process: 4988 ExecStart=/usr/sbin/iscsid (code=exited, status=0/SUCCESS)
   Main PID: 4991 (iscsid)
      Tasks: 2 (limit: 151112)
     Memory: 12.5M (peak: 15.5M)
        CPU: 2.438s
     CGroup: /system.slice/iscsid.service
             ├─4990 /usr/sbin/iscsid
             └─4991 /usr/sbin/iscsid

----
====
. Scopri i target iSCSI:
+
[source, cli]
----
$iscsiadm --mode discovery --op update --type sendtargets --portal <target_IP>
----
+
.mostra esempio
[%collapsible]
====
[listing]
----
iscsiadm --mode discovery --op update --type sendtargets --portal
192.168.166.70
192.168.166.70:3260,1042 iqn.1992-08.com.netapp:sn.c770be5d934811f0b624d039eac809ba:vs.5
192.168.165.71:3260,1045 iqn.1992-08.com.netapp:sn.c770be5d934811f0b624d039eac809ba:vs.5
192.168.165.70:3260,1044 iqn.1992-08.com.netapp:sn.c770be5d934811f0b624d039eac809ba:vs.5
192.168.166.71:3260,1043 iqn.1992-08.com.netapp:sn.c770be5d934811f0b624d039eac809ba:vs.5
----
====
. Accedi ai target:
+
[source, cli]
----
$iscsiadm --mode node -l all
----
. Imposta iSCSI per accedere automaticamente all'avvio dell'host:
+
[source, cli]
----
$iscsiadm --mode node -T <target_name> -p <ip:port> -o update -n node.startup -v automatic
----
+
Sostituisci  `<target_name>` con il nome del target a cui desideri accedere automaticamente all'avvio dell'host. Sostituisci  `<ip:port>` con l'indirizzo IP e il numero di porta del target. Ad esempio:

+
[source, cli]
----
iscsiadm --mode node -T iqn.1992-08.com.netapp:sn.c770be5d934811f0b624d039eac809ba:vs.5 -p 192.168.166.70:3260 -o update -n node.startup -v automatic
----
. Verificare le sessioni iSCSI:
+
[source, cli]
----
$iscsiadm --mode session
----
+
.Mostra esempio
[%collapsible]
====
[listing]
----
iscsiadm --mode session
tcp: [1] 192.168.166.71:3260,1043 iqn.1992-08.com.netapp:sn.c770be5d934811f0b624d039eac809ba:vs.5 (non-flash)
tcp: [2] 192.168.165.71:3260,1045 iqn.1992-08.com.netapp:sn.c770be5d934811f0b624d039eac809ba:vs.5 (non-flash)
tcp: [3] 192.168.165.70:3260,1044 iqn.1992-08.com.netapp:sn.c770be5d934811f0b624d039eac809ba:vs.5 (non-flash)
tcp: [4] 192.168.166.70:3260,1042 iqn.1992-08.com.netapp:sn.c770be5d934811f0b624d039eac809ba:vs.5 (non-flash)
----
====

