= 
:allow-uri-read: 


Il file multipath.conf deve esistere per l'avvio del daemon multipath, ma è possibile creare un file vuoto a zero byte usando il comando:
`touch /etc/multipath.conf`La prima volta che si crea questo file, potrebbe essere necessario attivare e avviare i servizi multipath.

[listing]
----
# chkconfig multipathd on
# /etc/init.d/multipathd start
----
Non è necessario aggiungere nulla direttamente a multipath.conf, a meno che non si disponga di dispositivi che non si desidera siano gestiti da multipath o che non si dispongano di impostazioni che sovrascrivono le impostazioni predefinite. È possibile aggiungere la seguente sintassi al file multipath.conf per escludere i dispositivi indesiderati.


NOTE: Sostituire l'<DevId> con la stringa WWID del dispositivo che si desidera escludere. Utilizzare il seguente comando per determinare l'ID WWID:

....
blacklist {
        wwid <DevId>
        devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
        devnode "^hd[a-z]"
        devnode "^cciss.*"
}
....
.Esempio
In questo esempio, sda è il disco SCSI locale da aggiungere alla blacklist.

. Eseguire il seguente comando per determinare l'ID WWID:
+
....
# /lib/udev/scsi_id -gud /dev/sda
360030057024d0730239134810c0cb833
....
. Aggiungi questo WWID alla "blacklist" stanza in /etc/multipath.conf:
+
....
blacklist {
     wwid   360030057024d0730239134810c0cb833
     devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
     devnode "^hd[a-z]"
     devnode "^cciss.*"
}
....


Controllare sempre il `/etc/multipath.conf` file per le impostazioni legacy, in particolare nella sezione delle impostazioni predefinite, che potrebbero sovrascrivere le impostazioni predefinite. La tabella riportata di seguito mostra le informazioni critiche `multipathd` Parametri per i LUN ONTAP e i valori richiesti. Se un host è connesso a LUN di altri vendor e uno qualsiasi di questi parametri viene ignorato, sarà necessario correggerli nelle successive fasi di `multipath.conf` Che si applicano specificamente alle LUN ONTAP. In caso contrario, i LUN ONTAP potrebbero non funzionare come previsto. Questi valori predefiniti devono essere ignorati solo in consultazione con NetApp e/o il vendor del sistema operativo e solo quando l'impatto è pienamente compreso.
