= 
:allow-uri-read: 


È possibile configurare NVMe/FC con adattatori Broadcom/Emulex FC o Marvell/Qlogic FC.  Per NVMe/FC configurato con un adattatore Broadcom, è possibile abilitare richieste I/O di dimensione pari a 1 MB.

[role="tabbed-block"]
====
.Broadcom/Emulex
--
Configurare NVMe/FC per un adattatore Broadcom/Emulex.

.Fasi
. Verificare di utilizzare il modello di adattatore supportato:
+
.. Visualizza i nomi dei modelli:
+
[source, cli]
----
cat /sys/class/scsi_host/host*/modelname
----
+
Viene visualizzato il seguente output:

+
[listing]
----
LPe36002-M64
LPe36002-M64
----
.. Visualizza le descrizioni dei modelli:
+
[source, cli]
----
cat /sys/class/scsi_host/host*/modeldesc
----
+
Dovresti vedere un output simile al seguente esempio:

+
[listing]
----
Emulex LightPulse LPe36002-M64 2-Port 64Gb Fibre Channel Adapter
Emulex LightPulse LPe36002-M64 2-Port 64Gb Fibre Channel Adapter
----


. Verificare di utilizzare il Broadcom consigliato `lpfc` firmware e driver della posta in arrivo:
+
.. Visualizza la versione del firmware:
+
[source, cli]
----
cat /sys/class/scsi_host/host*/fwrev
----
+
L'esempio seguente mostra le versioni del firmware:

+
[listing]
----
14.0.539.16, sli-4:6:d
14.0.539.16, sli-4:6:d
----
.. Visualizza la versione del driver in arrivo:
+
[source, cli]
----
cat /sys/module/lpfc/version
----
+
L'esempio seguente mostra la versione del driver:

+
[listing]
----
0:14.4.0.6
----


+
Per l'elenco aggiornato dei driver della scheda di rete supportati e delle versioni del firmware, vedere link:https://mysupport.netapp.com/matrix/["Tool di matrice di interoperabilità"^].

. Verificare che l'output previsto di `lpfc_enable_fc4_type` sia impostato su `3`:
+
[source, cli]
----
cat /sys/module/lpfc/parameters/lpfc_enable_fc4_type
----
. Verificare che sia possibile visualizzare le porte dell'iniziatore:
+
[source, cli]
----
cat /sys/class/fc_host/host*/port_name
----
+
L'esempio seguente mostra le identità delle porte:

+
[listing]
----
0x2100f4c7aa0cd7c2
0x2100f4c7aa0cd7c3
----
. Verificare che le porte dell'iniziatore siano in linea:
+
[source, cli]
----
cat /sys/class/fc_host/host*/port_state
----
+
Viene visualizzato il seguente output:

+
[listing]
----
Online
Online
----
. Verificare che le porte iniziatore NVMe/FC siano abilitate e che le porte di destinazione siano visibili:
+
[source, cli]
----
cat /sys/class/scsi_host/host*/nvme_info
----
+
.Mostra esempio
[%collapsible]
=====
[listing, subs="+quotes"]
----
NVME Initiator Enabled
XRI Dist lpfc2 Total 6144 IO 5894 ELS 250
NVME LPORT lpfc2 WWPN x100000109bf044b1 WWNN x200000109bf044b1 DID x022a00 *ONLINE*
NVME RPORT       WWPN x202fd039eaa7dfc8 WWNN x202cd039eaa7dfc8 DID x021310 *TARGET DISCSRVC ONLINE*
NVME RPORT       WWPN x202dd039eaa7dfc8 WWNN x202cd039eaa7dfc8 DID x020b10 *TARGET DISCSRVC ONLINE*

NVME Statistics
LS: Xmt 0000000810 Cmpl 0000000810 Abort 00000000
LS XMIT: Err 00000000  CMPL: xb 00000000 Err 00000000
Total FCP Cmpl 000000007b098f07 Issue 000000007aee27c4 OutIO ffffffffffe498bd
        abort 000013b4 noxri 00000000 nondlp 00000058 qdepth 00000000 wqerr 00000000 err 00000000
FCP CMPL: xb 000013b4 Err 00021443

NVME Initiator Enabled
XRI Dist lpfc3 Total 6144 IO 5894 ELS 250
NVME LPORT lpfc3 WWPN x100000109bf044b2 WWNN x200000109bf044b2 DID x021b00 *ONLINE*
NVME RPORT       WWPN x2033d039eaa7dfc8 WWNN x202cd039eaa7dfc8 DID x020110 *TARGET DISCSRVC ONLINE*
NVME RPORT       WWPN x2032d039eaa7dfc8 WWNN x202cd039eaa7dfc8 DID x022910 *TARGET DISCSRVC ONLINE*

NVME Statistics
LS: Xmt 0000000840 Cmpl 0000000840 Abort 00000000
LS XMIT: Err 00000000  CMPL: xb 00000000 Err 00000000
Total FCP Cmpl 000000007afd4434 Issue 000000007ae31b83 OutIO ffffffffffe5d74f
        abort 000014a5 noxri 00000000 nondlp 0000006a qdepth 00000000 wqerr 00000000 err 00000000
FCP CMPL: xb 000014a5 Err 0002149a
----
=====


--
.Marvell/QLogic
--
Configurare NVMe/FC per un adattatore Marvell/QLogic.

.Fasi
. Verificare che siano in esecuzione le versioni del firmware e del driver dell'adattatore supportate:
+
[source, cli]
----
cat /sys/class/fc_host/host*/symbolic_name
----
+
L'esempio seguente mostra le versioni del driver e del firmware:

+
[listing]
----
QLE2872 FW:v9.15.00 DVR:v10.02.09.300-k
QLE2872 FW:v9.15.00 DVR:v10.02.09.300-k
----
. Verificare che `ql2xnvmeenable` è impostato. Ciò consente all'adattatore Marvell di funzionare come iniziatore NVMe/FC:
+
[source, cli]
----
cat /sys/module/qla2xxx/parameters/ql2xnvmeenable
----
+
Il risultato previsto è 1.



--
====