= 
:allow-uri-read: 


. Installare `nvme-cli` pacchetto:
+
[source, cli]
----
rpm -qa|grep nvme-cli
----
+
L'esempio seguente mostra un  `nvme-cli` versione del pacchetto:

+
[listing]
----
nvme-cli-2.11-5.el10.x86_64
----
. Installare `libnvme` pacchetto:
+
[source, cli]
----
rpm -qa|grep libnvme
----
+
L'esempio seguente mostra un  `libnvme` versione del pacchetto:

+
[listing]
----
libnvme-1.11.1-1.el10.x86_64
----
. Sull'host, controlla la stringa hostnqn in  `/etc/nvme/hostnqn` :
+
[source, cli]
----
cat /etc/nvme/hostnqn
----
+
L'esempio seguente mostra un  `hostnqn` versione:

+
[listing]
----
nqn.2014-08.org.nvmexpress:uuid:4c4c4544-0056-5410-8048-b9c04f425633
----
. Verificare che il `hostnqn` la stringa corrisponde a. `hostnqn` Stringa per il sottosistema corrispondente sull'array ONTAP:
+
[source, cli]
----
::> vserver nvme subsystem host show -vserver vs_nvme_194_proxmox84
----
+
.Mostra esempio
[%collapsible]
====
[listing]
----
Vserver Subsystem Priority  Host NQN
------- --------- --------  ------------------------------------------------
vs_ nvme_194_proxmox84
        nvme4
                  regular   nqn.2014-08.org.nvmexpress:uuid:4c4c4544-0056-5410-8048- c7c04f425633
        nvme_1
                  regular   nqn.2014-08.org.nvmexpress:uuid:4c4c4544-0056-5410-8048- c7c04f425633
        nvme_2
                  regular   nqn.2014-08.org.nvmexpress:uuid:4c4c4544-0056-5410-8048- c7c04f425633
        nvme_3
                  regular   nqn.2014-08.org.nvmexpress:uuid:4c4c4544-0056-5410-8048- c7c04f425633
4 entries were displayed.
----
====
+

NOTE: Se le `hostnqn` stringhe non corrispondono, utilizzare il `vserver modify` comando per aggiornare la `hostnqn` stringa sul sottosistema di array ONTAP corrispondente in modo che corrisponda alla `hostnqn` stringa dall' `/etc/nvme/hostnqn`host.


