= Passaggio 1: Se lo si desidera, attivare l'avvio SAN
:allow-uri-read: 




== Passaggio 1: Se lo si desidera, attivare l'avvio SAN

È possibile avviare il sistema operativo Windows tramite un avvio locale o un avvio SAN.  NetApp consiglia di utilizzare un avvio SAN per semplificare la distribuzione e migliorare la scalabilità.

[role="tabbed-block"]
====
.Boot SAN
--
Se si sceglie di utilizzare l'avvio SAN, questo deve essere supportato dalla propria configurazione.

.Prima di iniziare
Utilizzare https://mysupport.netapp.com/matrix/#welcome["Tool di matrice di interoperabilità"^] per verificare che il sistema operativo Windows in uso, l'HBA (host Bus Adapter), il firmware HBA, il BIOS di avvio HBA e la versione ONTAP supportino l'avvio SAN.

.Fasi
. link:https://docs.netapp.com/us-en/ontap/san-admin/provision-storage.html["Crea un LUN di avvio SAN e mappalo all'host"^].
. Abilitare l'avvio SAN nel BIOS del server per le porte a cui è mappato il LUN di avvio SAN.
+
Per informazioni su come attivare il BIOS HBA, consultare la documentazione specifica del vendor.

. Verificare che la configurazione sia stata eseguita correttamente riavviando l'host e verificando che il sistema operativo sia attivo e funzionante.


--
.Avvio locale
--
Eseguire un avvio locale installando il sistema operativo Windows sul disco rigido locale, ad esempio su un SSD, SATA o RAID.

--
====